### ISSUE TITLE
Fix Breadcrumbs for Bootstrap 4 on Files App

### ISSUE THREAD

**Issue by msquee** [OSC/ondemand#1004]
The breadcrumb in the new Files app doesn't look natural. Opening this issue to discuss solutions, we can fix this purely in CSS.

**Potential solutions:**
Using the CSS selector `:first-child` and hide the first `/` in the breadcrumb.

![image](https://user-images.githubusercontent.com/6081892/112183639-d488e100-8bd4-11eb-8b2c-3e6fd3e88b19.png)

![image](https://user-images.githubusercontent.com/6081892/112183887-0e59e780-8bd5-11eb-833a-b69693110440.png)

**Comment by ericfranz** [comment]
There is a very simple solution to this. Commonly when we display a directory name, to indicate it is a directory, we may suffix the name with a slash. So we could do that here. What that means is these particular breadcrumbs we will be omitting the breadcrumb divider.

We would get rid of the arbitrary padding and optionally add a space after the / for directories. Maybe omit the slash in the final directory (or not):

Slash after dir (but not last one):

![screen 2021-04-02 at 9 44 46 AM](https://user-images.githubusercontent.com/512333/113420947-36e19e80-9398-11eb-8616-03cd01dc46ab.png)

When hovering over a directory:

![screen 2021-04-02 at 9 44 51 AM](https://user-images.githubusercontent.com/512333/113420944-35b07180-9398-11eb-9e0f-ea54f03fc283.png)

If all directories have / at end:

![screen 2021-04-02 at 9 44 28 AM](https://user-images.githubusercontent.com/512333/113420955-3cd77f80-9398-11eb-9135-2a28492f2453.png)

No spacing after the directory name for the slash:

![screen 2021-04-02 at 9 43 34 AM](https://user-images.githubusercontent.com/512333/113421082-77411c80-9398-11eb-89ec-b57d80b0455c.png)

This last one might be most preferable. Here is a screenshot where all the directories are lowercase names:

![screen 2021-04-02 at 9 49 39 AM](https://user-images.githubusercontent.com/512333/113421320-e3bc1b80-9398-11eb-99f1-06559a9eceab.png)

**Comment by ericfranz** [comment]
FWIW I think the first image is most aesthetically pleasing but the last is most usable. The last is most usable because it is clearest that the root directory "/" is a separate link or destination. I will use the last one.
