### ISSUE TITLE
refactor sprockets js files into webpacker

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1005]
We're still using sprockets to manages some javascript files. This ticket is to track the progress on migrating all those files into files/modules being managed by webpacker.

https://github.com/OSC/ondemand/blob/f2d596feec3b49273de46dfb571bf6ed8f4a7025/apps/dashboard/app/views/layouts/application.html.erb#L13

I guess we'd want to standardize on ES6 modules, but I'm not super familiar with the ecosystem and how much work we'd need to put into transpiling older packages, but that's something we can discuss here.

This may be a large ticket so it should definitely get fixed in multiple small PRs.

* [x] #1512
* [x] #1582 
* [x] #1513
* [x] #1514
* [x] #1515
* [x] #1516
* [x] #1517
* [x] #1518
* [x] #1519
* [x] #1520
* [x] #1742
* [x] #1747
* [x] #1784
* [x] #1783
* [x] #1801
* [x] #1802
* [x] #1809

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737297361610) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
I also think this is something that isn't urgent. Somethings we will want to migrate - others we might want to rewrite into webpacker, others we might want to just render unnecessary (like if we pull out the "web dev" interface altogether.

**Comment by johrstrom** [comment]
After all this work - this is now complete.
