### ISSUE TITLE
Feature Request: Disable Host Link in Batch Connect Per Application

### ISSUE THREAD

**Issue by kmanalo** [OSC/ondemand#1024]
https://discourse.osc.edu/t/disable-host-link-in-batch-connect-for-one-application/1417

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823104057033) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Sorry for delay, we fixed this in #1173 which was released in the 2.0 series.
