### ISSUE TITLE
cluster configs are read when building dashboard app

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#103]
When building the Dashboard app, the cluster configs were loaded (because presumably OodAppkit.clusters was called). This should not happen.

See https://github.com/OSC/ood-dashboard/issues/484 for an example of how this can be problematic.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823085365600) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
reviewed,
configuration is safe to read now
