### ISSUE TITLE
Add validation or restrictions on what can be specified as a job script

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#104]
Currently there is no restriction on what file can be selected to submit a job. Recently, some users have accidentally had their Abaqus input file selected as the script to submit, instead of the job script itself. The result is the job is rejected.

Some ideas:

* restrict the dropdown to files ending in .sh, and then let the user "uncheck" the checkbox to allow them to select any file
* restrict the dropdown to files whose first line starts with a shebang
* display a warning to the user if the "script" currently selected does not have a shebang as the first line of the file
* display a warning to the user if the "script" currently selected does not have the extension `.sh`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823086374594) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I think this is related to the job composer, in which case I'm going to close as won't do.

It does however relate to #2575 in that `auto_scripts` should glob the correct extensions.
