### ISSUE TITLE
variable resue in configuration singleton

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1052]
It's a bit confusing to use `config` twice in this class so refactor the inner loop variable name in the method `read_config` to be something other than the method name `config` to avoid confusion.

https://github.com/OSC/ondemand/blob/6b8f0be3435402da3b0b3b185bd8834a33e4d92b/apps/dashboard/config/configuration_singleton.rb#L325-L327

and it's reused variable name

https://github.com/OSC/ondemand/blob/6b8f0be3435402da3b0b3b185bd8834a33e4d92b/apps/dashboard/config/configuration_singleton.rb#L331

**Comment by ericfranz** [comment]
Possible read_config impl that might be simpler:

```ruby
def read_config
  Pathname.glob(config_directory.join("*.{yml,yaml,yml.erb,yaml.erb}")).map {|file|
    read_config_from_file(file)
  }.reduce({}, :deep_merge)
end
```
