### ISSUE TITLE
Run command when interactive app is deleted

### ISSUE THREAD

**Issue by btsherid** [OSC/ondemand#1063]
Hi,

I'm making an interactive app and I'm hoping to figure out how to run a command when I hit the Delete button (or when the app times out).

In my template/script.sh.erb, I am running a docker run command. This starts a docker container, but when I click the delete button (haven't tested timing out yet) the SLURM script is killed but the docker container is still running.

I have configured a unique name for the container which could be used to stop it. If I could simply trigger a command on Delete or timeout, I could ensure the container gets stopped and cleaned up. I tried making a template/clean.sh.erb but it did not seem to do anything.

Any suggestions for how I can trigger a custom cleanup command after an interactive app is Deleted or timed out?

Thanks,
Brendan Sheridan

**Comment by johrstrom** [comment]
Looks like a similar issue to this. You're likely better off setting an environment like JOB_CONTAINER_NAME using a Slurm prolog to delete it.  We typically assume when the scheduler deletes a job it actually removes everything from that job. This seems to be a deficiency in how Docker creates cgroups and Slurm clears out all the processes based on cgroups. Essentially you're allowing your users to create process' in a cgroup that Slurm then won't recognize.

That said, you're likely much much better off just using `podman` or some other container runtime so you can run rootless containers and avoid the issue entirely (not to mention the security issues!).

https://discourse.osc.edu/t/jupyter-launched-via-docker-and-cleaning-up-containers/1290

**Comment by btsherid** [comment]
How would I go about setting that environment variable?

I tried podman but ran into the same issue as the user from the link about managing ranges of subuids/subguids. Singularity also doesn't work for me because I need to utilize docker's --user flag which isn't compatible with Singularity.

Thanks,
Brendan

**Comment by johrstrom** [comment]
> I have configured a unique name for the container

You know the name of the container, just export it as the environment variable.  I'm a little out of my depth with Slurm prologue and what their environment is. Maybe instead of an environment variable, maybe the prologue can read a known file like `$TMPDIR/job_container_name`. If the file exists, read it and try to stop the container.

**Comment by treydock** [comment]
The environment for Prolog/Epilog is very limited and is not the job environment.  The TaskProlog/TaskEpilog (run as user) does have more information in the environment.  If you make the container name use things the Prolog knows about, so like `$SLURM_JOB_ID_$SLURM_JOB_USER` as the container name then the Prolog could create the container and Epilog could tear it down using information already available to those scripts.  The only other way I can envision this working with the Prolog/Epilog is to write a SPANK plugin that sets the environment variable in the Prolog/Epilog environment.

**Comment by btsherid** [comment]
Thanks for the suggestions. I actually discovered that what I was trying to do could be accomplished through the RStudio app I already had configured. You can close this.

**Comment by johrstrom** [comment]
Thanks. This is also related to #557.
