### ISSUE TITLE
'native instructions' tab doesn't work in 2.0

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1077]
The 'Native Instructions' tab doesn't change what's shown in the card. Users can open that tab, but nothing in the card changes.

![image](https://user-images.githubusercontent.com/4874123/116103647-cc154180-a67d-11eb-8513-9191f7dfe2a7.png)

**Comment by ericfranz** [comment]
The problem is using a UUID for an HTML element id. What happens is sometimes the UUID starts with a number instead of a letter, and this actually doesn't work with Bootstrap in particular. Bootstrap depends on HTML4 rules for id attribute, which requires starting with a letter.

**Comment by ericfranz** [comment]
This is because CSS still requires id selector that follows HTML4 rules even though HTML5 supports a wider variety of IDs.
