### ISSUE TITLE
Change the prehook to use fork+exec so we can pass options via ENV

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#1078]

**Comment by johrstrom** [comment]
I've made some progress on this, so I'm going to update here with my notes.

I started with the function implementation noted here. https://github.com/OSC/ondemand/pull/726#issuecomment-723245935 
As that comment suggests, it doesn't work right. Toying around with it I found 

```lua
    local output = posix.exec("/bin/sh", { "-c", cmd })
    -- local output = posix.exec(cmd)

**Comment by johrstrom** [comment]
```lua
--[[
  fork_and_exec
--]]
function fork_and_exec(cmd, env_table, r)
  local unistd = require 'posix.unistd'
  local stdlib = require 'posix.stdlib'

  r:info('parent: my pid is: ' .. unistd.getpid())
  local read_pipe, write_pipe = unistd.pipe()
  local childpid, errmsg = unistd.fork()

  if childpid == nil then
    return "failed to fork " .. cmd .. " with error message: '" .. errmsg .. "'"
  elseif childpid == 0 then
    r:info('child: my pid is: ' .. unistd.getpid())
    unistd.close(read_pipe)

    for key,value in pairs(env_table) do
      r:info('setting environment ' .. (key or "nil") .. "=" .. (value or "nil"))
      stdlib.setenv("OOD_" .. key, value)
    end

    stdlib.setenv("OOD_TEST_KEY", "HELLO THERE!")

    -- local idx = 0
    -- local cmd_root = ""
    -- local cmd_table = {}
    -- for token in string.gmatch(cmd, "[^%s]+") do
    --   if idx == 0 then
    --     cmd_root = token
    --   else
    --     cmd_table[idx] = token
    --   end
      
    --   idx = idx + 1
    -- end
    -- this works
    -- local output = unistd.exec("/bin/sh", { "-c", cmd })
    

    -- this doesn't like 'jeff' in quotes, should just be jeff
    -- local output = unistd.execp(cmd_root, cmd_table)
    
    --  pun -u jeff -a  -P %2fopt%2fproxy%2fpre_hook_wrapper
    -- local output = unistd.exec("/usr/bin/sudo", {
    --   "/opt/ood/nginx_stage/sbin/nginx_stage",
    --   "pun", "-u", "jeff",
    --   -- "-a", "http://localhost:8080/nginx/init?redir=$http_x_forwarded_escaped_uri",
    --   "-P", "/opt/proxy/pre_hook_wrapper"
    -- })
    local output = capture2e(cmd)
    unistd.write(write_pipe, output)
    unistd.close(write_pipe)
    unistd._exit(0)
  else
    unistd.close(write_pipe)
    
    r:info('pid ' .. unistd.getpid() .. ' waiting for the command to complete')
    require 'posix.sys.wait'.wait(childpid)

    local output = ""
    local b = unistd.read(read_pipe, 1)
    while #b == 1 do
       -- got a byte from the pipe, write it to stdout
       output = output .. b
       b = unistd.read(read_pipe, 1)
    end

    return output
  end
end

**Comment by treydock** [comment]
The version of Lua Lua POSIX on RHEL7 doesn't support `posix.stdlib`:

```
[root@webdev02 ~]# lua
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
> local stdlib = require 'posix.stdlib'
stdin:1: module 'posix.stdlib' not found:
        no field package.preload['posix.stdlib']
        no file './posix/stdlib.lua'
        no file '/usr/share/lua/5.1/posix/stdlib.lua'
        no file '/usr/share/lua/5.1/posix/stdlib/init.lua'
        no file '/usr/lib64/lua/5.1/posix/stdlib.lua'
        no file '/usr/lib64/lua/5.1/posix/stdlib/init.lua'
        no file './posix/stdlib.so'
        no file '/usr/lib64/lua/5.1/posix/stdlib.so'
        no file '/usr/lib64/lua/5.1/loadall.so'
        no file './posix.so'
        no file '/usr/lib64/lua/5.1/posix.so'
        no file '/usr/lib64/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: ?
> 
```

It looks like this to load Lua POSIX :

```
[root@webdev02 ~]# lua
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
> local posix = require 'posix'
> posix.getenv("USER")
> 
```

**Comment by treydock** [comment]
Version on RHEL7 is 32:

```
[root@webdev02 ~]# rpm -q lua-posix
lua-posix-32-2.el7.x86_64
```

**Comment by johrstrom** [comment]
Taking a look back at the original comments in https://github.com/OSC/ondemand/pull/726#issuecomment-723245935 I think I have a better handle on why apache was crashing and it's not nessicarliy only because it's forking. It was that the forked process wasn't exiting cleanly.  

The big takeaway here is that whatever the child process does, it needs to exit 0 or or apache won't like it.  Which now makes me wonder if the forked process takes a bite out of the thread pool settings it has. I mean this request to start a PUN may actually take 2 out of that pool instead of just 1.

@treydock Thanks for checking. I can fix up the imports to be centos:7 compliant.

**Comment by ericfranz** [comment]
> Which now makes me wonder if the forked process takes a bite out of the thread pool settings it has.

It would eventually I guess if the process didn't call exec to replace it with another process or exit, since then it would remain a copy of the parent Apache process.

In the previous approach with the fork + exec you could read from STDOUT and STDERR by using `/proc/{PID}/fd/1` and `/proc/{PID}/fd/2`. But I suppose that could be explored later or not at all, since you have an approach that works.

I guess its slightly less efficient since we fork twice - child process calling `capture2e` - but this is only done on the request for PUN startup and only done if we have pre-hooks enabled. And we don't have to go running and advertising all about pre-hooks yet until we have had time to use them in production for a bit so that is good.

In the example above I might rename the method from `fork_and_exec` to `capture` since if we follow the naming convention of the Open3 module from Ruby, for example, which I think was the intent of the previously named `capture2e`, here we are only returning stdout.

**Comment by ericfranz** [comment]
At the end of the method before returning the output should you do `unistd.close(read_pipe)`?
