### ISSUE TITLE
Enable shell app to have variations on the command it runs after connecting

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#109]
See https://discourse.osc.edu/t/possible-to-make-shell-access-app-start-on-a-compute-node-via-srun-pty-bash/586

A simple solution is to make the changes suggested in the Dashboard (or go even further, replacing `Shell Access` with just `#{title}`). Then you can make a copy of the shell app that behaves differently than the default app, and the links will appear as appropriate.

A more desirable solution would be to be able to add more link options to the shell app, where depending on which link you choose, the app behaves differently. This will take some design and thought. One approach would be the app itself could provide a list of links (think HATEOS API), however, we would want to determine a way to do this that didn't require starting the shell app process on every Dashboard access. Also, we would want this to be added to runtime configuration in etc. - not something that requires core app modification.

This could be a good argument for merging the shell app into the Dashboard.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823059537899) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
Of course, remember, a bad argument for merging the shell app into the Dashboard - if you do something that breaks the shell app (like cat a too large of a file) then if this ends up freezing up the same web process that is handling the Dashboard, it breaks the ability to go to the Dashboard and click "Restart Web Server" to kill your broken shell process. This is the same issue with merging the files app into the dashboard.

**Comment by ericfranz** [comment]
Here is another use case we want to support: https://discourse.osc.edu/t/run-commands-at-shell-access-from-env/599

**Comment by matt257** [comment]
reviewed,
introduces too many niche problems,
it would take a lot of time to implement securely
