### ISSUE TITLE
field "issuer" in generated dex config should be configurable

### ISSUE THREAD

**Issue by jose-d** [OSC/ondemand#1101]
https://github.com/OSC/ondemand/blob/09ec3a44bc6b1851710b9fd8a6f9d6784533dea2/ood-portal-generator/lib/ood_portal_generator/dex.rb#L110

As far I understood the mechanism, hostname of "issuer" in dex-provided `https://HOST:5554/.well-known/openid-configuration` is generated from `/etc/ood/dex/config.yaml`, field "issuer". And this configuration entry is generated from fqdn of OOD portal host ([here](https://github.com/OSC/ondemand/blob/09ec3a44bc6b1851710b9fd8a6f9d6784533dea2/ood-portal-generator/lib/ood_portal_generator.rb#L33)).

For deployments behind reverse proxy, e.g. haproxy this is not correct, instead of FQDN of OOD portal, the FQDN of proxy should be used there.

current workaround is to generate portal and dex config, and then manually replace field 'issuer' to match the proxy host FQDN. 

Because this is the only tweak needed to have fully working deployment behind haproxy, I suggest adding this configuration option into `config/ood_portal.yml`.

Please, provide feedback if you'd consider this idea as valid, and if project would be open to merge possible pull request implementing such a feature.

**Comment by treydock** [comment]
@jose-d Adjusting the configuration templates to accommodate things like HAProxy would be a good addition. If you'd like to make such a pull request, that'd be great.  Let us know if you need help with that.

**Comment by johrstrom** [comment]
This got fixed in #1233 and will be released this week as a part of 2.0.11
