### ISSUE TITLE
uid to username should always return string

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1130]
We should cast this to a string because it's likely an integer.
https://github.com/OSC/ondemand/blob/36460854190792bbbd424aeba2e0b7b39aba14ee/apps/dashboard/app/models/files.rb#L150

_Originally posted by @johrstrom in https://github.com/OSC/ondemand/pull/1125#discussion_r631068316_

**Comment by ericfranz** [comment]
It is indeed an integer: https://ruby-doc.org/core-2.7.0/File/Stat.html#method-i-uid

Though it is a good change for the API consistency, the client handles the integer uid gracefully:

![screen 2021-05-12 at 1 11 49 PM](https://user-images.githubusercontent.com/512333/118016641-a34ea680-b323-11eb-8e40-d5f125f2dea6.png)

**Comment by johrstrom** [comment]
This was fixed in #1160
