### ISSUE TITLE
Decide between Capybara and Watir

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#1138]
We have some tests in Watir and some in Capybara. Should decide on one over the other.

Watir looks more like plain Ruby code, Capybara is a DSL. I always prefer plain Ruby code :-). Capybara is default for Rails 5 & 6 system tests, so it was effortless to get started with it. But maybe a port from that to Watir is straightforward?

Regardless, we should probably use the Chromedriver: it with a portable Chrome install is very easy to install and get working in multiple environments including our Linux environments and its on the GitHub action vms.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823105675091) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Not a bad idea, but we just don't have the time. Maybe we'll get to it one day, but it just seems that we can keep business as usual until we have the free cycles to clean this up? Seems unlikely, but even so, maybe.
