### ISSUE TITLE
Automate running tests for each app using TravisCI

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#114]
Previously we did this one every commit for the dashboard: https://github.com/OSC/ood-dashboard/blob/master/.travis.yml

There are two approaches.

A. On every commit, Travis runs the tests for each core app and the tests for each proxy component then the tests that are in the root of the repo
B. On every commit to a branch not master, Travis runs tests for only the components/apps whose branch has commits that have modified files in these components/apps

**Comment by treydock** [comment]
A is easier and unless the tests take a very long time, no real benefit in skipping some tests during branches.

I'd recommend this in .travis.yml:

```
branches:
  only:
    - master
    - /^v\d/
```

This will build for master, tags and pull requests. Right now if I open PR using branch on this repo it runs tests twice I think.

**Comment by treydock** [comment]
I'd prefer also to have a single rake task that runs all unit tests. So `rake test` at the root will cd to each app and run whatever command is necessary to run tests. This avoids complex patterns in .travis.yml.

**Comment by johrstrom** [comment]
This is being worked in PR #303.
