### ISSUE TITLE
migrate jquery

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1155]
A long time ago we added jquery-migrate to update jquery in place without actually migrating. Now, years later, I think is the time to _actually_ migrate jquery.

I don't know all the spots where we need to do this in, but it seems like we should start to identify them and slowly migrate what we can until (a) we have no more deprecation warnings and (b) we can get rid of jquery-migrate altogether and just use jquery 3 directly.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201625178070145/1201627247816969) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
I think that rails-ujs requires jquery-migrate - warnings are raised when using it which prompted https://github.com/OSC/ondemand/pull/1153/commits/daeb862e6321c87f4b11c1c0e085b908eed2635f

**Comment by ericfranz** [comment]
Related issue https://github.com/OSC/ondemand/issues/1137
