### ISSUE TITLE
use `yarn set version` to manage yarn version developers use in OnDemand

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#1163]
See https://yarnpkg.com/getting-started/install#about-global-installs for the explanation.

The basic workflow is:

1. install a version of yarn 2+ in your home directory so it is in the path
1. cd to the dashboard app
1. run `yarn set version latest` to install a copy of the latest version of yarn into the dashboard's app directory AND add a .yarnrc.yml. Then commit the new files added to the project (both the copy of yarn and the .yarnrc.yml file)
1. when other developers start, install a global/user copy of yarn and then cd into the directory and the .yarnrc.yml will tell yarn to use the version installed with the app
1. periodically you can use yarn set version to upgrade the version used in the project

Yarn is installed as single executable file, so this makes life really easy.

When this new process is adopted, we can then:

1. revert these changes https://github.com/OSC/ondemand/commit/a6795400ea99fe094b7fc879a9a971261b98881b
1. use the same process for all other Rails 6 apps, whose JS dependencies will default to using webpacker and yarn

This process would be repeated for all the core apps that use yarn (so at least the shell and dashboard apps).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737414570276) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I'm not sure if we need to do this. In any case, I haven't felt the need to yet and don't foresee that.
