### ISSUE TITLE
ActiveJobs: Move the Ganglia graph templating to server side rendering

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand#117]
Refactor [the Jobs controller's JSON action](https://github.com/OSC/ood-activejobs/blob/master/app/controllers/jobs_controller.rb#L28-L38) such that it returns an additional HTML partial containing the table that is defined in [application.js](https://github.com/OSC/ood-activejobs/blob/master/app/assets/javascripts/application.js.erb#L270-L278). Change the click event handler so that the success handler of the `getJSON` request populates both the `.status-label` and the `row.child`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823111463603) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
We're not going to change/refactor things for ganglia. Closing as a won't do.
