### ISSUE TITLE
Recently launched quick launch buttons

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#1178]
Like the goal of the Pinned apps feature providing

* admin pinned apps
* user favorited apps
* recently used apps

We could provide parallel feature for quick launch buttons. We previously discussed quick launch buttons "admin pinned" and "user favorited" and this issue is to propose a simple solution for adding "recently used apps" as quick launch buttons.

After an initial version of the Quick launch button feature is added to OnDemand, it should be easy to add a factory method on the Quick Launch model object to generate a Quick Launch button using the context.json file we use for caching user form input's as the input to this factory method.

Given that for a user and a batch connect app you can quickly find the path to this context file and check the modified date of this context file, you can easily determine what batch connect app was most recently launched.

This could be another optional widget and could provide immediate value to OSC users even if custom quick launch buttons are not configured for ondemand.osc.edu since most apps require specifying account, etc.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823114976094) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
This has been solved in #2477 and other quick launch tickets.
