### ISSUE TITLE
Active Jobs and Interactive app session cards should present similar information

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#1179]
Active jobs provides access to a lot of information about the running job that Interactive apps do not. For example, when available, ganglia graphs, submission details, and buttons to open the job directory in the files app.

On the other hand, the session card provides connection buttons for connecting to interactive app sessions.

It would be nice to unify (at least in part) these two different views of data. While Active Jobs provides the ability to see other users jobs running, the list of **your jobs provides extra capabilities**. A single model object for "your job" which has information about connecting to it if it happens to be an interactive job, or accessing ganglia graphs, etc. would be nice so wherever we display information about "your job" in OnDemand we would have the option to display these details.

So for example, in the table listing of jobs on ActiveJobs a connect button could display for interactive jobs, and an open directory button could display for batch jobs.

![jobs!UNITO-UNDERSCORE!unified!UNITO-UNDERSCORE!jobs!UNITO-UNDERSCORE!viewer](https://user-images.githubusercontent.com/512333/119985702-ffa2fe80-bf90-11eb-89fb-4df079482acd.png)

This mock screenshot shows that. Note this mock screenshot also shows the wish to add completed jobs (likely using XDMoD or perhaps a mixture of XDMoD and sacct as a completed job source). There are other issues to address this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823114793550) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
We're going to close this as won't do. Most interactive jobs only request 1 core so there's not really that any information that's relevant to the user in those extended panels.
