### ISSUE TITLE
ActiveJobs: Switch from oboe.js to ndjson

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#118]
This will simplify the code AND allow for an option of the adapters to "stream json" directly to the response, by instead of passing a block to execute on each job, we pass the io stream which the adapter just writes new line delimited json to the output stream.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823217344020) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
reviewed,
no longer needed
