### ISSUE TITLE
Add support for extra toolbar buttons, metadata for git repos in files app

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#1185]
A directory or a subdirectory of a directory that contains a .git directory i.e. a valid git repo, could display toolbar of buttons for working with the git repo (commit changes), metadata on directory state (number of changes, current branch) and highlighting specific files that have been changed, etc.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823117125125) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
No thanks. This just seems a bit much.
