### ISSUE TITLE
Add support for a job composer like interface in the Files app

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#1186]
A further extension of some of the capability provided by https://github.com/OSC/ondemand/issues/1183 and https://github.com/OSC/ondemand/issues/1184 would be if a job composer template that was copied to a directory contained some type of manifest file such as .ood-job so that the files app would recognize this directory was an OOD Job directory, and then that manifest/metadata file might contain info required to provide similar details that you see in the job composer.

Then the Files interface could be enhanced to provide capabilities similar to what the user could do and see in the Job Composer with an individual job, such as:

1. set the current script to submit
1. submit the script
1. see the status of the running job and information about the running job
1. see the XDMoD link if the job completed
1. resubmit the job

If necessary a details view pane could display, perhaps in the same location where the copy/move clipboard displays.

This if course requires a bit of design, and it may be discovered that only a few tiny features in addition to https://github.com/OSC/ondemand/issues/1183 and https://github.com/OSC/ondemand/issues/1184 are required to provide sufficient functionality for users to switch away from the Job Composer.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823218891364) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I don't know about this one. I feel like it's more like "let's cram the files app functionality into the job composer" than the other way around.  That is, let the job composer have a small table to navigate through files. This keeps the page context to be job focused, while still having the utility of file navigation.

That said there is something here. If we complete #1183 the question becomes what happens next?  Yes you can submit the job but if you're just redirected back to the files app you've lost all context around that job (i.e., what it's state is and so on).

**Comment by johrstrom** [comment]
OK, we're closing this as won't do. The main issue I have is that you lose context. You submit the job, then what? Try to find it in active jobs? Hope you submitted it to the right cluster, and so on.

That said - a lot of this will be in the project manager where it'll have a file browser and job submission support.
