### ISSUE TITLE
Refactor out FilesController code into model object(s)

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#1187]
The FilesController is bloated with a lot of code that belongs in domain models. Two changes can help with this.

1. The introduction of a PosixFile model, which could be the model that is instantiated in the controller in many places, following the normal Rails pattern. Some logic from FilesController and some from Files helper object could move into this new PosixFile. Named PosixFile to differentiate from the ruby core File class and also to differentiate from future possible classes for other cloud storage.
1. The zip code can be moved into a model object if you pass the response as an argument. To do this you would not use zip_tricks_stream - just look at the implementation of zip_tricks_stream and it is very straightforward to use the underlying ZipTricks library so you can pass the response as an argument. This approach is used in ActiveJobs for passing response to an object to handle streaming of job data.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202815755532406/1202821771354479) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
PosixFile was created at some point. I feel like there's a lot in going on in the files_controller, but to me it's 6 in one half a dozen in the other. It's got to exist somewhere. So we're closing this as won't do with the option to pick it up later if we choose.
