### ISSUE TITLE
System installed captions are not i18n configurable

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1198]
System installed captions are not i18n configurable when dev and usr are.

https://github.com/OSC/ondemand/blob/3819a149c47e5963f24963a4ec260284af063a4a/apps/dashboard/app/apps/sys_router.rb#L43-L45

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201625178070145/1201627386361774) by [Unito](https://www.unito.io)

**Comment by ayushchatur** [comment]
i am taking this up @johrstrom
