### ISSUE TITLE
ActiveJobs: Add show route for a job

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#120]
https://ondemand.osc.edu/pun/sys/activejobs/show/3462615.owens-batch.ten.osc.edu

where "3462615.owens-batch.ten.osc.edu" is the id (can be whatever string?

This will just show the details section with the extra column information padded into it.

![](https://user-images.githubusercontent.com/512333/43091357-e47dbffc-8e77-11e8-960b-6164954e1e1c.png)

![](https://user-images.githubusercontent.com/512333/43091365-e8f79b3e-8e77-11e8-9cb1-efa254cf3d2d.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737363528366) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
not an issue for users,
not needed
