### ISSUE TITLE
Develop/Help Drop Down Menu CSS Issue

### ISSUE THREAD

**Issue by nlvw** [OSC/ondemand#1202]
After upgrading OnDemand from v1.8.20 to 2.0.9 I noticed that 2 menus in the top bar are opening in the wrong direction and being cut off. 

v1.8.20:
![image](https://user-images.githubusercontent.com/5723368/121068656-cbe28880-c789-11eb-9035-f33642471e74.png)
![image](https://user-images.githubusercontent.com/5723368/121068685-d3099680-c789-11eb-9bad-a9ddd4809e1a.png)

v2.0.9:
![image](https://user-images.githubusercontent.com/5723368/121068921-13691480-c78a-11eb-9fa8-1a7fc0527047.png)
![image](https://user-images.githubusercontent.com/5723368/121068939-182dc880-c78a-11eb-9ed3-c0e614dbc975.png)

All screenshots were taken at the same resolution and window size (just different tabs).

**Comment by johrstrom** [comment]
Thanks! Yep that's a bug.
