### ISSUE TITLE
ActiveJobs: Make navbar configurable at runtime with same color options like the dashboard

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#121]
Relevant commits/files include:

1. https://github.com/OSC/ood-dashboard/commit/b1c52db2bd70353353381d7bae290771a42b4ef4
1. https://github.com/OSC/ood-dashboard/commit/64c85324163172d44e821536a100481c8c05d893

We should consider adding the shared partial to ood_appkit and using that in MyJobs and ActiveJobs.

This would be a runtime-only config feature.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737418828979) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Yea one complaint we've gotten is the navbar being so different, it throws folks off. There's also #228 to split the navbar in 2.  Mabye we share 1 entirely (what's in the dashboard) and every app enables the second one.
