### ISSUE TITLE
replace function not found

### ISSUE THREAD

**Issue by Juanjdurillo** [OSC/ondemand#1224]
The call to the replace function on a profileId object fails with function not found in 
https://github.com/OSC/ood-shell/blob/f81fc1a7535a95318e1bb725110ed6d26ab0ac2b/public/javascripts/hterm_all_1.85.js#L12233
This prevents ood dashboard properly open a shell. Commenting out the line before solves the problem for me but I am not sure if there is any collateral issue that I might be missing and might explode in production

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737365255919) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Here's the line in question. [String replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) seems to have very wide compatibility so I'm surprised it fails.

https://github.com/OSC/ondemand/blob/aa5bc6269d0aa70e4e7056793bb97aaf95979dc2/apps/shell/public/javascripts/hterm_all_1.85.mod.js#L12240

Unless of course it's null at that point which it seems to default to `default` string as the profile.

https://github.com/OSC/ondemand/blob/aa5bc6269d0aa70e4e7056793bb97aaf95979dc2/apps/shell/public/javascripts/hterm_all_1.85.mod.js#L12201-L12202

What exactly was the error you were seeing?

**Comment by Juanjdurillo** [comment]
Exactly this was the code path, but ended in the error function "replace" not found. The object wasn't null, I printed it for the sake of debugging.  I am really new to javascript, but seemed to me that the function received an object that wasn't string (or maybe even a string object in javascript have a lot of fields other than the content). In any case, for me is working now without that line.

**Comment by johrstrom** [comment]
Hi, sorry just coming back to this. What OS/web browser versions are you using?

**Comment by Juanjdurillo** [comment]
Hi, no problem. Chrome Version 93.0.4577.82

For me the workaround was commenting out that line and got the shell working

**Comment by johrstrom** [comment]
What version of open ondemand are you running?

If it's 2.0 can you hop into the console in the dev tools when you're on that page and let me know this output is? (`window.localStorage.getItem('ood_shell_theme')`)

![image](https://user-images.githubusercontent.com/4874123/134538238-2aca2035-6c27-474f-b70e-a744ec2f28c3.png)

Also have you tried in a private window or clearing your browsers cache?

**Comment by Juanjdurillo** [comment]
OOD version 1.8
Also tried a private window and clearing the cache but did not solve the
issue
