### ISSUE TITLE
use temporary filesystem for session data

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1226]
While traiging #1193, one alternative I gave is to save session data in a `:cache_store` instead of through cookies.

It then occurred to me that if we can store session data to a fuse-fs mounted filesystem, tmpfs or shm - some filesystem that's actually just memory and bound to the process - it'd actually be faster and more secure.

This ticket is to explore and/or implement using `:cache_store` if we can create a tmpfs. 

I think the big things we'd need to keep in mind here are:

* safety - has to work and if it doesn't we fall back to what we use now. We may need `fuse` as a dependency or something.
* security - it's created with the right permissions or in a way where other folks can't possibly read this data
* concurrency - I think we're OK on this score given we limit instances to 1 but we ought to be sure.
https://github.com/OSC/ondemand/blob/aa5bc6269d0aa70e4e7056793bb97aaf95979dc2/nginx_stage/templates/pun.conf.erb#L44
* cleanup - we'd want to be able to automatically remove the mount/filesystem when nginx dies.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823224221918) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
I would not try and rely very heavily on FUSE filesystems.  You can write things to tmpfs or /tmp or /dev/shm without involving FUSE.  I think if we do start writing local files, the size of what can be written will greatly dictate the location. If we are talking KBs or a few MB, that can go pretty much anywhere. If you are talking much more than that, it would have to be /tmp or /var/tmp.  Also one thing to consider is writing to to like /dev/shm where /dev/shm is a private namespace through unshare.  We do something similar for SLURM where /dev/shm is private to the job and the real location is like /dev/shm/<jobid> but the user just sees /dev/shm thanks to user namespaces and unshare.

**Comment by johrstrom** [comment]
Yea size is small - I mean we're replacing what gets put into a cookie header so KBs is the size.

These would be secrets so not actually persisting it to a disk would be preferable. That's the only reason I mention FUSE. Really we just want a temporary filesystem that's only memory.and bound to the process that created it (in this case the dashboard).  Whatever suits that is good.
