### ISSUE TITLE
ActiveJobs: Consider not showing entire stacktrace on edge case errors

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#124]
When rescuing from errors that aren't `OodCore::JobAdapterError`, we print the entire stack trace to the user's browser. https://github.com/OSC/ood-activejobs/blob/master/app/controllers/pages_controller.rb#L67 (See image) I had to insert a raise statement here to demonstrate this, as I'm not sure what other types of exception are possible in this block.

We should probably just send the backtrace to the log here and only display an error message, with possibly the Exception class name and a timestamp that we can associate with a log file entry.

Again, this is only for edge cases and we haven't seen it in the wild, so it may not be a high priority.

![rescue](https://user-images.githubusercontent.com/2374718/27974806-88d4bcb2-632d-11e7-99ce-643a13992787.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737366862356) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
won't fix,
not a major issue
