### ISSUE TITLE
debian package release process for non-ondemand packages

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand#1242]
The current release process for any RPM is based on tags. So if this repo is tagged, that generates a new set of RPMs using that tag. If this repo is also responsible for building the passenger/nginx deb packages, I'd propose we utilize a different tag to denote those builds and tell Gitlab CI YAML to only build those specific tags with a given prefix.  So to build passenger/nginx you might generate a tag like `ondemand-passenger-6.0.9` and then the Gitlab CI could be told tags with `ondemand-passenger-*` are what triggers the rake tasks to build those applications.

The other approach is always build passenger/nginx when you build OnDemand. I would strongly recommend keeping the versions from upstream, but the current RPM upload script will not overwrite existing files so in theory this is possible and any duplicate builds would just simply not get pushed to the repo server. The big downside to this is you end up with a lot of unnecessary builds taking place in the CI/CD pipeline.

**Comment by johrstrom** [comment]
> The other approach is always build passenger/nginx when you build OnDemand

+1 to this. But I'd go further and say just put it in the ondemand package itself and not actually build an ondemand-nginx package. Just drop it right where we need it.

Dex as an optional package could fall into this category, but the more I think about it, the more I like the idea of ondemand-packaging gem that holds these rake tasks (or in ood_core). That would allow other projects to build in the same environment as ondemand.

**Comment by treydock** [comment]
Along the lines of using ondemand-packaging or some central Rake task, the build environment should be built and pushed to docker hub and not built on every build.  So the Rake task to build the buildbox could be executed in Github Action to publish the image to Docker Hub.  I think only benefit there is build time.  For the RPMs this cuts the build time by a lot, but debs might not be as drastic.

**Comment by treydock** [comment]
Also one reason not to move the logic into ood_core is I thought there was the goal to move ood_core into ondemand monorepo.

**Comment by treydock** [comment]
I think this is being replaced by refactor of ondemand-packaging which currently has the passenger/nginx build logic and that repo can handle the automatic release I think based on tags.
