### ISSUE TITLE
Bug report – Investigate logout not working with Chrome v90

### ISSUE THREAD

**Issue by msquee** [OSC/ondemand#1244]
[Discourse discussion](https://discourse.osc.edu/t/logout-not-working-with-chrome-bug/1549). I've had this problem before on `localhost` installations of OnDemand but never in production. This is worth looking into to see if it's an isolated issue or not.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737366528211) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
Logout only works if using HTTPS for the OIDC endpoint, so a localhost Dex install using mod_auth_openidc and not using SSL will not be able to support logout.  If you attempt to logout and then look at the Apache logs, you will see warnings and errors about not using HTTPS endpoint.

**Comment by johrstrom** [comment]
Reading the discourse topic this was from Dex and Dex does not have support for logout.
