### ISSUE TITLE
Run dex on all interfaces?

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1250]
While reviewing another PR, I noticed that we boot dex on `0.0.0.0`.  I'm wondering if this is appropriate for folks who have multiple interfaces? 

https://github.com/OSC/ondemand/blob/06c0c9e11a25ef174457460c83887b50760d6b36/ood-portal-generator/lib/ood_portal_generator/dex.rb#L24-L27
and
https://github.com/OSC/ondemand/blob/06c0c9e11a25ef174457460c83887b50760d6b36/ood-portal-generator/lib/ood_portal_generator/dex.rb#L33

I could be imagining the use case, but it seems like eventually someone's going to override this and listen on a specific interface.

**Comment by treydock** [comment]
I think this is a non-issue. If you have multiple interfaces, and listen on 0.0.0.0, external traffic will come in via whatever route is default or responds to whatever IP is accessed via the DNS record being used to access Dex. There really is no benefit to setting which IP to listen on for something public facing. The only time I've ever cared about the listening IP of something on multihome is when I DID NOT want that service to be public, so you point it at private IP.  There really is no issue with listening on all interfaces, the traffic will still come in on whatever interface is responsible for the DNS record and IP being used to access Dex and OnDemand.

**Comment by johrstrom** [comment]
Works for me. I guess if it comes down to it, they can setup an iptable rule to block traffic (or the modern equivalent if iptables is going away).

Sometimes a ticket is just a small piece of documentation. Or a place where someone can chime in later with new info.
