### ISSUE TITLE
locale fallbacks not working

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1252]
It should be the case that when a locale is not defined, it falls back to the default locale (en, english).

This is however, not the case as you can see.  Here `en.dashboard.shell_app_title` is defined (while I was working on #916).  Even so, `en.dashboard.shared_apps_caption` is defined.  So why didn't it fall back to it?

https://github.com/OSC/ondemand/blob/06c0c9e11a25ef174457460c83887b50760d6b36/apps/dashboard/config/locales/en.yml#L141 
![image](https://user-images.githubusercontent.com/4874123/123475900-0ccfff00-d5ca-11eb-8a0b-118156c2d59b.png)

**Comment by treydock** [comment]
If I had to guess, it's because the fallback is enabled: https://github.com/OSC/ondemand/blob/master/apps/dashboard/config/environments/production.rb#L69 but no default locale is defined: https://github.com/OSC/ondemand/blob/master/apps/dashboard/config/application.rb#L37

**Comment by johrstrom** [comment]
Yea I think so too.  We're setting the locale in the controller (not through rails, but directly in the I18n library) and not in the boot process.  I even tried to set fallbacks directly to `[:en]` but no love. 

https://github.com/OSC/ondemand/blob/06c0c9e11a25ef174457460c83887b50760d6b36/apps/dashboard/app/controllers/application_controller.rb#L10-L14

In any case, I spent 45 minutes on it and couldn't fix it quickly without some larger change that I hadn't yet tried.

**Comment by johrstrom** [comment]
This actually is not even cosmetic.

The files app literally fails to load because an exception is thrown in the ERB rendering of some pages.
![image](https://user-images.githubusercontent.com/4874123/128220030-f8a30239-1df3-4564-ae83-a38e266c4dab.png)

Not sure how I got pinned apps to show in the original image, but now they also fail because the exception is thrown during ERB rendering. Probably because I was working on the shared apps feature and that used a different page than pinned_apps at that time.
![image](https://user-images.githubusercontent.com/4874123/128220252-6df411e8-0f09-4549-a475-64e180e2d6bf.png)
