### ISSUE TITLE
Better way to handle API client secrets?

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1262]
In #1257 we write files that are the client id and secret to the APIs.

Sites are going to make these files. Automation can make the directories, so we can ensure the directory isn't world executable, otherwise the secrets leak.  I'm wondering if there's any other strategy we can employ to be sure these won't leak their information. 

The file name _is_ the content, so just being able to _see_ the file means you know the secret.  I'm wondering if there's a better, more secure, way to handle this.  To actually put the secret in the file itself and have apache read it (through environment variables?).

I guess I'm just worried the file name is easier to leak than the file contents.

**Comment by adaybujeda** [comment]
If you prefer, Apache `mod_rewrite` offers a way of using the contents of a file to map values to a `RewriteCond`.

Using this feature sys admins can add API client secrets to the file and will not be visible listing the files in the API root directory.

We didn't use this feature as we thought that protecting the directory was as secure as protecting the file and individual files are easier to manage and should be more performant than reading a single file that could grow quite big overtime.

**Comment by treydock** [comment]
I personally think securing the directory is good enough and like you said is as secure as protecting the file.

**Comment by johrstrom** [comment]
> I think we just need to put this parent directory into package and ensure only readable by Apache user as well as automate.

That works for me I suppose. Really we just need to reduce the chance for human error. If the packaging can create and chmod it, that'll work for me.

**Comment by johrstrom** [comment]
This was fixed in #1264. RewriteMap is available in 2.4.29 and later which I think is lower than the centos:7 version we use?

In any case, we'll have to rely on permissions of the parent directory for the time being.
