### ISSUE TITLE
ActiveJobs: Set default view as "My Jobs"

### ISSUE THREAD

**Issue by nickjer** [OSC/ondemand#127]
Updated description:

1. do not cache the previously used filter beyond the current browser window session. so if you go to https://ondemand.osc.edu/pun/sys/activejobs you always should end upt at https://ondemand.osc.edu/pun/sys/activejobs?jobcluster=all&jobfilter=user
1. revisit pbspro adapter implementation to determine whether a better approach could be had that would not involve getting all of the job array information in the request

- - -
It seems at Arizona they can have upward of 10,000+ active jobs on a single cluster. This can make a simple `qstat` take 3+ minutes.

In most cases people are interested in only their jobs, so maybe it would be best to make the default view when people visit:

https://ondemand.osc.edu/pun/sys/activejobs

set to "My Jobs" and "All Clusters". And allow them to change it through the query values we already established, e.g.:

https://ondemand.osc.edu/pun/sys/activejobs?jobcluster=oakley&jobfilter=all

for "All Jobs" and "Oakley" using the buttons. This would reduce the strain on the batch servers. For example if one user calls `qstat` for all jobs, then this will affect other users who call `qstat` with simpler conditions due to the heavy load this places on the batch server.

Note: This would hinge on us adding the `#info_where_user` optimization to the corresponding job adapters.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737424755965) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
reviewed,
browser already saves settings,
nothing to do
