### ISSUE TITLE
ssh_to_compute_node? fails when cluster does not exist

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1273]
With the addition of `ssh_to_compute_node?` there's something in there that doesn't check for nil or rescues this error. 

```text
COMPILER MESSAGES AND/OR LISTINGS: #<ActionView::Template::Error: Session specifies nonexistent 'quick' cluster id.>

/var/www/ood/apps/sys/dashboard/app/models/batch_connect/session.rb:179:in `cluster'
/var/www/ood/apps/sys/dashboard/app/models/batch_connect/session.rb:512:in `cluster_ssh_to_compute_node?'
/var/www/ood/apps/sys/dashboard/app/models/batch_connect/session.rb:503:in `ssh_to_compute_node?'
/var/www/ood/apps/sys/dashboard/app/helpers/batch_connect/sessions_helper.rb:98:in `host'
/var/www/ood/apps/sys/dashboard/app/helpers/batch_connect/sessions_helper.rb:40:in `block (2 levels) in session_view' 
```

Here's the DB json that can replicate.

```
{"id":"df1747eb-b8a5-456c-b83f-c87eb66cf66f","cluster_id":"quick","job_id":"34370.quick-batch.ten.osc.edu","created_at":1598547424,"token":"sys/bc_desktop/vdi-owens","title":"Owens VDI","view":null,"info_view":null,"script_type":"vnc","cache_completed":null}
```

 Without looking into it further, I'm guessing we can short circuit somewhere given this job is likely completed or can't be queried for anyhow.

**Comment by treydock** [comment]
Is there a way to purge the database of invalid entries? That appears to be from when we ran Torque/Moab and there was a dedicated `quick` cluster.  The give away is the JOB ID, those job IDs only existed in that `quick` Torque/Moab cluster.  The cluster simply doesn't exist anymore

**Comment by treydock** [comment]
Also based on the stack trace, it's not an issue with nil. It's this: 

https://github.com/OSC/ondemand/blob/c48a68a0bbc1cb11822bd7c40259bc17e3459bbf/apps/dashboard/app/models/batch_connect/session.rb#L179

The changes to add `cluster_ssh_to_compute_node?` did not introduce that exception logic, it was already there, just likely never getting called.

**Comment by johrstrom** [comment]
Yea they're just files that can be removed to fix the issue. It's just a matter of support tickets and so on, having a user manually delete the file.

It'll get deleted when the card is deleted, but now that you mention it - why does the file exist when it should have been cleaned up after 7 days?
