### ISSUE TITLE
ActiveJobs: Maybe look into saving user's preferences server side

### ISSUE THREAD

**Issue by nickjer** [OSC/ondemand#128]
It may be better to save the user's preferences for Cluster and Filter server side:

* removes javascript from code
* preferences are saved across browsers and locations

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737369870096) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
reviewed,
good issue but other user's preferences (dark mode) have higher priority
