### ISSUE TITLE
Rake task for Job Composer db re-population

### ISSUE THREAD

**Issue by Oglopf** [OSC/ondemand#1289]
Sometimes users must remove or rename the `production.sqlite3` db file when using the Job Composer in their `~/ondemand/data/sys/myjobs` subdirectory. 

It would be nice for users to be able to run a `rake task` to re-populate the database file from the directory containing the job data so that the user can still access the job information from the Job Composer.

In reference to at least this discourse topic: https://discourse.osc.edu/t/ood-1-7-0-job-composer-issue-corrupted-sqlite3-database/1108/2

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737372244828) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I'm going to close this as a won't do because we're redoing the job composer without a database.
