### ISSUE TITLE
ActiveJobs: Add "Time Used" to the extended view

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#129]
The "Time Used" is visible on the main display, but it would also be useful to show it in the extended display, immediately before or after the "Walltime" entry.

![aj](https://cloud.githubusercontent.com/assets/2374718/25184907/c4bfcc58-24e9-11e7-806c-418ef1e356ee.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737322585993) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
already complete
