### ISSUE TITLE
ActiveJobs: Add header to 404 page

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#130]
https://github.com/OSC/ondemand-testing/issues/1#issuecomment-223654209

> Active Jobs: 404 page is not branded and the header disappears.

![](https://cloud.githubusercontent.com/assets/512333/15788565/2408abee-2996-11e6-94b5-ef2da5342362.png)

**Comment by ayushchatur** [comment]
@johrstrom  @ericfranz  @brianmcmichael  I believe this is take care of in version 2.xx ?

**Comment by johrstrom** [comment]
Yea this is complete because we moved activejobs into the dashboard, so it now uses the same error pages as the dashboard.
