### ISSUE TITLE
hello world Rust library

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1307]
in an effort to explore #1306, let's start a Rust apache module.

I think writing our own proxy may a solid option. Many proxies have lots of extra features for lots of use cases. Our use case is specific and I'd like to keep the attack/configuration surface extremely small.

I think Rust is a really strong language choice for such a use case given it's safety, speed and ease of deployment.

So this ticket is fairly simple, just to get us started exploring this option.

* [x] `rake build:mod-ood-proxy` task
* [x] the Rake task builds a binary that prints 'hello world'

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737325493267) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
Curious, why not Go?  Go is also secure, fast and easy to deploy (ie single static binary that works on all x86_64 systems).  I think might be worth considering both Go and Rust and see which one works best for our particular needs, unless there are already compelling reasons to focus only on Rust.

**Comment by treydock** [comment]
Also I don't know how complicated it is to install Rust and compile things but installing Go is a wget and tar extraction and update to PATH, and compiling things is extremely simple.

**Comment by msquee** [comment]
@treydock Jeff wanted a Dockerfile for the build process. Would you prefer building from source for RPM installations?

**Comment by johrstrom** [comment]
Seems like we'd just want to pull a non-apline rust official image to start with.  With the `feature/deb-packaging` there are build boxes but that's a bit down the road. I think just invoking an official rust image will work for the time being.  We want to use a container to build it, because that'll ensure the same version no matter what system building you're on.

As to Go vs. Rust, Go is a garbage collected language. I think there are troubles with it binding to C because of that reason (or at least trouble's I don't want to find out). That and memory safety are the big reasons.   We need to get C bindings to talk to apache effectively and I don't thing Go's garbage collection plays nicely with that (though I could be wrong).  

Go maybe secure, but not memory safe.  You can hit a nil pointer at any place.

But a lot of this is exploratory right now, but it'd be super nice to build out this Rust library and never use `unsafe`. I don't know if that's possible - but it sure would be nice.

**Comment by treydock** [comment]
You can't use docker or podman when building code inside the RPM build root, so for RPM builds we will have to build from source. The RPM build can specify a version of Rust to either install into build root for building or just pull in Rust RPMs as dependency if such things exist.  RPMs are built using mock, which is a tool to isolate builds into systemd nspawn "containers" so the build is isolated and the environment is pristine every time.  The way we invoke mock is inside a Docker container but even if we did Docker-in-Docker, the mock environment wouldn't be able to make use of Docker.

I'm not sure how Go isn't memory safe, nil pointers are usually only going to happen if you try to reference something from a pointer that isn't valid, which is very easy to avoid with proper coding that checks for nil pointers.  Also for C bindings, there are plenty of places I've seen projects use C bindings so I know they work, like NVIDIA uses them with DCGM exporter to interface with NVML C library for getting GPU data into Go.  There are many places with other Go projects I've seen where they use C bindings and as far as I've seen there are no issues.

**Comment by johrstrom** [comment]
You are sure how Go isn't memory safe because you say "proper coding that checks for nil pointers". 

You literally can't reference nil pointers in Rust. Or at least you have to do it explicitly in an `unsafe` block. It checks all your references at compile time, not runtime, so it won't compile if you have a nil pointer somewhere.

To C bindings - yea I'm not super well versed in it. You've seen projects with no issues, but search in their issues and I'll be there were some. Googling "c bindings in go memory management" gives some of this away. Honestly I don't want to have to worry about memory management if we can avoid it.

Having c bindings from another language is new territory for me, especially as we need to bind to apache a 20 year old project. It just _seems_ like Rust for something so critical.

Discussions around building this for production use are very far off - like 6 months at best.
