### ISSUE TITLE
ActiveJobs: Remember which jobs someone is viewing and reopen them on refresh.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#131]
See https://github.com/OSC/ondemand-testing/issues/1#issuecomment-223649965

> Even though we don't have job selection, we should probably record the jobs that you are currently viewing... so that when we update the datatables we can "scroll you" to that location in the list, anchroing the view to the first job that is expanded.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737376198013) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I'm not entirely sure this is an issue any more.  I mean, I don't think active jobs updates unless you navigate or filter the requests.  

Automatic updates don't happen anymore, so this situation won't happen.  Unless we want to cache the job we're looking at when we filter?  I vote close.

**Comment by matt257** [comment]
reviewed,
closed as no longer an issue
