### ISSUE TITLE
ActiveJobs: Merge job status app into the dashboard

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#134]
i.e. /jobs or a JobsController added to the dashboard

This will partly address AweSim-OSC/osc-ondemand#81 because the dashboard menu will be above this view. The javascript may need to be adjusted so that it affects only appropriate divs etc. on this page - of course it can be loaded on any other page.

Add a more detailed design/plan of integrating and any modifications required before proceeding.

**Comment by johrstrom** [comment]
This was completed in 2.0. It's now a part of the dashboard app.
