### ISSUE TITLE
ActiveJobs: Change change the "group" used in the Group filter

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#135]
An option for the future - lets not do this just yet though!

A dropdown that shows supplemental groups you are part of, perhaps as part of the middle "button" i.e. 

![screen shot 2015-10-12 at 2 34 04 pm](https://cloud.githubusercontent.com/assets/512333/10435508/75f093ce-70ee-11e5-933c-0a3982f2d0c7.png)

![screen shot 2015-10-12 at 2 33 53 pm](https://cloud.githubusercontent.com/assets/512333/10435511/7cd07b1e-70ee-11e5-95f9-87b5ad6067ff.png)

* The filter would be by the Group selected
* The filter chosen would be stored in a cookie (along with the current state of the other controls)
* The text would display: "Your Jobs", then "PAW0003's Jobs", then 
* Or if the group name is not known by the user, maybe "Your Group's Jobs" (these users aren't going to be using a terminal by default)

Adding the dropdown inside the input selection is a little tricky though - styles will have to be modified with custom CSS.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737331705176) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Looks like we already have something similar [here at osc](https://github.com/OSC/osc-ood-config/blob/master/ondemand.osc.edu/apps/activejobs/initializers/filter.rb).  Do we want to do this in a different filter or add this functionality to the application? 

I'd think we should add it to the app and set it behind a flag.  My preference is probably that this is enabled by default and the flag(s) disable it.

**Comment by matt257** [comment]
reviewed as a team,
will reopen if requested
