### ISSUE TITLE
Feature Request: Node/Core specific data visualization

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#136]
Dave demonstrated a feature in Eclipse Parallel Tools that shows a view consisting of all of the nodes in a cluster. Each of those nodes is divided up into cores and they are color-coded and selectable based on the running jobs on that system.

He suggested an enhancement to the Job Status page that performs similar behavior.

![ptp-trestles-0318](https://cloud.githubusercontent.com/assets/2374718/10435082/d6ced712-70eb-11e5-84bb-dcdfd4c46316.png)

**Comment by ericfranz** [comment]
This is not a well defined feature. What questions are the we answering with a graphic like this? If we identify those questions, there are likely better graphics. Consult [Information Dashboard Design](http://www.stephen-few.com/idd.php) for guidance on this.
