### ISSUE TITLE
ActiveJobs: Feature Request: Favorite Jobs

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#137]
Dave requested a feature that allows a user to select favorite jobs and filter view by those favorites.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737332867457) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
This should be an OnDemand-wide feature. You can toggle a job as "favorite" in Active Jobs, and it displays as favorite in: Job Composer, Interactive Sessions, Completed Jobs. And then we might add a tiny widget of "favorite jobs", running and completed, on the front page of OnDemand. Information about "favorite jobs" could appear in XDMoD.

**Comment by johrstrom** [comment]
I'm going to close this as a job is ephemeral. Maybe you have a favorite shell script or project location, but jobs come and go - so it's not clear to me why you'd want to have favorite jobs.
