### ISSUE TITLE
add automation for updating the changlog

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1388]
With this command I can get a few lines of text from the git log. We should add (weekly, bi-weekly?) automation to pull this info and update the changelog. The PR that's made through the automation won't be mergeable directly - but could give us a good start that we could fix up inline through the GH editor.  This would help us keep the changelog up to date while we deploy nightlies.

```
[jeff 12:02:37 src(master)] 🐢 git log --after=$(date -d '7 days ago' +%Y-%m-%dT%00:00:00) --pretty=format:%s
update dependencies (#1376)
Support nightly RPM builds (#1367)
```

**Comment by treydock** [comment]
There are also tools to do this, I use github-changelog-generator on my Puppet modules, it's Ruby based so can integrate with Rake and can classify things based on labels like whether things are bug fixes, enhancements or breaking changes.

Example changelog: 

https://github.com/treydock/puppet-module-keycloak/blob/master/CHANGELOG.md

The Rake task to run `rake changelog`:

https://github.com/treydock/puppet-module-keycloak/blob/aa2ff7f956c78c4c5c391d6133fdced32419214c/Rakefile#L46-L70

Project URL: https://github.com/github-changelog-generator/github-changelog-generator
