### ISSUE TITLE
Shell: Shell Themes

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#141]
Updated description: see below for full convo. Summary:

1. If a file `~/.config/ondemand/apps/shell/themes/default.itermcolors` exists, that is the theme that will be used instead of the default theme for the shell app. Use `glob('default.*').first` in this directory to get the first default named theme, regardless of extension.
2. We want to support several formats. This repo https://iterm2colorschemes.com/ has an example of different theme types. The differentiator should be based on the extension.
3. The theme should be a json representation of a JavaScript object that looks like the [argument to the set function in this example PR](https://github.com/OSC/ood-shell/pull/69/files#diff-0fee1be8218cc43a268be5a23c313f2fR72-R96). It can be fetched from the Express app at an end point at the top of the HTML page, before the rest of the JavaScript executes that sets up the websocket connection.
4. If multiple themes or other themes besides default is in this directory, the list of themes can be presented to the user in a dropdown in the top right corner of the shell app like in https://github.com/OSC/ood-shell/pull/69. The default theme will appear first and be the initial theme, and will be either the default black theme or the default specified as stated above.

***

This has been requested several times in the past 2 weeks.

This would be for adding simple themes that just theme the client side colors, but do not affect server side formatting (such as using blue for directories).

If a shell app is started using a web form (for example, on the page that shows active shell sessions you can reconnect to OSC/ood-shell#66), this would be a natural place to also choose the theme.

Another consideration would be a tiny button in the top right corner to provide access to a themes dropdown, or an optional persistent menu like on other pages (as discussed in the original issue OSC/ood-shell#7).

The idea is to expose the hterm object to a function that can change the preferences. This is a crude example: https://github.com/OSC/ood-shell/pull/69

If we did this, some ideas include using a function to convert shell theme files from .itermcolors files into a "theme" that can be applied. A site or user could import https://github.com/mbadolato/iTerm2-Color-Schemes for 200 different themes for their use, and we wouldn't need to concern ourselves with any licensing issues.

**Comment by samirmansour** [comment]
Here is my design proposal for the terminal to incorporate the new shell themes and the sessions. The styling will definitely improve, but the basic idea I have is to have a button on the top right. Enough to not be too hard to find but also non-intrusive to the app itself. When you click the button you go to the menu with the options of themes and sessions.

**Comment by samirmansour** [comment]
In addition, the themes work by looking through a directory called themes in the home directory for the user. To name the themes you just need to change the file name. an example like **adventure_time.itermcolors** would turn into **Adventure Time** on the menu. Currently there are 10 themes supported.

- .itermcolors
- .colorscheme
- .colors
- .terminal
- .config
- Termite
- .config_0
- .theme
- .xrdb, Xresources

**Comment by ericfranz** [comment]
>In addition, the themes work by looking through a directory called themes in the home directory for the user.

As suggested at the top of this issue, this directory should be `~/.config/ondemand/apps/shell/themes/`, where the env var `XDG_CONFIG_HOME` points to `~/.config`. Also, the env var`OOD_APP_CONFIG_ROOT` points to `/etc/ood/config/apps/shell`.

So pseduocode:

```ruby
user_shell_themes_dir = Pathname.new(ENV['XDG_CONFIG_HOME'] || '~/.config').join('ondemand', 'apps', 'shell', 'themes')
system_shell_themes_dir = Pathname.new(ENV['OOD_APP_CONFIG_ROOT'] || '/etc/ood/config/apps/shell').join('themes')
```

Then to get the list of all the themes, you build the list from both locations. If a user shell theme is named the same as a system shell theme, the user's one overrides this.

**Comment by ericfranz** [comment]
I'd recommend we start with a home page that displays themes and sessions (or new session) when the user's go to and postpone any modification to an open shell session:

![image](https://user-images.githubusercontent.com/512333/72169402-0d0c1880-339d-11ea-99fb-e43aaa90fa4d.png)

This home page could be accessed if going to `https://ondemand.osc.edu/pun/sys/shell` or `https://ondemand.osc.edu/pun/sys/shell/` (note path does not contain `/ssh` or `/session` etc.

Keep this home page the simplest possible, and we can iterate on the rest of the code till its solid. Then save any dynamic menu or other options for last.

**Comment by ericfranz** [comment]
Fixed themes addressed in https://github.com/OSC/ondemand/pull/630. Will add separate issue for customizable themes.
