### ISSUE TITLE
Ruby conflicts when installing OOD on RHEL 8

### ISSUE THREAD

**Issue by ndusek** [OSC/ondemand#1413]
Hello,

We are deploying a new instance of Open OnDemand 2.0 on RHEL 8.4 (4.18.0-193.el8.x86_64) and we're running into issues resolving Ruby dependencies with yum. Here are the issues, in order:

1. Cannot enable `ruby:2.7` module without disabling `ruby:2.5`
When running step 2 from [Install Software from RPM](https://osc.github.io/ood-documentation/latest/installation/install-software.html), the following error is thrown:
```
~# dnf module enable ruby:2.7
Updating Subscription Management repositories.
Last metadata expiration check: 0:02:05 ago on Mon 27 Sep 2021 09:05:48 AM CDT.
Dependencies resolved.
The operation would result in switching of module 'ruby' stream '2.5' to stream '2.7'
Error: It is not possible to switch enabled streams of a module.
It is recommended to remove all installed content from the module, and reset the module using 'dnf module reset <module_name>' command. After you reset the module, you can install the other stream.
```
Running a `dnf module reset ruby` and then rerunning `dnf module enable ruby:2.7` seems to work, but results in disabling `ruby:2.5`. This causes a problem later down the line (see below).

2. After disabling `ruby:2.5` and enabling `ruby:2.7`, `yum install ondemand` fails for various reasons, some seemingly related to ruby.
```
~# yum install ondemand
Updating Subscription Management repositories.
Last metadata expiration check: 0:03:49 ago on Mon 27 Sep 2021 09:05:48 AM CDT.
Error: 
 Problem: problem with installed package libselinux-ruby-2.9-5.el8.x86_64
  - package libselinux-ruby-2.9-5.el8.x86_64 requires libruby.so.2.5()(64bit), but none of the providers can be installed
  - package libselinux-ruby-2.8-6.el8.x86_64 requires libruby.so.2.5()(64bit), but none of the providers can be installed
  - package libselinux-ruby-2.9-2.1.el8.x86_64 requires libruby.so.2.5()(64bit), but none of the providers can be installed
  - package libselinux-ruby-2.9-3.el8.x86_64 requires libruby.so.2.5()(64bit), but none of the providers can be installed
  - package libselinux-ruby-2.9-4.el8_3.x86_64 requires libruby.so.2.5()(64bit), but none of the providers can be installed
  - package ondemand-passenger-6.0.7-1.el8.x86_64 requires libruby.so.2.7()(64bit), but none of the providers can be installed
  - cannot install both ruby-libs-2.7.1-133.module+el8.3.0+7192+4e3a532a.x86_64 and ruby-libs-2.5.9-107.module+el8.4.0+10822+fe4fffb1.x86_64
  - cannot install both ruby-libs-2.7.3-136.module+el8.4.0+10728+4c884998.x86_64 and ruby-libs-2.5.9-107.module+el8.4.0+10822+fe4fffb1.x86_64
  - cannot install both ruby-libs-2.7.4-137.module+el8.4.0+12025+f744ca41.x86_64 and ruby-libs-2.5.9-107.module+el8.4.0+10822+fe4fffb1.x86_64
  - package ondemand-2.0.16-1.el8.x86_64 requires ondemand-passenger = 6.0.7, but none of the providers can be installed
  - cannot install the best candidate for the job
  - package ruby-libs-2.5.3-103.module+el8+2671+ebcc7ee0.x86_64 is filtered out by modular filtering
  - package ruby-libs-2.5.3-104.module+el8.0.0+3250+4b7d6d43.x86_64 is filtered out by modular filtering
  - package ruby-libs-2.5.5-105.module+el8.1.0+3656+f80bfa1d.x86_64 is filtered out by modular filtering
  - package ruby-libs-2.5.5-106.module+el8.3.0+7153+c6f6daa5.x86_64 is filtered out by modular filtering
  - package ruby-libs-2.5.9-107.module+el8.4.0+10822+fe4fffb1.x86_64 is filtered out by modular filtering
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
It's possible that something on our system is fundamentally broken, but I interpret the above to mean that ondemand needs `ruby-libs-2.7.x` but also depends on `libselinux-ruby` which is asking explicitly for `ruby-libs-2.5.x`. The result is that yum complains that it can't install both versions of `ruby-libs`.

**Comment by johrstrom** [comment]
@treydock any ideas?

**Comment by treydock** [comment]
I think you need to uninstall `libselinux-ruby` that was installed as part of Ruby 2.5 module and if needed reinstall it after enabling the Ruby 2.7 module.  I don't have a RHEL 8.4 system to test with, but using CentOS 8.4 and Rocky Linux 8.4 containers I'm not able to reproduce any issues with OnDemand pulling in anything Ruby and Selinux related. The only SELinux packages we pull in when installing `ondemand-selinux` is we pull in a few SELinux packages but nothing like `selinux-ruby`.  OnDemand does in fact need ruby-libs-2.7.x but because of issues with libselinux-ruby, that package got filtered out.

What I do notice is if I take a plain Rocky Linux 8.4 container, enable Ruby 2.7 module, then try to install `libselinux-ruby`, I get the same errors. So it looks like the issue is actually with libselinux-ruby which OnDemand does not need so my guess is you just need to uninstall that problematic package and it can't be re-installed since that non-modular package depends on a specific module which OnDemand can't have enabled.

**Comment by ndusek** [comment]
@treydock Thanks! That was the trick. After removing `libselinux-ruby`, ondemand installed without an issue.
