### ISSUE TITLE
Shell: Persist state in shells

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#143]
This feature is to persist state in shells so that users may, for example, exit out of OOD and come back several hours later to the same SSH session with all it's state in tact.

This is similar to the linux [screen](https://linux.die.net/man/1/screen) command or [tmux](https://github.com/tmux/tmux/wiki).

Essentially the users will be able to detach from the session and reattach later. This implies the session continues to run without the user.

The actual implementation of this feature is unclear at this time so this ticket is to hash out what that may look like.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737444035158) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
reviewed,
introduces security issues and would be difficult to implement,
maybe open a new ticket if we have other ideas
