### ISSUE TITLE
configurable option for how long cards stay

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1439]
Similar to this discourse topic, let's make this configurable.

https://github.com/OSC/ondemand/blob/f060e504758e3582d62c08a6130cb9d881f158ba/apps/dashboard/app/models/batch_connect/session.rb#L76

https://discourse.osc.edu/t/length-of-time-completed-job-cards-stay/1708/2

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737388693293) by [Unito](https://www.unito.io)

**Comment by mayank-agarwal-96** [comment]
I'd be happy to pick this up @johrstrom

**Comment by johrstrom** [comment]
Cool! I think looking at this config may give you something to emulate.

https://github.com/OSC/ondemand/search?q=file_download_dir_timeout

It could be as easy as this? 
```ruby
OLD_IN_DAYS=Configuration.ood_bc_card_time
```

Otherwise you'll have to do something like this and refactor the other pieces to use it.

```ruby
def self.old_in_days
  Configuration.ood_bc_card_time
end
```

Let me know if you have any questions. Here's a link to how to setup the dashboard for development.

https://github.com/OSC/ondemand/blob/master/apps/dashboard/README.md

**Comment by mayank-agarwal-96** [comment]
Thanks for all the info. I'll get back with an update

**Comment by mayank-agarwal-96** [comment]
I've opened [this](https://github.com/OSC/ondemand/pull/1776) PR. Do we write tests for such changes?
