### ISSUE TITLE
ensure e2e tests use local tar

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1467]
In a PR I've got open right now, we're pulling the 2.0.0 tar off of Github. This is failing because of a mime_magic dependency in that version that doesn't exist now.

My point is, if we were pulling say `2.0.18` the builds & E2E tests would pass, because they're testing that good tar.  We need some way to ensure that the packages in the CI pipeline are in fact built from a tar we just packaged and not tars off of Github.

**Comment by treydock** [comment]
If the failure was deb packaging action which shows as latest failure, it built tar locally as version 2.0.0:

https://github.com/OSC/ondemand/runs/3941535206?check_suite_focus=true#step:4:7

But the file being looked for is different:

https://github.com/OSC/ondemand/runs/3941535206?check_suite_focus=true#step:4:65

The code is master branch doesn't do that so maybe you are hitting a old e2e or packaging bug that just means need to merge lastest code into deb packaging branch.
