### ISSUE TITLE
Shell: Cat a large file (144MB, for example) and the shell app freezes while all the characters are being printed by JavaScript

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#147]
xterm.js has a solution for this:

1. https://github.com/sourcelair/xterm.js/pull/422
1. https://github.com/Microsoft/vscode/issues/17875

The easiest solution might be to move to using xterm.js instead of hterm.

In the short term we should consider documenting this limitation somewhere. This problem seems to make it difficult or impossible when working with the Apache Spark shell via hterm because commands will often print out a lot of data.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737474813673) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
reviewed,
will reopen if there is interest
