### ISSUE TITLE
debian apply patches

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1473]
Having a way to apply patches be good.  We need that resolve patch we applied to RPMs.  https://github.com/OSC/ondemand-packaging/blob/master/packages/passenger/patch.2021.resolver.txt.  With RPMs there is a specific way to patch RPMs before the application is compiled in build step, so if that exists for Debian be good to apply this patch just to cover all bases.  I'm fine with deferring it to another issue if that's preferred.

_Originally posted by treydock in https://github.com/OSC/ondemand/issues/1466#issuecomment-947130659_

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737447362442) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Where'd we leave this since we have packages for nginx passenger?

**Comment by treydock** [comment]
I think this can be closed. We build passenger and NGINX in ondemand-packaging repo so can add patches if necessary.
