### ISSUE TITLE
Remove "custom thor like framework" from nginx_stage and use optparser instead

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#15]
The current code for nginx_stage is hard to work with. Part of the reason is that the code that builds the CLI is mixed with the code that does the work. This is similar to if in a Rails app, there were no models and all the code was in controllers.

It would be much easier to understand for developers new to the code base, and third party contributors, if we used optparser for the CLI portion, which could neatly fit in a single file, and then simple objects and modules with many functions - no inheritance, and no module include statements.

You can use optparser for subcommands: https://gist.github.com/rkumar/445735

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737393394244) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
The first step is to write a test suite for the CLI tests the outer boundary of the application.

Currently the application starts with an invocation of `NginxStage::Application.start` which then utilizes `ARGV` directly. The body of this should be moved to a separate method that accepts `ARGV` as an argument, such as:

```ruby
def self.start
  cli(ARGV)
end

def self.cli(argv)
  ARGV << "--help" if ARGV.empty?
  command = ARGV.first[0] != '-' ? ARGV.shift : nil

  generator = commands.fetch(command) do
    command ? raise(InvalidCommand, "invalid command: #{command}") : nil
  end

  parser = generator ? cmd_parser(command, generator) : default_parser
  parser.parse!( ARGV )
  generator.new(options).invoke if generator
rescue
  $stderr.puts "#{$!.to_s}"
  $stderr.puts "Run 'nginx_stage --help' to see a full list of available command line options."
  exit(false)
end
```

Then tests can be written around `Application.cli`. The goal of the tests would be to have at least one example test of every possible sub-command + argument combination and to validate that the desired effect on the outside world occurs i.e. a particular system call is executed or a particular file is written to a particular location.

**Comment by matt257** [comment]
tests are a good idea for a first step,
thor may not be used anymore,
making a new GH issue if one doesn't exist
