### ISSUE TITLE
JobComposer: Export job data to CSV

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#150]
>I was wondering if there is a way to export the table data of all the jobs on the Job Composer webpage (i.e., a spreadsheet file where each row is a separate job and the columns are “Created”, “Name”, “ID”, “Cluster”, “Status” and if possible also the “Script Location” or Folder name)?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737393542118) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
With the project manager coming, I don't see this being implemented.
