### ISSUE TITLE
JobComposer: Creating a template should allow setting script name

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand#151]
The create template dialog only allows entry of the code path, but not the script to use by default. At the moment it appears to pick a random executable for the dir you specify. The only way I can see to fix this is to edit the manifest file after template creation.

Steps to recreate:

* New template
* Enter a code path
* Enter a name
* Hit save

New template is now shown with a job dialog on the right with a Script Name that was somehow chosen and is not changeable.

Thanks,
Louis

Copied from [Discourse](https://discourse.osc.edu/t/create-template-needs-way-to-specify-default-script-to-run/320).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737392600092) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I'm going to close this as won't do because we're redoing the job composer and it has different entities than just jobs and job templates.
