### ISSUE TITLE
JobComposer: Add support for markdown rendered localizations

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#153]
Out of the box Rails supports translations with html: https://guides.rubyonrails.org/v4.2/i18n.html#using-safe-html-translations

For example, we use this on the main page. It would be nice to have the option to use markdown here, like we do in other locations (manifest, batch connect). For fields we accept markdown support, we would also want to support plain text and html.

There are several complications:

1. The only mechanism to indicate the text provided is markdown is using the key name. This is problematic because if the view uses `t('welcome_html')` then `welcome_md` localization will not be used. The solution would appear to be a custom backend that actually handles multiple cases. For example, the backend translate method could take `welcome` key (from the view `t('welcome')` and try `welcome_md` then `welcome_html` if `welcome_md` is not found and then `welcome`. The problem is that if we take this approach and the base config has `welcome_md` then a custom `welcome_html` might never be used. We could just support markdown in specific fields, removing the ability to use straight html. That would be less flexible but might work okay, since you can embed html in markdown it might be okay.
1. Markdown renderers always surround the text with `<p>`. For text meant to be "inline" like many translations are, we would need to omit support for markdown or use a different markdown renderer than the default.
1. We need a custom backend regardless. Here is an example of how to do custom behavior based on the key extension: https://www.justinweiss.com/articles/rails-i18n-3-quick-tips-and-1-crazy-abuse/. Be careful to subclass the same backend that is used by default in Rails. I don't know if it is `I18n::Backend::Simple` or an Active Record subclass of that. Also, there is `Chain backend` for multiple backends.
1. Any work that increases the complexity calls for the use of fragment caching in the dashboard for these sections.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737452690755) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I'm closing this as won't do because we're re-working the job composer anyhow. (but also I'm not super in love with folks being able to use ERB & html in the things they render & share, so they'll be using plain text for the time being in descriptions and metadata they provide to projects)
