### ISSUE TITLE
JobComposer: App should not reference `OodAppkit.dataroot` directly

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#155]
This access should only occur in the ConfigurationSingleton class.

https://github.com/OSC/ood-myjobs/blob/e152e19af1a3285672cf78d1964ee90620a647ef/app/models/workflow.rb#L69-L71

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737484092323) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as won't do as we're rewriting the job composer anyhow.
