### ISSUE TITLE
JobComposer: If cluster config doesn't specify title in metadata section, a crash may occur

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#156]
Wherever we try to use
https://github.com/OSC/ood-myjobs/search?q=metadata.title&unscoped_q=metadata.title

we fall back on the cluster.id for the title. The cluster id is a symbol. So if we don't coerce to a string we end up with a crash like https://github.com/OSC/ood-dashboard/issues/395. The right solution is to fix https://github.com/OSC/ood_core/issues/98 and then use that wherever we want a title.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737400757001) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I'm going to close this as won't fix because we're re-writing the job composer.
