### ISSUE TITLE
support multiple vhosts

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1568]
Yale has this patch they need to support multiple vhosts. Let's merge it here. I'm also thinking we could backport to 2.0 given we're going to 20 anyhow.

https://github.com/ycrc/ood-user-mapping/blob/main/ood-portal.conf.erb.patch

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737401767401) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Actually, multiple vhosts looks more like this. I think we should do both, in 2.1. in 2.0, we can just provide the Servername in the plain http vhost.

https://github.com/ycrc/ood-user-mapping/blob/main/macro.conf

**Comment by johrstrom** [comment]
@treydock FYI.  with all the Rails work we're doing with profiles, especially #2127 - we'll need apache to respond to multiple hostnames.  I have the Yale thing linked here which I don't recall what it does, but the use case we're looking for is something like merging ondemand and class together and providing different views at the Rails layer based on the hostname of the request.

**Comment by treydock** [comment]
If all that's needed is different names then we could just do this:

```
ServerName ondemand.osc.edu
ServerAlias class.osc.edu
```

That might be all that's needed depending how the OnDemand code gets the hostname.

**Comment by johrstrom** [comment]
OK so just a `server_aliases: []` in `ood_portal.yml`.

I wonder if that'll solve Yale's requirement. It seems so - they're just doing the same with macros instead of aliases.

https://github.com/ycrc/ood-user-mapping/blob/ca6de35940b6c672f22cc49a30056c88186effa2/macro.conf#L176

> That might be all that's needed depending how the OnDemand code gets the hostname.

The Rails app will get the `hostname` from the HTTP request. So if an FQDN/ip routes to a PUN they'll see `ondemand.osc.edu` or similar in the request itself.

**Comment by treydock** [comment]
Aliases are a much more common and easy way to handle this if all that's changing is the hostname used for the Vhost.  I think macros would make sense if more was changed than just the hostname.

**Comment by johrstrom** [comment]
Cool I'd just like to ping Yale and let them know they don't have to patch stuff anymore that we have some native solution that works for them.

Sounds like `ServerAliase`s it is.
