### ISSUE TITLE
JobComposer: Loading button finishes early

### ISSUE THREAD

**Issue by nickjer** [OSC/ondemand#157]
I decided to open a separate issue for this as it is a small bug and shouldn't hold back the more important work.

You can reproduce this from MyJobs by:

1. Click a different job in the table
1. The loading button appears and spins, until Job Details appears, then it **disappears**
1. But if you wait a little longer, the Submit Script appears with the buttons to "Open Editor", "Open Terminal", and "Open Dir" below the Job Details.

So the loading hasn't fully completed and the user may begin to scroll down expecting to see the Submit Script details box.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737401977100) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as won't do because the new job composer will have it's own UI with it's own bugs/features.
