### ISSUE TITLE
/logout doesn't work super nice with mellon

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1590]
Logging out with `mod_auth_mellon` isn't a super nice experience. The user ends up hitting a 404. They're actually logged out - but we can't seem to get the redirect to work well.

https://github.com/latchset/mod_auth_mellon

**Comment by bp85** [comment]
@johrstrom this seems to be working

I've to set ReturnTo to ood homepage(https://site_ood_fqdn) and when I logout now I'm being re-directed to single signon login page, but I think having an intermediate logout page would be helpful for users.

```
logout_uri: /logout
logout_redirect: "/mellon/logout?ReturnTo=https%3A%2F%2FOOD_FQDN"
```

**Comment by bp85** [comment]
without `ReturnTo=` Mellon would just throw errors.

**Comment by johrstrom** [comment]
OK - so it just seems like an issue of documentation then right?

https://github.com/OSC/ood-documentation/issues/594

**Comment by bp85** [comment]
Pretty much. I think we can close this issue for now
