### ISSUE TITLE
Active Jobs app sorts incorrectly

### ISSUE THREAD

**Issue by keithosu** [OSC/ondemand#1594]
Running the "active jobs" app and clicking the sort up or down arrows. The time value is not sorted properly.

example clicking the up arrow (ascending sort):
11:35:21
142:54:26
19:57:53
202:02:11
23:38:42

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823531450170) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Thanks for the ticket! Looks like it's currently a string comparison that we'd have to cast to a time or number.
