### ISSUE TITLE
JobComposer: Stop using incrementing # for job directory, and instead start using database id

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#160]
When staging for the first time:

1. Use database id as default.
1. If directory exists, then append `_1`.
1. Repeat, incrementing `_#` till a unique directory is found.

This will avoid the problem where you:

1. using the shell app, delete first job directory when the list of directories is ordered from high to low
1. go to job composer and verify row indicates associated directory is missing
1. create a new job in job composer; now two rows refer to the same job directory (fail)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737539735213) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
closing this as won't do because the new job composer has a different mechanism for the same thing.
