### ISSUE TITLE
Support Debian 11 and possibly 10

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand#1606]
Now that we have worked out Ubuntu 20.04 support, be good to expand a bit and also support Debian distros directly.  I think this is best after ondemand-packaging refactor to be a gem.

Debian 10 - Ruby 2.5 NodeJS 10
Debian 11 - Ruby 2.7 NodeJS 12

This compares to Ubuntu 20.04 which is Ruby 2.7 and NodeJS 10

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737540486538) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
@johrstrom or @Oglopf Have any requests come into Discourse about supporting Debian or has it all been about Ubuntu?

**Comment by Oglopf** [comment]
From what I've seen people do seem to say specifically say "Ubuntu" when asking around "Debian" support, though some do leave it general. Ubuntu seems to be the more popular phrase though.

**Comment by johrstrom** [comment]
That's fine, I think if someone wants Debian proper we can deal with it when it comes.
