### ISSUE TITLE
dynamic BC javascript not parsing jupyter args correctly

### ISSUE THREAD

**Issue by gbyrketosc** [OSC/ondemand#1607]
Hi Jeff.

Here are my findings during the testing of Jupyter form without form.js

Cluster: pitzer
Node Type: 40 core
Number of cores should be maxed at 40, but actually maxes as 28

Cluster: pitzer
Node Type: 48 core
Number of cores should be maxed at 48, but actually maxes as 28

In this section, we have a duplicate.  It appears that the second line should read:
data-max-num-cores-for-cluster-owens: 28,

"debug",   "debug",
data-max-num-cores-for-cluster-pitzer: 28,
data-max-num-cores-for-cluster-pitzer: 48,

Cuda options (8.0.x) are not disabled for Owens cluster. Same result on prod. Should they be?

_Originally posted by @gbyrketosc in https://github.com/OSC/bc_osc_jupyter/pull/78#pullrequestreview-808958047_

**Comment by johrstrom** [comment]
We're don't seem to be normalizing `any-40core` as an option right. We cast back and forth between snake_case and mountainCase.

You can see the lookup table here. `xIdxLookup`'s key is `any-40core` but through whatever casting `x` is `any__4_0core`. 

![image](https://user-images.githubusercontent.com/4874123/142291114-19e0d181-b28b-43b4-84d9-f93e4a121141.png)

I took this from a breakpoint around here. Here `minMaxLookup[changeId].get('any__4_0core', y)` is undefined so there's no change. Hence the bug.

https://github.com/OSC/ondemand/blob/e88b6f15acd67d92ed35d938699c0b388a63b5b2/apps/dashboard/app/javascript/packs/batchConnect.js#L369
