### ISSUE TITLE
JobComposer: Replace ActiveRecord with key-value store

### ISSUE THREAD

**Issue by nickjer** [OSC/ondemand#161]
Currently we use ActiveRecord along with SQLite3 databases. Unfortunately there are few drawbacks to this:

* a DB needs to be created before Rails is started
  * this is usually done with a `bin/rake db:setup` call before you start Rails
  * this currently handled by the Dashboard app calling the apps `bin/setup-production` before redirecting the user to the app
  * this can confuse first time developers when a freshly generated Rails app raises an error upon first loading
* in our current setup it is impossible for an app to run a DB migration
  * this is currently handled by just creating a whole new app in a separate directory
  * we try to alleviate this problem by guessing the tables (e.g., Workflows, Jobs, Uploads, ...) ahead of time and including a catch-all JSON column in each table

Using a single key-value store would solve both of these problems, but also introduce some other problems (e.g., slower lookup times, less third-party support, ...). In my opinion a key-value store's benefits outweigh its cons when dealing with our "per-user web server" model. But this is just one man's opinion.

Note, one of the leading Ruby gems for key-value stores is [Moneta](https://github.com/minad/moneta), but I am not married to it.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737540853646) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as a won't do. The new job composer is just going to use files.
