### ISSUE TITLE
WHITELIST_PATH prevents file deletion in 2.0.13

### ISSUE THREAD

**Issue by maflister** [OSC/ondemand#1610]
The `WHITELIST_PATH` setting enforces path restriction, but it also prevents file deletion. Please advise.

**Comment by maflister** [comment]
Resolved in 2.0.16. Apologies for not checking all versions first.

**Comment by johrstrom** [comment]
No worries. Yes you're right, it was likely a duplicate of #1337 which as you indicate got fixed at some point in the release cycle.
