### ISSUE TITLE
Using different port than 443 (in container)

### ISSUE THREAD

**Issue by Micket** [OSC/ondemand#1614]
I wanted to try setting up a test instance next to my production container, so I can test deployments. I found configurations parameters
`listen_addr_port` and `port`  in `ood_portal.yml`  but these seem to do nothing, and the page redirects everything i try back to `:443`. 
Is this doable at all?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737462155008) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Hey - sorry I'm just now seeing this or getting back to it.

I think you also need `servername` set to localhost for redirects to work inside a container.

**Comment by Micket** [comment]
Sorry i even forgot i opened this ticket. I ended up running the test instance on another VM anyway, and I don't recall testing this proposed solution.

**Comment by johrstrom** [comment]
No problem at all. Just let us know if you run into more issues. I'm going to close this now just because I'm cleaning up old tickets, but I can reopen if you need.
