### ISSUE TITLE
Turn off Directory Indexes for public directory

### ISSUE THREAD

**Issue by karcaw** [OSC/ondemand#1617]
having the Indexes Option on in the apache config is frowned upon by Web Security folks:
http://cwe.mitre.org/data/definitions/548.html

Can we change:
```
  Alias "/public" "/var/www/ood/public"
  <Directory "/var/www/ood/public">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
  </Directory>
```
to
```
  Alias "/public" "/var/www/ood/public"
  <Directory "/var/www/ood/public">
    Options FollowSymLinks
    AllowOverride None
    Require all granted
  </Directory>
```

In the default ood-portal.conf.erb? https://github.com/OSC/ondemand/blob/cf10eec41dd95c6f35151201495ed96b02db61e4/ood-portal-generator/templates/ood-portal.conf.erb#L182

**Comment by gbyrketosc** [comment]
Closing this issue, as it has been resolved and pushed to production.
