### ISSUE TITLE
JobComposer: Create a script generation tool for creating batch headers

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#162]
Interest was expressed at PEARC for a tool to create batch script headers. This could be integrated into myjobs or exposed as a separate tool.

Some concerns 

1. I'm not sure if the current cluster config file contains the PPN's on a cluster.
1. This would require code for each adapter, the rosetta stone document can help with this, but other adapters would need additional research and testing.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737541593225) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I'm going to close this as won't do. Instead of using batch headers, the new job composer UI will just use a form that generates CLI arguments like batch connect apps.
