### ISSUE TITLE
logger lua error

### ISSUE THREAD

**Issue by stdweird** [OSC/ondemand#1625]
running 2.0.18 on el8, httpd logs have following error message (not fatal)
```
 AH01471: Lua error: /opt/ood/mod_ood_proxy/lib/logger.lua:22: bad argument #2 to 'date' (number has no integer representation)
```
line 22 is
```
msg["log_time"] = os.date("!%Y-%m-%dT%T", time / 1000000) .. "." .. time % 1000000 .. "Z"
```

**Comment by treydock** [comment]
I was able to reproduce using Docker images for OnDemand, found the logs in Apache error_log.  A fix is proposed in #1627
