### ISSUE TITLE
JobComposer: Add the ability to specify queue/partition in job options

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#164]
This was requested from an OOD site.

In Job Options, it would be nice to be able to specify (or select) the queue for a job. Currently, the only option is to do this via a header in the job script.

Without a solution to https://github.com/OSC/ood_core/issues/1 it seems the only option would be to add a text field to Job Options to type in the queue name if you want to specify it. I'm not sure of the value of this.

If the job_adapter for a cluster had a method to provide a list of queues/partitions, then we could create a dropdown, where the first option was <use default or specify in job script>, and then the rest of the options were the queues as returned by the adapter#queues method.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737462996314) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
At this point we can definitely do this, it's now just a question of if we want to.

**Comment by johrstrom** [comment]
I'm closing this as a won't do for the current job composer. The new job composer will allow for this, specifically with `auto_queues`.
