### ISSUE TITLE
rspec rubocop rules throw off projects without rspec

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1642]
I'm getting this error out of rubocop while in the dashboard.

```
unrecognized cop or department RSpec/MultipleMemoizedHelpers found in /users/PZS0714/johrstrom/ondemand/dev/dashboard/.rubocop.yml 
```

Not quite sure what our best option to do here is. Here's what I can think of off the top of my head

* include rspec everywhere
* remove the rspec rules and create an rspec rubocop that inherets the main one
* say the best practice is to open the entire project, not any given sub directory

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737347657911) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
@treydock I'm getting this error even when I'm loading projects that do have rspec. I wonder we have to enable `bundle` in our IDEs (our IDEs boot solargraph which boots rubocop which reads this file and throws this error)?   Do you just run this through the CLI or in an IDE?

**Comment by treydock** [comment]
I just run rubocop rake task from CLI
