### ISSUE TITLE
upload timeouts in the apache config

### ISSUE THREAD

**Issue by GKlouse** [OSC/ondemand#1646]
We noticed when uploading large amounts of data at once, file transfers were getting hung up.  Out IT department noted the following: 

> For v1.8 they don't have timeouts specified in the ood apache config. For fast / local filesystems, this works fine up to decent size uploads, but for network storage or filesystems that take longer for a copy operation after successful upload, this will time out and cause it to loop. I upped the apache Timeout and ProxyTimeout to 600 seconds from the unspecified default of 60.

We are currently using v1.8 & are preparing to upgrade our system to OODv2.0, which we understand has had a decent amount of work done to the Files App.  Is this something which has been addressed?

**Comment by johrstrom** [comment]
That specifically hasn't been addressed just because this is at the apache layer.

Looks like this is related to #706.  Is this solveable now just by adding a new file or does it need to be set in ondemand's vhost?

**Comment by GKlouse** [comment]
@johrstrom,
Sorry to leave you hanging, I have been working with our IT to debug a test run of OOD2.0 on our system, and they are implementing any changes which affect uploads into that rollout.  I will follow-up with you on what was done and how this has affected us so you/we can have a record of it. 

To answer your question, I believe this is at the apache layer, although I am not 100% sure at the moment.  We saw errors when uploading files as "small" as 1.8Gb, but have now been able to get it stable up to 10Gb file sizes.

**Comment by johrstrom** [comment]
TYSM. Yes please let us know what you find.

**Comment by GKlouse** [comment]
I didn't realize this was already posted on the discourse by our IT champion. 

(file size issues)
https://discourse.osc.edu/t/fails-to-upload-of-3g-file/1820

(upload to scratch, copy to target)
https://discourse.osc.edu/t/why-copy-operation-on-upload-file/1826

**Comment by johrstrom** [comment]
You still need to allow for these configs in our vhost though right?

```
modifications:
/etc/httpd/conf.d/ood-portal.conf
within <virtual host …>
Timeout 900
ProxyTimeout 900
```

**Comment by GKlouse** [comment]
Yes.

**Comment by johrstrom** [comment]
OK thanks. I'll leave this ticket open then so we can support it natively.

**Comment by johrstrom** [comment]
Actually, it'll be a part of #708 which will be in 2.1. Sorry for the spam.
