### ISSUE TITLE
clamp not working right

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1649]
This function `clamp` doesn't work right.

https://github.com/OSC/ondemand/blob/9cc2123b5f1b6b694b8ee5be8d72382284276810/apps/dashboard/app/javascript/packs/batchConnect.js#L393

1. Take an app like jupyter that has 28 cores for owens and 48 cores for pitzer.
2. enable this javascript
3. choose pitzer and the max becomes 48
4. set # of cores to 47
5. change to owens cluster

expected behaviour at this point is that cores should be set to 28 not 47.  If one chooses 48 in step 4 or skips step 4 it works. But it doesn't seem to be making the right comparisons.

**Comment by gbyrketosc** [comment]
Hi @johrstrom 

In response to the original Ticket.  
You wrote:  "I think the current form.js you have likely conflicts with these updates. Plus num_cores has it's own id which I don't believe is expected."

* The 1st things I did to troubleshoot was  remove the form.js file (which took away the 28 core limit on owens).
* I also removed the id from num_cores which had no effect.

Basically, those things which you told me to do, I had already tried them.

Thanks,
-gerald

**Comment by johrstrom** [comment]
I don't understand how your comment relates to _this_ issue specifically.  I know what you're referencing, but I don't see how it relates to this ticket.

**Comment by johrstrom** [comment]
It also seems like `clamp` needs to be outside of the [min,max] loop. There's another bug here where you clamp the max, then you clamp a second time.

So you end up shifting left (current value > new max) and _then_ shifting right (current value < new min) when the current value is at the maximum.
