### ISSUE TITLE
JobComposer: Link to someone else's template

### ISSUE THREAD

**Issue by nickjer** [OSC/ondemand#165]
A feature request @dhudak-osc brought up was being able to link to an instructor's or advisor's template so that as they update their template (i.e., fix mistakes) your linked template will get all of those changes live (the analogy being a symlink).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737542081145) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
duplicate of #183.
