### ISSUE TITLE
dynamic js doesn't seem to initialize right

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1650]
We're seeing mins and maxes aren't being updated on the initial page load. I mean if I 

1. have owens and pitzer with 28 and 48 maxes respectively 
1. load the page when owens is default
1. the max is still 48

The expected behavior is that the max is 28 right when you land on the page.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737266819092) by [Unito](https://www.unito.io)

**Comment by msquee** [comment]
@johrstrom 

Could this be a simple fix with something like this:

```js
window.addEventListener('DOMContentLoaded', (event) => {
  // ...
})
```

**Comment by johrstrom** [comment]
I think it all happens on  'ready' event, but I think this is the handlers are created right - but don't actually modify anything that very first time.

And specifically the min/max handler. It seems to require a 'change' event to actually start modifying things.
