### ISSUE TITLE
require node >= 12.13 on Debian 

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1654]
CI is failing right now to update dependencies on Debian systems. I think it's high time we start expecting node 12 on those systems.

```
error @npmcli/fs@1.1.0: The engine "node" is incompatible with this module. Expected version "^12.13.0 || ^14.15.0 || >=16". Got "10.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
/work/ubuntu-20.04/ondemand-2.1.0/gems/gems/rake-13.0.6/lib/rake/file_utils.rb:67:in `block in create_shell_runner': Command failed with status (1): [tmp/node_modules/yarn/bin/yarn --productio...] (RuntimeError)
```

**Comment by treydock** [comment]
For packaging, does the OS provide these versions or will we need to package NodeJS ourselves for the distros that don't provide it?

**Comment by johrstrom** [comment]
Most online resources say to do something like this.  Seems like we could add these to a mirror? I'd rather not repackage - I think mirroring or re-hosting would be best?

```
cd ~
curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh
```

All these do is setup the repo - so I'd say we'd probably want something similar?

```
exec_cmd "echo 'deb [signed-by=$local_node_key] https://deb.nodesource.com/${NODEREPO} ${DISTRO} main' > /etc/apt/sources.list.d/nodesource.list"
exec_cmd "echo 'deb-src [signed-by=$local_node_key] https://deb.nodesource.com/${NODEREPO} ${DISTRO} main' >> /etc/apt/sources.list.d/nodesource.list"
```

**Comment by treydock** [comment]
To streamline a site's deployment, to avoid a bunch of extra install steps, we could add that repo definition to the `ondemand-release` DEB package which installs the OnDemand apt sources. Would be trivial to add that though it also appears to add the GPG key that signs the repo, would have to also deploy that too with our package.  Then we could just say that we depend on whatever version of nodejs we need.
