### ISSUE TITLE
Migrate all Interactive Apps to implement Dynamic JavaScript in the Launch Forms

### ISSUE THREAD

**Issue by gbyrketosc** [OSC/ondemand#1657]
Before we can deploy Dynamic JS to production, we need to ensure that each Interactive app has this functionality implemented.
The apps to implement functionality are:
- [x] [OSC/ondemand/bc_desktop](https://github.com/OSC/ondemand/tree/master/apps/bc_desktop)
- [x] https://github.com/OSC/bc_osc_ansys_workbench/issues/32
- [x] https://github.com/OSC/bc_osc_abaqus/issues/13
- [x] https://github.com/OSC/bc_osc_comsol/issues/12
- [x] https://github.com/OSC/bc_osc_iqmol/issues/5
- [x] https://github.com/OSC/bc_osc_paraview/issues/15
- [x] https://github.com/OSC/bc_osc_pymol/issues/5
- [x] https://github.com/OSC/bc_osc_qgis/issues/5
- [x] https://github.com/OSC/bc_osc_schrodinger/issues/5
- [x] https://github.com/OSC/bc_osc_stata/issues/8
- [x] https://github.com/OSC/bc_osc_vmd/issues/6
- [x] https://github.com/OSC/bc_osc_codeserver/issues/24
- [x] https://github.com/OSC/bc_osc_jupyter/issues/89
- [x] https://github.com/OSC/bc_osc_jupyter_spark/issues/19
- [x] https://github.com/OSC/bc_osc_rstudio_server/issues/86

**Comment by treydock** [comment]
bc_desktop is part of this repo, it used to be separate app, now it's part of core ondemand, in the `apps` directory.

**Comment by Oglopf** [comment]
Not sure where to comment since this is referring to other repos.

What do we do for things like the Ansys app that looks to be doing more with its `form.js` than just setting cores and or hiding selections.

Also, I couldn't get this to work with the comsol app either but was unsure where to comment about that.

I'm not sure the desktop or iqmol needed to be on the list. I see no `form.js` in those repos.

**Comment by johrstrom** [comment]
Seems like you can't remove the `form.js` completely but rather remove the bits that are duplicated. Maybe comment on the Ansys ticket directly. We have functionality for hiding things on other things, but in any case we an keep the `form.js` just be sure it doesn't collide with other functionality.

**Comment by gbyrketosc** [comment]
All app migrations to Dynamic JS are completed.
