### ISSUE TITLE
Validate User Redirects 

### ISSUE THREAD

**Issue by karcaw** [OSC/ondemand#1663]
When sending redir=<url> options to the /nginx/stop endpoint, any url can be sent:
the normal use is something like this:

```
https://ondemand.fakelab.org/nginx/stop?redir=/pun/sys/dashboard/
```

But can also take things like:

```
https://ondemand.fakelab.org/nginx/stop?redir=https://cisa.gov
```

This can be used to trick users into thinking a valid ondemand URL is safe, but it really redirects them to another site altogether.  More information about this can be found here:
http://cwe.mitre.org/data/definitions/601.html

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823645174804) by [Unito](https://www.unito.io)

**Comment by karcaw** [comment]
It looks like the only valid redirects may be `/nginx/stop?redir=/pun/(dev/sys)/dashboard/`, can anyone confirm this?  are there other Redirects that are needed?

**Comment by johrstrom** [comment]
Using the `pun_uri` (which is default to `/pun` IIRC) as you are in that pull request if fine I think. It's open enough to say it's a URL that's OOD related _on this server_.

**Comment by johrstrom** [comment]
This also applies to `/nginx/noop`.

**Comment by karcaw** [comment]
We may have solved this one with:

https://github.com/OSC/ondemand/pull/1775

**Comment by johrstrom** [comment]
After some work and some time, this is complete.
