### ISSUE TITLE
JobComposer: Take advantage of new OodAppkit#dataroot default value

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#167]
In OodAppkit#dataroot we can set the dataroot if we only specify the OOD_PORTAL and APP_TOKEN env vars: https://github.com/OSC/ood_appkit/blob/a5a22388040c91d16188a8e255ca76c8ff004e60/lib/ood_appkit/configuration.rb#L66

It would be nice to take advanatage of this in myjobs. However, to do so, the bin/setup-production script will need to have access to this value, and unfortunately, OodAppkit is a Rails engine. Perhaps it will still work, but needs experimentation.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737492021975) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
This may have been solved, but in any case the new job composer has the same/similar mechanism.
