### ISSUE TITLE
JobComposer: Don't copy output files when copying a job

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#168]
Lets add a convention to myjobs:

1. when copying a job directory, we omit the directory called "output" or "results"
1. we update templates (and recommend users) specify the output and error files to be written to files under `/output` or `/results`

Whatever convention we use here should be the same convention we will use for batchsim.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737463475412) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I'm going to close this as won't do, the new job composer is going to have the same mechanism and should still account for this case, but we'll file a new ticket when we get there.
