### ISSUE TITLE
JobComposer: Prefix myjobs jobs with app token and use job name in form as job name when submitting job

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#169]
In My Jobs, assume I have a job titled: "(default) Simple Sequential Job". Then, when submitting a job, we will set the job name to: "sys/myjobs/default_simple_sequential_job".

1. Set APP_TOKEN to a config value in an initializer (ENV['APP_TOKEN'] || "sys/myjobs")
1. Use `.parameterize.underscore` to convert the job name:

```ruby
irb(main):012:0> name = "(default) Sequential Job Script"
=> "(default) Sequential Job Script"
irb(main):013:0> token = "sys/myjobs"
=> "sys/myjobs"
irb(main):014:0> "#{token}/#{name.parameterize.underscore}"
=> "sys/myjobs/default_sequential_job_script"
```

Bonus enhancements:

1. Add below the details view of the Job name:
  * >Job will be submitted using name: "sys/myjobs/default_simple_sequential_job"
  * ![](https://cloud.githubusercontent.com/assets/512333/24983012/6600e12a-1fb2-11e7-9a77-ad9814e85aea.png)
1. Add implementation copies of the Active Support "parameterize" and "underscore" methods applied to a string, so when a user is editing the job options form to change the job name we can show the string on the fly that will be created (in the help text)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737492731509) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I think this is was actually completed at some point.
