### ISSUE TITLE
JobComposer: Make template manifest optional

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#170]
A recent change made a manifest a required file for a job template.

7fdf6bdc8982cca685ee688b184486f41eb28225

This was in response to the observation that previously dot directories and all files were being included. The documentation says the manifest is optional.

We might want to make the manifest optional. To do so we would change the way we are pulling the list of valid directories. 

The code in Source#templates could also be simplified. `Pathname#children` for example can be used and will omit the "." and ".." and already have all the directories and files as paths so there could be one `select` followed by one `map` to return a list of Templates.

After this change is made we can undo the modification to the README that made the template manifests required: 

874c75039e8dd662c3539d1e182ce1af91b0ada6

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737503271669) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as won't do as the new job composer is going to handle these things in a different way.
