### ISSUE TITLE
JobComposer: Fix the way Manifests handle default host

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#171]
This pull request added a temporary fix to the issue:
https://github.com/AweSim-OSC/osc-jobconstructor/pull/150

Loading the manifest should not result in a crash. A TODO comment was added to address this: https://github.com/AweSim-OSC/osc-jobconstructor/blob/a3c3d7b1c32e2f76dc9d6ad674483d87e940f5df/app/models/manifest.rb#L48-L50

The correct solution is 3 fold:

1. OODClusters should be a `Clusters` instance, so you can just do `OODClusters.first.id` instead of `OODClusters.first[0].to_s`
1. If there are no clusters configured `OODClusters.count` should return 0 and `OODClusters.first` should return nil. We shouldn't throw an exception; rather add a guard clause and return the appropriate value (nil or "" if no cluster is set).
1. Manifest should probably not know about OODClusters. Rather, Manifest should probably have a class attribute `default_host` that is used, and we can set this in an initializer.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737552151009) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as a won't do. The new job composer is going to have a different mechanism for this anyhow.
