### ISSUE TITLE
JobComposer: Implement polling of job status for running jobs.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#172]
The status of a job currently updates only when an ajax request is made to the server. Which, in practice means a user would need to reload the page, or click off of a job and then back on to it to reinitialize the request.

We should add a polling feature to get the status of jobs in flight.

This functionality is already present in the LS-Dyna app, so integrating similar behavior here should be inexpensive.

**Comment by johrstrom** [comment]
At some point this was done as long as the user held focus on that particular row, or if the navigated away and then back. It's through [this on click](https://github.com/OSC/ondemand/blob/0e4270e2de0cb87f85db7ec68412b91ca3f92803/apps/myjobs/app/assets/javascripts/application.js#L70-L83) that updates the page.
