### ISSUE TITLE
JobComposer: Submit: Make the ScriptMissing error more user friendly or perform validation.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#173]
The ScriptMissing error message is very programmer-centric and not user-friendly.

![scriptmissing](https://cloud.githubusercontent.com/assets/2374718/17483587/a642050a-5d54-11e6-96f7-d0e2374b2795.png)

This is error can either 

1. Be rescued and passed with a more user-friendly message that the selected script is unavailable; or
1. _(ideally)_ The app should validate that the file exists before even attempting to submit the job and return a message that the file is not available. This way, we wouldn't submit the job at all until it's corrected.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201625178070145/1201627563632308) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as a won't do. The new job composer is going to have a different mechanism for this anyhow.
