### ISSUE TITLE
JobComposer: Add an optional "Notes" field to each job.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#175]
Currently, there are notes available in the template, but when you start creating many jobs that have similar names there's not a lot to differentiate them.

It may be useful to include a "notes" field for tracking useful information about a job.

The current layout doesn't lend itself to displaying these notes in the master view, but they could be displayed in the detail view.

Additionally, including them as a hidden column in the datatables form would also allow jobs to be searchable by note.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204156917323912) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
This isn't going to be completed as we're replacing the Job Composer.
