### ISSUE TITLE
JobComposer: Customizable project directory paths

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#176]
Along with customizing the directory names of the jobs themselves, a feature request was made by Kate to customize the project directory path. So every project directory would not appear in a subdirectory of `~/ondemand/data/sys/myjobs/projects` but could be in the user's home directory, or perhaps even in shared project space.

The fact that we store absolute paths to scripts etc. right now means we would need to consider changing this to storing relative paths - relative to the project directories that contain them (or perhaps with the project directories in the path). But if the user could change the project directory name after the fact, this also creates possible complications. So there are some edge cases that need to be thought through for this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737470999119) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
We're not going to fix this for the current job composer and indeed we have #2558 for the new one.
