### ISSUE TITLE
JobComposer: Pagination for the job constructor workflows list

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#177]
Some of the users end up producing many many jobs. We might consider pagination in the main list of jobs.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737504141452) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
Server side, there are two different gems that look promising. https://github.com/mislav/will_paginate has been around many years, and there are likely tutorials available for setting this up in Rails and setting up jQuery Datatables https://datatables.net/ to work with this.

The performance quality of https://github.com/ddnexus/pagy looks interesting. Though it is newer (riskier).

**Comment by treydock** [comment]
I've used that and https://github.com/kaminari/kaminari before.  More recently kaminari but where the pagination was done using bootstrap in views and not datatables.  Everytime I've done pagination with datatables I took the approach of having the datatables generated in Ruby, in that case I used will_paginate.

**Comment by johrstrom** [comment]
We're not going to fix this for the current job composer. And the new one will have a whole different UI we can file new tickets against.
