### ISSUE TITLE
JobComposer: Validate new jobs from existing templates?

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#179]
The new validations protect against creating a new template with a folder size.

A user can create a small template and add a lot of data to it. Do we want to validate against this as well?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737554159941) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as won't do at least for the current job composer.  When the newer job composer has the functionality for templates we should use `validate_path_is_copy_safe`.
