### ISSUE TITLE
Disable showing version in bc apps

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1797]
From discourse, it may be some sites don't want to expose the version of the app to users. This ticket is to disable showing the version through a configuration.

https://discourse.osc.edu/t/change-from-1-8-to-2-0-20/1889/7

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823659413017) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I tracked this feature down to this commit.

https://github.com/OSC/ondemand/commit/42552c309b4124c92ec8822efc28fd4cea1df6f0

**Comment by johrstrom** [comment]
And this bit in the partial.

https://github.com/OSC/ondemand/blob/7d45ff71eb56674c0aee4e0e105a0846243a4c23/apps/dashboard/app/views/batch_connect/session_contexts/new.html.erb#L76-L78

**Comment by justbennet** [comment]
@johrstrom Thanks.  I missed what the above comment meant, but my colleague Shelly did not.

It appears that simply adding a file called `VERSION` to the root of the application's directory and putting `unknown` on its only line will suppress the printing of the version number.

**Comment by johrstrom** [comment]
This was fixed in #2462.
