### ISSUE TITLE
JobComposer: Filesystem#validate_path_is_copy_safe and Filesystem#du are candidates for moving to ood_appkit or osc_machete

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#181]
Or another ood gem. The final home of https://github.com/AweSim-OSC/osc-machete/blob/d124db819b596f49abec12b4783293e39ebf2919/lib/osc/machete/user.rb and https://github.com/AweSim-OSC/osc-machete/blob/d124db819b596f49abec12b4783293e39ebf2919/lib/osc/machete/process.rb

**Comment by johrstrom** [comment]
I can't see this happening. I don't believe the `machete` library is actively maintained and the job composer itself we're looking to replace entirely (and likely use `ood_core` libraries).
