### ISSUE TITLE
JobComposer: Send stdout to log file

### ISSUE THREAD

**Issue by nickjer** [OSC/ondemand#182]
As the user can't qpeek to observe status of running job. It might be best to have the templates send output to a log file instead of the batch output. That way the user can observe progress through the File Explorer app.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737504786925) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as a won't do, at least for now. In any case new job composer will set a log file, but the real feature here is to be able to tail it and show it in the UI like say github actions do. But that's fairly far away and not part of the alpha launch just yet.
