### ISSUE TITLE
Pinned app icons to look nicer

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1836]
I think there are a few things here
* make them look nicer. Not clear what this may mean, but somehow bubblier? I suppose that's only a border update.

![image](https://user-images.githubusercontent.com/4874123/157495854-a5f29194-6bf1-4ee9-ba36-a586d720e7ff.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201816283554090) by [Unito](https://www.unito.io)

**Comment by gerald-byrket** [comment]
@johrstrom Let's have Harvard work on this specific piece.

**Comment by adaybujeda** [comment]
The Harvard IQSS team is looking into this issue. We will make a proposal for a new look and feel

**Comment by adaybujeda** [comment]
We have created a prototype based on the `pinned_apps` widget.
We have created a small demo to compare side by side.

![pinned_apps](https://user-images.githubusercontent.com/17336210/168262513-bb654a7e-6993-4ec6-9bbf-09ca02bdd760.gif)

**Comment by adaybujeda** [comment]
The prototype above uses a bit of JS to add the spinner and grey out the other apps when one is triggered.

**Comment by gbsoftwaresolutions** [comment]
> The prototype above uses a bit of JS to add the spinner and grey out the other apps when one is triggered.

Hey @adaybujeda
This looks great.  One question. We may want to meet for a little bit to show you how we are implementing javascript in ood before you get too far.

thanks,
-gerald

**Comment by adaybujeda** [comment]
Thanks @gbsoftwaresolutions.

As the JS is very small, I created an initial implementation based on the current files that are in OOD.
This will help to drive the conversation on the final implementation if the spinner and disable features are desired.

PR created: https://github.com/OSC/ondemand/pull/2031

**Comment by adaybujeda** [comment]
Final Look and Feel:
![pinned_apps](https://user-images.githubusercontent.com/17336210/168804928-c03786c7-7cff-409d-84e7-1f8c29a1c7f8.gif)
