### ISSUE TITLE
JobComposer: Add a spinner while waiting for ajax responses.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#185]
Job data is requested via ajax. This is pretty quick on my machine, but may have a noticeable delay off-site.

Add a spinner that appears in the duration between the ajax request and response.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737505146634) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as won't do. The new job composer will have it's own set of features.
