### ISSUE TITLE
Enable script models in new job composer

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1861]
Enable script models in the new job composer.  Projects should be able to CRUD these models and they should probably be saved as actual files in the hidden ondemand directory.

These models should be a combination of

* the script you want to submit to the scheduler
* plus arbitrary other fields you'd like to add.

That is the script is, the file you want to submit + all the other form items you added.  The `form.yml` files will/should behave a lot like batch connect form ymls.  (let's not support ERB just yet).

I'm thinking the files should live here, and they should respond to numeric IDs. 

```
<project>/.ondemand/scripts/1.yml
<project>/.ondemand/scripts/2.yml
```

this ticket is not to be able to submit these scripts - only to build the infrastructure to do so.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823607234195) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Actually let's focus on just reading them now.  Let's just recoginze the form.ymls if the exist and create the models.

We can defer updating to the next ticket.

**Comment by Oglopf** [comment]
I've got PR #2561 right now with some base scaffolding.

I need some clarity to finish up. For reading, this has to do with reading the `form.yml` only? 

Is the idea that we eventually have a `template/script` with the `form.yml` under the configuration directory? I think I'm having trouble understanding the wording and needs of `scripts` vs `forms` here.

**Comment by johrstrom** [comment]
> I need some clarity to finish up. For reading, this has to do with reading the form.yml only?

Yes.

> Is the idea that we eventually have a template/script with the form.yml under the configuration directory? I think I'm having trouble understanding the wording and needs of scripts vs forms here.

`scripts` could be the wrong word here. Maybe `job_options` is more appropriate?  One of those job options will be what script (shell script file) to submit to the scheduler.

To begin with, I'd say let's assume/hard code that there's a `script.sh` in the root directory of the project and attempt to submit that file.

But the `form` really lays out options for a job. It's a UI for any argument you'd give to `sbatch`, like how many nodes, how many cores, and as you've indicated, what script file to execute.

**Comment by johrstrom** [comment]
You can rename the models in the PR if you like.  I'm not married to the name `script`.

**Comment by Oglopf** [comment]
I may, but I'll likely change the path for the `form` to reflect that's what is stored there. I'm fine for now leaving the name as is though as this object will handle both forms (lol, not in the web sense) of scripts.

**Comment by johrstrom** [comment]
Updated the original comment mentioning numeric ids.

**Comment by Oglopf** [comment]
I'm not sure what the request here is and am going to try and clarify to understand.

We want:
- `Script` object that has data for the `script`s in the project and `job_options` passed from a web form.
-  Initialize the object by passing it the `hash` from the web request `form` options
-  Extract the request data from the hash and write it to a `yaml` file

Is this the idea for the scaffold?

**Comment by johrstrom** [comment]
> Script object that has data for the scripts in the project and job_options passed from a web form.

I don't quite follow you here, but I think so.  In any case, **all** of these are going to have to be predefined `smart_attributes`.  So, _really_ all it has is a smart attribute list.

So it'll have `smart_attributes` for the job submission and extra attributes (`attr_reader`s) like `title` that pertain only to the view.

(and yes we'll need new `smart_attributes` like `auto_script` to pick up what shell scripts are available, for example).

> Initialize the object by passing it the hash from the web request form options

Yes, but it can be read from the `yaml` representation too.  Just like `project`s have a physical (disk) representation after you've saved it, this will have the `yaml` representation _after_ you save it. 

But before you've saved it (i.e., in a `#new` controller method), it's just in memory being built through a form.

> Extract the request data from the hash and write it to a yaml file

Yea that's `#save`.

**Comment by johrstrom** [comment]
> Is this the idea for the scaffold?

Really, I just want functionality for controller methods `#new`, `#show` and `#delete`. And even in the `#new` I just care about title at the moment.

Once we have controller methods & views, then `#show` can really expand.  This is the building block to get there.
