### ISSUE TITLE
Enable customizing every file under /pun/html/ using /etc/ood/config/pun/html/

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#19]
Make this generic: https://github.com/OSC/ondemand/blob/ae11c86581557d223cd74db6fedb82c41a205e2b/nginx_stage/templates/pun.conf.erb#L79-L83

The trick is to pass the last part of the URL i.e. `/pun/custom_html/(*.)` to `/pun/html/` if try_files fails to find the corresponding file using NGINX.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737555504173) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
not a requested feature
