### ISSUE TITLE
JobComposer: Refactor TemplateController#create

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#190]
Most of this shouldn't be in the controller and the respective parts should be refactored to the respective Template or Manifest models.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737505990484) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as won't do and/or the features are going to be different in the new job composer.
