### ISSUE TITLE
Ubuntu Support?

### ISSUE THREAD

**Issue by simonLeary42** [OSC/ondemand#1901]
I see https://github.com/OSC/ood-ansible/
Does this give full OOD support to all the listed linux distros?

Is there some other way that OOD support Ubuntu 20.04LTS?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201949403599143) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
2.1 will support Ubuntu 20 focal, though it's not released yet.

We're publishing nightlies here, though I'm not sure how to enable that repo @treydock do you how?

https://yum.osc.edu/ondemand/nightly/web/apt/pool/focal/

**Comment by treydock** [comment]
Have to download the deb repo for latest repo and then add the nightly as packages come from both.

```
wget -O /tmp/ondemand-release.deb https://apt.osc.edu/ondemand/latest/ondemand-release-web-latest_2_all.deb
apt install -y /tmp/ondemand-release.deb
apt install -y apt-transport-https
echo "deb [arch=amd64] https://apt.osc.edu/ondemand/nightly/web/apt focal main" >> /etc/apt/sources.list.d/ondemand-web.list
apt update
apt install ondemand
```

**Comment by johrstrom** [comment]
Just note that nightlies have these features and/or bugs

https://github.com/OSC/ondemand/issues/1780

**Comment by johrstrom** [comment]
@simonLeary42 hope this works for you for the time being. 2.1 should be released later this year and I'll notify the community through discourse when nightlies become effectively stable release candidates.

**Comment by simonLeary42** [comment]
> @simonLeary42 hope this works for you for the time being. 2.1 should be released later this year and I'll notify the community through discourse when nightlies become effectively stable release candidates.

How stable are the nightlies at this time?

**Comment by johrstrom** [comment]
I keep #1780 up to date with what's buggy and what's breaking. It is current AFAIK. That is, I don't know of any bugs.
