### ISSUE TITLE
explore enabling active storage for files app

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1904]
explore enabling active storage for files app to potentially connect to cloud resources like s3.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201957019215230) by [Unito](https://www.unito.io)

**Comment by robinkar** [comment]
I took a closer look at Active Storage. From what I can see it doesn't seem like an option for enabling S3 support in the file browser, at least not for our use cases as it doesn't seem to be meant to be used in this way. Though it might be useful for #1905 depending on the idea for that one.

Some problems/concerns:
* It stores blobs with random names in the cloud and keeps track of the filename only in Rails. So uploaded data is useless outside of OOD, which is a large use case.
* It doesn't provide methods to list files in the cloud storage, so existing files and folders uploaded outside of OOD won't be visible. The underlying `aws-sdk-s3` gem would have to be used to do this, but would require creating `ActiveStorage::Blob` for every file to actually use Active Storage functionalities, which does not seem like a reasonable approach in my opinion.
* Swift support is something we at least would like to have. Though in this case the problems are more with Active Storage than this particular point as something like [activestorage-openstack](https://github.com/chaadow/activestorage-openstack) could potentially be used for Swift support.

**Comment by johrstrom** [comment]
That's a real shame. I wonder if there's a way to turn that off and/or how easy it is? I'm guessing probably not and very hard.

Well thanks for looking into it anyhow!  It appears, at a glance anyhow, that we'll probably just need to use `aws-sdk-s3` to generate file lists.

**Comment by robinkar** [comment]
I just realized you upgraded Rails to 6.1, which does add a way to specify what it is [uploaded as](https://github.com/rails/rails/commit/4dba136c83cc808282625c0d5b195ce5e0bbaa68) (the key), though I'm not sure if using that as the path will have some side effects.

**Comment by robinkar** [comment]
After some more investigation it seems relatively easy to just extend the existing Active Storage S3 Service with our own methods that add the missing functionality.
Small example:
```
# lib/active_storage/service/ood_s3_service.rb
require "active_storage/service/s3_service"

class ActiveStorage::Service::OodS3Service < ActiveStorage::Service::S3Service
  def ls
    # should output in some more suitable/generic format here other than using the AWS::S3 types
    bucket.objects
  end
end
```

In our case (at CSC) we would like Swift support too, but most likely one could make some abstraction here such as a `ActiveStorage::Service::OodService` class, which `OodS3Service` and `OodOpenStackService` would inherit.

**Comment by robinkar** [comment]
Active Storage for the regular files should be possible use from what I can see, but it doesn't provide much features that we need and only adds some additional issues that need to be considered.
The only features it would really give us is handling of download and upload, so the main reason to use it would probably be to not need to handle regular files and cloud files too differently from each other. All other features, such as listing, moving and copying would need to be implemented separately (e.g. using the existing code).
The additional issues that need to be considered is parts of how Active Storage work, mainly that it creates a database entry for every file it handles, which needs to have an unique key. So between each action (e.g. download/upload) we would need to clear existing database entries for that file, as the key defines where the file is stored, though that shouldn't be really be a problem.

If this is the route we want to go then moving the current regular file handling to Active Storage would probably be the place to start.

**Comment by johrstrom** [comment]
>  mainly that it creates a database entry for every file it handles

Database entry or cache entry? I'm not super interested in databases with schema migrations and headaches related to them.  We are starting to enable the `Rails.cache` though (it's already enabled as `:memory_store` in production) modes.

Can you share docs on the same or at least bits active storage that does this?

**Comment by robinkar** [comment]
Database entry, atleast for using `ActiveStorage::Blob`.
The [setup section in the docs](https://guides.rubyonrails.org/v6.1/active_storage_overview.html#setup) mentions the `active_storage_blobs` table, which is used to store the blobs (`ActiveStorage::Blob` < `ActiveStorage::Record` < `ActiveRecord::Base`).

Rails will fail to start if Active Storage is loaded and a database is not configured. 
Though I noticed today that if you configure an in-memory database and skip the migration it is possible to use `ActiveStorage::Service`, though it provides a much more [limited set of features](https://api.rubyonrails.org/v6.1.0/classes/ActiveStorage/Service.html). Particularly the url helpers that the blobs provide could be very useful.

**Comment by johrstrom** [comment]
seems like this is a won't do.
