### ISSUE TITLE
JobComposer: Design update: Support small screens

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#191]
On smaller screens, the master/detail view pushes the data to the bottom.

It's probably possible to move this to the top using [bootstrap push/pull](https://scotch.io/tutorials/reorder-css-columns-using-bootstrap), but we're bumping this into an issue for now.

![smallscreen](https://cloud.githubusercontent.com/assets/2374718/14154291/9fa306ea-f689-11e5-9697-87d015874612.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737556011532) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as won't do and/or the features are going to be different in the new job composer.
