### ISSUE TITLE
ood-portal-generator: Dex defaults to enabled unless explicitly set to false

### ISSUE THREAD

**Issue by murhum1** [OSC/ondemand#1929]
Much as the title says - unless one specifically disables dex by setting `dex: false` in ood_portal.yml, dex is set as enabled. This would otherwise probably not be a problem, but my own OpenID Connect settings are getting overwritten by whatever dex sets, as the initialization method calls `view.update_oidc_attributes(oidc_attributes)`.

https://github.com/OSC/ondemand/blob/e5f4515c1c45290e346fa7bd94d5a7e25cba9269/ood-portal-generator/lib/ood_portal_generator/dex.rb#L14-L20

I suggest changing line 14 above to

```
config = opts.fetch(:dex, nil)
```

which probably matches the intention implied by line 15 of having dex disabled if configuration is not explicitly provided.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823676527529) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Hi, thanks for the ticket. I quickly tried that fix but it didn't directly work. 

Looks like you're falling into this as well. I'd suggest uninstalling `ondemand-dex` and then see what the behavior is.  I suspect it's start working as you expect (if only by coincidence).
https://github.com/OSC/ondemand/blob/e5f4515c1c45290e346fa7bd94d5a7e25cba9269/ood-portal-generator/lib/ood_portal_generator/dex.rb#L46-L49

But you're right though, I don't know if the `@enabled` attribute is ever begin set correctly.

**Comment by johrstrom** [comment]
I believe that uninstalling `ondemand-dex` will solve your issue for 2.0. 2.1 does in fact have different default behavior so this should be resolved.

Please let me know if that's not the case and I'll re-open this ticket.
