### ISSUE TITLE
JobComposer: Support import of job metadata from database of previous app to new app

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#193]
**Needs design**

Proposed design:

Add an indexed boolean column to the simulation or workflow model: `legacy`. Then do this on each request to the index page:

```ruby
#pseudo code
unless Simulation.where(legacy: true).any?
  display "import" button if (File.exist?("~/crimson_files/JobConstructor") && Dir.glob("~/crimson_files/JobConstructor").length > 0)
end
```

Import button would be at top of page. The user can import old jobs by clicking the import button which will connect to mysql to read the user's information about their jobs and create corresponding database records. No files will be moved - the legacy jobs staged data would remain under `~/crimson_files/JobConstructor`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737505701658) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
It's not clear what this was, but I'm closing this as won't do and/or the features are going to be different in the new job composer.
