### ISSUE TITLE
Ubuntu proxy tests are failing

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1931]
Ubuntu proxy tests are failing with the error below for some unknown reason.

    
    Failures:
    
      1) Node and Rnode proxies rnode correctly redirects relative urls
         Failure/Error: expect(browser.url).to eq("#{ctr_base_url}/rnode/localhost/5000/one/one-level-down")
           
           expected: "http://localhost:8080/rnode/localhost/5000/one/one-level-down"
                got: "http://localhost:8080/rnode/localhost/5000/one/two/rnode/one/one-level-down"
           
           (compared using ==)
           
         # ./spec/e2e/proxy_spec.rb:53:in `block (2 levels) in <top (required)>'

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202045846683825) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I've tracked this down to this Location header edit. 

https://github.com/OSC/ondemand/blob/e5f4515c1c45290e346fa7bd94d5a7e25cba9269/ood-portal-generator/templates/ood-portal.conf.erb#L225

This test case

https://github.com/OSC/ondemand/blob/661bb57c9235203f574f76c7d9cdd411527922c5/spec/e2e/proxy_spec.rb#L52-L53


This is what the origin server is responding with
https://github.com/OSC/ondemand/blob/edcdbe373e8e39abad37abcc939e53b9007ed6e0/spec/fixtures/extras/simple_origin_server.py#L8-L10

On Ubuntu 20.04 the latest version of apache was just built
```
root@ubuntu2004:/# apache2 -v
Server version: Apache/2.4.41 (Ubuntu)
Server built:   2022-03-16T16:52:53
```
 and is now returning 
```
Location: ../rnode/localhost/5000/../../one/one-level-down
```

When it should be returning:
```
Location: /rnode/localhost/5000/one/one-level-down
```

@treydock please advise. That regex doesn't seem to account for relative URLs anymore.

**Comment by treydock** [comment]
I'm not sure, that regex predates even me, it was part of what was original OnDemand 3 deployment I'm pretty sure which is where Open OnDemand came from.  If I'm reading the regex correctly, the first part before pipe is doing what it's supposed to, so I wonder if maybe we've been benefitting from a bug this whole time? I did a quick skim of Apache changelog and nothing jumped out at me.
