### ISSUE TITLE
JobComposer: /jobs/new - add "Prefix" and "Suffix: increment by number" fields

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#194]
![jobconstructor!UNITO-UNDERSCORE!templates!UNITO-UNDERSCORE!prefix](https://cloud.githubusercontent.com/assets/512333/13936109/c0435b38-ef91-11e5-9def-02d45e81def5.png)

* by adding a prefix, this puts the text before the number
* by unchecking the "increment by number" the name of the job directory is the name specified in "prefix" without any number following it
* Because the default is to name the directory a number "incremented by 1" the next unique number needs to be determined before this view is rendered. 
* When submitting the form (after the user presses "Use selected template") the path we are copying to needs to be verified to not exist yet (i.e. unique) and a form validation error should be thrown if it does (i.e. a conflict) so the user can change this

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737505737082) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as won't do and/or the features are going to be different in the new job composer.
