### ISSUE TITLE
JobComposer: When editing a job, allow the user to rename the staged job directory if the job has not been submitted yet

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#195]
If we let the users specify a custom name for newly created jobs from templates, we don't do the same when the user just copies a job from another job - we might want to do this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737556143820) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as won't do and/or the features are going to be different in the new job composer.
