### ISSUE TITLE
files readme is very outdated

### ISSUE THREAD

**Issue by Micket** [OSC/ondemand#1968]
https://github.com/OSC/ondemand/blob/f2d596feec3b49273de46dfb571bf6ed8f4a7025/apps/files/README.md?plain=1#L102

Seems to be wrong; should be `/var/tmp/ondemand-nginx/$USER/client_body` right?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202168502815075) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Yes you fell into the tap of #1286. Indeed that README is for the node.js app that was ported to rails in 2.0.

This is the location for the correct documentation.
https://osc.github.io/ood-documentation/latest/customization.html?highlight=upload#set-upload-limits

**Comment by Micket** [comment]
Indeed! No need to keep a duplicate issue, thanks
