### ISSUE TITLE
Dashboard: Be able to enable app sharing mode without displaying "featured apps" page as home page

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#197]
Currently if you enable app sharing mode the home page [changes from the home page to the featured apps page](https://github.com/OSC/ood-dashboard/blob/855e94bf986e49532691cc1d8106fa60860cb196/config/routes.rb#L28-L30) which is undesirable for a site where 90% of the users do not take advantage of app sharing.

An interim solution is as follows:

1. Add "shared apps" as a fourth column (on the far left) to the "All Apps" page, we can provide users who have shared apps access to those by click-ing on "All Apps". This will appear if shared apps mode is enabled.
1. Add ability to change the home page to the default index page instead of the featured apps page.

The result of showing the default home page, with app sharing enabled, and displaying the all apps page would result in these two screenshots:

Home page:

* ![screen 2019-06-04 at 2 24 32 PM](https://user-images.githubusercontent.com/512333/58904054-c2bf0c80-86d4-11e9-9cec-0c5ba8fde905.png)

All Apps page:

* ![screen 2019-06-04 at 2 25 01 PM](https://user-images.githubusercontent.com/512333/58904044-be92ef00-86d4-11e9-8f5a-12c4cf9acc3c.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737612749215) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as fixed, indeed we need to get rid of `apps#featured` altogether I think.
