### ISSUE TITLE
Dashboard: Add optional hack to enable with copy/paste in NoVNC

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#198]
This PR https://github.com/novnc/noVNC/pull/1301/ works in Chrome but not Firefox. We did some extra work to make copy and paste work in Firefox in the shell app, and I think we can do the same here.

The idea would be to add this optional fix, and then give the user the option to include or exclude this hack when launching the noVNC client.

Original issue description:

>This looks interesting: https://github.com/novnc/noVNC/issues/509#issuecomment-399620468
>
>If we applied this, it would be interesting to see its benefits and limitations. We could provide this or something similar to a modified novnc.html and provide users with the option of which viewer they want to load (the one with the hack, the one without).
>
>If the code as is works we should reach out to the author asking for a license (maybe make a gist with the MIT license, for example).

**Comment by ericfranz** [comment]
Adding support to Firefox will not work at this time. Using the legacy `document.execCommand('copy')` approach will not work because you get an error: 

>document.execCommand(‘cut’/‘copy’) was denied because it was not called from inside a short running user-generated event handler

This is because unlike the shell app, in NoVNC the user is interacting with the canvas, and it is a message receive event that triggers the copy to clipboard event. Since this stack is not recognized as user generated (since the stack doesn't include a user click event, for example), copy will not work without substantial work.

As for utilizing the new Async ClipboardAPI, Firefox does not yet support the 'clipboard-read' and 'clipboard-write' permissions of the Permissions API.

References:

- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard
- https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
- https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API
- https://developers.google.com/web/updates/2018/03/clipboardapi

**Comment by userjjb** [comment]
Is the above still true? Based on the reference links from above, it appears this might now be possible as of Firefox 147. It would be a pretty big quality of life improvement in Firefox to not have to manually copy/paste in the noVNC clipboard widget.

**Comment by johrstrom** [comment]
> Is the above still true? Based on the reference links from above, it appears this might now be possible as of Firefox 147. It would be a pretty big quality of life improvement in Firefox to not have to manually copy/paste in the noVNC clipboard widget.

I think so. That said - I think there's been a lot of work upstream in noVNC for actual support. Namely `novnc/noVNC/pull/1993` which I think may be in 1.7.0, though the changelog doesn't indicate that it is.
