### ISSUE TITLE
ubuntu update_ood_portal errors in postinst

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1989]
I just got this installing on Ubuntu manually on a branch (need to verify from a nightly) so I'm putting it here.  The CI doesn't have this issue so it could be nothing. 

    Setting up ondemand-passenger (6.0.11) ...
    Setting up ondemand (2.1.0.0.start.3.1651764338.02eb20b) ...
    Updating NGINX configs using YAML config: '/etc/ood/config/nginx_stage.yml'
    + /opt/ood/nginx_stage/sbin/nginx_stage app_clean
    + /opt/ood/nginx_stage/sbin/nginx_stage app_reset --sub-uri=/pun
    /var/lib/ondemand-nginx/config/apps/sys/myjobs.conf
    /var/lib/ondemand-nginx/config/apps/sys/dashboard.conf
    /var/lib/ondemand-nginx/config/apps/sys/shell.conf
    + /opt/ood/nginx_stage/sbin/nginx_stage nginx_clean
    Completed successfully!
    
    undefined method `split' for nil:NilClass
    /opt/ood/ood-portal-generator/lib/ood_portal_generator/application.rb:118:in `checksum_matches?'
    /opt/ood/ood-portal-generator/lib/ood_portal_generator/application.rb:134:in `update_replace?'
    /opt/ood/ood-portal-generator/lib/ood_portal_generator/application.rb:194:in `update_ood_portal'
    /opt/ood/ood-portal-generator/lib/ood_portal_generator/application.rb:289:in `start'
    -e:1:in `<main>'
    Run 'update_ood_portal --help' to see a full list of available options.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202233190944742) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
While I have the container running - here's the sha file info.  It like it's just an empty file.
```
root@412ffb3ad370:/home/jeff/ondemand/temp/ondemand/tmp/work/ubuntu-20.04# ls /etc/ood/config/ -lrt
total 36
-rw-r--r-- 1 root root 13155 May  5 11:25 ood_portal.yml
drwxr-xr-x 2 root root  4096 May  5 11:25 ondemand.d
-rw-r--r-- 1 root root  7312 May  5 11:25 nginx_stage.yml
-rw-r--r-- 1 root root   357 May  5 11:25 hook.env
drwxr-xr-x 2 root root  4096 May  5 11:25 clusters.d
-rw-r--r-- 1 root root     0 May  5 14:33 ood_portal.sha256sum
root@412ffb3ad370:/home/jeff/ondemand/temp/ondemand/tmp/work/ubuntu-20.04# ls /etc/ood/config/ood_portal.sha256sum  -lrt
-rw-r--r-- 1 root root 0 May  5 14:33 /etc/ood/config/ood_portal.sha256sum
```

**Comment by johrstrom** [comment]
Not sure how I got into this state. The `ood-portal.conf` is empty too.

```
root@412ffb3ad370:/etc/ood/config# ls -lrt /etc/apache2/sites-available/ood-portal.conf
-rw-r--r-- 1 root root 0 May  5 14:33 /etc/apache2/sites-available/ood-portal.conf
```

**Comment by johrstrom** [comment]
This is real. A discourse user is reporting the same behavior on a VM.

**Comment by treydock** [comment]
So the error in original comment appears to be happening when the checksum file is missing.  So looks like checks for existence of checksum happen after we check the contents.  

So the location update_ood_portal is executed is postinst.  The beginning of that file we touch the checksum file.  I have vague recollection that there are possibly issues with doing things to /etc in post/pre type scripts with Debian packaging but could never find documentation to support the behavior I saw a while ago.  I think best we might be able to do is add some safe guards to avoid operating on non-existent checksum file.

**Comment by johrstrom** [comment]
>  I think best we might be able to do is add some safe guards to avoid operating on non-existent checksum file.

Yea, no/empty checksum would just mean that we do replace.

**Comment by treydock** [comment]
I think ood-portal.conf is empty because update_ood_portal failed before it got to the point it could be written. We `touch` both the checksum and ood-portal.conf in postinst.

**Comment by treydock** [comment]
Found really easy way to replicate in container. Install `ondemand` from nightly, and then re-run the postinst script:

```
root@417effc1cbbe:/# /var/lib/dpkg/info/ondemand.postinst 
Updating NGINX configs using YAML config: '/etc/ood/config/nginx_stage.yml'
+ /opt/ood/nginx_stage/sbin/nginx_stage app_clean
+ /opt/ood/nginx_stage/sbin/nginx_stage app_reset --sub-uri=/pun
/var/lib/ondemand-nginx/config/apps/sys/dashboard.conf
/var/lib/ondemand-nginx/config/apps/sys/myjobs.conf
/var/lib/ondemand-nginx/config/apps/sys/shell.conf
+ /opt/ood/nginx_stage/sbin/nginx_stage nginx_clean
Completed successfully!

undefined method `split' for nil:NilClass
/opt/ood/ood-portal-generator/lib/ood_portal_generator/application.rb:118:in `checksum_matches?'
/opt/ood/ood-portal-generator/lib/ood_portal_generator/application.rb:134:in `update_replace?'
/opt/ood/ood-portal-generator/lib/ood_portal_generator/application.rb:194:in `update_ood_portal'
/opt/ood/ood-portal-generator/lib/ood_portal_generator/application.rb:289:in `start'
-e:1:in `<main>'
Run 'update_ood_portal --help' to see a full list of available options.
/var/lib/dpkg/info/ondemand.postinst: line 37: /bin/systemctl: No such file or directory
```

Not having systemctl is likely just because containers don't tend to have systemd installed.

**Comment by treydock** [comment]
So I think I have this working in #2012 but what's really strange is in theory this should have also been an issue for EL builds because those packages also touch the same files and run update_ood_portal at end of install.  My only guess is maybe setting files to `%ghost` in RPM spec means they don't actually get put onto filesystem as empty files but just listed as belonging to the package but otherwise not managed.

**Comment by treydock** [comment]
Having now just read docs for RPM spec more closely, I think the ghost behavior is the files don't actually ever get created.  So maybe the better solution is to just not "touch" the files in postinst and leave the logic in ood-portal-generator alone?
