### ISSUE TITLE
Dashboard: Enable site wide option to open apps in same window instead of new window

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#199]
Originally all links external and internal, opened in the same window as you would expect a normal website to behave. The exception was the shell app. Because the shell app is a self-contained window, and adding the navbar above the shell app and navigating away from the shell app would result in losing your connection, we had that open in a new window.

Then, when navigating to help links (or other external pages) we got feedback that you would lose the dashboard. So we started opening that in a new window.

Then, because the other apps didn't share the navbar of the dashboard, we got feedback that it was difficult to navigate around - you would lose your dashboard. So we started opening all links external to the dashboard in new windows.

Now we get feedback from other sites that they prefer to stop opening so many windows for every app.

Three options:

A. Shell, Jupyter, NoVNC, and links external to the OnDemand instance, such as external Help or Support links
B. Only the Shell app and connecting to Jupyter or NoVNC would auto open in a new window
C. No new windows

Based on feedback from two external sites, B is preferred. The problem with B is of course, that the Files, Job Composer, and Active Job apps don't share the same navigation that the dashboard shares.

It would be better if navigation were improved throughout OnDemand, and that a current shell session could be preserved. Then we could change it to no new windows.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737612893683) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
Push this back to 2.0. In 2.0 we are going to make a number of interface and possibly architectural changes. Those may make a solution to this easier to solve, by removing the need for opening links in new windows.

**Comment by matt257** [comment]
reviewed as a team,
the goal should now be to implement this functionality https://www.w3.org/TR/WCAG20-TECHS/G200.html (in a new issue)
