### ISSUE TITLE
Use Etc.getpwn.name instead of Etc.getlogin

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1990]
From the docs https://ruby-doc.org/stdlib-2.5.3/libdoc/etc/rdoc/Etc.html we should use ` Etc.getpwuid.name` as it's more reliable than `Etc.getlogin` (I just ran into an issue in a container. Must rely on $LOGIN or similar).

https://github.com/OSC/ondemand/blob/5c00c088070ebe2d2397f0b8329375f0c136eb79/ood-portal-generator/lib/ood_portal_generator.rb#L50

and here
https://github.com/OSC/ondemand/blob/5c00c088070ebe2d2397f0b8329375f0c136eb79/ood-portal-generator/lib/ood_portal_generator.rb#L58

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202233273571794) by [Unito](https://www.unito.io)

**Comment by SaumyaBhushan** [comment]
Can you please assign me this issue ?

**Comment by treydock** [comment]
Pretty sure this logic is in ood_core too as I think that's where I pulled it from or maybe one of the other ood gems used by OnDemand.

**Comment by SaumyaBhushan** [comment]
https://github.com/OSC/ondemand/pull/1992
