### ISSUE TITLE
Update missing_home_directory.html to use JavaScript with a query param to display missing home directory

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#20]
So instead of the default page saying:

>Your home directory appears to be missing.

It could say:

>Your home directory at /users/PZS0562/efranz appears to be missing.

This is more complex to implement after #19 is because we would want to pass the same query params to the custom location and have those be passed to the default appropriately.

Also, we would want to follow guidelines https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Safely_inserting_external_content_into_a_page, perhaps by having the page have a placeholder like:

```html
<p>Your home directory <span id="homedir"></span> appears to be missing.</p>
```

And then we could have JavaScript at the bottom of the page like:

```js
var homedir = (new URLSearchParams(document.location.search.substring(1)).get("homedir");
if(homedir){
  var span = document.getElementById("homedir");
  span.textContent = "at " +homedir;
}
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737557211951) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
current implementation is a better solution,
most centers would be able to work around this issue
