### ISSUE TITLE
Dashboard: Invalid OOD_LOCALES_ROOT causes unhandled NoMethodError

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand#200]
If `OOD_LOCALES_ROOT` points to a non-existent directory then attempting to load the application will cause an unhandled `NoMethodError` to be throw in the application controller.

This defect impacts:

- https://github.com/OSC/ood-dashboard/pull/447
- https://github.com/OSC/ood-myjobs/pull/284

**Comment by Oglopf** [comment]
I attempted to recreate this issue recently by setting `.env` files with `OOD_LOCALES_ROOT='/nothing_here'` in both the Dashboard and Job Composer apps but was not able to recreate this error in either app.
