### ISSUE TITLE
Missing ood_auth_map.regex

### ISSUE THREAD

**Issue by linhbngo** [OSC/ondemand#2007]
We have installed OpenOD 2.0.1 from RPM on Rockly Linux 8.5 with Shibboleth, and everything was working fine. There was a minor roadblock, which is a missing `ood_auth_map.regex` file inside `/opt/ood/ood_auth_map/bin`. After creating a copy of this file from our older 1.18 installation, everything works. Checking the Git repository, it shows that this file is missing there as well.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202254994715420) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
It's not a mistake, it was a breaking change from 1.8.  You can see the release notes here:

https://osc.github.io/ood-documentation/latest/release-notes/v2.0-release-notes.html#no-longer-providing-ood-auth-map-regex

**Comment by johrstrom** [comment]
But thanks for the ticket anyhow! I don't mean to be dismissive, it is just known.

Thanks again, and feel free to reach out again with questions or issues.
