### ISSUE TITLE
Support Ubuntu 22.04

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2009]
With #1811 never going to happen, let's not make the same mistake with 22. OOD 2.1 may be out for 1-1.5 years before the next release.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202260595413690) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
On Ubuntu 22.04 these are the versions:

* Ruby - 3.0
* bundler - 2.3.5
* nodejs - 12.22.9 (So will need to continue using 3rd party repo to get NodeJS 14)

**Comment by johrstrom** [comment]
Thanks i see those errors. Do we need to force `python3` in 2.1? I'm happy to allow that. Apps have the ability to override the binaries like `python` and since we don't ship any we don't have to migrate any.

**Comment by treydock** [comment]
Not sure I see anything about `python3` in errors?  The latest failures are related to me adding a flag to command that forces version into changelog and it doesn't like maintainer defined in this repo's deb packaging.  Without that flag I would get a prompt about missing email and had to hit "enter" interactively and only way I found to avoid that was pull email from control maintainer entry.

**Comment by johrstrom** [comment]
I must have been mistaken. I'll let you take care.

**Comment by treydock** [comment]
Now I see what you mean by python3 errors, I was too focused on the errors further down.  I opened #2011 to force `python3` for all Ubuntu and Debian packages.

**Comment by treydock** [comment]
@johrstrom Looks like we need to update `osc-machete` gem to support Ruby 3.0:

```
osc-machete-1.2.2 requires ruby version ~> 2.2, which is incompatible with the
current version, ruby 3.0.2p107
Bundler::InstallError: osc-machete-1.2.2 requires ruby version ~> 2.2, which is incompatible with the current version, ruby 3.0.2p107
```

**Comment by johrstrom** [comment]
Thanks. I made the ticket with that repo. I think it should be easy enough to update, just need to add the release action.

**Comment by treydock** [comment]
Should have probably opened PR to bump unit tests to Ruby 3.0 as would have caught this there. I am testing out Ubuntu 22.04 locally on my laptop and ran into this issue: https://stackoverflow.com/a/70467301

Looks like the sqlite3 gem doesn't yet even test against Ruby 3.0, but there are open pull requests to do it.  Maybe we bump sqlite3 gem to latest available and hope for the best?

**Comment by johrstrom** [comment]
Looks like it should

![image](https://user-images.githubusercontent.com/4874123/168154283-47e5374c-7c40-498f-9ea9-4b3c5f49efcb.png)

**Comment by treydock** [comment]
Yep it does.  Now I am getting new errors while testing locally:

```
TZInfo::DataSourceNotFound: tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install
```

Looks like just missing `tzdata` package, which I'm adding and will continue testing.  My guess is Ubuntu 22.04 container image is much slimmer than Ubuntu 20.04.
