### ISSUE TITLE
Dashboard: Add ability to specify additional paths for where the Dashboard searches for sys and dev apps

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#201]
This would enable apps that are batch connect plugins or just external links to be added to another directory besides `/var/www/ood/apps/sys`, and would make it easier to version all of these in a single repo, similar to how we do with /etc/ood/config. In fact it could be a subdirectory under /etc/ood/config. Two implementation approaches include: 

1. have `OOD_DEV_APPS_ROOT` be colon delimited
1. add an additional colon delimited set of paths, something like `OOD_MORE_DEV_APPS_PATH` or `OOD_MORE_SYS_APPS_PATH`

Another option would be to explore supporting https://github.com/OSC/ood-dashboard/issues/204 instead.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737556893663) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
reviewed,
not an issue
