### ISSUE TITLE
packages need mod_proxy_wstunnel 

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2022]
packages need mod_proxy_wstunnel. So much so that we could add it as a package dependency along with `apache` or `httpd`.

Seems like RHEL has it, but I think at least we'd have to enable it on Ubuntu.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202276056172849) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
That module is installed by default by the `httpd` package for RHEL8 and `httpd24-httpd` for RHEL7.

Example:
```
# repoquery -l httpd24-httpd | grep wstunnel
/opt/rh/httpd24/root/usr/lib64/httpd/modules/mod_proxy_wstunnel.so
```

This is default install on CentOS 7 container:

```
# grep -HnR "wstunnel" /opt/rh/httpd24/root/etc/httpd/conf.modules.d/
/opt/rh/httpd24/root/etc/httpd/conf.modules.d/00-proxy.conf:18:LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
```

This is fresh install on Rocky 8 container:

```
# grep wstunnel /etc/httpd/conf.modules.d/00-proxy.conf 
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
```

So maybe only thing to do is update the deb package to do proper symlink?
