### ISSUE TITLE
Dashboard: App sharing enabling should work the way app development enabling works

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#203]
The way it works is if the app sharing root directory exists, show the interface. Since the directory must be created by the admin, the admin still has control. But it is one less step - as you don't have to enable app sharing mode.

If we do this we need to first unify the app sharing mode and normal mode dashboards so they present apps you can launch in a unified way.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737556969100) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
introduces security complexity
