### ISSUE TITLE
Dashboard: We should properly capture two common problems for interactive apps and report that to the user

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#205]
Two problems are common when setting up interactive apps

1. The launching of the interactive app fails, for whatever reason, prior to NoVNC being able to connect
1. The launching of the interactive app succeeds, but the compute node is not configured properly to accept requests from the web node on the port the app is listening on, so NoVNC cannot connect.

This is related to an issue (I cannot currently find this) where we want to show the cards for previously completed interactive sessions, and perhaps a history tab to see all previous sessions, with button to clear all history, button to delete individual session information.

This would also mean that running sessions would get a STOP and DELETE button.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737507214422) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
reviewed,
more complex than suggested by the ticket
