### ISSUE TITLE
Insufficient checks on app access permission

### ISSUE THREAD

**Issue by i-mtz** [OSC/ondemand#2066]
johrstrom , we where discussing again the file restriction option from Open OnDemand and remembered this issue we discussed on [discourse](https://discourse.openondemand.org/t/is-possible-to-restrict-or-limit-the-access-to-the-files-app/2040/14?u=i-mtz)

From the [docs](https://osc.github.io/ood-documentation/latest/app-sharing.html?highlight=facl#system-installed-apps) changing the permission of the folder containing the `manifest.yml` for an app should be enough to limit the access to the app. This however only works on the dashboard, where the app will not be shown but can be bypassed by using a full url, for example restricting the access to the `files` app:

`https://example.com/pun/sys/dashboard/` works as expected and I don’t see the option for Files, but if I edit the url to `https://example.com/pun/sys/files` I end up in the Files app: `https://example.com/pun/sys/dashboard/files/fs/<path/to/my/home>`, I can then even edit files.

The problematic line is this one:

https://github.com/OSC/ondemand/blob/1d4a0355e11fef26fa81240cf0aa87c5d36796b5/apps/dashboard/config/configuration_singleton.rb#L428

A potential fix could be:
```app_dir.directory? && app_dir.readable? && app_dir.join('manifest.yml').readable?```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823731183022) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Thanks for opening the ticket, I don't always remember to do so off of Discourse. I put this bug into the 2.1 release.

**Comment by johrstrom** [comment]
I cannot replicate the issue on 2.1 or 2.0. Whenever I change the folder or the file to 700, there is no Files entry on the navbar and navigating to `/pun/sys/dashboard/files` or `/pun/sys/dashboard/files/<path to real files>` does not work (which is expected).

* changing the folder `/var/www/ood/apps/files` to 700 gives me errors when I navigate to `/pun/sys/files` or `/pun/sys/dashboard/files`
* changing the file `/var/www/ood/apps/files/manifest.yml` to 700 also gives me errors.

**Comment by i-mtz** [comment]
I'm also unable to reproduce this anymore on our test instance running `2.0.29`. I think the issue can be closed.

**Comment by johrstrom** [comment]
Thanks for the confirmation.
