### ISSUE TITLE
Possible Ruby 3 issue

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand#2069]
I launched a Kubernetes job on dev and it was running according to kubectl but the session page didn't show it ready. I then refreshed the page and got this:

    #<NoMethodError: undefined method `encode' for URI:Module>
    
    (erb):6:in `block in _app_views_batch_connect_sessions_connections__custom_html_erb___2803768356638317546_13840'
    /opt/rh/rh-ruby30/root/usr/share/ruby/erb.rb:905:in `eval'
    /opt/rh/rh-ruby30/root/usr/share/ruby/erb.rb:905:in `result'
    /var/www/ood/apps/sys/dashboard/app/views/batch_connect/sessions/connections/_custom.html.erb:1:in `_app_views_batch_connect_sessions_connections__custom_html_erb___2803768356638317546_13840'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/base.rb:247:in `public_send'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/base.rb:247:in `_run'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/template.rb:154:in `block in render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb:205:in `instrument'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/template.rb:345:in `instrument_render_template'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/template.rb:152:in `render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb:205:in `instrument'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/partial_renderer.rb:280:in `render_partial_template'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/partial_renderer.rb:271:in `render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/renderer.rb:22:in `render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/rendering_helper.rb:38:in `block in render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/base.rb:273:in `in_rendering_context'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/rendering_helper.rb:34:in `render'
    /var/www/ood/apps/sys/dashboard/app/helpers/batch_connect/sessions_helper.rb:195:in `block (2 levels) in connection_tabs'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:45:in `capture'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/tag_helper.rb:342:in `content_tag'
    /var/www/ood/apps/sys/dashboard/app/helpers/batch_connect/sessions_helper.rb:194:in `block in connection_tabs'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:45:in `capture'
    /var/www/ood/apps/sys/dashboard/app/helpers/batch_connect/sessions_helper.rb:190:in `connection_tabs'
    /var/www/ood/apps/sys/dashboard/app/views/batch_connect/sessions/_panel.html.erb:26:in `block (2 levels) in _app_views_batch_connect_sessions__panel_html_erb__2281903315280541662_13640'
    /var/www/ood/apps/sys/dashboard/app/helpers/batch_connect/sessions_helper.rb:47:in `block (2 levels) in session_view'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:45:in `capture'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/tag_helper.rb:342:in `content_tag'
    /var/www/ood/apps/sys/dashboard/app/helpers/batch_connect/sessions_helper.rb:47:in `block in session_view'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:45:in `capture'
    /var/www/ood/apps/sys/dashboard/app/helpers/batch_connect/sessions_helper.rb:36:in `session_view'
    /var/www/ood/apps/sys/dashboard/app/views/batch_connect/sessions/_panel.html.erb:2:in `block in _app_views_batch_connect_sessions__panel_html_erb__2281903315280541662_13640'
    /var/www/ood/apps/sys/dashboard/app/helpers/batch_connect/sessions_helper.rb:29:in `block (2 levels) in session_panel'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:45:in `capture'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/tag_helper.rb:342:in `content_tag'
    /var/www/ood/apps/sys/dashboard/app/helpers/batch_connect/sessions_helper.rb:28:in `block in session_panel'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/capture_helper.rb:45:in `capture'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/tag_helper.rb:342:in `content_tag'
    /var/www/ood/apps/sys/dashboard/app/helpers/batch_connect/sessions_helper.rb:3:in `session_panel'
    /var/www/ood/apps/sys/dashboard/app/views/batch_connect/sessions/_panel.html.erb:1:in `_app_views_batch_connect_sessions__panel_html_erb__2281903315280541662_13640'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/base.rb:247:in `public_send'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/base.rb:247:in `_run'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/template.rb:154:in `block in render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb:205:in `instrument'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/template.rb:345:in `instrument_render_template'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/template.rb:152:in `render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/collection_renderer.rb:189:in `block in collection_with_template'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/collection_renderer.rb:70:in `block in each_with_info'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/collection_renderer.rb:70:in `each'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/collection_renderer.rb:70:in `each_with_info'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/collection_renderer.rb:180:in `each'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/collection_renderer.rb:180:in `map'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/collection_renderer.rb:180:in `collection_with_template'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/collection_renderer.rb:162:in `block (2 levels) in render_collection'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/partial_renderer/collection_caching.rb:21:in `cache_collection_render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/collection_renderer.rb:161:in `block in render_collection'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb:205:in `instrument'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/collection_renderer.rb:147:in `render_collection'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/collection_renderer.rb:119:in `render_collection_with_partial'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/renderer.rb:72:in `render_partial_to_object'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/renderer.rb:22:in `render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/rendering_helper.rb:38:in `block in render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/base.rb:273:in `in_rendering_context'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/helpers/rendering_helper.rb:34:in `render'
    /var/www/ood/apps/sys/dashboard/app/views/batch_connect/sessions/index.html.erb:42:in `_app_views_batch_connect_sessions_index_html_erb__3812428278177760429_13600'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/base.rb:247:in `public_send'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/base.rb:247:in `_run'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/template.rb:154:in `block in render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb:205:in `instrument'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/template.rb:345:in `instrument_render_template'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/template.rb:152:in `render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb:205:in `instrument'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb:205:in `instrument'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/template_renderer.rb:11:in `render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/rendering.rb:117:in `block in _render_template'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/base.rb:273:in `in_rendering_context'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/rendering.rb:116:in `_render_template'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/streaming.rb:218:in `_render_template'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/rendering.rb:103:in `render_to_body'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/abstract_controller/rendering.rb:25:in `render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/rendering.rb:36:in `render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
    /opt/rh/rh-ruby30/root/usr/share/ruby/benchmark.rb:308:in `realtime'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb:45:in `render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
    <internal:kernel>:90:in `tap'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/abstract_controller/base.rb:228:in `process_action'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb:106:in `run_callbacks'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb:203:in `block in instrument'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb:203:in `instrument'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/abstract_controller/base.rb:165:in `process'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionview-6.1.5.1/lib/action_view/rendering.rb:39:in `process'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal.rb:190:in `dispatch'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_controller/metal.rb:254:in `dispatch'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb:32:in `each'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb:32:in `serve'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb:842:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/rack-2.2.3.1/lib/rack/tempfile_reaper.rb:15:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/rack-2.2.3.1/lib/rack/etag.rb:27:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/rack-2.2.3.1/lib/rack/conditional_get.rb:27:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/rack-2.2.3.1/lib/rack/head.rb:12:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/http/content_security_policy.rb:19:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/rack-2.2.3.1/lib/rack/session/abstract/id.rb:266:in `context'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/rack-2.2.3.1/lib/rack/session/abstract/id.rb:260:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/cookies.rb:689:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/railties-6.1.5.1/lib/rails/rack/logger.rb:26:in `block in call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb:37:in `tagged'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb:99:in `tagged'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/railties-6.1.5.1/lib/rails/rack/logger.rb:26:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/request_id.rb:26:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/rack-2.2.3.1/lib/rack/method_override.rb:24:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/rack-2.2.3.1/lib/rack/runtime.rb:22:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/activesupport-6.1.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/rack-2.2.3.1/lib/rack/sendfile.rb:110:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220604/gems/railties-6.1.5.1/lib/rails/engine.rb:539:in `call'
    /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
    /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
    /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
    /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
    /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202392584565107) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
This backtrace is happening everytime I try to view my interactive sessions.

**Comment by treydock** [comment]
I have been searching through not only OnDemand and OOD gems but my entire RVM gemset looking for something like `URI.encode` and I'm not finding anything.

**Comment by johrstrom** [comment]
I think it's trying to render this custom partial.

https://github.com/OSC/bc_osc_jupyter/blob/5f272e0515bad5a24850f8ed66ad3d6ba0399e58/view.html.erb#L6

**Comment by johrstrom** [comment]
So this was trying to generate partial `view.html.erb` of an app. Let's keep this ticket open because we should have rescued here and shown an error instead.
