### ISSUE TITLE
Dashboard: feature request: public login page

### ISSUE THREAD

**Issue by michaelkarlcoleman** [OSC/ondemand#207]
Somewhat similar to the logout page, it would be nice to have a login page of some sort that is shown to users prior to authenticating.  Currently, at least with Basic Auth, they're given a blank page and a dialog box to type their username/password into.  It would be nice to be able to show a page describing what they're logging into, public announcements, and some basic security advice (beware of public terminals, use "private browsing" mode if possible, etc.)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737508191454) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
@michaelkarlcoleman it has been a while since you suggested this, but I did a test using a Vagrant image and it worked okay. You can see it here: https://discourse.osc.edu/t/content-for-initial-auth-page/632/3

**Comment by johrstrom** [comment]
Yes using the `root_uri` in the `ood_portal.yml` that points to your own HTML page in the public space does this. You just need to write the HTML yourself and have a link (anchor) somewhere to `/pun/sys/dashboard` so users can then navigate to the dashboard.
