### ISSUE TITLE
Dashboard: Add a menu caching mode to OnDemand, and make that default

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#209]
The dashboard builds the menu dynamically on each request, instead of caching the information. This is great when you have multiple people doing app sharing and app development and you are deploying new apps and want to see them appear immediately in your dashboard menu.

This is not great otherwise.

A simple solution would be to run the dashboard in two modes, one which caches the menu on load, the other which continues as before.

A more complex solution is the dashboard caches the menu information on load (via initializer) and invalidates cache for individual apps when the files that were used to build the information changes (a manifest.yml or a form.yml.erb file).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204169044282257) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
Caching the metadata about an app and using the cache key as the manifest path + modified timestamp may be sufficient

**Comment by matt257** [comment]
reviewed,
closing and opening a new ticket for caching issues
