### ISSUE TITLE
passenger temp directory should be created under tmp_root rather than /opt/rh/ondemand/root/usr/share/nginx

### ISSUE THREAD

**Issue by davidmonro** [OSC/ondemand#2090]
After upgrading to ondemand 2.0.26 we discovered that the PUN wouldn't start, with the following error:

`Error -- nginx: [emerg] mkdir() "/opt/rh/ondemand/root/usr/share/nginx/passenger_temp" failed (13: Permission denied)`

in the browser.

At one level this appears to be an selinux issue, in that if selinux is disabled it creates the directory successfully
However, it creates it as the user who happens to run the first PUN instance. This doesn't seem good.
I think it makes a lot more sense to redirect it to where the other temp directories are using the passenger_temp_path directive.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202470714057100) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Thanks for the issue and the Pull Request! It's simple & straightforward enough. I think it does make much more sense to put all this in `/var/tmp/ondmend-nginx/$USER`.

**Comment by johrstrom** [comment]
@davidmonro thank you for opening the ticket. `2.0.27` is now available with this fix.
