### ISSUE TITLE
Upload same filename replaces file

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2097]
When you upload a file that shares the same name of a file that already exists - we currently replace it.  Instead, we should do what Web browsers and curl, wget and likely others all do, append numbers to the filenname like so:

```text
foo.txt
foo_1.txt

# this tends to be strange/bad in Linux, so I'm tempted to just use underscore `_N`. 
foo (1).txt 
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823777464629) by [Unito](https://www.unito.io)

**Comment by lukew3** [comment]
> Does #2094 also fix this? or is it just related?

Just related. The code to generate a new filename is written in #2094 but would have to be applied to this context
