### ISSUE TITLE
Improve location directive URI pattern for custom html and default html

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#21]
See https://github.com/OSC/ondemand/blob/667919bce701c7ec4daa1528e3367dd38ea0b46f/nginx_stage/templates/pun.conf.erb#L79-L88

Once #19 is fixed, and we have a reliable way to reliably serve up custom static files from /etc/ood with defaults from /opt/ood, we should change the URIs so instead of the default URI being `/pun/html/....` the custom URI is `/pun/html/...` and the default URI is `/pun/default_html/`. Then the dashboard and other apps can include shared resources using `/pun/html/...` and sites can override as they desire. 

Once this is done we could use the same pattern to have certain per-user assets generated at PUN startup stored at `/var/lib` (with optional sensible defaults in `/opt` dropped into), even including files containing json.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737614301138) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
reviewed,
closing (#19 already closed)
