### ISSUE TITLE
stricter import of ood_packaging

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2101]
Without updating my bundle I got this error.  Seems like the dependency isn't quite right.  It probably should have failed because it couldn't find `ood_packaging-0.4.0`. 

    [src(master)] 🐷  rake package:build['el9']
    rake aborted!
    ArgumentError: Invalid dist selected: el9. Valid choices are el7 el8 ubuntu-20.04
    /home/jeff/.gems/ruby-2.7.6/gems/ood_packaging-0.1.2/lib/ood_packaging/build_box.rb:28:in `initialize'
    /home/jeff/.gems/ruby-2.7.6/gems/ood_packaging-0.1.2/lib/ood_packaging/package.rb:23:in `new'

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202502920484439) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
Not sure how to make it more strict, the version is in Gemfile.lock , so shouldn't a "bundle exec ..." fail if the needed gems are not present?

Set non-existent version:

```diff
$ git diff
diff --git a/Gemfile b/Gemfile
index 7209de967..d6fd9880d 100644
--- a/Gemfile
+++ b/Gemfile
@@ -8,7 +8,7 @@ gem 'rake'
 gem 'dotenv', '~> 2.1'
 
 group :package do
-  gem 'ood_packaging', '~> 0.4.0'
+  gem 'ood_packaging', '~> 0.5.0'
 end
 
 group :test do
diff --git a/Gemfile.lock b/Gemfile.lock
index e040cc8e2..80c1b43ed 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -101,7 +101,7 @@ GEM
     oga (3.3)
       ast
       ruby-ll (~> 2.1)
-    ood_packaging (0.4.0)
+    ood_packaging (0.5.0)
       rake (~> 13.0.1)
     open_uri_redirections (0.2.1)
     parallel (1.21.0)
@@ -189,7 +189,7 @@ DEPENDENCIES
   beaker-docker (~> 1.1.1)
   beaker-rspec
   dotenv (~> 2.1)
-  ood_packaging (~> 0.4.0)
+  ood_packaging (~> 0.5.0)
   rake
   rspec
   rubocop
```

```
$ bundle exec rake -T
Could not find ood_packaging-0.5.0 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by johrstrom** [comment]
Now that you mention it, I don't typically run `bundle exec` and that likely should be our best practice because it's better at edge cases like this.
