### ISSUE TITLE
Dashboard: Dashboard assumes the bin/setup-production script is in a Ruby app with Bundler

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#211]
If bin/setup-production exists and is executable, the dashboard executes this prior to launching:

https://github.com/OSC/ood-dashboard/blob/ad5edd97add7a8462a9119e5494152392f94d7c6/app/apps/ood_app.rb#L195-L213

This "bundle exec" probably shouldn't occur unless this is verified to be a Ruby app i.e. does `config.ru` exist?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737614643833) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
maybe check if a gemfile exists before using bundler
