### ISSUE TITLE
Dashboard: Consider printing the contents of the environment during an interactive app job for debug purposes

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#212]
i.e. `set > $PBS_O_WORKDIR/env_during_job` or writing this to stderr. This would help with debugging.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737559130205) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
reviewed,
not a useful addition
