### ISSUE TITLE
Cloud Storage: Support copying/moving files 

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2129]
Right now when I try to copy or move a file from a remote file system to the local filesystem it does not recognize that the destination is another file system.  I.e., it tries to move/copy to a local location that doesn't exist on the remote.

Steps to replicate

* navigate to a remote filesystem
* select a file to copy
* navigate to the local file system
* try to copy/move the file

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202671567663170) by [Unito](https://www.unito.io)

**Comment by robinkar** [comment]
I've managed to get my implementation of this working quite nicely, will submit a PR after next week.
