### ISSUE TITLE
developer is no longer enabled in the dev container

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2130]
Dev containers built from the nightly RPMs don't seem to have development enabled by default which they should.

The `entrypoint.sh` used to create the symlink, but looking at this directory shouldn't `dev` be created by the RPM?

```
[root@275ba3434139 /]# ls /var/www/ood/apps/ -lrta
total 16
drwxr-xr-x 1 root root 4096 Jul 14 10:30 usr
drwxr-xr-x 1 root root 4096 Jul 14 22:39 sys
drwxr-xr-x 1 root root 4096 Jul 14 22:39 ..
drwxr-xr-x 1 root root 4096 Jul 14 22:39 .
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823782067071) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
@treydock should we be making the dev directory here too?  Do you happen to recall why we don't?

https://github.com/OSC/ondemand/blob/23447343a534b68ed6de39372464856d4a58b562/packaging/rpm/ondemand.spec#L146-L147

**Comment by treydock** [comment]
I believe this was left off to avoid enabling app development by default which can be somewhat undesirable for a site given what it allows users to do (ie access files and run code on OnDemand web server that might not be vetted by admins).  If there is more to enabling app development than creating that directory, then I think it's safe to add that directory to packages.  If creating /var/www/ood/apps/dev will enable app development, it should not be in the package.

**Comment by johrstrom** [comment]
OK - I'll have to check on it specifically, but it seems like you'd still have to create the symlink back to the users home directory. But there is 1 config that'll make development enabled for everyone by default, but IIRC that bypasses the var directory altogether and goes straight to your home.
