### ISSUE TITLE
File editor save button toggle

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2135]
The file editor used to have this feature that would toggle the save button given updates.  That is, the save button isn't clickable when there are no changes (i.e., nothing to save) then does toggle to be clickable when there are indeed changes that can be saved. Let's add that functionality back.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823782685085) by [Unito](https://www.unito.io)

**Comment by gerald-byrket** [comment]
Why???

**Comment by johrstrom** [comment]
To visually indicate whether you _can_ save or not. I found it useful to see that you have something in the buffer that you need to save.
