### ISSUE TITLE
Dashboard: batch connect adapter errors do not contain stack trace or exception type

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#214]
So there is no easy way to determine why this is broken:

```
Failed to submit session with the following error:

wrong number of arguments (1 for 0)
```

When submitting a desktop app.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737614990170) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
same issue is tracked in #221
