### ISSUE TITLE
problems installing nightly deb

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2146]
I'm getting this error trying to `apt install ondemand` in 20.04. You can see my `ondemand-web.list` below.

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ondemand : Depends: ondemand-nginx (= 1.20.2) but it is not going to be installed
            Depends: ondemand-passenger (= 6.0.14) but 6.0.14.ood2.1 is to be installed
E: Unable to correct problems, you have held broken packages.


root@c05cdc893c35:/# cat /etc/apt/sources.list.d/ondemand-web.list
deb [arch=amd64] https://apt.osc.edu/ondemand/latest/web/apt focal main
deb [arch=amd64] https://apt.osc.edu/ondemand/nightly/web/apt focal main
```

**Comment by treydock** [comment]
The versions of ondemand-nginx and ondemand-passenger were changed here: https://github.com/OSC/ondemand/commit/474db8022fa0b6252f1ddca932e9b2c5a1f919c6

I had to remove the old deb packages to avoid conflicts with 2.0 builds which use the older, less specific, version scheme.  What I'm not sure about is why the nightly didn't pick this up.  Based on info on code.osu.edu, the nightly pipeline was using commit [0d485ef0](https://code.osu.edu/ondemand/ondemand/-/commit/0d485ef05d9ea60067adbd3c949af84f3ff282f0) which is from 5 days ago.  I'm forcing a new nightly build to run which appears to have picked up the latest commits.

**Comment by johrstrom** [comment]
> the nightly pipeline was using commit [0d485ef0](https://code.osu.edu/ondemand/ondemand/-/commit/0d485ef05d9ea60067adbd3c949af84f3ff282f0) which is from 5 days ago.

I guess we'll have to check up on it throughout the week. Seems like it should be syncing itself every 30 minutes.

**Comment by treydock** [comment]
The new nightly is correct

```
$ dpkg -I /var/www/repos/public/ondemand/nightly/web/apt/pool/focal/ondemand_2.1.20220720.124641.dd22ef4.nightly_amd64.deb  | grep nginx
 Depends: libc6 (>= 2.29), libgcc-s1 (>= 3.0), libruby2.7 (>= 2.7.0), libsqlite3-0 (>= 3.7.10), libstdc++6 (>= 9), ruby, apache2, sudo, lsof, lua-posix, tzdata, nodejs (>= 14.0), nodejs (<< 15.0), ondemand-nginx (= 1.20.2.p6.0.14.ood2.1), ondemand-passenger (= 6.0.14.ood2.1)
```

**Comment by treydock** [comment]
One thing I was going to do with the Puppet module is run Github Actions via cron like schedule and the E2E tests on the Puppet module install both stable and nightly packages.  So that's one way to catch this issue.  Unfortunately because nightlies are 2.1, I can't merge that logic into main branch and have the cron run to test nightlies until the Puppet module can have 2.1 logic merged into main branch.

**Comment by johrstrom** [comment]
Yea this got fixed. At least for now given our code osu edu issues!
