### ISSUE TITLE
Branding Customizations - Support branding customizations based on profiles

### ISSUE THREAD

**Issue by adaybujeda** [OSC/ondemand#2149]
At IQSS, we have a requirement to support different look and feel for different departments. Moving the existing branding customizations to new profile feature will allow us to implement some of these requirements.

**Definition of Done**
Move the following environment values from `ConfigurationSingleton` to `UserConfiguration` 

* `OOD_DASHBOARD_TITLE`
* `OOD_DASHBOARD_LOGO`
* `OOD_DASHBOARD_LOGO_HEIGHT`
* `OOD_PUBLIC_URL`
* `OOD_BRAND_BG_COLOR`
* `OOD_BRAND_LINK_ACTIVE_BG_COLOR`
* `OOD_DASHBOARD_HEADER_IMG_LOGO`
* `OOD_NAVBAR_TYPE`

Update the UserConfiguration functionality to read from the `ENV` object first before using the `config` object data.
Values in the `ENV` object will have precedence over values in the `config` object.

Update all references to these values from the ConfigurationSingleton to the new UserConfiguration object.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202671563945156) by [Unito](https://www.unito.io)

**Comment by adaybujeda** [comment]
We have started working on this feature. Draft PR coming shortly

**Comment by johrstrom** [comment]
One thing on implantation that I'd expect is moving all these env variables to `string_configs` if they're simple. I.e, default or value. some have more complicated toggling logic. If that's the case, they can have their own function, but I'd say most can move here.

https://github.com/OSC/ondemand/blob/a66892f2d93af77cdbc478bb583fd3b7bc754166/apps/dashboard/config/configuration_singleton.rb#L54-L59

**Comment by johrstrom** [comment]
I see, you just duplicate the same blocks. That could work too.

**Comment by adaybujeda** [comment]
Just to be on the same page. These are the changes: https://github.com/OSC/ondemand/pull/2151

Still work in progress and not complete, but the general idea is there.
Let me know what you think.

**Comment by adaybujeda** [comment]
Small demo of what is possible with the OnDemand Branding setup using the new profile based configuration:

![branding](https://user-images.githubusercontent.com/17336210/180829609-cd9d348e-637c-4016-ab74-a433f737e4f8.gif)

**Comment by johrstrom** [comment]
This was fixed in #2151.
