### ISSUE TITLE
Dashboard: Ruby VDI (and thus Pitzer VDI) appear in the dropdown even if you do not have access to the cluster

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#215]
The problem is that in the VDI case, we are using a shared cluster (quick), and it is resources of that cluster (Ruby nodes, Pitzer nodes) that happen to be unavailable.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737559100018) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I'm not sure if we can replicate now.
