### ISSUE TITLE
Branding Customizations - Support for custom CSS file

### ISSUE THREAD

**Issue by adaybujeda** [OSC/ondemand#2150]
At IQSS, we have a requirement to support different look and feel for different departments. The existing branding customizations are not enough to achieve the desired look and feel for the Sid UX.

We think that for cases were branding customizations are more complex, allowing the inclusion of custom CSS files, will allow us to have more possibilities on what is possible to achieve.

**Definition Of Done**
This new feature should be added to the new profile based configuration to be able to load different CSS files per profile.

The custom CSS files should be loaded in all pages and last so that they take precedence over the default OnDemand files.

The new `UserConfiguration` property should be an array of strings, each one representing a CSS file to be loaded

The custom CSS files need to be placed under `public/custom` folder within the dashboard application directory.

The custom files could be inserted in the `application.html.erb` template as:

```
  <% custom_css_paths.each do |path| %>
      <%= stylesheet_link_tag "/custom/#{path}", nonce: true, media: 'all' %>
  <% end %>
```

This will result in the final URL for the file as: `/pun/sys/dashboard/custom/<path>`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202671449622368) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
This could be tough as assets are precompiled then shipped with OnDemand. That is, any assets you provide after the fact won't be recognized by sprockets, so it's unlikely any rails helpers will work.

>The custom CSS files need to be placed under public/custom folder within the dashboard application directory.

Plus anything you put here will be overwritten, it'd have to come out of `/etc`. 

What CSS are you looking for that bootstrap wouldn't provide?  I'm wondering if there's another way to solve the problem here. We'd like to really increase our CSP so that you won't even be able inline `<style>` tags at some point. Are the classes generic enough to just add to the distro?

**Comment by adaybujeda** [comment]
When doing the gap analysis, we tried to replicate the navigation look and feel with the current Branding configuration options in OnDemand. We can achieve around 95% of the Sid look.

<img width="758" alt="Screenshot 2022-07-21 at 14 28 19" src="https://user-images.githubusercontent.com/17336210/180225586-1d7b5bee-d7e3-4ac4-8249-a0ce0b2852dc.png">

We thought that requesting overrides for the missing items to achieve the Sid look was not an scalable solution that is why we thought of a custom CSS file.

**Comment by johrstrom** [comment]
You can try it!  But here are some items to note.

* it may require asset recompilation at the site 
* without compilation (no nonces, it's a static html tag that can pull assets) it may not hold for what we'd like our content security policy to be. I.e., nonce only.

I guess this is sort of an advanced use case, so maybe recompilation isn't too much to ask. Although it could obviously lead to trouble when upgrading and so on.

**Comment by johrstrom** [comment]
I'm now realizing there's a `skip_pipeline` flag you can pass which could be an option - but we'll still have to see how it affects our CSP.

**Comment by adaybujeda** [comment]
I have created an initial PR to discuss implementation: https://github.com/OSC/ondemand/pull/2168

I am currently using `stylesheet_link_tag` method to print the `"link type=stylesheet"` HTML tag.
I am currently prepending `/custom` to the value for the css file property.

This seems to work ok. The generated path to the CSS is: `/pun/dev/ood/custom/sid.css`.
`stylesheet_link_tag` is prepending to the path the application root path, in my case: `/pun/dev/ood`.

`skip_pipeline` has no effect in this case.
Only when the path used in `stylesheet_link_tag` is relative (no leading /), is when `skip_pipeline` does something.
Without a leading /, it will try to find an asset in the pipeline that matches the name and errors if it doesn't . `skip_pipeline` in this case, generates the CSS path as before, prepending this time: `/pun/dev/ood/stylesheets/custom/sid.css`.

**Comment by adaybujeda** [comment]
As for the CSP, there should be no issues. The configuration under `content_security_policy.rb` adds `self`, `https`, and `nonce` for `style_src`.  The current implementation will only allow CSS to be served from the same application (same host and port) so `self` will suffice. But we can add the `nonce` to the tag by using the `content_security_policy_nonce` method:
`<%= stylesheet_link_tag path, nonce: content_security_policy_nonce, media: 'all' %>`

**Comment by adaybujeda** [comment]
We could use the public Apache folder to deploy the CSS files instead of Dashboard application public folder.
The CSS will not be overriden when upgrading OnDemand.

in order to achieve this, we would need to print the CSS tag directly like:
  <% custom_css_paths.each do |path| %>
    <link rel="stylesheet" media="all" href="<%= path %>" nonce="<%= content_security_policy_nonce %>" />
  <% end %>

**Comment by adaybujeda** [comment]
I have updated the PR. The latest adds a link HTML tag directly in the application layout and uses the Apache public URL as the based for all custom CSS files.
https://github.com/OSC/ondemand/pull/2168

**Comment by adaybujeda** [comment]
This was fixed in https://github.com/OSC/ondemand/pull/2168
