### ISSUE TITLE
Unable to edit file with latest nightly

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand#2159]
I clicked on a file name from job composer to edit that file or view it and got this:

    #<NoMethodError: undefined method `remote_type' for nil:NilClass>
    
    /var/www/ood/apps/sys/dashboard/app/controllers/files_controller.rb:175:in `validate_path!'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb:427:in `block in make_lambda'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/actionpack-6.1.5.1/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb:512:in `block in invoke_before'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb:512:in `each'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb:512:in `invoke_before'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb:105:in `run_callbacks'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/actionpack-6.1.5.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/actionpack-6.1.5.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb:203:in `block in instrument'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/activesupport-6.1.5.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb:203:in `instrument'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/actionpack-6.1.5.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/actionpack-6.1.5.1/lib/abstract_controller/base.rb:165:in `process'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/actionview-6.1.5.1/lib/action_view/rendering.rb:39:in `process'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/actionpack-6.1.5.1/lib/action_controller/metal/live.rb:261:in `block (2 levels) in process'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/activesupport-6.1.5.1/lib/active_support/dependencies/interlock.rb:42:in `block in running'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/activesupport-6.1.5.1/lib/active_support/concurrency/share_lock.rb:162:in `sharing'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/activesupport-6.1.5.1/lib/active_support/dependencies/interlock.rb:41:in `running'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/actionpack-6.1.5.1/lib/action_controller/metal/live.rb:253:in `block in process'
    /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.20220720/gems/actionpack-6.1.5.1/lib/action_controller/metal/live.rb:303:in `block in new_controller_thread'

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202671444810839) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
If I select job template and choose "Edit Files" I see no issues.  I can also choose to edit that file. But when I click on "sequential_job.sh" here I get the error:

<img width="787" alt="Screen Shot 2022-07-25 at 3 03 14 PM" src="https://user-images.githubusercontent.com/739622/180854347-c8f23494-e8d2-4a8f-b11f-7d0303645c9a.png">

**Comment by robinkar** [comment]
The URL needs an extra `fs`. So `files/edit/fs/home/...` instead of `files/edit/home/...`
This should probably be fixed in [ood_appkit](https://github.com/OSC/ood_appkit/issues/67).
I could probably submit a PR for it there, but I'm not sure what the process is for getting the changes synced here.

According to a quick grep this also occurs in `apps/dashboard/app/models/product_readme.rb`.

**Comment by johrstrom** [comment]
You're right, we need to update that ood appkit API for something like `edit(fs: 'fs')`.  If you submit a PR there, I can handle publishing and updating on this side.  Should be fairly simple, just haven't gotten around to it with yet.

**Comment by robinkar** [comment]
Submitted PR, https://github.com/OSC/ood_appkit/pull/68
