### ISSUE TITLE
Dashboard: Refactor away "SmartAttributes" to remove complexity from both code and admins

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#216]
The [SmartAttributes module](https://github.com/OSC/ood-dashboard/tree/a5f8834da4c9ce3eacd42d4581c303f81dc5fac2/lib/smart_attributes) was introduced to address these problems:

1. Provide some default batch connect form attributes that all apps could use with default labels and help
1. Localize those attribute labels and help text to a specific job adapter (Slurm, or PBS Pro, etc.)
1. Define the resulting submit arguments hash that should be used based on the value in the form
1. Use ruby code in a method to build this submit hash, so that some logic can be used

Unfortunately this code and the resulting [SessionContext class](https://github.com/OSC/ood-dashboard/blob/a5f8834da4c9ce3eacd42d4581c303f81dc5fac2/app/models/batch_connect/session_context.rb) has complexity that makes it more challenging to maintain, understand, and it has some limitations.

There may be a simpler way to address the problems above without using the SmartAttributes module.

1. Localization of attribute labels and help text specific to job adapters could move into ood_core itself (https://github.com/OSC/ood_core/issues/68) and ood_core could be updated to provide a basic abstraction to requesting nodes, cpus, etc. (i.e. slots) to use when submitting a job, removing the need for "format" argument to label and submit, which are used https://github.com/OSC/ood-dashboard/blob/a5f8834da4c9ce3eacd42d4581c303f81dc5fac2/lib/smart_attributes/attributes/bc_num_slots.rb#L34-L44 and https://github.com/OSC/ood-dashboard/blob/a5f8834da4c9ce3eacd42d4581c303f81dc5fac2/lib/smart_attributes/attributes/bc_num_slots.rb#L55-L70 and https://github.com/OSC/ood-dashboard/blob/a5f8834da4c9ce3eacd42d4581c303f81dc5fac2/lib/smart_attributes/attributes/bc_queue.rb#L22-L30
1. To handle "logic" in the "submit hash" for a single attribute, this could actually be accomplished if in the form.yml.erb a submit section could be added specifying the template the value to be used here. Some thought would be required to determine how to do  this. Maybe just a [format string](https://ruby-doc.org/core-2.2.0/Kernel.html#method-i-sprintf) via [String#%](https://ruby-doc.org/core-2.2.0/String.html#method-i-25) with the value would be possible. Or maybe the value of the form field is the submission parameter. Or maybe the name of the form field is `submit[FIELDNAME]` instead of `batch_connect_session_context[FIELDNAME]` i.e. for bc_account instead of the form name being `batch_connect_session_context[bc_account]` which the Rails form helpers normally produce when building the form object is a BatchConnect::SessionContext instance, we instead would have form field name be `submit[script][accounting_id]` since this is the actual hash that is being created by https://github.com/OSC/ood-dashboard/blob/a5f8834da4c9ce3eacd42d4581c303f81dc5fac2/lib/smart_attributes/attributes/bc_account.rb and the form submission would result in this hash being available in the Rails controller's `params` hash. This also means we could store extra values like these in hidden fields and use javascript to update these, applying whatever logic we want.
1. If these existed, then it would be possible to define these "smart attributes" using the same "form.yml.erb" format as is currently used for other "smart attributes". In fact, we could go further, using YAML anchors provided to the form.yml.erb to use. Then there would be no "default attributes defined" at all, and no merging happening in Ruby code:

    ```yaml
    attributes:
      bc_account:
        <<: *bc_account
      bc_resolution:
        <<: *bc_resolution
    ```The point of all of this is removing complexity from the code and also removing things users need to learn to build batch connect. For example* if most batch connect apps could be completely defined using a form.yml.erb and the submit.yml.erb is unnecessary, that would reduce the number of things people need to learn* if the form.yml.erb could actually be a form.html.erb or a form.html then it could simplify things for people as well, since everyone knows HTML and some know JavaScript

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823788030630) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I'm going to close this as (a) I don't generally understand the solution, but (b) we've been adding a lot of `auto_` smart attributes that auto discover things from the system like queues and accounts and so on.

So we've infact doubled down on our use of SmartAttributes because now the project manager uses them too.
