### ISSUE TITLE
need to set passenger_preload_bundler

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2167]
We ran into this issue with the hpc toolset containers where Passenger was preferring personal gems over system installed gems. Setting `passenger_preload_bundler` to true seemed to do the trick. More info may be needed.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202671691538193) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
This is the stack trace you get when trying to boot 2.1 (/pun/dev/dashboard) from 2.0 (/pun/sys/dashboard).

```
You have already activated stringio 3.0.0, but your Gemfile requires stringio 3.0.2. Since stringio is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports stringio as a default gem. (Gem::LoadError)
  /usr/share/gems/gems/bundler-2.2.22/lib/bundler/runtime.rb:302:in `check_for_activated_spec!'
  /usr/share/gems/gems/bundler-2.2.22/lib/bundler/runtime.rb:31:in `block in setup'
  /usr/share/gems/gems/bundler-2.2.22/lib/bundler/spec_set.rb:159:in `each'
  /usr/share/gems/gems/bundler-2.2.22/lib/bundler/spec_set.rb:159:in `each'
  /usr/share/gems/gems/bundler-2.2.22/lib/bundler/runtime.rb:26:in `map'
```

**Comment by treydock** [comment]
Curious why setting to off is needed, that's the default: https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_preload_bundler

**Comment by johrstrom** [comment]
Yea sorry, updated the comment. Need to set it to `true`. I can't replicate on OSC systems for whatever reason, but can in a container (maybe because it's el 8?)
