### ISSUE TITLE
Configuration Question, not able to SSH to compute nodes.

### ISSUE THREAD

**Issue by bviviano** [OSC/ondemand#2169]
I am a new admin of OnDemand, so sorry if this is a basic question.  I've deployed 2.0.27 with DEX onto our RHEL8 based cluster.

I've configured an interactive Desktop and it launches VNC w/XFCE fine through Chrome/Firefox to one of the cluster compute nodes no problem.

The issue I'm having is when I try and use the SSH to compute node link that shows up on `/pun/sys/dashboard/batch_connect/sessions`.

When I click that link, it opens a new tab in my browser, but I get the error

```
Failed to establish a websocket connection. Be sure you are using a browser that supports websocket connections.
```

I assume I just have a configuration error someplace in my setup as I can use the Cluster->Shell Access link to the login node no problem.

I have tried the steps detailed here

https://osc.github.io/ood-documentation/latest/customization.html#fix-unauthorized-websocket-connection-in-shell-app

with no luck, and  I can't seem to locate anything else in the online documentation that addresses this.  There isn't anything clear to me in either the Apache or nginx logs that helps point as to why this isn't working.  Any insight into what I am missing in my configuration would be appreciated.

Thanks.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202675546336869) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Hi! No issues in opening a ticket here. We can help.

If you _can_ ssh into say login nodes, but _not_ compute nodes, my guess is it's your ssh allowlist https://osc.github.io/ood-documentation/latest/customization.html#set-ssh-allowlist - we're not letting you shell into just anywhere. 

If you open your browsers dev tools you may see a header like so:
![image](https://user-images.githubusercontent.com/4874123/181253589-a7058cee-1a32-4657-a43d-90801abba38a.png)

**Comment by bviviano** [comment]
Thanks.  I'll not if I manually set the name of the compute node AS a login node in my `cluster.yml`
```
---
v2:
  metadata:
    title: "Luna Cluster"
    hidden: false
  login:
    host: "r1n01.local"
```
Then restart nginx, I can use Cluster->Shell access to that compute node no problem, so it doesn't seem to be a configuration issue on the compute node side.

I did try setting the OOD_SSHHOST_ALLOWLIST before opening the ticket:
```
[root@login1 ~]# cat /etc/ood/config/apps/dashboard/env 
OOD_SSHHOST_ALLOWLIST='r[0-9]n[0-9][0-9].local'
OOD_SHELL_ORIGIN_CHECK='off'
```

and restarted Apache and nginx for my user and that didn't seem to make a difference.

**Comment by johrstrom** [comment]
It's the wrong file location. You have `dashboard` should be `shell`. Also I'd suggest turning `OOD_SHELL_ORIGIN_CHECK` back on or at least turning it on when you've sorted out this issue, as it's a security thing.

That Glob you have looks OK AFAICT.
```
# /etc/ood/config/apps/shell/env 
OOD_SSHHOST_ALLOWLIST='r[0-9]n[0-9][0-9].local'
```

**Comment by bviviano** [comment]
Yes, I realized the exact same thing as I was typing my response, but didn't 100% process it until after I hit the submit button :).

The following worked correctly.
```
[root@login1 shell]# cat /etc/ood/config/apps/shell/env 
OOD_SSHHOST_ALLOWLIST='r[0-9]n[0-9][0-9].local'
```

Thanks for your assistnace.
