### ISSUE TITLE
Remove dependency of efranz in unit testing.  All locations

### ISSUE THREAD

**Issue by gerald-byrket** [OSC/ondemand#2172]
Remove dependency of efranz in unit testing.  All locations.

We need to make this where it is not dependent upon any specific employee.

Sample Code:
`   expected = [
      ['cp', '-v', '-r', '/Users/efranz/dev/ondemand/apps/dashboard/app', '/var/folders/w7/fn8w83s10510pkc5j2wq8cpnhxtn3j/T/d20210201-68201-u3azoj/app'],
      ['cp', '-v', '-r', '/Users/efranz/dev/ondemand/apps/dashboard/config', '/var/folders/w7/fn8w83s10510pkc5j2wq8cpnhxtn3j/T/d20210201-68201-u3azoj/config'],
      ['cp', '-v', '-r', '/Users/efranz/dev/ondemand/apps/dashboard/manifest.yml', '/var/folders/w7/fn8w83s10510pkc5j2wq8cpnhxtn3j/T/d20210201-68201-u3azoj/manifest.yml']
    ]
    assert_equal expected, transfer.commands`

in apps/dashboard/test/models/transfer_test.rb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202678328563638) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
> We need to make this where it is not dependent upon any specific employee.

They're not dependencies, it's just a string really. It's just an example. Do the tests fail for you in any environment?

**Comment by gerald-byrket** [comment]
> > We need to make this where it is not dependent upon any specific employee.
> 
> They're not dependencies, it's just a string really. It's just an example. Do the tests fail for you in any environment?

No they do not. I think you are missing the point.  The point is.  There should be no automation, or anything tied to an individual's account.  Individual's come and go.  It is bad practice.  We need to undo these dependencies.   If there is functionality tied to a user's home directory, then there is a dependency on that user's home directory.  If Eric's home directory had been deleted when he left, then this test would have started failing.

We must, not should, we will need to get all dependencies from individual's gone.

Hopefully, this clarifies this request.

**Comment by johrstrom** [comment]
>  If Eric's home directory had been deleted when he left, then this test would have started failing.

These tests run in github actions where that directory does not exist. They also can run on _any_ machine like your local system where that directory does not exist.

There is no dependency, it's just an example. It's just testing string equivalence, it doesn't not actually validate or require that actual directory.

**Comment by gerald-byrket** [comment]
> > If Eric's home directory had been deleted when he left, then this test would have started failing.
> 
> These tests run in github actions where that directory does not exist. They also can run on _any_ machine like your local system where that directory does not exist.
> 
> There is no dependency, it's just an example. It's just testing string equivalence, it doesn't not actually validate or require that actual directory.

ok. That makes sense.  Thanks for the education. ;)

I will close this ticket then.
