### ISSUE TITLE
Dashboard: Batch connect validation errors do not appear in the developer interface

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#219]
The launch button disappears because it is invalid. But the validation errors do not display in its place.

Take a valid batch connect app and verify it shows in Sandbox apps. Change any quoted value to unquoted with `:` at beginning, which should generate a yaml load error. The launch button disappears but the validation errors do not display.

**Comment by KinanAlAttar** [comment]
Couldn't reproduce the bug
