### ISSUE TITLE
review profile choices in help menu

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2203]
I'm not quite sure we want the choices for profiles in the help menu. Let's use this ticket to maybe polish how users interact with this choice, should they have it.

Things to consider

* back out options - when you choose a profile, how can you reset back to no profile?
* #1909 
* A `themes` or `profiles` navbar entry

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202822854506750) by [Unito](https://www.unito.io)

**Comment by adaybujeda** [comment]
> back out options 

Currently, you can reset back to no profile by adding a link with an empty `id`:
```yaml
profile_links:
  - id: ""
    name: "default"
    icon: "cog"
  - id: team1
    name: "Team1"
    icon: "user"
  - id: team2
    name: "Team2"
    icon: "user"
```

**Comment by adaybujeda** [comment]
> A themes or profiles navbar entry

This makes more sense than using the `Help` menu. I was just wary of using space in the main navigation when decided to use an existing nav item.

**Comment by adaybujeda** [comment]
> Help menu responds to array

I think this can be done once we complete https://github.com/OSC/ondemand/issues/2154.
Adding a new property for the right hand side navigation, we could do exactly the same as with the main navigation.

**Comment by johrstrom** [comment]
>> back out options

> Thinking about the back out options, do you think it would be best, when a profiles are defined, that a profile should always be selected?
> 
> So that, what we are now calling the root configuration, cannot be selected and it is only used to add common configuration between profiles?

I guess the underlying question here is - do we want to expose the root configuration as an option? When we get that first page load (right now) it'll be the root configuration. And then you can choose a profile. 

But maybe we actually want a way to provide a default profile.  That is, say you have 2 defined A and B and you want A to show by default. Users can toggle between A and B, but they never see (or get to choose) the root configuration.

I think that if a user **ever** sees the root configuration, they should be able to switch back to it.  But if they don't ever see it - they can't toggle to it.

Put succinctly - I think any layout a user sees they should be able to recreate.

**Comment by johrstrom** [comment]
@abujeda did we ever come up with a backout strategy for profiles? How can a user navigate back to the default profile without modifying their preference file?

**Comment by abujeda** [comment]
The current back-out strategy is to select a profile that is not defined. This will use the root configuration. We use the empty profile:
```
help_menu:
  - group: "Profiles"
  - title: "Default"
    profile: ""
  - title: "Team1"
    profile: "team1"
```
The "`Default`" link generated above will select the root/default profile without manually modifying the preferences file.

We thought about using a special key like `root` or `default` to tell the backend to use the default profile, but never implemented it.

**Comment by abujeda** [comment]
Related to backing out of a profile, is having a default profile. We thought that it might be useful to users. when they first arrive at the site, to pre-select one of the profiles. After that, they can select other from the dropdown.

We thought about adding a string property to `ConfigurationSingleton`: `default_profile`

**Comment by johrstrom** [comment]
> The current back-out strategy is to select a profile that is not defined. 

🤦‍♂️  I should have read the other comments, I see you've said that before.  That'll work, I just need to check that it's documented.
