### ISSUE TITLE
Move settings for NavConfig and ShowAllApps to profile based configuration

### ISSUE THREAD

**Issue by adaybujeda** [OSC/ondemand#2215]
Part of the work related to user profiles: #2126 

`NavConfig.categories` is used to control the enabled groups and order for the navigation items. We would like this setting to be available in profile based configuration.

As well `Configuration.show_all_apps_link?` adds a link to the all applications page to the main navigation. We would like this too in the profile based configuration.

relates to #2154

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202822767740998) by [Unito](https://www.unito.io)

**Comment by adaybujeda** [comment]
Created a PR with a proposal implementation: https://github.com/OSC/ondemand/pull/2221

**Comment by johrstrom** [comment]
Completed in #2221 (mostly) and the touch up (#2241)
