### ISSUE TITLE
Yum repo is down

### ISSUE THREAD

**Issue by jsteel44** [OSC/ondemand#2222]
Hi,

I'm not sure if this is the correct place to report this, but we can no longer get to https://yum.osc.edu/ondemand/; the connection times out. If you do not manage this, do you know where best to report this issue?

Many thanks

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202770265975626) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
OSC is having a center wide downtime, but I think someone neglected to update SRX firewall allow to work with new RHEL8 VM hosting OnDemand repos.  I'll pass this to our networking folks to get this fixed.

**Comment by treydock** [comment]
The person at OSC who manages the SRX is out today.  The downtime should be done by this evening which is when repo services will be back.

**Comment by treydock** [comment]
@jsteel44 The firewall changes were made so yum.osc.edu should be accessible again.
