### ISSUE TITLE
Rclone Install Breaks Current Container Build

### ISSUE THREAD

**Issue by Oglopf** [OSC/ondemand#2245]
After adding the `rclone` dependency in #2234 it looks like the `dev` container will fail to build with an error:

```
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides rclone needed by ondemand-2.1.20220817-126590.a35d485.nightly.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
The command '/bin/sh -c dnf -y update &&     dnf install -y dnf-utils &&     dnf config-manager --set-enabled powertools &&     dnf -y module enable nodejs:14 ruby:3.0 &&     dnf install -y ondemand ondemand-dex &&     dnf install -y epel-release &&     dnf install -y rclone &&     dnf clean all && rm -rf /var/cache/dnf/*' returned a non-zero code: 1
rake aborted!
Command failed with status (1): [docker build --build-arg VERSION=v2.1.0-0....]
```

Reproduce:

* `cd ondemand`
* Pull in any changes to `master`
* `bundle exec rake dev:rebuild`

Using  image `ood-dev:20220817`.

Looking in the `Dockerfile.dev` it looks like the `epel-release` is placed first yet this might not be present when the `rclone` install is done, meaning the order listed may not be the order of install:

https://github.com/OSC/ondemand/blob/68167c595161bb1dc25ea3b537a2ffb86b834d80/Dockerfile.dev#L20

But then:

https://github.com/OSC/ondemand/blob/68167c595161bb1dc25ea3b537a2ffb86b834d80/Dockerfile.dev#L21

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202816366405794) by [Unito](https://www.unito.io)

**Comment by Oglopf** [comment]
Since `rclone` is required as part of the `ondemand rpm` the install command is not needed, and the ` dnf install ondemand` line needs moved _after_ the `dnf install epel-release` line.

**Comment by treydock** [comment]
FWIW it's always best practice to install repos first, then packages. EPEL should have always come before OnDemand because of some Lua dependencies.
