### ISSUE TITLE
Improve large file upload to remote filesystems

### ISSUE THREAD

**Issue by robinkar** [OSC/ondemand#2250]
https://github.com/OSC/ondemand/blob/a05670f1fc062cb61b8e5f617d22e24e412635b6/apps/dashboard/app/models/remote_file.rb#L74
Currently uploading files to remote file systems fails with large files, depending on the speed of the connection to the remote.

Rails only receives the request once the whole file has uploaded, once that happens Apache expects a response from the PUN within 60s, otherwise Apache assumes it is a proxy timeout. So if the file takes longer than 60s to upload to the remote server, the upload fails with response 502.

A temporary solution would be to set `ProxyTimeout` to a larger value in the Apache config for the PUN. From the user's perspective the upload is stuck at 100% while the file is being uploaded from the OOD web server to the remote.

The best solution here would probably be to instantiate a `RemoteTransfer` for the upload from the OOD web server to the remote filesystem.
This would require copying the tempfile and handle deletion of it after the upload is done as Rack deletes uploaded files once a response is sent. Making that progress visible to the user would also be needed, but if we use `RemoteTransfer` that sounds simple enough as we already have that for file transfers.

Initially I had assumed something similar to how the file downloads work would be possible, where we would receive the file upload as a stream, which we could then write asynchronously to the remote filesystem. Sadly, that seems to not be possible, unless there are some hacky ways to do that, as Rack only passes the request to Rails once the whole file has been uploaded.

Part of #1789.

Are there other ways to handle this?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203792865249824) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
> Are there other ways to handle this?

I see this ticket, but don't know the answer off the top of my head. As an off the top guess, I'd bet there's a `rack` solution available or writable by us.  I say off the top, but I did search the rack tickets for streaming/chunks and it's at least being discussed. As well as some http/2 options that we could benefit from.
