### ISSUE TITLE
Remove NavConfig

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2255]
With #2221 changing the behavior and then #2254 adding the warning. Let's then remove NavConfig altogether.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203792942552408) by [Unito](https://www.unito.io)

**Comment by HazelGrant** [comment]
What needs to happen with the use of `NavConfig` in `UserConfiguration`- specifically where it's referenced here: 

https://github.com/OSC/ondemand/pull/2221/files#diff-8cbe6007d5dceb9e69860110358bae6e7d11cfa8791bc7c150a4c868ec9695efR108

**Comment by johrstrom** [comment]
> What needs to happen with the use of NavConfig in UserConfiguration- specifically where it's referenced here:

Something needs to hold/continue the defaults.

https://github.com/OSC/ondemand/blob/7f328014f02a9c37221092965802aebf0d5b52ed/apps/dashboard/app/apps/nav_config.rb#L6
