### ISSUE TITLE
Dashboard: Provide documentation for accessing batch connect apps

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#226]
The README should be updated to include the routes to access batch connect apps in sys and dev. (i.e., how do I access a `bc_` app via the dashboard after I clone it?)

Ideally, this would also be included in each of the `bc_` repos, but a single guide here would be helpful.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737616591485) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as won't do. There are 2 routes to discover the app - through the interactive sessions page or through my sandbox apps.
