### ISSUE TITLE
Dashboard: When launching a session from a dev app, do not auto-delete the session after it completes

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#229]
Session should show the state "Completed" and then provide links for debugging purposes, and maybe even display the error and output in bootstrap's progressive disclosure panes

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737561321090) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as a won't do. Developers should enable canceling the job so they can restart.
