### ISSUE TITLE
Ensure Caching Works As Expected

### ISSUE THREAD

**Issue by Oglopf** [OSC/ondemand#2291]
In #1420 we introduced caching for the images. It appears some of these are still making requests even with caching enabled.

This is to investigate this work and ensure the caching is working as expected before releasing in 2.1.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203792970866096) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Maintenance pages were the one thing I was worried about. That is, when maintanence mode is toggled from on (showing the static page) to off (allowing traffic to the PUN) that it still worked.

I've confirmed that the static html page isn't being cached and that when you toggle maintenance mode nothing is being cached and users can go directly to the PUN when it's turned off.
