### ISSUE TITLE
Use single version string for Open OnDemand

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#23]
Currently we embed the version string in multiple places:

./ood-portal-generator/lib/ood_portal_generator/version.rb ./ood_auth_map/lib/ood_auth_map/version.rb ./nginx_stage/lib/nginx_stage/version.rb ./mod_ood_proxy/lib/ood/version.lua

We might consider reducing the number of places we are displaying this. Or even have it read the VERSION file in the root of the directory or use the git sha.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737617094916) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
not really a customer facing issue,
not much of an issue for anyone
