### ISSUE TITLE
Dashboard: Add Batch Connect documentation to dashboard readme.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#230]
The "Batch Connect" features are now embedded into the dashboard. The dashboard readme should include documentation of the batch connect features available to app developers, or a link to the location where they reside (if elsewhere).

Particularly:

* [ ] Batch connect form helpers
* [ ] Notes on where the submit scripts are defined (including the before and after callbacks)
* [ ] Notes on the script wrapper for the cluster config

This documentation may already exist in the `OSC/ood-documentation` repo, but it should be linked here because developers may not know to check the install guide for this info.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737511438505) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as a won't do. The public documentation should be good enough.
