### ISSUE TITLE
Add functionality to easily disable built-in OnDemand Apps.

### ISSUE THREAD

**Issue by gerald-byrket** [OSC/ondemand#2304]
Regarding Discourse: https://discourse.openondemand.org/t/disabling-built-in-interactive-apps/2288

Is there a better way to disable a default interactive app, other than changing permissions on RPM-provided directories? Modifying /var/www/ood/apps/sys/ doesn’t seem like a very clean nor very robust approach. Wouldn’t it be better to allow local customization in /etc/ood to allow completely disabling apps?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203792936769739) by [Unito](https://www.unito.io)

**Comment by kcgthb** [comment]
It _seems_ like adding an override, invalid `manifest.yml` file in `/etc/ood/config/apps` is now sufficient to disable built-in apps (in version 3.0.x at least)?.

For instance, for `bc_desktop`, the following file prevents the app from being listed in the list of Interactive Applications:
```
$ cat /etc/ood/config/apps/bc_desktop/manifest.yml
disabled
```

**Comment by johrstrom** [comment]
That could work, though maybe by coincidence. I'd say using FACLs is the best approach. I know for sure we have puppet support for it, so it's not that fragile if you use automation. If we don't currently have ansible support for it (I don't think we do) we can add it.
