### ISSUE TITLE
ondemand 2.0.x and EOL nodejs12 dependency

### ISSUE THREAD

**Issue by CSC-swesters** [OSC/ondemand#2308]
Hello,

It was confirmed in the recent #2261 issue that ondemand 2.0.x only supports nodejs12. That dependency has been [end-of-lifed by the upstream since April 2022](https://nodejs.org/en/blog/release/v12.22.12/). Seeing as this is a growing security risk for sites using the stable OOD releases as time progresses, I'm interested to know

1. Are there any plans to backport nodejs14 support to the 2.0.x releases, or will we have to wait for the 2.1 release?
1. Do you have any estimates on how far out an initial 2.1 release is, in case nodejs14 won't be backported?

Thanks for all your good work!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203045989810784) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
> Are there any plans to backport nodejs14 support to the 2.0.x releases, or will we have to wait for the 2.1 release?

No, but with this we may need to consider it. Off the top it would depend on OS support - if we can target 14 on Ubuntu or not.

> Do you have any estimates on how far out an initial 2.1 release is, in case nodejs14 won't be backported?

No, but I think backporting is more likely.

**Comment by treydock** [comment]
For Ubuntu we deploy nodejs repos specific to a given nodejs version so not using what comes from OS.  This seems very do-able for 2.0 release.

**Comment by johrstrom** [comment]
Yea I am just worried about changing versions this late.  We just need to be sure we think it through.

**Comment by CSC-swesters** [comment]
Thanks for the quick replies! I'm glad to hear that you're considering to backport. 

One idea on how to handle the stability concerns with backports would be to call the release with nodejs updates 2.1.0, and shift the current 2.1 branch to be called 2.2. Then it would be a bigger heads-up to admins that something significant happened, rather than just bugfixes like users might assume with 2.0.x point releases. If all goes well, the 2.0.x branch can be deprecated since it's less secure and maybe not worth maintaining, but if there are issues, the stable branch hasn't been impacted. 

How does this sound? I have no idea about the actual amount of work involved, just throwing out ideas :)

**Comment by treydock** [comment]
It's actually a lot more work to cut 2.1 than to just backport to 2.0, especially given we've been working in 2.1 repos from master branch.  From my perspective a NodeJS update is less an impact to admins than Ruby since most OnDemand apps will tend to depend more on the Runtime scripting language than NodeJS

**Comment by CSC-swesters** [comment]
I see you shipped [2.0.29](https://github.com/OSC/ondemand/releases/tag/v2.0.29) including this NodeJS update. Thanks a lot, we'll be sure to try it out soon!

Let's close this issue, and open new ones in case there are further things to discuss.

**Comment by treydock** [comment]
Just FYI that 2.0.29 is not yet in 2.0 repos.  We don't put new RPMs into the release repos, like 2.0, until it's been tested for a little bit at OSC.

**Comment by CSC-swesters** [comment]
I see it's available in the ["latest" repository](https://yum.osc.edu/ondemand/latest/web/el7Server/x86_64/). Thanks again!

**Comment by treydock** [comment]
Yep, that's how OSC installs OnDemand, from latest.  This maybe redundant information but I always like to warn people of the dangers of using the "latest" repo since it does contain newer pre-alpha OnDemand 2.1 RPMs that are very unstable.  We install with automation so doing things like `yum install ondemand-2.0.29` as well as adding this to repo file:

```
exclude=ondemand*-2.1*
```

**Comment by CSC-swesters** [comment]
Yes, that's familiar for us at CSC, we've been using "latest" for about a year or so. We have a few separate test systems where we deploy OnDemand and verify that it works for our needs before rolling out to production.

In addition to your exclusion, I could mention that we've needed to also exclude some `ondemand-passenger` packages, since their versioning scheme is such that Yum will want to update, but the `ondemand` package doesn't want the newest version. For example these packages cannot be put into the Yum repos if using OnDemand 2.0.x versions:
```
ondemand-passenger-6.0.14-1.ood2.1.el7.x86_64.rpm
ondemand-passenger-6.0.14-1.ood2.1.1.el7.x86_64.rpm
```
If you have any way of making that work more smoothly that would be appreciated, but the current workarounds are to just delete these two files before generating the repofiles.

**Comment by treydock** [comment]
That exclude rule we use (in my previous comment) would wok with those since it excludes anything beginning with ondemand and container 2.1.  Those passenger RPMs are built for OnDemand 2.1.  Here is full yumrepo file we use:

```
$ cat /etc/yum.repos.d/ondemand-web.repo
[ondemand-web]
name=Open OnDemand Web Repo
baseurl=https://yum.osc.edu/ondemand/latest/web/el7/$basearch
enabled=1
gpgcheck=1
gpgkey=https://yum.osc.edu/ondemand/RPM-GPG-KEY-ondemand
metadata_expire=1
repo_gpgcheck=1
priority=1
exclude=ondemand*-2.1*
```

**Comment by johrstrom** [comment]
Yes OSC uses the puppet module which works well for us. If you use the ansible role and need any updates just let us know (I don't believe it supports switching to `latest` at the moment, but it could!).
