### ISSUE TITLE
Missing Home Directory

### ISSUE THREAD

**Issue by connorourke** [OSC/ondemand#2309]
We have open on demand running to access a cluster, however when users first log in they do not have a home directory.

We are using  **_OnDemand version: v2.0.27_**

I thought this [PR](https://github.com/OSC/ondemand/pull/18) provided a fix for that but it doesn't seem to have helped. 

In `ood/nginx_stage/html` i have copied the example over:

`cp missing_home_directory.html.example.pam_mkhomedir missing_home_directory.html`

Is this incorrect, or is there some other step I need to take in order to get this to work correctly?

Thanks

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203065081878398) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
That should be all you need to do. That's what the docs indicate and a quick spot check of the code seems to indicate the same. 

These NGINX directives should be there. Note it may be affected by the configuration `custom_html_root` (in `nginx_stage.yml` - did you change that?)
```
    <%- if missing_home_directory? -%>
    rewrite ^/pun/sys/dashboard(/.*|$) /pun/custom_html/missing_home_directory.html;
    <%- end -%>

    location = /pun/custom_html/missing_home_directory.html {
      add_header Cache-Control "no-store";
      root <%= custom_html_root %>;
      try_files /missing_home_directory.html /pun/html/missing_home_directory.html;
    }
```

What's the behavior you see - you have an error page around missing home directories instead of this missing_home_directory.html.

This is going to sound silly - but I'd spot check the filename that you copied. Looks like we're looking for `missing_home_directory.html` specifically, so misspelling this could be the issue.

**Comment by connorourke** [comment]
Thanks for the reply @johrstrom.

Actually I didn't see the error - our users did. And it doesnt seem to happen when I remove my own home directory and try logging in (I'm confused as to why that is).

I'll ask a user to show me what they see and get back to you.

**Comment by johrstrom** [comment]
> I remove my own home directory and try logging in (I'm confused as to why that is).

Likely your Per User Nginx (PUN) is still running. You can stop it by issuing one of these commands. Looks like we regenerate those templates every time.

```
/opt/ood/nginx_stage/sbin/nginx_stage nginx_clean <user> 
# and/or force it to close 
/opt/ood/nginx_stage/sbin/nginx_stage nginx_clean <user> --force
```

To try to replicate I would:
* if you have an open tab with your ondemand instance, close it.
* stop your PUN with the command given above
* remove your HOME (if it's safe for you to do so) 
* log back in 
* check `/var/lib/ondemand-nginx/config/puns/$USER.conf` to see if you have the rewrite config I posted above.

Also - and this is not likely - but I do want to be sure it's not as simple as you misspelled `missing_home_directory.html`. Again, not likely, but I would like to check it off.


Lastly - I'd ask that you spot check a user through `irb` (Ruby's interactive shell).  Here's what I did to verify my user's home directory. You can do the same with one of your customers that's having issues. Maybe there's some funny business with your LDAP where it's returning a different HOME directory (`user.dir`).
```
[johrstrom ~()]  irb
irb(main):001:0> user = Etc.getpwnam('johrstrom')
=> #<struct Etc::Passwd name="johrstrom", passwd="*", uid=30961, gid=5515, gecos="Jeff Ohrstrom", dir="/users/PZS0714/johrstrom", shell="/bin/bash">
irb(main):002:0> user.dir
=> "/users/PZS0714/johrstrom"
irb(main):003:0> File.exist?(user.dir)
=> true
```

**Comment by connorourke** [comment]
Hi @johrstrom 

Apologies for the delay - been on holiday last week. Using your instructions to stop the PUN I was able to step through this and see that it is working. 

Not sure what the user was seeing, but at least I know it is an issue in following the instructions not with the system setup.

Thanks for the help!
