### ISSUE TITLE
Footer in the Job Composer app?

### ISSUE THREAD

**Issue by kcgthb** [OSC/ondemand#2310]
Hi!

It looks like the "Job Composer" (`myjobs`) app is missing the same HTML footer that could be found on the main dashboard page, the "File Manager" page or the "Active Jobs" page. 

It actually doesn't seem to be following the same layout than the other applications, is that expected?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203792967035661) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
This is expected. It does use a different layout and is an entirely different code base from the dashboard.

**Comment by kcgthb** [comment]
Thanks Jeff! 
Any plans to bring it in line with other apps in the dashboard, to unify the look and feel across those various pages?

**Comment by Oglopf** [comment]
Yep! The new job composer will keep the same look and feel as the rest of the dashboard.

**Comment by kcgthb** [comment]
@lukew3 I see that this issue was closed, but I can't find the corresponding commit that brought the job composer under the same layout as the other pages, as @Oglopf 
mentioned? Could you please point it out? Thanks!

**Comment by johrstrom** [comment]
I can re-open it for you (@lukew3 went off to another job), but that said - I don't think it'll get fixed. We're re-working the job composer (nee Project Manager) in #1245 (which has many updates associated with it).

**Comment by kcgthb** [comment]
All right, thanks for the information, I'll follow the new Job Composer app developments in #1245 then!

**Comment by johrstrom** [comment]
3.1 will ship with it, although it's disabled by default because it doesn't have some key features like file management or historic jobs yet.
