### ISSUE TITLE
ood_portal command outputs RHEL commands only

### ISSUE THREAD

**Issue by Oglopf** [OSC/ondemand#2315]
## Problem
While troubleshooting an Ubuntu 20.04 install of OOD 2.0.28 I noticed that when the user issued the `update_ood_portal` command that the response which came back only included the commands for `RHEL/CentOS` and not what would be needed on Ubuntu.

## Possible Solution
Introduce some logic when the message displays to check the `OS` and display the appropriate message based off of that.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203095145964086) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
This is fixed in master.  So is this issue for a backport to 2.0 ?

**Comment by Oglopf** [comment]
Thanks Trey. My concern was the user on `2.0.28` who was seeing these messages. Given that we are pushing for a `2.1` release and trying to avoid more backporting until then, I'd say we should not worry about it.
