### ISSUE TITLE
Dashboard: When group membership changes, in AweSim we auto-restart the dashboard, in OnDemand, we don't provide the option

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#234]
The AweSim dashboard has app sharing enabled, and thus the default route is /apps/index. This controller checks if group permission changed and redirects the user to /apps/restart which warns the user of the change and restarts the PUN automatically.

In the OnDemand dashboard, app sharing is disabled and this is not available.

We need to update both dashboards so this check happens on each request to display the index page, and we display an alert with a restart PUN link, instead of auto-restarting the PUN, because if we auto-restart the PUN, the user may lose work if they have a terminal open.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737511962965) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
not worth effort
