### ISSUE TITLE
Customizing Session Cards

### ISSUE THREAD

**Issue by Oglopf** [OSC/ondemand#2342]
# Overview
We've had several discourse topics about customizing the panel card that is displayed for users. These requests have asked for things like a text field to provide a description, to something like adding the memory available. 

The topics can be seen here:
- https://discourse.openondemand.org/t/report-job-memory-allocation-in-my-interactive-sessions-currently-only-nodes-and-cores-are-reported/2254
- https://discourse.openondemand.org/t/session-information-in-info-md-erb/2332/6

Currently, we provide a very small amount of ability to customize this card and do some backend variable checking that you can use the `conn_params` with the `before.sh.erb` to setup in connection with the `form` to then alter how the `view` for an app may render, but actually passing anything to the `info.md.erb` is not possible.

# Proposal
The way to do this might be to adjust the `BatchConnect::Session` by allowing a list to be appended that has the attributes someone would like to have in a `form` which can take values of many types, and then render the array's members as `html` elements like a `string` to provide descriptions.

We have another [ticket](https://github.com/OSC/ondemand/issues/1228) in to refactor the entire way we do the Session Cards themselves as currently they are partials in the controller, and it would make sense to combine these tasks so that we refactor and enhance that part of the codebase.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203251644956789) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Yea I'm thinking some attribute like `show` or `display`. So in a form you have an example with `r_version` below. 

```yaml
attributes:
  r_version:
    display: true # show the choice in the card
    widget: "select"
    options:
      - "4.2"
      - "4.1"
```

I think the trick is just how to pass this back to the session where the session files will have to be vectors (hashes) instead of scalars (a single thing).

**Comment by adaybujeda** [comment]
Implementation idea based on the comments above: https://github.com/OSC/ondemand/pull/2366

```yaml
attributes:
  bc_account:
    value: "test data"
    display: true
```

<img width="400" alt="Screenshot 2022-11-11 at 16 17 26" src="https://user-images.githubusercontent.com/17336210/201383988-452c47b2-38c5-4372-9e9a-619fde3b18d7.png">

**Comment by Oglopf** [comment]
Thank you so much!
