### ISSUE TITLE
Modify OOD so that we can use value/text in the combo-box (select) when choosing a cluster.

### ISSUE THREAD

**Issue by gerald-byrket** [OSC/ondemand#2352]
Modify OOD so that we can use value/text in the combo-box (select) when choosing a cluster.

From Alan.

I just noticed something we probably need to have a discussion about, but it's not urgent.  In the Jupyter app on [ondemand.osc.edu](http://ondemand.osc.edu/), the cluster pull down has 'kubernetes' as an option.  And the lightweight deskop has "ascend-login" as an option.  Those might be rather confusing terms to our clients.  I think we need to talk about messaging around things like that in the descriptions of those apps.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202815755532406/1203280052613985) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I don't think we have to modify OOD to achieve this. It seems we just need to modify the apps directly to set a `cluster` attribute instead of having OOD generate it.

https://osc.github.io/ood-documentation/latest/app-development/interactive/form.html#configuring-which-cluster-to-submit-to

**Comment by johrstrom** [comment]
This isn't an OOD issue. If we want to change the names of clusters we can do so, we just need a new name.
