### ISSUE TITLE
Ubuntu 22.04

### ISSUE THREAD

**Issue by DavidKelly999** [OSC/ondemand#2356]
Hello,

Is Ubuntu 22.04 supported? I followed the instructions at https://osc.github.io/ood-documentation/latest/installation/install-software.html, but I'm getting these errors when running 'sudo apt update':

```
Ign:5 https://apt.osc.edu/ondemand/2.0/web/apt jammy InRelease                                                                        
Err:6 https://apt.osc.edu/ondemand/2.0/web/apt jammy Release                                
  404  Not Found [IP: 192.148.247.165 443]
Ign:7 https://deb.nodesource.com/node_12.x jammy InRelease                         
Err:8 https://deb.nodesource.com/node_12.x jammy Release
  404  Not Found [IP: 23.39.46.9 443]
Reading package lists... Done
E: The repository 'https://apt.osc.edu/ondemand/2.0/web/apt jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://deb.nodesource.com/node_12.x jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203292932503711) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1202821104799596/1203292932503711

**Comment by treydock** [comment]
For OnDemand 2.0 only Ubuntu 18.04 and 20.04 are supported.  The particular error you got is because the NodeJS repos don't support Ubuntu 22.04 which is not something we control. However if NodeJS did support Ubuntu 22.04, OnDemand itself does not.  For OnDemand it mostly comes down to Ruby versions, OnDemand 2.0 does not work with Ruby 3.0.

For OnDemand 2.1 we can look at supporting 22.04 but that release is many months away, if not longer.

**Comment by treydock** [comment]
I forgot we actually already support Ubuntu 22.04 with OnDemand 2.1 but per previous comment, the stable release of 2.1 is many months away or longer.

**Comment by johrstrom** [comment]
Hi, thank you for the ticket.

2.0 - has Ubuntu 18 & 20 support.
2.1 - will have Ubuntu 20 and 22 support.
