### ISSUE TITLE
dashboard unit tests failing on cluster

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2424]
Dashboard Unit tests have started failing on cluster for some reason.  It's unclear why these should start failing now as I'm sure our CI doesn't have `/opt/torque/lib64/libtorque.so` as well.

```
Error:
SessionsTest#test_default_application_menu_renders_correctly_when_nav_bar_property_defined:
LoadError: Could not open library '/opt/torque/lib64/libtorque.so': /opt/torque/lib64/libtorque.so: cannot open shared object file: No such file or directory
    app/models/batch_connect/session.rb:385:in `update_info'
    app/models/batch_connect/session.rb:376:in `info'
    app/models/batch_connect/session.rb:370:in `status'
    app/models/batch_connect/session.rb:443:in `completed?'
    app/models/batch_connect/session.rb:138:in `block in all'
    app/models/batch_connect/session.rb:137:in `map'
    app/models/batch_connect/session.rb:137:in `all'
    app/controllers/batch_connect/sessions_controller.rb:8:in `index'
    test/integration/sessions_test.rb:22:in `block in <class:SessionsTest>'
```

I'm sure it's something do do with `test/fixtures/config/clusters.d/` being torque clusters, but why it should start failing now is unclear.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203536481557649) by [Unito](https://www.unito.io)

**Comment by adaybujeda** [comment]
I think this could be related to the order the tests are running.
The sessions test could be picking up existing sessions from another test and trying to render them.

Will look into resetting the list of sessions in this test to see if this fixes the issue.

**Comment by adaybujeda** [comment]
Created PR to fix this issue: https://github.com/OSC/ondemand/pull/2427
