### ISSUE TITLE
File-Editor: File Editor should use File Explorer to display directories

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand#243]
Currently if a user edits the URL to point to a valid directory then they will be treated to the directory view. This is confusing because OOD already has a file explorer, but it is not being used in this situation.

https://github.com/OSC/ood-fileeditor/blob/2734edc215bd8e91e23a251dd6099981d49e755a/app/controllers/pages_controller.rb#L17-L19

An alternative implementation:

```ruby
    elsif @pathname.directory?
      redirect_to OodAppkit.files.url(path: @pathname).to_s
    else
...
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737512659558) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
this issue has been resolved
