### ISSUE TITLE
File-Editor: Change default font

### ISSUE THREAD

**Issue by nickjer** [OSC/ondemand#251]
Might be nice to use the same font that Google uses for `hterm`. They use the DejaVu Sans Mono font.

You can see the difference in:

![image](https://cloud.githubusercontent.com/assets/4260509/25148237/350d7a2a-2448-11e7-826f-5844f12b2571.png)

The left is the font I see in AceEditor (Ubuntu Mono) and the right is DejaVu Sans Mono.

**Comment by johrstrom** [comment]
Not going to change the default font. But I did make #1323 so we can allow folks to choose.
