### ISSUE TITLE
use plain javascript in toggleOptionsFor

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2517]
While working on #2516 I became very frustrated with the translations we have to do back and forth from javascript objects to jQuery objects and back again.

This ticket should build on the work in #2516, but you can see in the mainline already.

Here's a just the first example of this:
https://github.com/OSC/ondemand/blob/f24bc6f80cf5be695ffb2d7b00129ce13492f2ba/apps/dashboard/app/javascript/packs/batch_connect.js#L596-L599

Here in this line, `options` is a jQuery object while `option` (singular) is a native js object. We then have to cast `option` back to a jQuery object, `optionElement`.

But the question is, why can't we just interact with & update `option`?  With #2516 it gets worse casting back and forth. So let's reduce the complexity both in js runtime and also in the code by just using plain js objects and not recasting them back to jQuery objects.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203847725744881) by [Unito](https://www.unito.io)

**Comment by lukew3** [comment]
How can I test my changes? I'm having trouble figuring out what page this is working on or how to trigger `toggleOptionsFor`.

**Comment by johrstrom** [comment]
You can use one of our batch connect apps. Here's rstudio for example. This `node_type` `40 core` is only available on the `pitzer` cluster. So the option should disappear when any other cluster type is chosen.

https://github.com/OSC/bc_osc_rstudio_server/blob/f3b030e008ff012523571329f3373cf59c068f2f/form.yml.erb#L76-L83

**Comment by johrstrom** [comment]
So given this url

https://ondemand.osc.edu/pun/dev/dashboard/batch_connect/sys/bc_osc_rstudio_server/session_contexts/new

and this break point you can switch clusters back and forth and see 

![image](https://user-images.githubusercontent.com/4874123/215890558-42b72ae8-e625-4b26-bf2b-d710ec82d7d6.png)

plus you can push a branch and open a draft pull request and you can let the CI tell you.

here's the documentation for this feature

https://osc.github.io/ood-documentation/latest/app-development/interactive/dynamic-form-widgets.html#hiding-select-options

**Comment by lukew3** [comment]
The `batch_connect.js` file isn't visible from my debugger. Is there something I needed to do to make it show? All node types are available no matter what the selected cluster is, even when I remove all of my changes and rebuild.

**Comment by johrstrom** [comment]
Sorry! yes you need this flag in your `~/ondemand/dev/.env.local` file

```
OOD_BC_DYNAMIC_JS=1
```
