### ISSUE TITLE
Session Card - Relaunch Session Button

### ISSUE THREAD

**Issue by abujeda** [OSC/ondemand#2522]
Based on the implementation for `recently_used_apps` widget, it is very easy to do the same for already completed sessions.

Sessions store all the submitted parameters for each execution into the user_context file, this can be used to generate a new form and submitted to the back end.

I created a prototype, added a mini GIF demo.

Do you think this would be useful?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203859050578788) by [Unito](https://www.unito.io)

**Comment by abujeda** [comment]
![relaunch](https://user-images.githubusercontent.com/17336210/215527310-e3c103ec-800f-4517-b28a-6b1161444da1.gif)

**Comment by johrstrom** [comment]
> Do you think this would be useful?

Yes.

**Comment by abujeda** [comment]
OK - Will review the changes and create a PR shortly

**Comment by abujeda** [comment]
I have a PR ready: https://github.com/OSC/ondemand/pull/2529

I have changed the look and feel a bit to be more consistent with the session panel:

![relaunch](https://user-images.githubusercontent.com/17336210/215781139-e0c87719-0bb3-40b8-9524-4c401846a372.gif)

**Comment by abujeda** [comment]
This is now completed by https://github.com/OSC/ondemand/pull/2529
