### ISSUE TITLE
Ondemand via docker on aarch64 fails

### ISSUE THREAD

**Issue by michaelfuckner** [OSC/ondemand#2545]
Hi,

I just tried to install ondemand on docker on Fedora37 (aarch64), do the webfiles really have to be x86_64 or should the be noarch to be compatible to other architectures as well?

steps to reproduce:
`
git clone https://github.com/OSC/ondemand; cd onemand; docker build -t ondemand .
`

error:
`Open OnDemand Web Repo                          175  B/s | 196  B     00:01
Errors during downloading metadata for repository 'ondemand-web':
  - Status code: 404 for https://yum.osc.edu/ondemand/latest/web/el8/aarch64/repodata/repomd.xml (IP: 192.148.247.165)
Error: Failed to download metadata for repo 'ondemand-web': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203897489532738) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
OnDemand does not have aarch64 repos at this time.  Several of the dependencies used by OnDemand are compiled so they have to have to be specific to a given architecture.

**Comment by johrstrom** [comment]
The hpc-toolset container set has support for amd64, but I can't tell from a quick google search if amd64 _is_ aarch64 or not.

https://github.com/ubccr/hpc-toolset-tutorial

**Comment by michaelfuckner** [comment]
AARCH64 is for ARM CPUs (e.g. Raspberry, but some Server CPUs as well), AMD64 are commonly used x86 CPUs. Source Code should be identical, compiled code is different- so I asked why the web files are AMD64 only.
