### ISSUE TITLE
Lookups For Scripts

### ISSUE THREAD

**Issue by Oglopf** [OSC/ondemand#2551]
The new job composer needs the following ability:

- Lookup file for name of script to integer
- Encode the integer to the `url` used
- Ensure renaming the script updates this lookup correctly so bookmarks still work.

## Idea:
Create a directory in the project for `scripts` and have the lookup table reside somewhere within this to map between the file names and the `id`s while also updating this file when a `script` is renamed.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203913281883560) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I think this was completed in #2573. Script ids are numeric and the underlying files they generate are `1.yml` and so on.

**Comment by johrstrom** [comment]
This was fixed in #2573.
