### ISSUE TITLE
job composer Support multiple paths.  

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2558]
**#2578 is a prerequisite to this ticket**

This ticket is to allow the new job composer to create a project from _any_ directory, not just subdirectories of DATAROOT.

When creating a new project the user should be able to choose if they want to use the default directory (the current setup under DATAROOT) _or_ if they want to create/use an arbitrary path.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203932943290371) by [Unito](https://www.unito.io)

**Comment by abujeda** [comment]
I started looking into this issue.
I think I understand the idea, with the `.project_lookup` file as the index for all projects, and each directory storing user files and metadata within the same folder.

But I was wondering if the project and script metadata (internal files) should be kept under `DATAROOT` and only allow the user data directory to be configurable. This is where project files, libraries, scripts, and outputs will be stored.

Changing the idea to a working directory for projects.

**Comment by johrstrom** [comment]
> But I was wondering if the project and script metadata (internal files) should be kept under DATAROOT and only allow the user data directory to be configurable. This is where project files, libraries, scripts, and outputs will be stored.

I'm not sure - seems more complex to hold things in multiple places. It just makes it easier if everything is co-located. What this would need would be 2 parameters - `metadata_location` and `actual_location` (or similar variable names) and I get the sense that could be weird.

Let's move forward with colocating everything and then re-evaluate what would be required to make that change and see if it's worth while as a stand-alone change. I'll create a ticket for the same.

**Comment by abujeda** [comment]
I have completed this prototype, but I am not sure about it. I need some guidance:

![project_path](https://github.com/OSC/ondemand/assets/17336210/7bedbcb7-ae97-45fd-b0aa-f5039d64e145)

**Comment by johrstrom** [comment]
> I have completed this prototype, but I am not sure about it. I need some guidance:
PS: It is using path_selector widget.

LGTM - what do you need guidance on?

**Comment by abujeda** [comment]
I am not sure.
If you are ok with what I have so so far, I will doing another iteration and then submit a PR.

**Comment by johrstrom** [comment]
Yea - if it was about using the `path_selector` I think we should. Hopefully it _just works_ but it could not.

**Comment by abujeda** [comment]
This the next iteration, making the directory override look optional.

![project_path](https://github.com/OSC/ondemand/assets/17336210/e7542df4-b081-4de0-8ef5-17a459969ebf)

**Comment by abujeda** [comment]
Created a draft PR to start reviewing the implementation: https://github.com/OSC/ondemand/pull/2971
