### ISSUE TITLE
File-Editor: Use Monaco instead of Ace

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#256]
Version 2 of the editor could use Monaco instead of Ace

https://microsoft.github.io/monaco-editor/index.html

This has a diff mode that could be very useful, and auto-complete.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737563833418) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I can't imagine us getting around to this anytime soon, so I'm going to close at this time. We can revisit at some point in the future if cycles free up and we're interested in it again.
