### ISSUE TITLE
Script View

### ISSUE THREAD

**Issue by Oglopf** [OSC/ondemand#2572]
The Projects will have various scripts within them that a user will have the ability to select, and then have a similar experience as the `batch_connect` of having a form then presented which then will take inputs from the user to set things like `SBATCH` commands within the script along with other common parameters users may want to tweak.

This view will start at a baseline of:
- presents one or two fields with the idea we can add more later as needed
- display the current path of the selected script

More will be added as time passes and more is known about what data will be collected.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203969688391257) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
This looks to be a combination of the work done in #2573 and #2574 (with a dash of #2575?)? 

I guess the question I have is do we want to keep and/or repurpose this ticket or use the others?
