### ISSUE TITLE
FileExplorer: Viewing Large Files Causes Problems

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand#258]
Attempting to View a 20MB file causes right click to stop working in Firefox. Also EXR images do not render properly.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737564010693) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I cannot replicate anymore. Just tested on 30 and 100 MB text files.
