### ISSUE TITLE
Add Support for Non-Standard SSH Ports in Linux Host Adapter as well as entire OnDemand System.

### ISSUE THREAD

**Issue by gerald-byrket** [OSC/ondemand#2582]
Add Support for Non-Standard SSH Ports in Linux Host Adapter as well as entire OnDemand System.

From Discourse:  https://discourse.openondemand.org/t/ssh-flags-for-linuxhost-adapter/2481/6

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203979885304821) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Shouldn't this belong to `ood_core`?

**Comment by gerald-byrket** [comment]
I'm sure there is ssh that happens in places other than ood_core.  This is to cover all ssh in ondemand.

**Comment by johrstrom** [comment]
The shell app can use a wrapper, and all the dashboard does is redirect to it.

https://osc.github.io/ood-documentation/latest/customization.html#shell-app-ssh-command-wrapper
