### ISSUE TITLE
`develop` drop down menu enabled for non-developers?

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2586]
While writing the documentation, I'm wondering if the `develop` drop down menu is enabled for non-developers when defined in the `nav_bar` or `help_bar`.  I just want to ensure that if this menu item is defined in either `nav_bar` or `help_bar` it still follows some authorization rule and will only show up for folks who are actually enabled as developers. Otherwise it shouldn't show up at all.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203986443902213) by [Unito](https://www.unito.io)

**Comment by robinkar** [comment]
I think this was fixed, #2847.

**Comment by johrstrom** [comment]
Yea, thanks.
