### ISSUE TITLE
FileExplorer: Folder permission issue with ACL

### ISSUE THREAD

**Issue by gp4r** [OSC/ondemand#259]
Hello 

We are using OpenOnDemand 1.3 with File-Explorer v1.4.1. We have set ACL on the folder for group write permission, and it set rw when we create a new file or folder via Terminal.

```
drwxrwxr-x+ 2 gp4r rcai       4096 Jan 23 15:58 test1
-rw-rw-r--  1 gp4r rcai          0 Jan 23 15:58 test2
```

However, if we create them with File-Explorer, it set the permission correctly for a new file, but write permission is missing for a new folder.

![image](https://user-images.githubusercontent.com/33124907/51636830-32074180-1f28-11e9-811b-58d2a3fdd798.png)

This is output of getfacl

```
# file: .
# owner: root
# group: rcai
user::rwx
group::rwx
other::r-x
default:user::rwx
default:group::rwx
default:other::r-x
```

Could you help me how to resolve this issue?

Thank you.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737507703301) by [Unito](https://www.unito.io)

**Comment by lukew3** [comment]
Outdated file explorer

**Comment by johrstrom** [comment]
I would actually question whether we still exhibit the behaviour. New code base, but could still do the wrong thing. Indeed we've had bugs surrounding uploads and the file permissions of the resulting file.

The bugs were around the default `umask` and ensuring it's applied correctly. Again, I wonder if we inheret FACLs from it.

As to the shell app - there's nothing we can do there. I'd guess the same behaviour occurs when you get a shell session through putty or similar.

**Comment by johrstrom** [comment]
Yea i can't replicate in the new file browser. I tested on 2.1 but I'd imagine 2.0 has the same behavior.
