### ISSUE TITLE
icon based projects#index

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2596]
`projects#index` should be almost solely icon based. What I'm suggesting is that we get rid of the table and simply have rows of icons.

If you open a new tab in firefox, they're doing something we can take inspiration from. I.e., you have a row of icons, and when you hover over them and press the `...` you get more options (i.e., to `edit` or `delete`).

![image](https://user-images.githubusercontent.com/4874123/219772610-a884d6d9-1a7c-4c3e-b74c-b18857a0ffa8.png)

This is not the only example we can take from, lot's of things use icons only. It was just handy for me to come up with an example. Think smart phones OS's just to name another off the top of my head.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203996873377869) by [Unito](https://www.unito.io)

**Comment by Oglopf** [comment]
I'm skeptical of this design if this was the plan. If I'm a researcher, and I go into my projects index and just see a bunch of icons, I'm not going to know what project that maps to. The name would tell me that. I can't understand how this would be friendly from a UX perspective.

**Comment by johrstrom** [comment]
> I'm not going to know what project that maps to. The name would tell me that.

The icon would still show the project name. Of course it's not _just_ icons, we can still use text captions and so on like we do with these icons.

![image](https://user-images.githubusercontent.com/4874123/219792594-92aa70c4-a17e-4d74-a67f-d86c63d69dbf.png)

What I'm really getting at is getting rid of the table. The icons can still have text captions & hover over text.

**Comment by Oglopf** [comment]
Unless the idea is more like the Google Drive interface. But, in that case I'd rather the user not be picking the icons at all.

Instead, the icons are static and _mean_ something, such as a folder or file.

**Comment by Oglopf** [comment]
Ok, yeah this is a better example to work from. I am guessing the font awesome icons are just a placeholder then for now? Is the idea more about icons that suggest the type of work contained in the project?

**Comment by johrstrom** [comment]
>  I am guessing the font awesome icons are just a placeholder then for now?

No, I don't want to force anything on the user or limit the options.

>  Is the idea more about icons that suggest the type of work contained in the project?

No I just think it's a cleaner more modern look than the table.

**Comment by johrstrom** [comment]
To be clear, what' I'm suggesting looks something like this (only better!). Yes we'll still use/rely on FA icons, but no we're not going to make assumptions about the project type (i.e., type of science). Users will just be able to choose the icon form the list we have.


![image](https://user-images.githubusercontent.com/4874123/219802621-2fbedfb0-2f76-447a-8066-dc5db15cd5af.png)

**Comment by johrstrom** [comment]
Here's the code I made to generate that image above before I forget and/or lose it.

[index.diff.txt](https://github.com/OSC/ondemand/files/10785348/index.diff.txt)
