### ISSUE TITLE
Dashboard Views - Profile based override path

### ISSUE THREAD

**Issue by abujeda** [OSC/ondemand#2619]
The IQSS team was creating a custom view template for the footer, to add more department icons, and started wondering if it would be useful to support an override view path that depends on the current selected profile.

Currently view template overrides can be configured dropping template files under `::Configuration.config_root.join("views") `.
But these overrides will be the same for all profiles.

An quick investigation shows that supporting a profile based path for custom templates is quite simple:

```ruby
  # app/controllers/application_controller.rb

  before_action :set_profile_views

  def set_profile_views
    prepend_view_path(::Configuration.config_root.join(@user_configuration.profile.to_s).join("views").to_s) unless @user_configuration.profile.blank?
  end
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204070055899604) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I'm not sure, it's very early in the boot stack to be picking this stuff up

I would say instead just changing this to recognize a new file you could drop in `widgets`. Something like `@user_configuration.footer`. 

https://github.com/OSC/ondemand/blob/b3bcc4aeabc665c5cc672c23c6b7ebdf07bb352d/apps/dashboard/app/views/layouts/application.html.erb#L115
 
I am worried about so much user/site generated content. I don't clearly see any attack vector here, but adding directories to the load path certainly opens that up.

**Comment by abujeda** [comment]
Yes, that makes sense. We currently don't have the need to customize the footer per profile, but If we do, I know what direction to follow. Thanks

**Comment by abujeda** [comment]
Closing. If we need to customize the footer, we would add an specific footer profile property and use it to override the default as Jeff suggested.
