### ISSUE TITLE
Files app shows nothing if at least one file name has non-UTF-8 bytes

### ISSUE THREAD

**Issue by CSC-swesters** [OSC/ondemand#2624]
When opening a directory in the Files app, which contains a file whose name contains invalid UTF-8 bytes, the Files app will show an error message saying:

> invalid byte sequence in UTF-8
> Error occurred when attempting to access /pun/sys/dashboard/files/fs//${my_redacted_file_path:?}

After clicking "OK" on the error prompt, the table that should list the files and directories within the chosen directory will remain empty and say "No data available in table".

This error reproduces at least with OOD version 2.0.29. You can easily test this by creating a file in a given directory, e.g., with the following lines of Python3:
```py
>>> funky_file_name = bytes([255, 1, 2, 3]) + bytes("-ood-test-file", "utf-8")
>>> funky_file_name
b'\xff\x01\x02\x03-ood-test-file'
>>> # Do not overwrite possible existing files by using 'x' instead of 'w'
>>> with open(funky_file_name, 'x') as f:
...    f.write("Hello world\n")
...
12
```

I would expect OOD to show an error message about the existence of invalid files, but still show those that have valid UTF-8 names. Maybe give the number of problematic file names, e.g., "There are $N files in this directory whose names are invalid UTF-8. Only files and directories with valid names will be shown."?

Another alternative would be to replace the faulty bytes with question mark characters or something similar. I don't know about Ruby, but with Python3, this is what `errors="replace"` does (note that Github might render this differently than a terminal emulator would, but at least there is no error raised):
```py
>>> print("Funky name: %s" % str(funky_file_name, encoding="utf-8"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

>>> print("Funky name: %s" % str(funky_file_name, encoding="utf-8", errors="replace"))
Funky name: �-ood-test-file
```
However, I assume that all of the file operations like "View", "Edit", "Download", "Rename", etc. would suffer from the file name showing up elsewhere (e.g. in URLs and text fields). So perhaps it's easier to start by not show that file as an entry in the table, even if it does exist.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204088949394813) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Thanks for the way to reproduce. As we're working on releasing 2.1, I'll try to get this fixed for that release.

**Comment by johrstrom** [comment]
I'm having trouble replicating. My system will not even let me make the file.

I've tried
* ruby
```ruby
#!/usr/bin/env ruby

prefix = [255, 1, 2, 3].pack('C*')

fname = "#{prefix}-test.foo"
puts fname

File.write(fname, 'hello world', encoding:'utf-8')
```
* your python provided script
* `touch "$(dd if=/dev/urandom bs=4 count=1 2>/dev/null)"`
* I can create a bad file on my Windows WSL. Tried to tar that file up and untar it on the other side. `tar` fails to untar it.

**Comment by johrstrom** [comment]
Actually scratch that - I can create bad files but not on our NFS storage systems. If it's a local filesystem I can.

**Comment by CSC-swesters** [comment]
Would you mind backporting this to 2.0 as well? Or if you're busy, I can submit a PR for that. Let me know :)

**Comment by johrstrom** [comment]
I think we're going to cut a proper 2.1.0 next week, would that work for you?

If not, I may have to consider upgrading the shell app for 2.0 because it's giving some folks headaches with characters as well.

**Comment by CSC-swesters** [comment]
We aren't prepared to jump to 2.1 for some time, so we would appreciate if 2.0.x would still hang around with critical fixes like this one. What's your current plan for supporting 2.0 after the proper release of 2.1?

**Comment by johrstrom** [comment]
> What's your current plan for supporting 2.0 after the proper release of 2.1?

I'd like to drop support altogether, but that doesn't seem viable. In any case, I'm inclined to reward your effort instead of just leaving you hanging. Plus the people with the shell app issues are trying all sorts of hacks to upgrade themselves.

We can fix critical stuff like this, especially if you ping us for it - it's just difficult to test when we're on 2.1, so they'll be patches with just tests in development.  We can't go to production ourselves with 2.0 anymore.

**Comment by CSC-swesters** [comment]
Totally understandable from a maintainer's point of view :+1: This particular issue could easily be fixed with manual patching in the ruby source files for our 2.0 installations, of course. That way you don't need to rebuild the RPMs and do release testing, etc.

I asked for backporting since I assumed that 2.0 will still be supported for a short while, but if you're planning to drop support for 2.0 immediately when 2.1 releases, that changes things :slightly_smiling_face: Thanks for the info!

**Comment by johrstrom** [comment]
> I asked for backporting since I assumed that 2.0 will still be supported for a short while, but if you're planning to drop support for 2.0 immediately when 2.1 releases, that changes things 🙂 Thanks for the info!

For this is relatively easy/simple, but again, there are folks doing crazy things to try to upgrade the shell app in 2.0 so it's kinda worth it to help them.

In any case, it's not like it's years later we're still updating, we haven't even really release 2.1 yet, so I'm happy to support 2.0 for at least the next few months.

**Comment by johrstrom** [comment]
I've created #2633 as a follow up to show them in the UI.  The CI for 2.0 is acting up, so that could delay it's release (especially as we deal with some 2.1 bugs we have in OSC production at the moment).
