### ISSUE TITLE
FileExplorer: Submit jobs from the app

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#263]
The feature would allow users to submit (`qsub`, `sbatch`, `bsub`, etc.) a file from the File Explorer GUI.

Listed in our community feature requests, but I'm not sure of the origin. Needs design.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737513243297) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Duplicate of #2036 and at least 1 other that I can't find at the moment.
