### ISSUE TITLE
FileExplorer: Incorrect link in tree root

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#264]
"Open in a new tab" does not work for the file explorer tree menu root link. 

The tree link is not building the link with the api prefix, so opening it in a new window provides an error.

For example, when my home directory is `/users/appl/bmcmichael`:

The link is: `https://ondemand.osc.edu/users/appl/bmcmichael`
The link should be: `https://ondemand-dev.osc.edu/pun/dev/ood-fileexplorer/fs/users/appl/bmcmichael/`

![filex404](https://user-images.githubusercontent.com/2374718/33499075-7ab22790-d6a1-11e7-968f-10135da44eb5.png)

**Comment by johrstrom** [comment]
This doesn't affect 2.0 and we'll likely not backport a fix for it.
