### ISSUE TITLE
FileExplorer: Browsers (occasionally) block html/pdf launched from the view button.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#266]
Occasionally a browser will block an attempt to open a new window for html/pdf files when the view button is clicked.

This is because the action is not generated via a user-directed action (i.e. 'onclick').

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737620986744) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
PDFs correctly show (at least in firefox) and HTML is a duplicate of #1619.
