### ISSUE TITLE
FileExplorer: Directory/File names wrong with HTML ampersand character codes

### ISSUE THREAD

**Issue by nickjer** [OSC/ondemand#268]
It seems if a file or directory has HTML ampersand character codes in the name, then it replaces the ampersand and following letters with the HTML ampersand character.

For instance the file named `a&nbspb.txt` shows up incorrectly as `a b.txt`:

![screenshot from 2017-07-17 13-32-12](https://user-images.githubusercontent.com/4260509/28281221-613c6528-6af4-11e7-9a83-b604795e2a97.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737565001058) by [Unito](https://www.unito.io)

**Comment by lukew3** [comment]
Issue not present in new file browser
