### ISSUE TITLE
Dashboard does not support feed: or http(s):// URIs

### ISSUE THREAD

**Issue by willfurnell** [OSC/ondemand#2680]
I'm trying to use the MOTD functionality to retrieve an RSS feed from a website - however, this does not show up and I get the following error in the PUN error logs, even when trying different feeds and URIs:

```
App 2312542 output: [2023-03-20 16:01:40 +0000 ]  WARN "MOTD File is missing; it was expected at https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?RSS&L=SCARF-USERS&v=2.0&LIMIT=100"
App 2315186 output: [2023-03-20 16:11:53 +0000 ]  WARN "MOTD File is missing; it was expected at feed:https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?RSS&L=SCARF-USERS&v=2.0&LIMIT=100"
App 2316382 output: [2023-03-20 16:17:48 +0000 ]  WARN "MOTD File is missing; it was expected at feed:https://willfurnell.com/index.xml"
App 2316591 output: [2023-03-20 16:21:32 +0000 ]  WARN "MOTD File is missing; it was expected at https://willfurnell.com/index.xml"
```
I believe this to be a bug because the documentation, and the code (https://github.com/OSC/ondemand/blob/c74cc4a3ecc364c3431374c9e295f3b81c08810e/apps/dashboard/app/models/motd_file.rb#L63-L70), suggests that loading feeds from a web address may work.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204218613615528) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Thanks for the ticket, yea it does seem like we should be able to pull that URI. We'll look into it.
