### ISSUE TITLE
save settings when submitting a job

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2689]
Once #2576 is complete we can save the settings of the job that you submit.

Here's basically how it should work
* the user chooses the appropriate fields in `script#show`
* the user submits the job
* At this point - **this is the feature** - we save those values that the user submitted the job with in some sort of cache file.
* Now when the user navigates back to `script#show` we can read that cache file and use these values in the cache file as the initial values in the form.

This is similar to how batch connect apps work. They save your settings such that when you submit the app/job with a given value, the next time you load the form, the form's initial values' are from the cached file (i.e., from the last job you submitted).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204230122367697) by [Unito](https://www.unito.io)

**Comment by Oglopf** [comment]
Should each script have this behavior? Looking at what is here, if i go in and show one script then select options, then go into another script in the project, should it load those cached values of the other script from the same project?

**Comment by Oglopf** [comment]
Also, if the submission works, do we want to clear the cache file or save the fields selected regardless of what happens.

**Comment by johrstrom** [comment]
> Should each script have this behavior? Looking at what is here, if i go in and show one script then select options, then go into another script in the project, should it load those cached values of the other script from the same project?

Each script should have this behavior. That is they each have their own cache file.

> Also, if the submission works, do we want to clear the cache file or save the fields selected regardless of what happens.

The latter. Seems like we should cache before we submit. I don't think we ever want to clear it. You can think of a use case where the user is editing the `script.sh` (the actual shell script) but wants to keep submitting the updated file with the same arguments.
