### ISSUE TITLE
scripts#new errors if there are no clusters

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2690]
`scripts#new` crashes if there are no clusters defined throwing this stack trace.

Instead, let's catch this error and redirect back to `projects#show` informing the user that there are no clusters defined and without clusters, the entire project app is basically useless because you can't submit anything you create.

```
NoMethodError: undefined method `id' for nil:NilClass
    app/models/script.rb:151:in `fixed_cluster'
    app/models/script.rb:137:in `add_cluster_to_form'
    app/models/script.rb:68:in `initialize'
    app/controllers/scripts_controller.rb:7:in `new'
    app/controllers/scripts_controller.rb:7:in `new'
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204239512919479) by [Unito](https://www.unito.io)

**Comment by abujeda** [comment]
I had a look and with all the new changes this is no longer happening.
When no clusters are defined, an empty dropdown will be rendered.

**Comment by johrstrom** [comment]
Thanks. Even if there's no error directly, then we should alert the user to the fact that this will not work at all. They would likely have to try to submit a job and get a failure, and we can preempt their attempt.

So, we should still keep this ticket to have some UI indication that this won't work at all until there's a cluster defined.

Maybe disable buttons and add an alert flash?

**Comment by abujeda** [comment]
What about something like this:
![scripts_validation](https://github.com/OSC/ondemand/assets/17336210/3eea9318-2f36-4ef0-9821-1cf47cb04335)

**Comment by johrstrom** [comment]
> Maybe disable buttons and add an alert flash?

I'd meant more like in the `project#show` page. There's no point in even allowing them to step into `scripts#edit` (or any script page) if there are no clusters.

**Comment by abujeda** [comment]
More like this then:
![scripts_validation](https://github.com/OSC/ondemand/assets/17336210/0a35906b-1db4-4a97-8724-40b6ddc21943)

**Comment by johrstrom** [comment]
> More like this then:

Yes! But with a better message. Should be clear and concise: `There are no clusters to submit to. Contact your administrator to configure an HPC cluster that the system can submit to.` or similar (likely some localization so folks can change it).

**Comment by abujeda** [comment]
Should we do the same validation for the `auto_scripts` field?
So that users are required to add/upload a script file to the project before they can add a new script.

**Comment by johrstrom** [comment]
> Should we do the same validation for the auto_scripts field?
So that users are required to add/upload a script file to the project before they can add a new script.

Yea let me make a new ticket for that. I'm thinking some button that can initialize a `hello_world.sh` file.

**Comment by abujeda** [comment]
I have created a PR with a fix. I have deferred `auto_scripts` Smart Attribute validation to the new issue: #3255
