### ISSUE TITLE
FileExplorer: Inconsistent view handling of very long paths

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#270]
The path is around 107 characters long:

```
https://ondemand-test.hpc.osc.edu/pun/sys/files/fs/users/PZS0562/efranz/apache-tomcat-6.0.33/webapps/edu.osc.epi/WEB-INF/classes/edu/osc/epi/apps/abaqus/
```

In Safari, the tree displays, the path gets cut off the screen, but right side of panel (including Delete button) slide in:

<img width="1188" alt="screen shot 2016-11-01 at 5 06 34 pm" src="https://cloud.githubusercontent.com/assets/512333/19907558/ca827528-a055-11e6-9b84-0fe75fc007a5.png">
<img width="985" alt="screen shot 2016-11-01 at 5 06 38 pm" src="https://cloud.githubusercontent.com/assets/512333/19907557/ca813172-a055-11e6-9d58-4bdf58a67a84.png">

In Chrome, the tree collapses, the path stays unclipped, and the right side gets hidden:

<img width="1245" alt="screen shot 2016-11-01 at 5 06 50 pm" src="https://cloud.githubusercontent.com/assets/512333/19907564/cfba676c-a055-11e6-9b0f-786c3b661af6.png">
<img width="811" alt="screen shot 2016-11-01 at 5 06 55 pm" src="https://cloud.githubusercontent.com/assets/512333/19907565/cfbd0030-a055-11e6-9c26-7f384ae32aa9.png">

Seems like we would want to word-wrap the path.

However, this looks intentional. It might be a carry-over from previous functionality. The class ".reduce-text" has set `whitespace: nowrap`. Removing this "fixes it":

<img width="1245" alt="screen shot 2016-11-01 at 5 11 52 pm" src="https://cloud.githubusercontent.com/assets/512333/19907702/538b87a6-a056-11e6-91b6-00dc155ccbd4.png">

<img width="1011" alt="screen shot 2016-11-01 at 5 11 54 pm" src="https://cloud.githubusercontent.com/assets/512333/19907701/538aff5c-a056-11e6-924e-487e7c80ebea.png">

**Comment by johrstrom** [comment]
This no longer applies in 2.0 and we're not likely going to back port to 1.8.
