### ISSUE TITLE
pinned apps using POST instead of GET

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2705]
The `pinned_apps` functionality on the dashboard is getting intercepted by rails ujs and submitting a POST request instead of just a GET.

It's an `<a>` HTML tag with a proper `href` so it has to be intercepted by rails otherwise it would just be a regular GET request.

It's a bit superficial. The user wouldn't notice anything, other than this: After clicking the link, it sends you to a batch connect form. That's OK, that's expected, that's the correct URL. However, since it was a POST request, refreshing the page (ctrl+shift+R) asks if you're sure and that you'll have to resend the data. This isn't the case with GET requests. GET requests just refresh without an alert.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204285744080443) by [Unito](https://www.unito.io)

**Comment by abujeda** [comment]
I think I introduced this behaviour when implementing the improvements to the pinned apps.

I have a fix in https://github.com/OSC/ondemand/pull/2708
