### ISSUE TITLE
FileExplorer: Sort files by modified date or size.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#271]
User enhancement request:

> Overall, I like a lot about the new OnDemand, especially the increased speed. However, in the file browser, I can't sort files by things like modified date or size. The view mode in the file browser also does not cycle through files in the proper order. 

Look into sorting files by date or size.

We already manipulate the file array for hiding dotfiles, so sorting it wouldn't be a problem, I'd just need to think up a good way to figure out which way to do the sort before rendering them.

**Comment by ericfranz** [comment]
@johrstrom this can be closed now

**Comment by johrstrom** [comment]
This was a part of the 2.0.x release.
