### ISSUE TITLE
Reset Button does not reset Icon when editing Project.

### ISSUE THREAD

**Issue by gerald-byrket** [OSC/ondemand#2716]
Reset Button does not reset Icon when editing Project.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204309450672170) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
When #2744 is merged note that that functionality with the blank template also has this bug.  That is, when the blank template is selected - the icon field is correctly updated but the actual icon image isn't.

**Comment by abujeda** [comment]
Created a fix for the refresh the icons when the form is reset: https://github.com/OSC/ondemand/pull/2983
