### ISSUE TITLE
show jobs#info fetch errors in html

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2718]
#2717 created a TODO. This ticket is to do that.

When the fetch to `jobs#info` fails, we should catch that error and create an element in the HTML showing the error.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204309408564080) by [Unito](https://www.unito.io)

**Comment by abujeda** [comment]
Are you looking for something simple like this?

<img width="1200" alt="Screenshot 2023-12-12 at 11 20 38" src="https://github.com/OSC/ondemand/assets/17336210/a87ebfe3-6700-4fea-8dff-707e3a2d9bbf">

**Comment by johrstrom** [comment]
That could work. Maybe put the job in `undetermined` state with a `<span class="text-muted">Unable to find the job details</span>`.

I don't disagree with a hover over, but I want it the messaging 100% clear (or as close as possible).

**Comment by abujeda** [comment]
Something like this:
<img width="600" alt="Screenshot 2023-12-12 at 16 06 21" src="https://github.com/OSC/ondemand/assets/17336210/a2294476-474e-4306-a3d1-47cb7870a2ae">
<img width="600" alt="Screenshot 2023-12-12 at 16 06 54" src="https://github.com/OSC/ondemand/assets/17336210/c9fa36b9-5f7f-45f3-89bb-d96af24929e9">

**Comment by johrstrom** [comment]
Yea I think so. This UI is subject to heavy changes, but yea, I think the additional text is warranted to really re-enforce that something went wrong, even at a glance.

**Comment by abujeda** [comment]
PR Created: https://github.com/OSC/ondemand/pull/3249
