### ISSUE TITLE
FileExplorer: Limit size of directory downloads.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#272]
Add a block which returns an error and message if user attempts to download a folder that is too large. 

Check can be added to the express component at:

https://github.com/OSC/ood-fileexplorer/blob/master/app.js#L56-L95

What's an appropriate limit? 2GB? 10GB? 20GB?

This uses a custom route with the node `archiver` module to prepare the zip files, so some benchmarking will need to be done to figure out where the buffering is happening, and if the app buffers all the files in a folder at once, or each file individually, in which case we could impose a file size limit rather than a folder size limit.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737564600394) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
@johrstrom this can be closed now

**Comment by johrstrom** [comment]
Yea it's a duplicate of #275.
