### ISSUE TITLE
Building ood image - redirects to port 80

### ISSUE THREAD

**Issue by MoamenMetwali** [OSC/ondemand#2726]
I am trying to run ood by running a container
first, I mapped it to 8080:80 but trying to curl localhost:8080 it always redirects to port 80 which is not working unless I am trying to access it inside the container itself.

Tried to change the port to 8080 inside 'ood_portal_example.yml', then built it again with 8080:8080. 
This time I wasn't redirected but I got the following "This website you are visiting is either experiencing problems or could be going through maintenance."

What is done wrong by me or what should I set to make it work properly?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204327267142189) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
If this is just to play around with the container `rake dev:start` should work out of the box for you (it uses 8080).

If it's deployed somewhere for others to access, you shouldn't need to rebuild, just mount files into `/etc/ood/config`.

You should configure these 2 ports.
```yaml
listen_addr_port: 8080
port: 8080
```

If you still get errors, look into `/var/log/httpd` for error messages.
