### ISSUE TITLE
FileExplorer: MS Edge - Terminal button does not work after initial panel load.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#273]
This bug only appears to exist in MSEdge.
- Load page
- Click 'Open in Terminal' Button
  - No Response.
- Click a file or folder in the panel.
- Click 'Open in Terminal' Button
  - Works to spec.

Need to find out what I'm using to detect the current folder and find an option that works with Edge.

**Comment by johrstrom** [comment]
I can only guess that this no longer applies in 2.0 because the app is entirely different now.  In any case, we're not going to backport a fix to 1.8.
