### ISSUE TITLE
FileExplorer: Large File/Directory Download Max Size Limits

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#275]
Similar to https://github.com/AweSim-OSC/osc-fileexplorer/issues/2 we should place a limit on the directory or file sizes we let the user download. Past a certain point, they should be using sftp.osc.edu.

Downloading via file explorer was done via this pull request: https://github.com/AweSim-OSC/osc-fileexplorer/pull/102

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737565646252) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
This was fixed with the `file_download_dir_max` config.
