### ISSUE TITLE
File upload (Uppy) localization

### ISSUE THREAD

**Issue by robinkar** [OSC/ondemand#2764]
We at CSC would like to customize the text shown during file uploads, particularly the text telling the user that the file exceeds the maximum size (`%{file} exceeds the maximum allowed size of %{size}`, [en_US.js](https://github.com/transloadit/uppy/blob/96ae2bf04981f73b63ebc034156bcf418ded11a5/packages/@uppy/locales/src/en_US.js)), to clarify that this a limit placed by OOD and not a limit on files on the system. This text seems to be the default text in Uppy and can be changed by passing extra parameters when [initializing Uppy](https://github.com/OSC/ondemand/blob/bfddc1f2eaff28ad073f44cac76e9d213fd6ab9a/apps/dashboard/app/javascript/packs/files/uppy_ops.js#L68):

```
uppy = new Uppy({
  locale: {
    strings: {
      exceedsSize: '%{file} exceeds...'
    }
  }
})
```

One idea we had for how this could be implemented would be to expose this locale object passed to Uppy through the I18n localization (`config/locales/*.yml`), e.g:

```
# config/locales/en.yml
en:
  dashboard:
    uppy:
      strings:
        exceedsSize: '%{file} exceeds...'
```

It could probably be passed from the backend to the frontend similarly to how maximum file upload size already works, i.e. in the [meta tag in the HTML head](https://github.com/OSC/ondemand/blob/bfddc1f2eaff28ad073f44cac76e9d213fd6ab9a/apps/dashboard/app/views/layouts/application.html.erb#L22).

Let us know if you want us to submit a PR for this as described above.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204422499390987) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
>It could probably be passed from the backend to the frontend similarly to how maximum file upload size already works, i.e. in the [meta tag in the HTML head](https://github.com/OSC/ondemand/blob/bfddc1f2eaff28ad073f44cac76e9d213fd6ab9a/apps/dashboard/app/views/layouts/application.html.erb#L22).

> Let us know if you want us to submit a PR for this as described above.

I think that'd be just fine.
