### ISSUE TITLE
FileExplorer: You can create or rename files to files with names that are only spaces or have characters like $ and !!

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#277]
We might want to prevent the user from shooting themselves in the foot, but we should also handle legal file names even if they have odd characters in them

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737565761565) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
My thinking is if Linux allows it we should too. Plus deleting and/or interacting with it through the UI makes it easier to rename and/or delete without having to worry about escaping everything.
