### ISSUE TITLE
Forget to migrate ALLOWED_HOST to ODD_ALLOWED_HOSTS

### ISSUE THREAD

**Issue by link89** [OSC/ondemand#2779]
OOD 3.0 have changed ALLOWED_HOST to ODD_ALLOWED_HOSTS in the Apache config, but some app still use the ALLOWED_HOST. Which will lead to 403 error as Ruby app cannot find the value in  ALLOWED_HOST.

Ref: https://discourse.openondemand.org/t/config-open-ondemand-with-nis-auth/2656/5

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204463829665387) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
They should both be getting populated. Here I've highlighted them both (in yellow) out of my processes' environment file.

![image](https://user-images.githubusercontent.com/4874123/234075416-b71e3aaa-a6ae-4cad-a860-1059a9bf9179.png)

**Comment by johrstrom** [comment]
Hi, I'm going to close this given your response on discourse. Thanks for the ticket! Feel free to open more if you run into other issues.
