### ISSUE TITLE
FileExplorer: Add project space directories to tree

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#278]
So that you can change the "root" of the tree to be project space OR the home directory

We might want to think through this a little more because you might want to select some files and drag it to a project space directory in the tree. So you might want to be able to expand the root of the project space while looking in your home directory. But it could work like an accordion control, in that only one tree is open at a time.

![screen shot 2016-06-03 at 11 31 41 am](https://cloud.githubusercontent.com/assets/512333/15784055/ce5085bc-297e-11e6-8315-6156b79efb91.png)
![screen shot 2016-06-03 at 11 31 43 am](https://cloud.githubusercontent.com/assets/512333/15784054/ce4edbc2-297e-11e6-8e32-9588c4cb0a83.png)

**Comment by johrstrom** [comment]
Seems like this was a feature in 1.8-? In any case, Tree View isn't a part of 2.0, though when it is, it should inheret the FavoriteCandidates from the navbar menu (which I imagine 1.8- did).
