### ISSUE TITLE
FileExplorer: Tree view is reset on browser window reload

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#282]
If we could track a "session" i.e. the state of the tree view associated with the "browser name" - so we could cache different tree view states on multiple browser windows, the user could reload the browser safely without losing the tree state. This is related to https://github.com/AweSim-OSC/osc-fileexplorer/issues/84 - where the file size gets out of date when the file is modified (if you modify a file using file editor or vim etc)

**Comment by johrstrom** [comment]
We don't have Tree view in 2.0.  Of course, when we do this may come up again, but we'll cross that bridge when we get there.
