### ISSUE TITLE
support script#delete functionality.

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2820]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204613118820269) by [Unito](https://www.unito.io)

**Comment by abujeda** [comment]
Taking a look. I cannot assign myself to this issue.

**Comment by abujeda** [comment]
Added the delete button in-between edit and launch: 
<img width="1450" alt="Screenshot 2023-08-10 at 14 21 35" src="https://github.com/OSC/ondemand/assets/17336210/f47f6fca-4a29-48ba-ada0-52eb9a561dc9">

**Comment by abujeda** [comment]
While doing the implementation, and deleting the yml, log, cache, and output files, I created a folder to store all outputs for the script. The folder is called: `"#{id}_output"` and is created under the project root directory.

This is to make it easier to cleanup when deleting.

Should this be extended to create a folder per script?
having a folder per script should simplify file management.

**Comment by johrstrom** [comment]
That sounds fine. Although, `slurm-234.out` won't be included in the hidden files - longer term that'll be configurable, but for now they'll stay in the project root. The output files should be visible/findable for users, all the rest is internal stuff that should be kept hidden.

**Comment by abujeda** [comment]
Created a draft PR for the delete implementation: https://github.com/OSC/ondemand/pull/2959

As for moving the script files into a script folder, will do that in a different PR
