### ISSUE TITLE
script#new should create default values for auto* smart attributes

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2824]
When I create a new script - I get something similar to what's below. This is fine, but you'll see that there are no `value` attributes in the attribute section for `auto_scripts` and `auto_batch_clusters`.

Because there is no default value - the button for launching does not work directly.  Instead one has to edit and save to get a default value populated in the yaml.

to replicate simply:
* navigate to a project
* press `New Script`
* name the script
* press `Save`

**Expected behavior**

When you save the script object, the resulting yaml file should have `attributes.auto_scripts.value` and `attributes.auto_batch_clusters.value`

**Actual behavior**
`attributes.auto_scripts.value`. and `attributes.auto_batch_clusters.value` are not present in the resulting yaml.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204623704708355) by [Unito](https://www.unito.io)

**Comment by Oglopf** [comment]
I have some questions after looking at this more. 

Should `SmartAttributes::Attribute#value`  handle this or `Script#save`? The `Script` seems to really only know about its `project_dir`, `id`, and `title` with all other `attributes` coming from `SmartAttributes` . 

The `Script#to_yaml` could also handle default values I guess, but I'm having trouble understanding how to use the `smart_attributes` tbh and that seems like the wrong method to make this change anyway. 

When I look at `smart_attributes` in the `save` I only see the following:
```
smart_attributes: [#<SmartAttributes::Attributes::AutoBatchClusters:0x00007f6c75445fc8 @id="auto_batch_clusters", @opts={:options=>["ascend", "owens", "pitzer"]}>, #<SmartAttributes::Attributes::AutoScripts:0x00007f6c75445c08 @id="auto_scripts", @opts={:options=>[], :directory=>"/users/PZS0714/travert/ondemand/misc/ondemand/apps/dashboard/data/projects/1"}>]
```
And if the answer is the values aren't set because we didn't set them, I guess I'd point to the question of below, when there is no script. As for the `auto_batch_clusters`, I'm again not sure where those values come from really.

Lastly, there's no way to make actual scripts, so I'm not sure if the idea here is to have a default `hello_world.sh` made that is populated for the `attributes.auto_scripts.value` if the user hasn't made an actual script yet, or to set the field as empty if there are truly no scripts created still.

**Comment by johrstrom** [comment]
> When I look at smart_attributes in the save I only see the following:

> smart_attributes: [#<SmartAttributes::Attributes::AutoBatchClusters:0x00007f6c75445fc8 @id="auto_batch_clusters", @opts={:options=>["ascend", "owens", "pitzer"]}>, #<SmartAttributes::Attributes::AutoScripts:0x00007f6c75445c08 @id="auto_scripts", @opts={:options=>[], :directory=>"/users/PZS0714/travert/ondemand/misc/ondemand/apps/dashboard/data/projects/1"}>]

In your example here - `auto_batch_clusters` could use opts.first as their default value.  `auto_scripts` could too, only it'd be null, there's just no way around that. You're right in thinking we can't invent data (scripts that don't actually exist), but we can best effort try.

If they have at least 1 script then we'll use it, if not, then at least we tried (we likely need good error messaging around error that specifically). That's the best we can do - try to do the reasonable thing and if it fails, give the user an error message that they'll understand.

So it seems we need a statement like:
```ruby
smart_attr.value = smart_attr.opts.first if smart_attr.value.nil?
```

Where such a statement would exist is a great question. I think `Script#save` or `Script#to_yaml` are our best options, so that when they're read back they're as good as they can be.

**Comment by Oglopf** [comment]
I can get this to work using the following:
```ruby
def save
...
  sm_opts = smart_attributes.map(&:opts)
  auto_batch_clusters_attrs = sm_opts.first[:options].first
  auto_scripts_attrs = sm_opts.last[:options].first.first
```
But, I this code is not very maintainable is my concern. I can move forward with this for now though, but my guess is I'm not using this `SmartAttributes` object correctly.

**Comment by johrstrom** [comment]
A thousand apologies. I wrote that from memory and confused `opts` (the inner object that is everything) as if it were `select_choices` (i.e, `[:options]` or `@opts[:options]`). 

So that original statement should be something more like:
```ruby
smart_attr.value = smart_attr.select_choices.first if smart_attr.value.nil? 
```

Using `is_a?` seems very fragile.

**Comment by johrstrom** [comment]
OR we could just embed default values like `bc_num_hours` does.  That may actually just be the safest/easiest route. Especially since that pattern is already in use.

https://github.com/OSC/ondemand/blob/133b879d381a037f01bcc7a4373c71608c980dc1/apps/dashboard/app/lib/smart_attributes/attributes/bc_num_hours.rb#L22-L24

**Comment by Oglopf** [comment]
I'm going to go with the last suggestion here. I mentioned that originally as the place this seemed best, and I think that makes sense given what each object knows about.

Looking more at this `SmartAttributes` object though, this may take me a moment. It seems like I'd want to initialize defaults and add something like:
```ruby
def value
   return opts[:default].to_s if opts[:value].nil? && opts[:default].present?
   ....
end
```
I can't just hardcode a value like `bc_num_hours` unfortunately. 

Looking at this, the `SmartAttributes::Attributes::AutoScripts` object is not something I can understand. I'm thinking i can add `value` method there to override this hierarchy that is setup, but I don't know how to get the actual default value. From the `opts`?

**Comment by Oglopf** [comment]
Yeesh, yeah I may have to keep this in the `Script`, I'm not sure how this `SmartAttribute` code works and I don't want to eat up more time than already has gone by.

I'll play with this a bit but I see no way to retrieve defaults from `SmartAttributes` aside from hardcoded values.
