### ISSUE TITLE
SELinux prevents ruby from name_connect access on the tcp_socket port 25 for use in support ticket

### ISSUE THREAD

**Issue by genericdata** [OSC/ondemand#2825]
We installed ondemand and ondemand-selinux v3.0.1-1.el8 on RHEL 8.7. I want to enable the [Support Ticket](https://osc.github.io/ood-documentation/latest/customizations.html#support-tickets).  After following the instructions and attempting to submit the form I get the following error in OOD portal.

**There was an error processing your request: Permission denied - connect(2) for xx.xx.xx.xx:25"**

In `/var/log/messages` we get the following,
```
/SetroubleshootPrivileged.py[116825]: failed to retrieve rpm info for /var/lib/selinux/targeted/active/modules/400/ondemand-selinux
ood setroubleshoot[116812]: SELinux is preventing /usr/bin/ruby from name_connect access on the tcp_socket port 25. For complete SELinux messages run: sealert -l ...
```

I can manually allow ruby and then the form submits and emails as expected.

My question is, shouldn't the ondemand-selinux install already handle this?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204632685873780) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
> My question is, shouldn't the ondemand-selinux install already handle this?

Sorry, this was likely missed.  We'll get this fixed and back port to 3.0.x.
