### ISSUE TITLE
Change bc_mem max value based on user

### ISSUE THREAD

**Issue by btsherid** [OSC/ondemand#2831]
Hi,

I have written some javascript to set the max memory differently based on the value of an select widget attribute in form.yml.erb. So for example, if I select "allnodes" from the drop down of the select widget, the javascript will make the max memory 16. If I select "bioinformatics", the javascript will set the max memory to 32. This works good.

Is there a way I can do the same thing based on the user that is logged in? For example, what I would like now is that the max value of bc_mem is 16 for all users but have that value change to 128 only for user btsherid.

If this is possible, I'm also wondering if I can change the help attribute of bc_mem dynamically based on the value that was set. So if the value is 16, the help menu would print "Please input a value between 1 and 16(GB)" and for a different user whose value is 128, the help menu would print "Please input a value between 1 and 128(GB)"

See relevant code below:

form.yml.erb

<pre>
  custom_queue:
    label: Partition
    help: Please select a partition from the drop-down
    widget: select
    options:
      - [ "ondemand", "ondemand" ]
      - [ "allnodes", "allnodes" ]
      - [
          "bioinformatics", "bioinformatics",
          data-min-memory: 1,
          data-max-memory: 32,
        ]
      - [ "gpu", "gpu" ]
      - [ "abacus", "abacus" ]
</pre>

form.js:

<pre>
function set_custom_queue_change_handler() {
  let custom_queue_input = $('#batch_connect_session_context_custom_queue');
  custom_queue_input.change((event) => custom_queue_change_handler(event));
}

function custom_queue_change_handler(event) {
        const custom_queue_input = $('#batch_connect_session_context_custom_queue');
        const data = custom_queue_input.find(':selected').data();
        const max = data["maxMemory"];
        const min = data["minMemory"];
        console.log(min + " " + max);

        const bc_mem_input = $('#batch_connect_session_context_bc_mem');
        bc_mem_input.attr('max', max);
        bc_mem_input.attr('min', min);

}

set_custom_queue_change_handler();

</pre>

Thank You,
Brendan

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204640140125273) by [Unito](https://www.unito.io)

**Comment by btsherid** [comment]
I was able to solve this problem a different way.

They main thing I wanted to accomplish was allowing a small group of users to have higher upper resource limits for apps, perferably without letting other users know (i.e trying to limit the "They can have it why can't I" question through obscurity).

I was able to accomplish this by creating a duplicate app (with different resource limits) under /var/ood/apps/sys with a _hr suffix and then changing the file permissions on the _hr subdirectory to 750 owned by root:LDAP group. In this way, only users in that LDAP group will see those apps when they log into OnDemand.

-Brendan

**Comment by johrstrom** [comment]
Sorry I didn't get around to this. The help message was really what I can't do off hand. I believe you may be able to bundle together data-min & data-max directives on the queue (as you have) and also applied to your account select field.

**Comment by btsherid** [comment]
No worries. Without the help message piece, this is probably a better solution for us. Also, it's probably a little cleaner in terms of having other admins understand how things are set up even though some users now have "duplicate" apps.

-Brendan
