### ISSUE TITLE
FileExplorer: Incorrect link associated with "Home Directory" on tree view.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#284]
Incorrect link appears when hovering over the tree view. It works functionally when you click it, but if a user types the address that appears they won't get to the correct place.

Maybe just suppress 'href' here? It seems to be operating via javascript anyways.

![treelink](https://cloud.githubusercontent.com/assets/2374718/15715231/abe24ae0-27eb-11e6-9916-56d26c3cdd2c.png)

**Comment by johrstrom** [comment]
This no longer applies to the 2.0 file browser and we're not likely to backport a fix.
