### ISSUE TITLE
FileExplorer: Design File Explorer 2.0 (which uses our own codebase)

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#285]
Opening an issue to collect some ideas for a 2.0 version that we will open source with Open OnDemand.

We should identify features from these apps that would be helpful to include:
- file explorers like OS X's Finder and the uber Path Finder app http://www.cocoatech.com/pathfinder/
- sftp clients like Cyberduck, FileZilla, and WinSCP

For example, some features we should consider:
- drag and drop in the window and between window and tree
- favorites (like in Apple's finder)
- "actions" like "new folder" and "new file" or other things that work on the "current directory" (not the selection) could go in an actions button dropdown similar to apple's finder:
  
  ![screen shot 2016-05-31 at 10 19 14 am](https://cloud.githubusercontent.com/assets/512333/15677655/366a5ce4-2719-11e6-9ee1-91e9d99130c8.png)
- embeddable "file picker" mode that we can use with other apps

**Comment by johrstrom** [comment]
How nice! We completed this in 2.0.
