### ISSUE TITLE
support ticket crashes if misconfigured

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2867]
From discourse - below - the `support_ticket` feature seems to crash if it's misconfigured.

https://discourse.openondemand.org/t/support-ticket-is-not-working/2733

**Comment by johrstrom** [comment]
> The exception was thrown on purpose to force admins to configure the support ticket feature.

What you have shown here is the correct behavior. I haven't tested this myself, but the discourse topic seemed to indicate there was  a crash. Though re-reading it now, they could have pulled that from the logs and not the UI.

If we catch the error and display it, then that's all we can do really. Maybe it's just an issue of documentation/better error messaging?

**Comment by johrstrom** [comment]
Yea I think the best to do is just enhance the error message and redirect. 

> I think the documentation is clear on what fields are required:
https://osc.github.io/ood-documentation/latest/customizations.html#configuration

Looking at the discourse topic - the configuration they used was from the documentation 😆 , so we've got to update that a bit to show a more full example of overriding the template.

**Comment by abujeda** [comment]
Created a PR for the dashboard: https://github.com/OSC/ondemand/pull/3004

And a PR for the documentation: https://github.com/OSC/ood-documentation/pull/855
