### ISSUE TITLE
FileExplorer: Data integrity

### ISSUE THREAD

**Issue by nickjer** [OSC/ondemand#287]
Doug brought up a good point about verifying the integrity of the data that was transferred whether through an upload or download. I know in some zip formats there is a checksum built-in, but having something similar built into the file explorer may be worth exploring in the future.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737515313419) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
closed as unfeasible
