### ISSUE TITLE
FileExplorer: Consider finer grained cache busting in future

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#288]
In this commit we essentially bust the cache of all files: 8a1d5b9cf79546a82f3fa6d3ee874adcbd747803

We will test and see if this has any negative implications in the perception of startup time when using the file explorer. If it does, we might want to revisit this and use a more appropriate client side cache management solution, such as including a fixed constant (timestamp) in the asset URLs which could be set when the app is started.

https://github.com/AweSim-OSC/osc-fileexplorer/issues/24 for a complete list of files to cache bust

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737516995216) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
This no longer applies, though caching is always on my mind.
