### ISSUE TITLE
NodeJS 14 is EOL

### ISSUE THREAD

**Issue by CSC-swesters** [OSC/ondemand#2884]
Judging by [this page](https://github.com/nodejs/release#end-of-life-releases), NodeJS 14.x was end-of-lifed on 2023-04-30. The RHEL8 family is still using it, however. See e.g. [this line in the ood-packaging repository](https://github.com/OSC/ondemand-packaging/blob/2ad5f40616b8c172e889993c8503ecb74dac7fa3/packages/ondemand-runtime/rpm/ondemand-runtime.spec#L112).

RHEL8 seems to have NodeJS 16 available as a module too (based on `dnf module list nodejs` output), so that could be an easy fix, since RHEL9 already requires `%{nodejs} >= 1:16.0, %{nodejs} < 1:18.0`. However, that will only be a short-term fix, since NodeJS 16 is going EOL in October of 2023. The more sensible thing would be to move towards NodeJS 18 or 20, which still have support until at least 2025.

Can you share your plans on how to move forward with the NodeJS roadmap? Thanks in advance!

**Comment by CSC-swesters** [comment]
It would seem to me that Red Hat won't do any support of their own. I found this page indicating that users are responsible for choosing a NodeJS version that is supported: https://access.redhat.com/articles/3376841

> "[Node.js 14 LTS](https://access.redhat.com/articles/3376841#NODE_14) End of Support as of April 30, 2023"

And in that section:

> "In order to be running in a supported configuration, Red Hat build of Node.js must be running on a supported Node.js LTS release and supported environment."

Let me know if I've interpreted this incorrectly.

**Comment by CSC-swesters** [comment]
New finding, let me correct myself.

That page says that "RHEL8.7 or later" is a supported configuration for NodeJS 18 LTS. I verified this with a Rockylinux 8.7 container as well:

```
# dnf module list nodejs
...
Rocky Linux 8 - AppStream
Name                     Stream                   Profiles                                                Summary                             
nodejs                   10 [d]                   common [d], development, minimal, s2i                   Javascript runtime                  
nodejs                   12                       common [d], development, minimal, s2i                   Javascript runtime                  
nodejs                   14                       common [d], development, minimal, s2i                   Javascript runtime                  
nodejs                   16                       common [d], development, minimal, s2i                   Javascript runtime                  
nodejs                   18                       common [d], development, minimal, s2i                   Javascript runtime                  

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled
```

Why is the upper version limit needed in the ondemand-nodejs package? I would think that removing that would allow sites to choose their own NodeJS, based on availability (e.g. NodeJS 16 for RHEL8.6, and NodeJS 18 for RHEL8.7). The minimum version can of course stay, based on what the OOD applications require.

**Comment by treydock** [comment]
For RedHat appstream EOL dates are all on one page: https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle.  The EOL dates from the upstream vendor almost never matter with RedHat as RedHat will continue to back port security fixes if the appstream is still supported.

One issue, OnDemand still supports RHEL 7 and there is not any SCL NodeJS higher than version 14.  OnDemand 3.1 will be last release to support RHEL 7 so this isn't that big a deal.

**Comment by treydock** [comment]
The packaging infrastructure change to use NodeJS 18: https://github.com/OSC/ondemand-packaging/pull/248.  Once that's merged I'll update this repo to pull in those changes.
