### ISSUE TITLE
refactor globus inline js

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2890]
This is how we currently pass YAML configuration back to the client for javascript to read.  I'm not super keen on inline javascript so this ticket is to look into how to refactor this such that we can just template HTML and the configuration javascript can read and interpret that HTML.

https://github.com/OSC/ondemand/blob/5d8419b4d2173c4caba29f7dd1150c0fefedee24/apps/dashboard/app/views/files/_globus.html.erb#L6

Having said that, I'm not sure if it's easy. Actually I'm quite sure the structure we'd need to embed in HTML (a map) is not straight forward.

**Comment by DavidKelly999** [comment]
Hey Jeff,

What do you think about serializing and deserializing the json data? This would remove the inline javascript. Something like:

ERB: 
`<input type="hidden" id="globus_endpoints" value="<%= JSON.dump(Configuration.globus_endpoints) %>"></input>`

Javascript:
`globus_endpoints = JSON.parse($("#globus_endpoints").val());`

**Comment by johrstrom** [comment]
That could be fine. I think we're abusing the `meta` tag here, likely should just be a `div`. but yea something like 

```
data-globus-endpoints="<%= JSON.dump(Configuration.globus_endpoints) %>" 
```
could work. We already do something similar for `data-uppy-locale`.

https://github.com/OSC/ondemand/blob/867ae75dd055099ea784b3c3ec6a77bc1c2f9799/apps/dashboard/app/views/layouts/application.html.erb#L27
