### ISSUE TITLE
Checkboxes don't respond to 'Enter' in the file explorer

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#290]
And if we do this, consider "Enter" to open the selected directory

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737516974138) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Arrow keys work in 2.0, though you need to have focus on the table. Enter works on everything except for the checkbox. I think this would fall under 'should work the same when using a screen reader' - which is to say the checkboxes should respond to enters.  That seems to be the only functionality that's missing here in 2.0.
