### ISSUE TITLE
FileExplorer: Double-click on file behavior?

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#293]
Currently double-clicking a folder with open the folder, however, double-clicking a file will cause no event.

It may not be difficult to implement a double click listener for files that triggers the view action.

There may be unintended consequenses though. What happens if I 'view' a very large file?

**Comment by johrstrom** [comment]
Double clicking a file now opens the file for viewing in 2.0.  Whether we want to prompt users for very large files is a separate issue (the ticket for which may not exist yet?).
