### ISSUE TITLE
Allow hyphens in `auto_modules_...` module names

### ISSUE THREAD

**Issue by gferrari-bmrc** [OSC/ondemand#2933]
This is a suggested improvement for the `auto_modules_` features. Thanks for implementing this feature - it's super useful. However...

module names can contain hyphens. This is true, for example, of the `RStudio-Server` module (and many other modules) provided by [EasyBuild](https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs), a very popular tool for managing modules on HPC sites.

The `auto_modules_...` functionality is currently incompatible with hyphenated modules because the `AUTO_MODULES_REX` defined in `apps/dashboard/app/lib/smart_attributes/attribute_factory.rb` does not permit it. The `\w` matcher will match underscores but not hyphens.

I've tried a quick local test of changing from this:
```
AUTO_MODULES_REX = /\Aauto_modules_([\w]+)\z/.freeze
```
to this
```
AUTO_MODULES_REX = /\Aauto_modules_([\w-]+)\z/.freeze
```
And it appears to enable hyphenated modules i.e. I can now use `auto_modules_RStudio-Server`.

Many thanks.

**Comment by johrstrom** [comment]
Hi, thanks for the ticket and the proposed solution. We should account for this and likely underscores too.

**Comment by gferrari-bmrc** [comment]
If one implemented my suggested one, one would ideally like to be able to write e.g.
```
<%= context.auto_modules_RStudio-Server` %>
```
within an `*.erb` file, but apparently that doesn't work.

However, one can still use `context["auto_modules_RStudio-Server"]`.

**Comment by johrstrom** [comment]
> However, one can still use context["auto_modules_RStudio-Server"].

Yea I think this is our best bet for the moment. Seems like ruby is interpreting the `-` as the minus operator.

So something like this 
```erb
<%= context.auto_modules_RStudio-Server %>
```

is actually trying to evaluate this. 

```ruby
context.auto_modules_RStudio - Server
```

`Server` variable won't exist, but it doesn't matter because there is no method `auto_modules_RStudio` on the context object.

**Comment by johrstrom** [comment]
I have a patch for this coming, you should be able to access the variable by using underscores instead of hyphens.

So something like this should work:
```
context.auto_modules_RStudio_Server
```
