### ISSUE TITLE
BcDesktop: More robust solution to getting shell by piping `getent passwd` to `cut`?

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#295]
https://github.com/OSC/bc_desktop/blob/62376c8b1dff1659c68d27c654c6635541d1b92d/template/script.sh.erb#L10 assumes that the login shell is always the 7th field of the passwd struct. Is there ever a case where this is not true?

If Etc is already required and available to be used in erb rendering in batch connect apps, it would seem this might be preferable:

```ruby
export SHELL="<%= Etc.getpwuid.shell %>"
```

That assumes that the passwd struct for the user on the web node is the same as on the compute nodes. Is this a safe assumption? Except if you have the case where there are multiple clusters with separate home directories, and a newer cluster has that zshell you want to use, and the older cluster has bash... then perhaps you do want the batch job to determine this, not the web app.

Another option would be to add a `get_preferred_shell` helper function to the list of helper functions available for all batch connect apps (see ood_core). We could then keep the implementation as above, but that would provide the ability to override this helper function in the rare case this code was problematic.

**Comment by johrstrom** [comment]
It seems there's nothing to do here. Finding the SHELL during runtime is fine by me.
