### ISSUE TITLE
BcDesktop: noVNC repaint bugs/stalls for certain platform combinations 

### ISSUE THREAD

**Issue by michaelkarlcoleman** [OSC/ondemand#297]
Adding this to track noVNC ticket: https://github.com/novnc/noVNC/issues/1175

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737623419447) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Is this still an issue for you?  I've never experienced it myself but our OOD web server has a lot of resources and the compute node it's running on is generally under utilized too.

**Comment by michaelkarlcoleman** [comment]
It's not really an issue, in the sense that no one has complained, and I feel like "get a modern computer" is an acceptable workaround.  (Note that this bug tracks the hardware of the web browser, rather than anything on the server.)

I will say that it's one of those baffling bugs that if I had more time would totally draw me in.  It's far from obvious what could be going on here.  Almost certainly some sort of race in the noVNC code, and that would theoretically be worth finding.  But realistically, no, it seems not to matter right now.
