### ISSUE TITLE
Authorization issues with Ruby apps for servers without domain names

### ISSUE THREAD

**Issue by wtripp180901** [OSC/ondemand#2970]
We have been upgrading from OnDemand 2 to 3 and found that trying to access the dashboard would give a 403 error
The `error.log` file in the user's `/var/log/ondemand-nginx` directory contained:
`ERROR "[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: <our IP address>`

This was fixed by specifying our IP as the `servername` in the `ood_portal.yml` file, but it is documented that leaving this as the default null value should allow IP connections https://osc.github.io/ood-documentation/latest/reference/files/ood-portal-yml.html

On investigation of the error message, we found that we could connect via IP by injecting
`config.hosts = nil`
into `/var/www/ood/apps/sys/dashboard/config/environments/production.rb` and `/var/www/ood/apps/sys/myjobs/config/environments/production.rb` and the error message would no longer appear

The line replaced in both files was originally
`config.hosts = ENV['ALLOWED_HOSTS'].nil? ? nil : ENV['ALLOWED_HOSTS'].split(',')`
We can't find where this environment variable comes from

Is this a bug or is there something wrong with our config? Thank you

**Comment by johrstrom** [comment]
> This was fixed by specifying our IP as the servername in the ood_portal.yml file, but it is documented that leaving this as the default null value should allow IP connections https://osc.github.io/ood-documentation/latest/reference/files/ood-portal-yml.html

> Is this a bug or is there something wrong with our config? Thank you

`ALLOWED_HOSTS` is populated from a combination of `servername` and `server_aliases` - I think both apply to hostnames.  you should be able to see a `SetEnv OOD_ALLOWED_HOSTS <host list>` directive in the `ood-portal.conf` for the same (that's how we set it and pass it to the PUN).

I wonder what this value is for you when you don't have `servername` set?  I suspect you just found a bug where it's set to nothing like `SetEnv OOD_ALLOWED_HOSTS` then is evaluated on the other side as not nil because it's an empty string.

**Comment by johrstrom** [comment]
I suspect this is always evaluated to `true` because `allowed_hosts` is at least an empty array which would be true here.

https://github.com/OSC/ondemand/blob/f392397f9becc9de396471c3c8c40d009867dc3f/ood-portal-generator/templates/ood-portal.conf.erb#L189-L190

**Comment by johrstrom** [comment]
I have a patch incoming for this. Do you need ipv6 addresses too?

**Comment by wtripp180901** [comment]
ipv4 should be fine for now thanks

**Comment by flybirdkh** [comment]
I'm having the same issue, and  how did I fix it

**Comment by flybirdkh** [comment]
OS: CentOS7.9  OnDemand version:3.03
