### ISSUE TITLE
Adding custom button to job card to run script

### ISSUE THREAD

**Issue by miesav** [OSC/ondemand#2972]
Hi team,

One of our apps will most likely require a custom button added to the session card. The button has to execute a remote command through ssh on the node the job is running. I see custom html can be added to view.html.erb, was just wondering what would be the easiest way to accomplish this? Possibly with a js script? 

Kind regards.

**Comment by johrstrom** [comment]
I don't think what you're asking is possible.

Can you explain what the remote command does? There could be another facility to accomplish what you want, depending on what this command does and/or what side effects you want from it.

**Comment by miesav** [comment]
Didn't think so but worth the try. The command has to send SIGUSR1 to a PID contained in a specific pidfile created with script.sh.

**Comment by johrstrom** [comment]
OK yea there's no way to do that outside of the `script.sh` or `after.sh`.

**Comment by miesav** [comment]
Thank you Jeff, ended up implementing through the deployed app itself.
