### ISSUE TITLE
save templates into the users' profile

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2973]
Once #2958 is merged let's refactor where these templates are being stored.

Let's start using the users' profile file for storing this information in it. Currently (at the time of writing) we're only using this file to store which profile the user has selected. Let's expand this so that it also stores prefill templates for batch connect apps.

This may require some thought as CurrentUser holds all this logic currently when it probably shouldn't. IDK where this should go off hand, but I don't think CurrentUser should have it as we want to be able to use CurrentUser in the boot stack (i.e., it shouldn't rely on any external library).

**Comment by johrstrom** [comment]
Note the `CurrentUser` stuff I was talking about in the original comment has been fixed in #3035

**Comment by Oglopf** [comment]
I need to write out what actual needs done as I am not capable of following this flow of consciousness coding and building, my apologies.

## Files
File: `models/concerns/user_setting_store.rb`

## Goal
The code generates a `yaml` file with:
```ruby
def user_settings_path
  Pathname.new(::Configuration.dataroot).join(::Configuration.user_settings_file)
end
```
And the idea is to now have a top level key for `prefill_templates` in this `yaml`, and then to allow any number of keys to be added in later and saved the same way. With each key being at the top level and the settings being inside that.

**Comment by Oglopf** [comment]
Will need to `include UserSettingStore` in the `SessionContextController` in order to replace the current implementation where a `json` is built. This should leave the `view` alone to contine to call the `@prefill_template` and have it work.

**Comment by Oglopf** [comment]
Weird. These are saving as JSON in `data/batch_connect/sys/bc_osc_paraview/prefill_templates/`.

`session_contexts_controller.rb#save_template` is currently being used, yank that out since we don't want the `json` and replace with module behavior as well.
