### ISSUE TITLE
Slow PUN reload times for users with many apps

### ISSUE THREAD

**Issue by Oglopf** [OSC/ondemand#2975]
We had a user create a Discourse that gathered some information for us around slow load times for PUNs being restarted with many apps to reload. 

The Discourse can be seen here:
https://discourse.openondemand.org/t/help-troubleshooting-poor-dashboard-load-performance/2908

This is possibly an issue in the dashboard code in the routers where there may be some regexes that could be sped up, or the `nav_bar.rb` in the `::items` or some of the longer class methods there which are doing quite a bit of work and may need some attention.

**Comment by Oglopf** [comment]
# Design Proposal

Looking at this and thinking of the design I have some thoughts on how to proceed:

1. Let's use a namespace to logically organize the code. This directory is already out of hand with many files that interact but which have no logical seperation. So something like this:
  app/
  └── nav_bar/
      ├── nav_item.rb
      ├── string_nav_item.rb
      ├── hash_nav_item.rb
      ├── links_nav_item.rb
      └── url_nav_item.rb

With code then following this pattern within the directory:
```ruby
module NavBar
 class <Various Nav Classes>
   # code
 end
end
```

2. With this done, the next focus should be on the way the code currently runs. Let's break out all these type checks for `hash` and `string` and instead use compostio this. Then we can use `case` statements for easier to read and maintain code in the `NavItem` with something like:
```ruby
module NavItem
  def self.create(nav_item)
    # Factory logic to return the correct type of NavItem
  end

  def generate
    # Generate the actual navigation item
  end
end
```
And then specific classes, which we could always add to, to handle the types and geenerate the configs themselves:
```ruby
class StringNavItem
  include NavItem

  def initialize(nav_item)
    @nav_item = nav_item
  end

  def generate
    # logic specific to String navigation items
  end
end

class HashNavItem
  include NavItem

  def initialize(nav_item)
    @nav_item = nav_item
  end

  def generate
    # logic specific to Hash navigation items
  end
end
```
Then `self.items` can look a bit more maintainable:
```ruby
def self.items(nav_config)
  nav_config.map do |nav_item|
    item = NavItem.create(nav_item)
    item.generate
  end.flatten.compact
end
```  
3. It may be beneficial to also see if any of these classes are sharing behavior and if so, to factor that out into a module as well to be used when needed.

4. The constants at the end of the file seem like the could be put into a module labeled as such as `StaticNavConfigs`.

Happy to hear more ideas, this is just my first stab at trying to clean this up a bit.

**Comment by johrstrom** [comment]
I kind of assumed it was related to #210.  We never updated to start benchmarking, but benchmarking would tell us where all our time is being spent.

Refactoring sounds fine - but the question I'd have is it to have better performance or just human maintenance?

**Comment by Oglopf** [comment]
I'm closing this since it seems to be a duplicate of that old ticket.
