### ISSUE TITLE
add some safety around where projects can be made

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2976]
With #2971 being worked - we need some mechanism to ensure that the project directory is OK.

Here's an example where I was able to create a project on the data_root itself (the 4th project), which shouldn't be allowed. 

```
[johrstrom dashboard(2558_added_implementation_for_project_path)]  cat data/projects/.project_lookup 
---
1: "/users/PZS0714/johrstrom/ondemand/src/apps/dashboard/data/projects/1"
2: "/users/PZS0714/johrstrom/ondemand/src/apps/dashboard/data/projects/2"
3: "/users/PZS0714/johrstrom/ondemand/src/apps/dashboard/data/projects/3"
4: "/users/PZS0714/johrstrom/ondemand/src/apps/dashboard/data/projects"
5: "/users/PZS0714/johrstrom/temp/test_project"
```

That's the only directory I can think of that we should check for, but there likely could be others.

**Comment by abujeda** [comment]
I am doing an analysis on project locations and location management. These are my 2 notes:
 - A project location override should not be equal to `Project.project_dataroot` or any children there on.
 - On Project.destroy, we should only delete the project `.ondemand` folder, to avoid the deleting a whole subtree from the filesystem.

**Comment by johrstrom** [comment]
I think your note about re-rendering the form instead of redirecting may be included here as well.
