### ISSUE TITLE
Quality and compression slider values don't do anything

### ISSUE THREAD

**Issue by ndusek** [OSC/ondemand#2994]
We found that somewhere between 2.x and 3.x, the compression and quality sliders in the session card for VNC apps don't actually affect the quality and compression. To actually change those settings, we have to use the side bar settings that noVNC puts in the actual GUI window.

The reason for this seems the be that the variables passed in the URL are `compressionsetting` and `qualitysetting` (see `_novnc.html.erb` [here](https://github.com/OSC/ondemand/blob/6259e46ac58ab08490098188585d04639480db8a/apps/dashboard/app/views/batch_connect/sessions/connections/_novnc.html.erb), for instance) whereas noVNC takes as arguments simply `compression` and `quality`. Maybe this was a change from noVNC 1.1 to 1.3?

In any case, we found that manually changing `compressionsetting` -> `compression` and `qualitysetting` -> `quality` in the noVNC launch URL fixed the problem. Not sure if this is a known issue or not, but we thought we'd report it just in case.

**Comment by johrstrom** [comment]
🤦‍♂️ Thanks for report! I'm unaware of the bug. I'll try to get this patched in 3.0.

**Comment by ndusek** [comment]
No problem. We can submit a PR too, if it's just a matter of doing a quick substitution for those two arguments in `_novnc.html.erb`? Or is it more complicated than that?
