### ISSUE TITLE
Share gems between core apps

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#30]
Eric wrote:

>Okay. Maybe we can discuss for 1.6+ adding rh-ror50 dependency, unless we want to go the route of building our own gem rpms. I think we can transition all the core apps to use the same Gemfile.

Trey wrote:

>I think having a single Gemfile or identical Gemfiles and same --path with bundler to shared location would be enough, maybe?  We now have place to put gems in /opt/ood/ondemand/root that is for SCL so in theory we could install the gems in a way where they work without bundler but with bundler is fine too if they all share the same path to gems?
> 
>I really don’t want to do RPMs for every gem, I mean we could but that’s a lot of overhead and would slow down upgrade development.  The current approach of using something like bundler and just packaging the results seems fine to me but reducing the duplication would be nice, right now ondemand RPM is bigger than Linux kernel and other kernel packages like headers and development files combined.

One approach that would be easy to implement is acknowledging that the location of the gems when building is specified by the path argument i.e. `bundle install --path vendor/bundle` and this value is stored in `.bundle/config` which is then used when Passenger loads the app. What this means is that for an rpm build of ondemand, we could change the path to be `bundle install --path /opt/ood/ruby/vendor/bundle` and ensure that the Gemfile and Gemfile.lock for all of the core apps were identical. If we are going to do this, however, we should consider the alternative: using a Gemfile and Gemfile.lock, run `bundle install` to populate the ondemand-ruby SCL with the gems that we want to use, and then the core apps would use the system gems. The benefit here is that other apps would also have access to these system gems without having to install their local copies - such as the System Status app, for example.

The problem with this is that it is too easy an app's Gemfile to diverge - just modify and run bundle install. So if we go this way, what will be the systematic approach to introducing changes to the global Gemfile so that an individual app can use this.

A monorepo may make these type of changes much easier to implement.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737623331922) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
Another type of sharing that would be easier for a mono repo are:

- shared assets (i.e. bootstrap, jquery, datatables)
- shared templates (i.e. navbar, etc.)

**Comment by johrstrom** [comment]
I think we do this in packaging both for RPMs and debians. Going to close this as 'probably completed in the past'.
