### ISSUE TITLE
User .bundle/config can break OnDemand 1.7.1+

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand#302]
See #299.

We'll need to ship an updated Bundler (>= 1.17), and set one or more environment variables. Candidates for controlling this behavior include:

- `BUNDLE_USER_HOME`
- `BUNDLE_USER_CONFIG`
- `BUNDLE_IGNORE_CONFIG`

**Comment by treydock** [comment]
I'm going to set just `BUNDLE_USER_CONFIG` so that app `.bundle/config` for like dev apps can still work and also `BUNDLE_USER_HOME/cache` will still work. I will set in nginx_stage pun.conf and maybe make it configurable to not set.
