### ISSUE TITLE
Files app: downloading a FIFO file fails silently

### ISSUE THREAD

**Issue by CSC-swesters** [OSC/ondemand#3029]
How to reproduce:

- In your home folder, or wherever you can go with the OOD Files app, create a FIFO file: `mkfifo ood-reproducer`
- Write something into the FIFO: `date > ood-reproducer`
  - Note that this command will block, but that's expected.
- Via a browser with OOD, find the `ood-reproducer` file and try to download it

Expected results:
- There should be some kind of error notification that I could not download the file

Actual results:
- Nothing is shown to the user.
- There is a HTTP request for `<path to files app>/fs/<path to fifo>/ood-reproducer?download=<millisecond timestamp>` which returns `HTTP 200` that contains a HTML render with an error notification, but none of that shown to me in Firefox 116, nor Chromium 116.

This issue touches on #3026, but is more focused on actually conveying error messages, rather than preventing misunderstandings.

**Comment by johrstrom** [comment]
I'm finding this is a bit larger of an issue. The same happens when you try to download a file you have no read permissions on.
