### ISSUE TITLE
Dashboard: BatchConnect session SSH link needs feature flag

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand#306]
We have a site that does not support SSHing to the compute node that a job is running on. They would like to be able to turn that feature off. I was surprised to learn that our usual initializer / monkey patch approach does not appear to be able to impact view helpers which is where the relevant code is. The quick fix is to add a feature flag, part of the larger fix is to reduce how much actual templating the BatchConnect session view helper is doing.

**Comment by MorganRodgers** [comment]
`OOD_BC_SSH_TO_COMPUTE_NODE=0`

Add test for variable to here:
https://github.com/OSC/ondemand/blob/master/apps/dashboard/config/configuration_singleton.rb

Reference this one:
https://github.com/OSC/ood-dashboard/commit/0207ee6769a0880985110e1c29ab73d035bf6d6b#diff-249e7cd3bbb5900c2f61a62d0e942cd6R82-R88

Change this one:
https://github.com/OSC/ondemand/blob/master/apps/dashboard/app/helpers/batch_connect/sessions_helper.rb

**Comment by ericfranz** [comment]
In OnDemand 1.7.3
