### ISSUE TITLE
path_selector - buggy behavior when selecting for the second time.

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3060]
to replicate:
* select a file somewhere using the path selector.
* Now try to open the path selector again and choose a different path

At this point (on the second attempt) you'll get this screen
![image](https://github.com/OSC/ondemand/assets/4874123/680166b9-4eef-4641-bc4f-474dc9c64df0)

And to make matters worse - the single row `No data available in table` is clickable and makes an erroneous request to reload the table.

**Comment by HazelGrant** [comment]
Have figured out that this might be happening when `lastVisited` at path_selector_data.js:143 is a file instead of a directory while working on a different ticket.
