### ISSUE TITLE
cant update ffi gem on el:7

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3073]
The automation to update gems is currently failing on centos:7 with this error message below.

I'm not entirely sure why it's trying to compile all python code - but as you can see it does and fails on some file it shouldn't even be interacting with (generate-darwin-source-and-headers.py). 

```
+ /usr/bin/install -D -m 644 hooks/hook.env.example /work/el7-x86_64/BUILDROOT/ondemand-3.1.0-1.el7.x86_64/etc/ood/config/hook.env
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Compiling /work/el7-x86_64/BUILDROOT/ondemand-3.1.0-1.el7.x86_64/opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.0-1/gems/ffi-1.16.2/ext/ffi_c/libffi/generate-darwin-source-and-headers.py ...
  File "/opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.0-1/gems/ffi-1.16.2/ext/ffi_c/libffi/generate-darwin-source-and-headers.py", line 220
    f"--host={platform.target}",
                              ^
SyntaxError: invalid syntax
```

It seems we have 2 options for 3.1 (possibly/probably the last el:7 release)
* lock the ffi gem to a given working version
* add this line `%undefine __brp_python_bytecompile` to the spec file. (I don't know what side effects that may have)

**Comment by treydock** [comment]
Depending on the timeline for OnDemand 3.1, another option is dropping EL7 support as EL7 will be End-Of-Life at end of May in 2024.

Given OnDemand doesn't tend to use Python , not byte compiling the Python code probably won't affect anything so I think that solution sounds fine if it works.

**Comment by johrstrom** [comment]
> Depending on the timeline for OnDemand 3.1, another option is dropping EL7 support as EL7 will be End-Of-Life at end of May in 2024.

I'd like to release end of this year-ish

> Given OnDemand doesn't tend to use Python , not byte compiling the Python code probably won't affect anything so I think that solution sounds fine if it works.

Yea maybe we can try it - if it fails it'll fail completely because we (unprivileged users) won't be able to write any `.pyc` files.

**Comment by treydock** [comment]
Generally Python won't try and write out a `.pyc` file if the access isn't there.  There are plenty of `.py` files that OSC deploys without corresponding `.pyc` to locations only writable by root but no issues running those scripts as unprivileged user.  Good example:

```
tdockendorf@pitzer-rw01 ~]$ ls -la /opt/osc/sbin/host*
-rwxr-xr-x 1 root root 10651 May 17 09:01 /opt/osc/sbin/hostgroup-parameter.py
-rwxr-xr-x 1 root root  9649 May 17 09:01 /opt/osc/sbin/host-parameter.py
```

**Comment by johrstrom** [comment]
Good to know - it could be a much safer change that I'd thought.

**Comment by johrstrom** [comment]
This was fixed in https://github.com/OSC/ondemand/pull/3083
