### ISSUE TITLE
"No clusters configured" error

### ISSUE THREAD

**Issue by btsherid** [OSC/ondemand#3080]
Hi,

I am trying to setup OnDemand 3.0.1 on Rocky 9 and I'm getting errors saying I haven't set up a cluster, even though I have configured one.

 If I click on the Shell Access app, I see the message "No clusters defined". The Job Composer says "There are no configured hosts that allow you to submit jobs. Please contact your system administrator"

However, if I click on Active Jobs, it pulls up my cluster and shows me all the jobs.

Here is my /etc/ood/config/clusters.d/lbg_cluster.yml file:

<pre>
v2:
  metadata:
    title: "LBG Cluster"
    hidden: "true"
  login:
    host: "login.bioinf.unc.edu"
  job:
    adapter: "slurm"
    bin: "/usr/bin"
    conf: "/etc/slurm/slurm.conf"
  batch_connect:
    basic:
      script_wrapper: |
        module purge
        %s
    vnc:
      script_wrapper: |
        module purge
        export PATH="/opt/TurboVNC/bin/:$PATH"
        export WEBSOCKIFY_CMD="/usr/local/bin/websockify"
        %s
</pre>

**Comment by johrstrom** [comment]
What are the permissions on `/etc/ood/config/clusters.d/lbg_cluster.yml`? I.e., can an unprivileged user read it?

**Comment by btsherid** [comment]
Yes, these are the permissions:

**Comment by johrstrom** [comment]
OK - Maybe you just need to 'restart your webserver' (the button at the top right in the help menu) to pick the file up? This could have happened if you wrote the file _after_ the webserver started. I.e., it only picks these configurations up on startup.

**Comment by btsherid** [comment]
I've done the 'restart your webserver' multiple times with no effect. It also does not change if I run `systemctl restart httpd` and then `systemctl restart ondemand-dex`.

Thanks,
Brendan

**Comment by johrstrom** [comment]
This is the button to restart your Per User Nginx. When _this_ is restarted - it'll pick up the configs.

![image](https://github.com/OSC/ondemand/assets/4874123/9111ee08-3997-4218-9362-ab667d450e80)

**Comment by btsherid** [comment]
Yep, that's the one I was using. After that, I'm still seeing this:

Job Composer:
![image](https://github.com/OSC/ondemand/assets/62118099/dc9d75dd-04d0-48c8-93a9-91284646c8a7)

Shell Access:
![image](https://github.com/OSC/ondemand/assets/62118099/ff951e6d-81d7-4a45-b018-0d6f196f235a)


But Active Jobs works and sees the cluster correctly. 
![image](https://github.com/OSC/ondemand/assets/62118099/e0461d53-d5c8-49ec-97f8-553897e699ad)

**Comment by johrstrom** [comment]
I see - you've set hidden as true. Remove this and restart your web server and I think it'll work.

```
    hidden: "true"
```

**Comment by btsherid** [comment]
Ah, that was it! Makes sense, thank you!
