### ISSUE TITLE
Change "version" of components (except for ood-portal-generator) to output the same value as VERSION file for this repo 

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#31]
Same logic as https://github.com/OSC/ood-dashboard/blob/baea5558a4e55e8f7ca49599670e6731ad2da94b/config/configuration_singleton.rb#L30-L44

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737622573406) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Duplicate of #23
