### ISSUE TITLE
nginx_stage nginx_clean cleans up active PUN

### ISSUE THREAD

**Issue by robinkar** [OSC/ondemand#3111]
We are having a strange bug in one of our OOD environments, where active PUNs are being cleaned up when running `/opt/ood/nginx_stage/sbin/nginx_stage nginx_clean`.
This happens, for example, even when there is an active file transfer (using Rclone in this case) in progress and the user's browser is actively querying the progress. The cleanup then causes the file transfer to be aborted. The OOD versions we are using are 3.0.1 and 3.0.2.
We run OOD in a container, and even though two of the environments are running exactly the same image, it only happens in one of them.
Having the terminal (shell app) open in OOD prevents the PUN from being cleaned up.

With the dashboard open and an active transfer using Rclone, `nginx_clean` and the `lsof` command used by it gives the following output:
```
[root@ood-testing /]# date ; /opt/ood/nginx_stage/sbin/nginx_stage nginx_clean --skip-nginx; echo ; lsof -F piu /var/run/ondemand-nginx/robkarls/passenger.sock
Fri Oct  6 09:27:17 UTC 2023
robkarls

p2708
u0
f5
i412849896
p2734
u10018239
f5
i412849896
```
Here the PUN is considered inactive by nginx_stage. Process 2708 here is `nginx: master process (robkarls)` and 2734 is the `nginx: worker process`.

In the other OOD environment, where it is working as expected, this is the output:
```
[root@ood-future /]# date ; /opt/ood/nginx_stage/sbin/nginx_stage nginx_clean --skip-nginx ; echo ;lsof -F piu /var/run/ondemand-nginx/robkarls/passenger.sock
Fri Oct  6 10:06:49 UTC 2023

p758
u0
f5
i12826345
```
Process 758 here is `nginx: master process (robkarls)`.

After opening the shell app in both of these environments, these are the outputs from the commands:
```
[root@ood-testing /]# date ; /opt/ood/nginx_stage/sbin/nginx_stage nginx_clean --skip-nginx ; echo ;lsof -F piu /var/run/ondemand-nginx/robkarls/passenger.sock
Fri Oct  6 10:07:29 UTC 2023

p2708
u0
f5
i412849896
p2734
u10018239
f3
i413408799
f5
i412849896
```
```
[root@ood-future /]# date ; /opt/ood/nginx_stage/sbin/nginx_stage nginx_clean --skip-nginx ; echo ;lsof -F piu /var/run/ondemand-nginx/robkarls/passenger.sock
Fri Oct  6 10:06:49 UTC 2023

p758
u0
f5
i12826345
```

The logic for counting active sessions seems to happen [here](https://github.com/OSC/ondemand/blob/479058f0af32e6a8e6ec59ca5842180733c6f8ba/nginx_stage/lib/nginx_stage/socket_file.rb#L24). In the output from `lsof` in the problematic OOD environment (ood-testing), without the shell app open, the inode `412849896` occurs twice, which means it is filtered out by `.select{|k.v| v.size == 1}`, which seems wrong. Active sessions in that case is 0. Later, when the shell app is open, the inode `413408799` occurs, passing the check there and counts as an active session.
There seems to be a few things that could be wrong here, although I am not sure what exactly is wrong. Is the nginx worker process supposed to have the socket open at all, as it happens only in the problematic environment? The comment for that line of code seems outdated as these sockets are open by the root nginx process, not the apache proxy as the comment seems to indicate, is the logic still up to date after 7 years?

**Comment by johrstrom** [comment]
Thank you for the very detailed description and debugging. I'll have to dig in myself and see what's what.

**Comment by robinkar** [comment]
It seems like `nginx_stage nginx_clean` does not do anything in the environments unaffected by this bug. Even though we have PUNs that have been inactive (no connections, no Passenger apps running) over 12 hours, their processes (Passenger+nginx) are still running and are not seen as inactive by `nginx_stage nginx_clean`.

**Comment by johrstrom** [comment]
> environments unaffected by this bug

What's the difference between these environments?

**Comment by robinkar** [comment]
> > environments unaffected by this bug
> 
> What's the difference between these environments?

We haven't been able to track down / pinpoint any meaningful difference that would lead to this. For every difference between ood-testing and ood-future, we have the same config or setup in some other environment where the problem does not occur.

In the environment where the problem occurs (ood-testing), we have sandbox apps enabled, while in ood-future we don't, but at the same time we have another environment with sandbox apps enabled where the problem does not happen.
As for the OOD configuration, the environment where it does occur (ood-testing) has `passenger_friendly_error_pages: "on"` set in `nginx_stage.yml`, which the other environment (ood-future) does not have that set. ood-testing also has `app_root` explicitly defined to the default value, but that should not have any practical impact at all.
One difference is that ood-future and ood-testing run on different hosts, although we also have another environment running on the same host as ood-testing, which is not affected by the bug. Other than that, the environments are identical, running the same container image.

**Comment by johrstrom** [comment]
I'll have to look at where all `socket_file` is being used, but for nginx clean it's here: https://github.com/OSC/ondemand/blob/bee91868d5774398f870a4fcff7c733b4693ef46/nginx_stage/lib/nginx_stage/generators/nginx_clean_generator.rb#L63


I think a naive implementation may be something like this. Attached to that class, I don't think you'd need to pass user into the method, I just made this hacking around.

```ruby
def sessions(user)
  `ps  -o cmd -u #{user}`.split("\n").select do |command|
    command.match?(/Passenger [\w]+App:/)
  end.count
end
```

nginx processes will always be running. But the Passenger processes' will only kick in once you have an active session.  Passenger apps stop themselves, but nginx does not - hence this nginx_clean action here.

So my theory is - if you have Passenger processes (that haven't stopped themselves) you have active sessions. If you don't have any Passenger processes (because they've stopped themselves) we can go ahead and stop nginx too.

**Comment by CSC-swesters** [comment]
Thanks for fixing this! We tried out the new `nginx_stage nginx_clean` and the first impressions are that it seem to do what it is supposed to do. Cannot say anything about how it scales yet, but theoretically, it should be better than before :slightly_smiling_face: 

@johrstrom is this something which could be backported to the 3.1.x branch? We're interested in taking the fixed version into production as soon as possible, since we've currently disabled the old version from running completely.

**Comment by johrstrom** [comment]
> @johrstrom is this something which could be backported to the 3.1.x

Yes, this'll be in 3.1.5.

**Comment by johrstrom** [comment]
Just to update 3.1.5 is in the `latest` repo right now. We haven't installed at OSC so that's why we haven't promoted to 3.1 repo.
