### ISSUE TITLE
Integrate gems into monorepo

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#313]
Here is a versioning proposal for gems we integrate into this repo. The idea is to move ood_core, ood_support, and add ood_branding (to replace ood_appkit?) or merge in ood_appkit as well.

All of the latest release versions of these gems are below 1.7.

The proposal is when gems are merged into this repo, they get the same version as the ondemand version. As a result, core apps will be set to use the version of the gems that are built with the apps.

We can even add pushing the gem releases to rubygems to the GitLab pipeline.

We won’t want to do this for build from source or prerelease versions. In those builds we would want to “build the gem” locally and install it locally to the system gems, perhaps prior to running bundle install for the others.

This might run into problems with bundler wanting to use rubygems.org and always looking there even if a valid gem version is installed (you can bypass this with bundle install —local but that introduces other problems).

I’ll post more details of this idea in comments soon. But to summarize, the benefits include:

1. Core apps can use the version of the gem code that is in the repo (same sha), removing the need to manually update Gemfiles... well Gemfile.lock files would need updated unless we stopped versioning those or did something clever.
1. Gems can be auto published to rubygems in the release pipeline, removing the need to manually to this.
1. Changes that involve core apps and gems could happen in 1 commit or branch.

Drawbacks:

1. Gem versions would lose semantic meaning. The difference between ood_support 1.7 and ood_support 1.8 might be nothing! On the other hand, ood_core 1.7.1 might introduce new features that ood_core 1.7.0 did not provide. Of course we could still stick to avoiding breaking changes in minor or patch and take that seriously for all published gems. We would need to update external apps to depend on very specific versions of ood_core.
1. We lose ability to easily vary versions of the gems used between each core library, so changes to gems would impact all core apps that depended on gems, instead of deciding which ones to update. But maybe this is good. 

There are other options too. For example, we could automate the push of gems to rubygems.org in the separate gem repos. To assist with development, we could. 
We could setup path to /opt/ood/gems/... for the gem files and just have core apps rely on a separate deployment of these gems, though that would remove these from the ondemand-gems repo...

We could also install all gems from rubygems.org except for the core gems and install those separately and then when running bundle install on the apps (after the separate gem setup task invocation) use bundle install --local.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737568343019) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
Just curious, why have separate gems if they get merged into mono-repo? Why not just have `ondemand` gem or something and merge them all into one? I'm not too concerned about keeping these in ondemand-gems RPM since their install time is minimal. The big benefit to ondemand-gems comes from things that require compiling code like nokogiri and sassc as those take considerable amounts of time to install. So if the gem(s) have to be installed in some way to avoid ondemand-gems, that's not a huge loss in terms of build times.

**Comment by ericfranz** [comment]
If we only had 2 gems, we could have:

ood_core
ood_rails

One of the gems does not depend on Rails and can be easily used in Sinatra apps etc. externally. The other gem depends on Rails and provides Rails plugin and shared assets.

If we can remove the Rails dependency from ood_appkit by refactoring things, we could have just one gem. There isn't any reason to have separate ood_core and ood_support so we could deprecate ood_support and add similar classes to ood_core.

I think its important to have these in ondemand-gems RPM so that external apps can easily use these.

**Comment by treydock** [comment]
If we didn't put them in `ondemand-gems` then I'd think they'd get packaged directly into `ondemand` RPM so external apps could still utilize. I like keeping them in `ondemand-gems` but I don't want that to be a hard requirement for future decisions unless there is an aspect I'm not seeing.

**Comment by ericfranz** [comment]
Here’s a proposal:

The Gemfiles of the apps are configured with something like:

    gem "ood_core", path: "/opt/ood/gems/ood_core"

Gems are all still installed and added to ondemand-gems rpm. However the duplicate code of the gem is added to the /opt/ood... path. The core apps use the path so their Gemfile.lock does not change... though I guess they would if the ood_core dependency changers... 

Other apps could have the option to use the installed gem.

It’s a little odd having two copies of the gem in an OnDemand deployment and when git cloning to not have the core app code by default use the local copy of ood_core. I don’t know another way that is clean to meet these goals:

- have ood_core gem in this repo
- have core apps auto use whatever the code of ood_core is in the same repo, and avoid having to play games with versions and/or publish a new version of ood_core to rubygems before updating core apps
- make releases of ood_core avail for other apps

Another approach is to postpone this work and instead make the current process less onerous:

1. Merge gems into one ood_core gem
2. Add CD pipeline to auto publish ood_core to rubygems.org

I’m leaning towards this second approach.

**Comment by treydock** [comment]
What about something like:

```
dir = File.expand_path(File.dirname(__FILE__), '..')
gem "ood_core", path: File.join(dir, 'gems/ood_core')
```

This would require putting apps in `/opt/ood/apps` and symlinking them to `/var/www/ood/...` if the Gemfile is at root of each app. Ideally we could update nginx_stage to search multiple paths and not deal with symlinks.

This would not require Rubygems maybe? Because if someone installs an app they will have OnDemand installed, unless they want different version than one published as part of ondemand. 

Also what about a meta gem? One called "ondemand" that pulls in the other gems used by ondemand like ood_core? Would maybe simplify things for sites.

**Comment by ericfranz** [comment]
Are there any drawbacks for transitioning from a core app like the dashboard from /var/www/ood/apps/sys/dashboard to being a symlink to /opt/ood/apps/? Will the rpm installation process make the transition seamless?

**Comment by treydock** [comment]
I don't recall the exact issue but either going from directory to symlink or symlink to directory is not possible with RPMs because of how they are extracted. We ran into this before with one of the NodeJS apps where a dependency transitioned from one state to another and we had to fix it in the RPM spec. When possible I like to avoid symlinks, not just for the issues with RPMs but also to avoid ambiguity of where things are actually installed.

**Comment by ericfranz** [comment]
Another drawback of integrating the gems into the monorepo and using the `path:` approach, is the [path option does not compile native extensions](https://bundler.io/man/gemfile.5.html#PATH) so any native extensions would need to be provided in a gem outside of this repo.

**Comment by ericfranz** [comment]
Also even if we used `path:` in the Gemfile it would still be necessary to push new versions of ood_core (and any other gems) to rubygems.org so that other apps could make use of the gem.

And if we are going to do this, then it also would be preferable that we at least do this on an official tagged release (like 1.7.6 etc.) which also means that if we have generated the ood_core ruby gem, we could use that version, instead of what might end up in /opt/ood/.

**Comment by matt257** [comment]
reviewed,
reconsider the goal and open a new issue if this is wanted later
