### ISSUE TITLE
Document the dangers of greedy `host_regex` expression (it must not match on /)

### ISSUE THREAD

**Issue by Micket** [OSC/ondemand#3130]
I spent some time debugging why some of my apps didn't work correctly, when I eventually discovered I had been neglectful when specifying my `host_regex` configuration. I had done something like
```
host_regex: "foo.*"
```
which will cause confusing issues, no error messages (from what I could find), but apps either didn't work, or just partially didn't work.
Example, the desktop app still worked fine, while a jupyter notebook will launch the browser just fine, but won't be able to connect to any python kernel.
Other fails to find most of it's linked material, leaving a typical white page and maybe a favicon.

While the examples do correctly show regex which correctly excludes /, I think it would help to make this requirement explicitly written in the docs, otherwise strange things will happen with the proxy'ing.

https://osc.github.io/ood-documentation/latest/reference/files/ood-portal-yml.html?highlight=host_regex#configure-reverse-proxy

**Comment by Oglopf** [comment]
Hey, thanks for this! I've linked this issue and copied it over to our docs repo to make sure it gets picked up. So, I'm closing it here but you can find the new ticket at:
https://github.com/OSC/ood-documentation/issues/883
