### ISSUE TITLE
Remove useless comments and replace with return type information

### ISSUE THREAD

**Issue by Oglopf** [OSC/ondemand#3162]
The `BatchConnect::SessionContextsController` code has some pretty funny comments that are just the method names without the underscores. These comments do nothing for a developer.

Given how useful this object is, let's annotate the _return types_, which are really the only comments I'm interested in as we can then code much faster having an idea what messages can be sent.

**Comment by johrstrom** [comment]
>  let's annotate the return types,

Not sure if that pull request full-filled this or not - but we found that many of those methods either don't have return types at all (they just set member variables) or they're Rails methods like `new` or `create` that take all those Rails conventions of rendering the `new.html.erb` or similar view.
