### ISSUE TITLE
Proxying to services that use HTTPS

### ISSUE THREAD

**Issue by griznog** [OSC/ondemand#3186]
Opening this issue based on this discourse thread:

https://discourse.openondemand.org/t/reverse-proxy-rnode-or-node-to-ssl-service/3080/7

with two goals:

1. Solve my current issue trying to run NoMachine's web service behind OnDemand (as an alternative to noVNC)
2. Request a general way to handle the case of using OnDemand with backend apps that use HTTPS other than my current method below of hard-coding a specific port in  `/opt/ood/mod_ood_proxy/lib/ood/proxy.lua`.

What I've done so far to get this to work is to add this to my portal config:
```
ssl:
  - 'SSLProxyEngine On'
  - 'SSLVerifyClient none'
  - 'SSLProxyVerify none'
  - 'SSLProxyProtocol TLSv1.2'
  - 'SSLProxyCheckPeerName off'
  - 'SSLProxyCheckPeerCN Off'
  - 'SSLProxyCheckPeerExpire Off'
```

Which solves the issue of NoMachine using a self-signed certificate and enables Apache proxying to HTTPS backends.

Next I've modified `/opt/ood/mod_ood_proxy/lib/ood/proxy.lua` to be:

```
--[[
  set_reverse_proxy

  Modify a given request to utilize mod_proxy for reverse proxying.
--]]
function set_reverse_proxy(r, conn)

  -- find protocol used by parsing the request headers
  -- Check if an upstream port was set for reverse proxies.
  local upstreamPort = nil
  local isUpstreamPortSet = (r.subprocess_env['MATCH_PORT'] and 'true' or 'false')
  if isUpstreamPortSet == 'true' then
    upstreamPort = r.subprocess_env['MATCH_PORT']
  end

  local protocol = (r.headers_in['Upgrade'] and "ws://" or "http://")
  if upstreamPort then
    -- If specified port was used, then use secure protocols
    if upstreamPort == '4443' then
      protocol = (r.headers_in['Upgrade'] and "wss://" or "https://")
    end
  end

  -- setup request to use mod_proxy for the reverse proxy
  r.handler = "proxy-server"
  r.proxyreq = apache2.PROXYREQ_REVERSE

  -- define reverse proxy destination using connection object
  if conn.socket then
    r.filename = "proxy:unix:" .. conn.socket .. "|" .. protocol .. "localhost" .. conn.uri
  else
    r.filename = "proxy:" .. protocol .. conn.server .. conn.uri
  end

  -- include useful information for the backend server

  -- provide the protocol used
  r.headers_in['X-Forwarded-Proto'] = r.is_https and "https" or "http"

  -- provide the authenticated user name
  r.headers_in['X-Forwarded-User'] = conn.user or ""

  -- **required** by PUN when initializing app
  r.headers_in['X-Forwarded-Escaped-Uri'] = r:escape(conn.uri)

  -- set timestamp of reverse proxy initialization as CGI variable for later hooks (i.e., analytics)
  r.subprocess_env['OOD_TIME_BEGIN_PROXY'] = r:clock()
end

return {
  set_reverse_proxy = set_reverse_proxy
}
```

With these changes it almost works. I can successfully reach the NoMachine service on 4443 via an `/rnode` URL, but get the error:

```
Error
An unexpected error was encountered during the installation of the Web Player component.
```

NoMachine support suggested these settings to reverse proxy behind Apache:

```
SSLProxyEngine On
SSLProxyVerify none
SSLProxyCheckPeerCN Off
SSLProxyCheckPeerName Off
SSLProxyCheckPeerExpire Off


ProxyPass  "/" "https://192.168.3.201:4443/"
ProxyPassReverse "/"  "https://192.168.3.201:4443/"
ProxyPass "/nxplayer"  "https://192.168.3.201:4443/nxplayer"
ProxyPassReverse "/nxplayer"  "https://192.168.3.201:4443/nxplayer"
```

But I don' t know how/where to translate them so I get the equivalent behavior when using `/rnode/...` to proxy to the service. 

Happy to provide additional information, but note that I'm not adept at troubleshooting web stuff so would appreciate guidance in how to collect any information needed to troubleshoot this further.

**Comment by griznog** [comment]
`/rnode` does _almost_ work, but something is happening that prevents the `nxplayer` from getting installed. The resulting error page has some broken links to images at the `/nxplayer` URL and if I add those to the full `/rnode` URL the load fine. Not exactly sure how to figure out why it works if I go to `https://hostname:4443` but not via the ondemand `/rnode` proxy when all the links I can find in the source work when I recreate them under the `/rnode` link and try them manually.

**Comment by griznog** [comment]
Possible clue, in the chrome devtools for a failed connection I see this link failed to load with a 404:

```
<script type="text/javascript" src="/nxplayer/js/deviceDetection.js"></script>
```

However, if I then add `/nxplayer/js/deviceDetection.js` to the `/rnode` URL, the script loads fine for me, like all the other resources. It seems like the recommended apache config having 

```
ProxyPass "/nxplayer"  "https://192.168.3.201:4443/nxplayer"
ProxyPassReverse "/nxplayer"  "https://192.168.3.201:4443/nxplayer"
```

actually matters? But again, I don't know how to have the `/rnode` chain of proxies do the equivalent of that.

**Comment by johrstrom** [comment]
OK then you may need #2311 which we haven't implemented yet.


> ProxyPass "/nxplayer"  "https://192.168.3.201:4443/nxplayer"
> ProxyPassReverse "/nxplayer"  "https://192.168.3.201:4443/nxplayer"

The problem with adding something like this is that that origin (the ip there) is ephemeral.  It's the host of your job at that time - a job that will end sometime, so you'd have to somehow update apache when the job starts and stops.

If that wasn't enough, that's for _your_ session - what about others?  What do we do when you need a 2nd instance for a 2nd user?

**Comment by griznog** [comment]
There's an underlying issue that complicates this in that I am ignorant of what is going on behind the curtain when I click the `/rnode/...`  URL in a client browser. So when I say I don't know how to integrate those apache directives into OnDemand I don't mean literally move them into the portal config, I mean convince whatever magic is happening behind that `/rnode/...` URL to do the Right Thing(tm) which would be the equivalent of having a simple Apache reverse proxy using these static directives. 

https://github.com/OSC/ondemand/issues/2311 does look like what I want, in addition to wanting to put NoMachine behind OnDemand I also have on the to-do list Cryosparc and an abandoned entry for LabelStudio after we gave up trying to get it to work as an OnDemand app. So having that issue make it into OnDemand would be really helpful for us.

**Comment by griznog** [comment]
Actually I'll close this issue and just follow #2311 as it'll (I think) address this problem. In the meantime we can use some simple instructions to tunnel to NoMachine in `view.html.erb` instead of providing links to the webplayer. Which IMO is superior anyway as the native NoMachine client works a lot better for me than the webplayer.

**Comment by johrstrom** [comment]
You should also follow #3179 as I believe you'll need it as well (at least for NoMachine).
