### ISSUE TITLE
Feature request, job cancellation

### ISSUE THREAD

**Issue by snowbird294** [OSC/ondemand#3189]
Hi all, good talk at SC. Following up with my request from there. One of the things I do as an admin is to submit lots and lots of test submissions with different parameters for different applications. When those submissions don't work, the card gets saved for a few days. This works great. When those submissions do work, I usually don't want them to run the maximum time I've alloted, but I do need to retain the parameters I used for reference. The only way to stop these from the interactive jobs page is to delete them. Ideally, I would like a second button next to delete named "cancel" that issues a command like "scancel JOBID", and then retains the card and submission forms, so that I can reference them.

This feature would also be valuable for some of our users who host workshops in userspace, and do a similar process of submitting a handful of jobs, each slightly different, and then being able to save the card and files of a successful job after revoking the allocation.

Yes, users could just navigate to the shell and issue the appropriate job revoke command, and then OOD shows the card because an error happened, but a button that does a job revoke would be much appreciated. I believe most of this feature already exists in the delete button revoke allocations method, I just occasionally need the submission forms and card to stick around.

**Comment by johrstrom** [comment]
Is this what you're looking for? It's in 3.0. 

https://osc.github.io/ood-documentation/latest/customizations.html?highlight=cancel#cancel-interactive-sessions

**Comment by snowbird294** [comment]
> Is this what you're looking for? It's in 3.0.
> 
> https://osc.github.io/ood-documentation/latest/customizations.html?highlight=cancel#cancel-interactive-sessions

Yep. Would you believe we are in the planning stage for upgrading from versions just before 3, and we hadn't finished reading through the full docs?

Thanks much yall
