### ISSUE TITLE
Support SLURM federations

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand#32]
https://slurm.schedmd.com/federation.html

This may have implications for how command line tools are used.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737624320899) by [Unito](https://www.unito.io)

**Comment by MorganRodgers** [comment]
@treydock to help us prioritize this do we know of any sites that are using this feature? Or do we expect that if OSC moves to Slurm that we may use it?

**Comment by treydock** [comment]
I do not know of sites using it.  OSC might use it but not right away I would think.  If the 2020 system is SLURM it wouldn't be until the 2022 system that would be possible to have federation but not even sure we would then.  I think this was in response to Henry Neeman email thread where I proposed a solution of using SLURM federations for one of their problems they were trying to solve.

**Comment by johrstrom** [comment]
What's the status of this ticket now? Do we have Slurm federation?

**Comment by treydock** [comment]
I'm inclined to say we close this and can re-open if the community has a need for OnDemand to support federated Slurm jobs.  OSC does not use federated jobs.  The logic to support wouldn't be too terribly hard but we currently have no way to test the changes at OSC.  My read of the docs is the `--clusters` flag would have to accept a list of clusters and maybe support the `--clusters-constraint` flag though the main thing to support is `--clusters` having multiple values.  The rest of the support is handled by site administrators outside what OnDemand can handle.

**Comment by johrstrom** [comment]
OK great, I'll close and we can reopen if we find a site that needs it and either can patch (i'm guessing ood_core?) or give us access for development.
