### ISSUE TITLE
vnc options for quality and compression are hard coded

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3218]
These default values appear to be hard-coded. This means centers running GUI applications have no way to set these defaults.

https://github.com/OSC/ondemand/blob/251f5b8f1bf0239cc2d5173619851e2426eb5a1f/apps/dashboard/app/views/batch_connect/sessions/connections/_novnc.html.erb#L9
and
https://github.com/OSC/ondemand/blob/251f5b8f1bf0239cc2d5173619851e2426eb5a1f/apps/dashboard/app/views/batch_connect/sessions/connections/_novnc.html.erb#L12

**Comment by jose-d** [comment]
ah, this would be amazing to fix.
Often our users forget to set the "max" at the first login, and then they're negatively surprised how sub-optimal the picture is looking.

**Comment by johrstrom** [comment]
> Often our users forget to set the "max" at the first login, and then they're negatively surprised how sub-optimal the picture is looking.

They can change the settings and reconnect without restarting the job. These aren't static values after the job has launched, they can be changed after the fact.
