### ISSUE TITLE
Files searches over all text

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3219]
I'm using the file browser trying to navigate to my `Downloads` directory. Filling in the text search with `download` returns all results in my `$HOME` instead of my `Download` directory.

Why? The datatable's search must be searching over _all text_ in the table including the `download` buttons, so every row has is a result because every row has a download button 🤦‍♂️ .

**Comment by HazelGrant** [comment]
Are you still able to reproduce this? I am not - either locally or in test.

**Comment by johrstrom** [comment]
> Are you still able to reproduce this? I am not - either locally or in test.

Yea - it's on any directory. Try to filter the table by using the string `download` and nothing gets filtered.

**Comment by HazelGrant** [comment]
Oh! 🤦 It does filter for 'downloads' but not 'download,' that's where I was confused.
