### ISSUE TITLE
Favicon with dashboard

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand#322]
I have noticed the OSC favicon is not used with the dashboard but is used with other apps.

~~Also @MorganRodgers noticed issues with font awesome in development apps.~~

**Comment by MorganRodgers** [comment]
After additional investigation the FontAwesome issues were specific to me.

**Comment by ericfranz** [comment]
Cannot reproduce.

**Comment by MorganRodgers** [comment]
@ericfranz you see the favicon?
