### ISSUE TITLE
ood-portal-generator: add option to skip httpd logging directives in the VirtualHost section

### ISSUE THREAD

**Issue by CSC-swesters** [OSC/ondemand#3235]
The current implementation allows specifying `accesslog` and `errorlog` file paths in the `ood_portal.yml`. If these are left undefined, the ood-portal-generator will currently automatically generate file names for them, and fill in the template, as can be seen here: https://github.com/OSC/ondemand/blob/75c3c72f99ab5a880c08a9b2e02b781cb0b5dd67/ood-portal-generator/templates/ood-portal.conf.erb#L80-L86

If a site wants to use httpd's global "server logs", as described [in the documentation](https://httpd.apache.org/docs/2.4/logs.html), one would need the VirtualHost to not have any `CustomLog` or `ErrorLog` directives at all.

> If `CustomLog` or `ErrorLog` directives are placed inside a `<VirtualHost>` section, all requests or errors for that virtual host will be logged only to the specified file. Any virtual host which does not have logging directives will still have its requests sent to the main server logs.

This could be solved by adding a new option, e.g., `skip_virtualhost_logging: true`, which would completely leave out the lines of the template `ood-portal.conf.erb` that I linked above. I.e., wrap the whole thing in an if clause:

```erb
<%- if @skip_virtualhost_logging -%>
# skip_virtualhost_logging was true, no logging directives were generated.
<%- else -%>
  ErrorLog  "<%= @errorlog %>"
  <%- if @logformat -%>
  LogFormat <%= @logformat %>
  TransferLog "<%= @accesslog %>"
  <%- else -%>
  CustomLog "<%= @accesslog %>" combined
  <%- end -%>
<%- end -%>
```

**Comment by CSC-swesters** [comment]
I'm not certain that I follow your idea 100%. Do you mean that you would add some magic here: 
https://github.com/OSC/ondemand/blob/75c3c72f99ab5a880c08a9b2e02b781cb0b5dd67/ood-portal-generator/lib/ood_portal_generator/view.rb#L125-L131

which would handle a "false" string value of `accesslog`, `errorlog`, and leave them out of the final template?

In my opinion, that would be confusing, since magically blending file paths and booleans into the same configuration option isn't really what I'd personally expect.

**Comment by johrstrom** [comment]
> In my opinion, that would be confusing, since magically blending file paths and booleans into the same configuration option isn't really what I'd personally expect.

OK! And yes, you seem to understand what I'd meant.  Well, I agree with the feature in principle at least. The key phrase here is `what <someone would> personally expect`. I guess I kneejerk reacted to more configs, but really it is all about what the person doing the configuration would _expect_.

**Comment by CSC-swesters** [comment]
Okay, I guessed correctly. Well others are of course able to chime in now. My own thinking is that if a config parameter is expected to be a file path, it should not take on "magic" values which do something else.

I thought that adding a new parameter to completely skip these logging directives would make sense, as long as the defaults stay the same. In this case `skip_virtualhost_logging` would be `false` by default.

Another interesting approach would be to add the ability to remove the magic `log_filename` defaults, and actually use whatever strings are passed to `accesslog` and `errorlog`. If they are empty, or undefined, nothing is added into the configuration.

This would also enable logging into a syslog socket via this type of configurations for example:
```
CustomLog "| /usr/bin/logger -u /ood-log/log-socket -tondemand_httpd -plocal6.notice" combined
ErrorLog "| /usr/bin/logger -u /ood-log/log-socket -tondemand_httpd -plocal6.error"
```

This is something we aim to achieve, but we thought it might warrant its own issue. Being able to skip VirtualHost logging is enough for the moment, so that we can use global log settings outside of OOD's configurations.

**Comment by johrstrom** [comment]
>  If they are empty, or undefined, nothing is added into the configuration.

Yea defaults are harder to change. I'm not a hard no on a new config, but I'm a pretty hard no on changing defaults that _just work_. Again, circling back to user expectations, you'd expect a default base install to _just work_ (as best it can anyhow).

A new config option could be our best bet, which is fine if it meets user expectations.

> This is something we aim to achieve, but we thought it might warrant its own issue. 

Feel free to open as many tickets as you like!

**Comment by CSC-swesters** [comment]
> > If they are empty, or undefined, nothing is added into the configuration.
> 
> Yea defaults are harder to change. I'm not a hard no on a new config, but I'm a pretty hard no on changing defaults that _just work_. Again, circling back to user expectations, you'd expect a default base install to _just work_ (as best it can anyhow).
> 
> A new config option could be our best bet, which is fine if it meets user expectations.

You're right, we should not change the defaults. Perhaps we could add an option which would allow changing the behavior instead?

For example an option like `use_literal_log_names` which would be `false` by default, but if set to `true`, the template would straight up use whatever is in the `accesslog` and `errorlog` parameters. What happens currently, is that the `log_filename` function forces the value into being an absolute file path, so it's impossible to achieve the log piping I described above.

> > This is something we aim to achieve, but we thought it might warrant its own issue.
> 
> Feel free to open as many tickets as you like!

I will do that, it's a separate feature from this one, even if we started discussing it here already.
