### ISSUE TITLE
ood-portal-generator: add option to insert custom configuration lines

### ISSUE THREAD

**Issue by CSC-swesters** [OSC/ondemand#3240]
As briefly discussed in #3235 already, the ood-portal-generator has a function called `log_filename`, which currently will force the strings given in the `accesslog` and `errorlog` parameters to become absolute paths. If left empty, a default path name will be generated based on the host name.

This behavior is problematic in cases where one would like to pipe the logs (see [httpd documentation](https://httpd.apache.org/docs/2.4/logs.html#piped)) into `/usr/bin/logger` and send it into a syslog socket, for example. That configuration would look like this, for example:

```
CustomLog "| /usr/bin/logger -u /ood-log/log-socket -tondemand_httpd -plocal6.notice" combined
ErrorLog "| /usr/bin/logger -u /ood-log/log-socket -tondemand_httpd -plocal6.error"
```

I was previously going to propose that we should allow any custom strings to be passed through `accesslog` and `errorlog`, but it would make even more sense, and be much more useful to add an option for admins to add any configurations they like.

There are a few tricks for doing this already, but it doesn't seem to be intended for *any* options. For example, the `oidc_settings` array can be used to inject things into the `<VirtualHost>` scope (albeit with some added challenge due to sorting).
https://github.com/OSC/ondemand/blob/c359f7cde0446907a353f58486d0eef2dea8b9de/ood-portal-generator/templates/ood-portal.conf.erb#L138-L140

Also the `auth` options will be inserted into each `<Location>` tag:

https://github.com/OSC/ondemand/blob/c359f7cde0446907a353f58486d0eef2dea8b9de/ood-portal-generator/templates/ood-portal.conf.erb#L217-L220

To be clear, it's not an issue that these variables allow custom configurations to be inserted. However, it would make sense to create an option which explicitly invites admins who wish to add or modify certain configurations to insert their own configuration options. Enable power users to do their things without using a "workaround", so to speak.

I envision something like this:

```yml
# ood_portal.yml
---
...
site_specific_vhost_configs:
  - 'CustomLog '"| /usr/bin/logger -u /ood-log/log-socket -tondemand_httpd -plocal6.notice" combined'
  - 'ErrorLog "| /usr/bin/logger -u /ood-log/log-socket -tondemand_httpd -plocal6.error"'
  ...

...
```

And then the template would have a similar for-each loop that inserts the configurations, without sorting. Note that I intentionally used an array of strings in the YAML, instead of the hash type, which does not make any guarantees for ordering, if I'm not mistaken.

Except the main `<VirtualHost>` scope, there are also the following scopes which could have these wildcard configurations:
- The port 80 VirtualHost scope
- The various Directory scopes
  ```
  <Directory "<%= @public_root %>">
  <Directory "<%= @public_root %>/maintenance">
  <Directory "<%= @oidc_discover_root %>">
  <Directory "<%= @register_root %>">
  ```
- The various Location scopes
  ```
  <Location "<%= @pun_uri %>">
  <Location "<%= @nginx_uri %>">
  <Location "<%= @oidc_uri %>">
  ```
- The various LocationMatch scopes
  ```
  <LocationMatch "^<%= @node_uri %>/(?<host><%= @host_regex %>)/(?<port>\d+)">
  <LocationMatch "^<%= @rnode_uri %>/(?<host><%= @host_regex || "[^/]+" %>)/(?<port>\d+)(?<uri>/.*|)">
  ```

Ideally, there would be a possibility to add custom configurations into all of these. Initially, the global scope would be most important, so that the logging settings could be overridden, for example. In combination with a fix for #3235, that is.

Let me know what you think.

**Comment by CSC-swesters** [comment]
Good catch. Indeed, that seems to be the same as what I'm proposing :+1:

**Comment by simonLeary42** [comment]
In this thread, I think I was told that the SSL section also serves as a general purpose "add your own stuff here", but I could be misunderstanding.

https://discourse.openondemand.org/t/how-to-insert-an-alias-into-apache-ood-portal-conf/2259/2

**Comment by johrstrom** [comment]
> In this thread, I think I was told that the SSL section also serves as a general purpose "add your own stuff here", but I could be misunderstanding.

Yes you can, but it's kinda hacky (actually very hacky). Plus it's vhost wide #708 also describes a facility for adding things to the locations in `custom_directives_locations`.
