### ISSUE TITLE
Retain job name after job finishes

### ISSUE THREAD

**Issue by multimeric** [OSC/ondemand#3338]
I had a request from a user of our OnDemand deployment to add the job name to the completed sessions on the sessions page. The reason for this is that each completed session has a "relaunch" button, but without the job name it's not clear which job you actually want to relaunch.

For example, how can I tell these jobs apart without manually looking up the job names by ID?
![Screen Shot 2024-02-06 at 5 15 18 pm](https://github.com/OSC/ondemand/assets/5019367/51360d88-9110-4fa4-879e-fb97f5bbaa98)

**Comment by johrstrom** [comment]
The job name is the same for all those jobs. If you look in sacct they're all something like `ondemand/sys/rstudio`.

I think what you're looking for is this: Adding for example, the number of cores to the job's card, so you can differentiate them.

https://osc.github.io/ood-documentation/latest/how-tos/app-development/interactive/form.html?highlight=display#displaying-form-items-in-the-session-card

**Comment by multimeric** [comment]
Ah yes that's what it is. So I guess I'm rephrasing this issue to "Display the `display: true` form items in a *completed* job card".

**Comment by johrstrom** [comment]
That said - I don't actually know if they show in completed stage (docs only show running stage), so let me know if they don't.

**Comment by multimeric** [comment]
That's the issue. I don't believe that any of the `display: true` form items do show in a completed job card.

**Comment by abujeda** [comment]
I believe that the `display: true` attributes show on the completed sessions. Account being the one I added:

<img width="700" alt="Screenshot 2024-02-06 at 14 03 19" src="https://github.com/OSC/ondemand/assets/17336210/d16146e4-39e4-40ad-ab24-6ec41d0faf3e">

**Comment by multimeric** [comment]
Thanks. I'll have to dig into the specifics behind why it's not showing for us.

**Comment by multimeric** [comment]
Okay so in our app it seems we display the `sess_name` ruby variable in our `view.html.erb`. I guess this disappears once the job finishes because `view.html` isn't used at all at that point (`completed.html` will be used instead? https://github.com/OSC/ondemand/pull/3269). So I think this is a problem at my end with how we're handling this.

**Comment by johrstrom** [comment]
Is this an ongoing issue? I can't tell if you've resolved the request or not.
