### ISSUE TITLE
Content type for files in the files app

### ISSUE THREAD

**Issue by multimeric** [OSC/ondemand#3339]
If I request an HTML page on the files browser, for example by hitting `/pun/sys/dashboard/files/fs//home/users/allstaff/milton.m/ResidBenchmark/resid.html` in my browser, it gets served to me without a content type, and consequently it's rendered as plaintext in my browser. However, being an HTML file I was hoping my browser would render it for me.

I checked the headers for this request and they are as follows:
```
HTTP/1.1 304 Not Modified
Date: Tue, 06 Feb 2024 06:23:42 GMT
Server: nginx
Connection: Keep-Alive
Keep-Alive: timeout=5, max=100
ETag: "65604587-a90d"
Cache-Control: private
Set-Cookie: mod_auth_openidc_session=25932fe5-309f-433e-87fd-beec309fe06c; Path=/; Secure; HttpOnly; SameSite=None
```

Notably, there is no `Content-Type: text/html; charset=utf-8` header or indeed no `Content-Type` header at all. Was this a deliberate decision to not set content types, or would it be possible to add them based on the file extension?

**Comment by johrstrom** [comment]
I think this is a duplicate of #1619 - we don't show HTML files because we don't have a strong enough content security policy to block potentially malicious files.

**Comment by multimeric** [comment]
Yep, definitely a duplicate thanks.
