### ISSUE TITLE
nav_bar subcategory order should be alphabetical when not specified

### ISSUE THREAD

**Issue by HazelGrant** [OSC/ondemand#3343]
See: https://discourse.openondemand.org/t/alphabetical-order-of-interactive-apps-subcategories/3249/1

Steps to reproduce:
- On test, you can see that the default order of categories and sub-categories are alphabetical
- Update your config to include:

```
nav_bar:
  - interactive apps
```

Refresh your page, and the listed sub-categories of interactive apps are no longer alphabetical.

Expected behavior: Listed sub-categories should be alphabetical even when nav_bar is not default

**Comment by mcuma** [comment]
Thanks for looking into this. While at it, would it be possible to think of some customization of the order of the sub-categories in the Interactive Apps menu?

**Comment by johrstrom** [comment]
> While at it, would it be possible to think of some customization of the order of the sub-categories in the Interactive Apps menu?

This is already possible if you were to more fully define the menu item.

https://osc.github.io/ood-documentation/latest/customizations.html?#menus-based-on-applications

**Comment by abujeda** [comment]
This is a fix for the subcategory order: https://github.com/OSC/ondemand/pull/3344
