### ISSUE TITLE
Address GLS authentication issue so we can support third party apps

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#336]
We need to either contribute back to the Passenger project for https://github.com/phusion/passenger/issues/2207 or find a work around. GLS starts apps on open ports instead of IPC sockets. This means anyone on the web node can make an unauthenticated request to the GLS app.

One work around would be some type of container for the PUN and its apps that ensures "ingress TCP requests" come only through the PUN.

With proper GLS support in OnDemand we could run apps on the web node that are not in Ruby, Python, or Node such as WebMO (PHP).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737519845481) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
Once GLS authentication issue is addressed, GLS support can be added to in this manner. https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_app_start_command needs to be set in the app config. So app configs ideally will be auto-generated on every PUN restart, instead of at 1 time.

We could invent a convention, like if the app has `bin/passenger_app_start` that is executable then it is executed with a single argument `$PORT` i.e. `passenger_app_start_command "/path/to/approot/bin/passenger_app_start $PORT"`.

**Comment by ericfranz** [comment]
Actually correction, `bin/passenger_app_start` would accept 2 arguments: the port and the base uri of the app. Below is a summary of an experiment I did before SC that explains why we need the port and the base uri (i.e. PASSENGER_BASE_URL).


I got Hugo working to serve up a website and dynamically rebuild when files were edited. These are the steps I took:

1. create a hugo site at ~/ondemand/dev/quickstart, add a theme, and a post, but don't build the content (so hugo server needs to build on request)
2. edit /var/lib/ondemand-nginx/config/apps/dev/efranz/quickstart.conf with following line:

        # Configure as GLS
        passenger_app_start_command "/users/PZS0562/efranz/bin/hugo server -D --disableFastRender -p $PORT -b 'https://ondemand-dev.osc.edu/pun/dev/quickstart'";
3. Restart web server and access /pun/dev/quickstart

Some issues include:

- link going back to the front page includes port (i.e. https://ondemand-dev.osc.edu:5000/pun/dev/quickstart/) which fails of course
- obviously you can just curl the app which handles unauthenticated requests on the web node i.e.

```
curl localhost:5000/pun/dev/quickstart/
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>My New Hugo Site </title>
```

**Comment by matt257** [comment]
reviewed
