### ISSUE TITLE
project manager respond to README

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3377]
The idea for this ticket is fairly straight forward. If the project has a `README.txt` or `README.md` in the root of the project, we should display that.

The motivation being something like this: The project (template most likely) is for a semester or perhaps a joint research study. In any case, the README has information about what to do, how to do it and so on.

The UI for the project manager is in flux, so I'm not sure where we could display it on the `projects#show` page, but that can be sorted out as we go.

**Comment by ashton22305** [comment]
Fixed in #3678
