### ISSUE TITLE
Interactive Sessions - Favorites

### ISSUE THREAD

**Issue by abujeda** [OSC/ondemand#3379]
With the recent changes to add a "re-launch" button to the interactive session cards and the new feature proposal to add an "edit and launch" button (#3358), it might be useful for users to highlight some of the interactive sessions into a favorites list.

Sessions in this list will not be deleted and a new view can be created to only show these sessions.
Screenshots for a prototype below

<img width="650" alt="Screenshot 2024-02-27 at 15 57 20" src="https://github.com/OSC/ondemand/assets/17336210/1883b5e3-4cc6-4eda-8c1b-c9aff5fc718e">

<img width="650" alt="Screenshot 2024-02-27 at 15 57 33" src="https://github.com/OSC/ondemand/assets/17336210/d866d6ec-aabc-4d3f-a9cb-311f656154eb">

**Comment by abujeda** [comment]
Yes, similar to the saved settings, but from the session card side.

**Comment by johrstrom** [comment]
> Yes, similar to the saved settings, but from the session card side.

OK so maybe we can use the same language, instead of favorites it's saved settings?

**Comment by abujeda** [comment]
Something like this?
<img width="600" alt="Screenshot 2024-02-29 at 12 40 59" src="https://github.com/OSC/ondemand/assets/17336210/9ac2b247-a5b9-472a-a583-19d6ffc7807b">
<img width="600" alt="Screenshot 2024-02-29 at 12 41 06" src="https://github.com/OSC/ondemand/assets/17336210/e4a24df2-e29d-4d17-b40b-60e55dbc5027">
<img width="600" alt="Screenshot 2024-02-29 at 12 41 31" src="https://github.com/OSC/ondemand/assets/17336210/90fc6360-f055-46cd-9c1c-76a20798270c">

**Comment by johrstrom** [comment]
> Something like this?

Sure, I just don't want the underlying feature to be separate from what we already have. If we're looking at CRUD - we have a way to create and update these saved settings, but no real way to read or delete, which I think is what this provides?  If so, then yea I think that's what we'd want.

**Comment by abujeda** [comment]
Well, I think I misled you when I say that this feature was similar to the save settings.
The idea here was to "save" or "group" key session cards into a separate space called "favorites" or "saved sessions". This way, users could refer back to them to re-launch or to edit and launch (icons in the actual session card). All driven from the `Session` object and the list of sessions available. Saved sessions will not be automatically deleted.

I am not using the session to get the parameters used to launch it and save them into the `UserSettingsStore` as with `save_bc_template`.

For me it is similar as both ideas serve the same purpose: Allow the user to launch an app with previously used parameters, but the implementation is driven from session cards.

**Comment by johrstrom** [comment]
> For me it is similar as both ideas serve the same purpose: Allow the user to launch an app with previously used parameters, but the implementation is driven from session cards.

Yea I guess I would just say it's sort of untenable as a maintainer to maintain 2 similar features that do similar things but in different ways. Indeed even from the user's perspective - they may expect them to be the same thing. I think I would. I think I would be surprised if I found these to be two separate distinct features that didn't actually relate to each other.

**Comment by abujeda** [comment]
Let me review and see if I can combine with save settings.

**Comment by abujeda** [comment]
I am not sure now, after the analysis, that the original idea of "saving" sessions into "favorites" to keep them around for longer and not being deleted is a similar feature as `bc_saved_settings`. Even if the intention is for the user to be able to re-launch the session in the future.

**Comment by johrstrom** [comment]
> I am not able to merge the 2 ideas in the current form, even if they have a similar purpose.
The only idea that came to mind is to change the implementation of bc_saved_settings

I don't think we can change this now that we've released it. Why not work it the other way? have the session recognize if it's `from_saved_settings?`. I'm not against changing the underlying implementation - but now that the feature's released we do need to keep compatibility, which I think what you're describing breaks.

> I am not sure now, after the analysis, that the original idea of "saving" sessions into "favorites" to keep them around for longer and not being deleted is a similar feature as bc_saved_settings. 

It would be to the user. To the user it all falls under the same feature - I want to reuse these settings.  It would be very annoying to the user to find out to reuse _these_ settings I have to do X and to reuse _those_ settings I have to do Y.

**Comment by abujeda** [comment]
> Why not work it the other way? have the session recognize if it's from_saved_settings?

I did that initially, and added a new field to the session card to show the saved setting the session was created from (which I think it is useful). But after that, I wasn't able to add more functionality from the session side.
The new left hand menu to filter sessions that were created from a saved settings didn't seem to add value.

For saved settings, it feels more fitting to add improvements and new features to the interactive apps form.

**Comment by johrstrom** [comment]
OK, well I'm not sure where that leaves us then. I mean I do like this feature - but it just can't be different from a UX perspective, users just can't have 2 ways of doing 1 thing (what they think is 1 thing anyhow).

I would prioritize the UX as must do over any ugly business we as maintainers have to deal with, but the best would be something is maintainable.

**Comment by abujeda** [comment]
I will close this issue for now. Will have a re-think having `saved_settings` as the starting point and see what features come from that side.

**Comment by johrstrom** [comment]
Sorry if it's bad news! I can just hope you can see where I'm coming from, especially as it relates to UX. It just _feels_ like the same thing to a user.
