### ISSUE TITLE
Add job script suggestions to Workflow new_from_path

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand#339]
While this #310 is a good start the workflow is not all that I would expect as a user.

I would expect that when creating a new workflow from an existing directory I would be able to select my script there. We could add this to the `new_from_path` view by adding some JS to listen to the change event on `workflow[staging_template_dir]`, and then updating the script select options via AJAX.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737519180809) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as won't do as we're redoing the job composer, plus we'll have the smart attribute `auto_scripts` to handle this I think.
