### ISSUE TITLE
Glyphicons-halflings 404's

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand#342]
The Save button in the File Editor has a missing font icon because `ondemand-1.7.3-3/assets/bootstrap/glyphicons-halflings-regular-*` are 404-ing.

Impacts 1.7.3.

**Comment by treydock** [comment]
The URL looks incorrect:

https://ondemand-test.osc.edu/pun/sys/ondemand-1.7.3-3/assets/bootstrap/glyphicons-halflings-regular-fe185d11a49676890d47bb783312a0cda5a44c4039214094e7957b4c040ef11c.woff2

Shouldn't it be `pun/sys/file-editor/assets...`. If I replace `ondemand-1.7.3-3` with `file-editor` in URL then the asset is accessible.

**Comment by treydock** [comment]
Looking through files it looks like the applications CSS has `url("/pun/sys/ondemand-1.7.3-3/assets/...` which isn't right.
