### ISSUE TITLE
Job script suggestions should ignore dot files / directories

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand#346]
In the happy situation where OnDemand users are making use of version control the job script suggestions should not include `.git`, `.hg` or `.svn` directory contents.

![script-suggestions](https://user-images.githubusercontent.com/13316545/70653785-29445a80-1c23-11ea-9054-85e94504eefe.png)

**Comment by ericfranz** [comment]
We should probably omit all dot files/directories from the possible suggestions.
