### ISSUE TITLE
Add Linting / Static Analysis 

### ISSUE THREAD

**Issue by nealepetrillo** [OSC/ondemand#35]
Linting and static analysis of the code base could help spur adoption of OOD on risk averse organizations. Services such as https://scan.coverity.com/ can help improve quality by providing extensive feedback while also providing a way of assuring 3rd parties that the code is reasonably secure.

**Comment by achalker** [comment]
Neale:  Good suggestions.  We actually have gone through a TrustedCI audit (https://trustedci.org/) which did a pretty thorough analysis.  Unfortunately, we haven't figured out a good way to advertise the results of this.  Here's the executive summary they provided in their report.  Any suggestions on the best way to document this more publicly?

-Discovered several implementation issues (bugs) that could affect the proper operation
of Open OnDemand.
-No major issues were found in a comprehensive evaluation of the architecture and
critical resources in Open OnDemand, and analysis of potential code weaknesses in
critical components.
-Found a potential vulnerability, dormant based on current configuration and launch
settings.

**Comment by nealepetrillo** [comment]
Excellent! Do you think they'd give you permission to post a badge, maybe their logo, on the readme page? How about adding a security section to the RTD page that includes a link to the report? 

I know there are also a lot of organizations that are concerned with the DISA / NIST STIGS. Adding notes on any deviations on that security page would help but it'll probably be a significant amount of work.

**Comment by ericfranz** [comment]
@nealepetrillo good idea adding to RTD. Do you think if we added the link to the Security page in the "Release Notes" section that would be prominent enough? We are also adding a "Known Issues" page and we might put it there too.

<img width="1220" alt="screen 2019-05-31 at 5 28 09 PM" src="https://user-images.githubusercontent.com/512333/58735809-a025ae80-83c9-11e9-811d-fa043ccf68c1.png">

**Comment by nealepetrillo** [comment]
I think that'll be good enough!
