### ISSUE TITLE
Multiple path-selectors are slow

### ISSUE THREAD

**Issue by HazelGrant** [OSC/ondemand#3524]
Based on this Discourse topic: https://discourse.openondemand.org/t/slow-when-using-multiple-path-selectors/3431

I can reproduce this issue in Firefox on an M1 Mac. 

I'm adding this to the 3.1 milestone because I think it should be fixed before 4.0 if we plan on any further releases between now and then.

**Comment by HazelGrant** [comment]
My guess is this has something to do with the fact that `$('#loading_icon')` is referenced twice when two or more path selectors are present.

**Comment by moffatsadeghi** [comment]
Confirmed via changelog that this got into 4.0 actually
