### ISSUE TITLE
Make project size calculation optional

### ISSUE THREAD

**Issue by CSC-swesters** [OSC/ondemand#3530]
We noticed while trying out one of the nightly builds, that the `project.rb` will try to calculate the size of the project directory using `du -s`

https://github.com/OSC/ondemand/blob/1a35d7eb54b975d7577c6d566ecfca678103bcbe/apps/dashboard/app/models/project.rb#L188-L193 

This should be configurable, since it would put unnecessary load on the file system, and delay the response to the user unnecessarily, if the file system where the project directory resides is under heavy load, or the project directory is very large.

I suggest adding a boolean configuration item, e.g., `calculate_project_size: false` (by default, is my suggestion), and then sites can enable it at will, by changing the configuration.

**Comment by johrstrom** [comment]
OK.  Though, it is done through an ajax callback, so it's asynchronous to the page load, so it doesn't affect the timing of the page load.

That said - I'm happy to provide a config given the strain it puts on the filesystem.

**Comment by CSC-swesters** [comment]
I missed the AJAX part, sorry about that. Either way, we would appreciate a way to disable it :+1: Thanks!

**Comment by johrstrom** [comment]
>  sorry about that

No issues! Thanks for the ticket. Yes I suspsect with larger projects (with may GB/TB of input/output data) this will be troublesome.

**Comment by abujeda** [comment]
possible solution here:
https://github.com/OSC/ondemand/pull/3531
