### ISSUE TITLE
kubernetes test workflow broken

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3532]
It appears the kubernetes tests workflow is broken. This ticket is to fix it. There appears to be some issue with generating secrets. 

Here's the output from a recent job's `get ondemand token` step of the workflow.

```
Run TOKEN_NAME=$(kubectl describe serviceaccount ondemand -n ondemand | grep Tokens | awk '{ print $2 }')
  TOKEN_NAME=$(kubectl describe serviceaccount ondemand -n ondemand | grep Tokens | awk '{ print $2 }')
  TOKEN=$(kubectl describe secret $TOKEN_NAME -n ondemand | grep "token:" | awk '{ print $2 }')
  echo "ondemand=${TOKEN}" >> $GITHUB_OUTPUT
  shell: /usr/bin/bash -e {0}
  env:
    KIND_REGISTRY: kind-registry:5000
Error from server (NotFound): secrets "<none>" not found
```

**Comment by treydock** [comment]
I don't think service accounts by default generate tokens anymore.  That came up a few weeks/months ago.  We don't appear to pin our Kind cluster to specific version of Kubernetes so likely Kubernetes got updated to version that has the changed behavior.

https://github.com/OSC/ondemand/blob/e67de5b83708462f108ee340478c1ffaa6988ccc/.github/workflows/tests.yml#L95-L96

**Comment by treydock** [comment]
https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#manual-secret-management-for-serviceaccounts

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-an-api-token-for-a-serviceaccount

And seems you only figured that out in https://github.com/OSC/ondemand/pull/3533 lol
