### ISSUE TITLE
Shibboleth authentication only works with Require valid-user

### ISSUE THREAD

**Issue by btsherid** [OSC/ondemand#3542]
Hi,

I am testing Shibboleth authentication for our OnDemand set up. It works perfectly if I have Require valid-user in the ood_portal.yml file. However, I would like to change that to Require user <user> <user> to only allow a list of username. Everything I've tried gives me an Unauthorized page. The Shibboleth authentication still works but after authenticating with Shibboleth, OnDemand give me the Unauthorized message. Let me know what I should try to get this working.

Thank You,
Brendan Sheridan

**Comment by btsherid** [comment]
OK, I was able to fix this. Even though I have the user_map_cmd configured to do the regex, I still need to put <user>@<domain> in the Require shib-user line. This is not a big deal and I can make that change.

**Comment by johrstrom** [comment]
Thanks for the update - I also found this documentation on the Shibboleth wiki: https://shibboleth.atlassian.net/wiki/spaces/SP3/pages/2065335062/Apache#Authorization
