### ISSUE TITLE
visual updates for the system status page

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3555]
The current system status panel for a cluster is given below. 

![image](https://github.com/OSC/ondemand/assets/4874123/d1c32e08-b185-4cc4-8278-d5a995cb9d56)

Researchers will look at this page and ask one and only one question - `If I submit a job with N resources - will it run or will it get queued?`

This ticket is to update it visually around a few things to help answer that question.
* Remove total counts. I don't care how many nodes/cpus/gpus there are in total. All I care about is how many are free. %s may look cool - but again, the number of free resources is all I really care about
* I don't think jobs running & queued should be percentages. Probably better to just say N jobs queued and M jobs running. percentages in this context don't make a lot of sense

That's all I can think of off the top of my head - I'm sure I'm missing something else.

**Comment by ashton22305** [comment]
fixed in #3561
