### ISSUE TITLE
Update buttons for bootstrap 5

### ISSUE THREAD

**Issue by ashton22305** [OSC/ondemand#3576]
Child of #3461 

This ticket is to ensure that buttons work and are correctly formatted when upgrading to Bootstrap 5

**Comment by ashton22305** [comment]
`btn-danger` buttons seem to show black text because the contrast calculations changed in Bootstrap 5 to ensure accessibility, causing the contrast between red and white to become too low.
![image](https://github.com/OSC/ondemand/assets/149011429/fbbd7346-0598-4bb7-b743-d49dde53379a)
Our danger color doesn't match the default in bootstrap 5 - changing it to the default seems to work
![image](https://github.com/OSC/ondemand/assets/149011429/d1ea1817-8a11-43b7-b306-f1e476f30fb2)
Should we change it? I'm not sure how/if we even should keep the current color.

**Comment by johrstrom** [comment]
> changing it to the default seems to work

You mean changing it back to the default makes the buttons have white text? If that's the case - then yes I'd say let's use the default with white text if that's an option.
