### ISSUE TITLE
Can't install on RHEL9

### ISSUE THREAD

**Issue by st1553** [OSC/ondemand#3584]
Running this command from the installation docs:
sudo dnf install https://yum.osc.edu/ondemand/3.1/ondemand-release-web-3.1-1.el9.noarch.rpm

Gives the following error:
Last metadata expiration check: 0:00:15 ago on Sun 02 Jun 2024 09:42:34 PM EDT
**[MIRROR] ondemand-release-web-3.1.1.el9.noarch.rpm: Status code: 404 for https://yum.osc.edu/ondemand/3.1/ondemand-release-web-3.1.1.el9.noarch.rpm (IP: 192.148.247.165)**

Please advise. Thank you

**Comment by johrstrom** [comment]
No problem at all! Just open another ticket here or on discourse if you run into more issues!
