### ISSUE TITLE
Batch connect sessions card headers not displaying status color

### ISSUE THREAD

**Issue by ashton22305** [OSC/ondemand#3597]
Child of #3461 
After upgrading to Bootstrap 5, card headers no longer display the color associated with the status of the session.

Bootsrap 4:
![image](https://github.com/OSC/ondemand/assets/149011429/68f9724f-ff9c-4264-9fcd-30b115410fc7)

Bootstrap 5:
![image](https://github.com/OSC/ondemand/assets/149011429/534845fe-4cc8-4c3a-9291-893a0cb3058d)

**Comment by abujeda** [comment]
Found a possible solution, but requires some custom CSS as Bootstrap5 alerts seem to add a border that creates a double border in the card.

<img width="700" alt="Screenshot 2024-06-10 at 18 30 20" src="https://github.com/OSC/ondemand/assets/17336210/6c2309eb-7ef6-4fda-ae49-615aca71c261">
