### ISSUE TITLE
batch_connect_sessions and authentication timeout

### ISSUE THREAD

**Issue by mattmix** [OSC/ondemand#3605]
When authentication times out for a user, requests are redirected to the auth server so they can login again. However, if they are sitting on the `/pun/sys/dashboard/batch_connect/sessions` page, the background polling for session updates will hit the redirect and fail in a way that gives no indication to the user that they aren't getting updates without pulling up the browser's console. This also causes noise on the authentication server since the polling function will follow the redirect on each poll and, at least on ours, fail also due to a CORS error.

I think it would be better if a failure to retrieve session information caused the whole page to be reloaded. That way, if the user's session has timed out they will be properly redirected to the login page. 

The code that does the session polling was changed since 3.1's release, but I think the result is still the same regarding this issue: https://github.com/OSC/ondemand/commit/fdf9920d0ab733ff054b764ccd8c2ef66ed5a439

**Comment by johrstrom** [comment]
Yes I've noticed this too in our apache logs. We should not keep pinging the server if we get 403 or similar errors. I think this often happens to me when I leave the browser open and let my machine fall asleep.

**Comment by johrstrom** [comment]
I've got a fix for this that'll be in 4.0. Note that it'll just stop querying when a failure occurs. But if/when one does it'll additionally create a div on the page that tells the user there's been an error.
