### ISSUE TITLE
suse/opensuse support

### ISSUE THREAD

**Issue by DetlevCM** [OSC/ondemand#3626]
Dear developers,

OpenOnDemand supports a number of Linux distributions - but lacks suse/opensuse support.

Suse and opensuse are rpm-based (like RedHat, CentOS, Rocky, etc.)

There used to be discussion around suse in an ansible role, but I'm not sure where that stands...
( https://discourse.openondemand.org/t/how-to-install-ood-on-suse12sp4/428 )
However other distributions gets a convenient package to use.

Is there and possibility of suse/opensuse support in the near future?

**Comment by johrstrom** [comment]
> Is there and possibility of suse/opensuse support in the near future?

This is being tracked here in this ticket, though I can't say when it will come.

https://github.com/OSC/ondemand-packaging/issues/243

**Comment by DetlevCM** [comment]
Thanks. -> I guess if there are any further discussions, it can be in the linked ticket.

I tried building OpenOnDemand from source (using a self-compiled ruby 3.3)  and setting $GEM_HOME...
-> Building was mainly fine, except for one unit test that fails (well, one can skip the unit tests...) - Then the shellcheck had some issues... (skip that too) and it seems happy...

Though with all the paths and variables I didn't have a way of test installing it - that failed because a user cannot write services and using sudo -E doesn't seem to pass required parameters for ruby... 

So I gave up for now...
