### ISSUE TITLE
Upgrade all use of Rails in OnDemand to 5.2.4.1

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#366]
https://weblog.rubyonrails.org/2019/12/18/Rails-5-2-4-1-has-been-released/

The way Rails upgrades work https://guides.rubyonrails.org/upgrading_ruby_on_rails.html is that you move up 1 minor version at a time (choosing the latest patch version of that minor version). Fix things as appropriate, make sure the tests run, etc. then commit the changes!

- [x] Upgrade Dashboard from Rails 5.2.3 to 5.2.4.1
- [x] Upgrade Job Composer from Rails 4.2.11 to 5.2.4.1
    - [x] 4.2.11 => 4.2.11.1
    - [x] [4.2.11.1 => 5.0.7.2](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0)
    - [x] [5.0.7.2 => 5.1.6.2](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-0-to-rails-5-1)
    - [x] [5.1.6.2 => 5.2.4.1](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-1-to-rails-5-2)
- [x] Upgrade Active Jobs from Rails 4.2.11 to 5.2.4.1
    - [x] 4.2.11 => 4.2.11.1
    - [x] [4.2.11.1 => 5.0.7.2](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0)
    - [x] [5.0.7.2 => 5.1.6.2](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-0-to-rails-5-1)
    - [x] [5.1.6.2 => 5.2.4.1](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-1-to-rails-5-2)

Don't forget `rails app:update` which is helpful when moving to all the new versions of Rails 5. So you update the Gemfile to the new rails version, gem install, run `rails app:update`, handle conflicts, handle any other changes you need to make manually by reviewing the upgrade procedure.

**Comment by MorganRodgers** [comment]
Upgrades to Job Composer are blocked by https://github.com/OSC/osc_machete_rails/issues/66.

**Comment by ericfranz** [comment]
Alternative to this is to inline all the osc_machete_rails code into job composer, then update that code to work well with Rails 5.

**Comment by MorganRodgers** [comment]
https://github.com/OSC/ondemand/pull/378 is ready for review/merge.

**Comment by johrstrom** [comment]
Upgrades to Job Composer are also blocked by [ood_appkit's need to upgrade](https://github.com/OSC/ood_appkit/issues/54).
