### ISSUE TITLE
render tables in motd markdown broken in 3.1

### ISSUE THREAD

**Issue by stdweird** [OSC/ondemand#3679]
With ondemand 2.0, we were able to render markdown tables in the motd.
After the upgrade to 3.1, this is now broken.

Quick glance at the ood_core configuration has `tables: true`, so not sure why this is not working.

On a side note: how can i run a ruby script using the whole ondemand gems setup, so i can test redcarpet directly?

**Comment by johrstrom** [comment]
I'll take a look at replicating. You may need to set `motd_render_html` here, though I don't know for sure without looking yet.

https://osc.github.io/ood-documentation/latest/reference/files/ondemand-d-ymls.html?highlight=motd_render_html



> On a side note: how can i run a ruby script using the whole ondemand gems setup, so i can test redcarpet directly?

You can source this file - `/opt/ood/ondemand/enable` and it'll set the appropriate environment variables.

**Comment by stdweird** [comment]
@johrstrom  thanks, this is indeed the issue.
perhaps a small warning/error in the logs that certain MOTD formatters are not working properly when the setting is false?

anyway, i'm closing this issue
