### ISSUE TITLE
JoyRide starting location is off to the bottom of the screen

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#368]
You have to scroll to see it. Go to the page and click Help:

![screen 2020-01-07 at 4 56 32 PM](https://user-images.githubusercontent.com/512333/71932838-b3260b80-316e-11ea-9b74-b983ce9f96ad.png)

**Comment by MorganRodgers** [comment]
Possibly relevant warning:

```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.
```

**Comment by ericfranz** [comment]
For reference: https://zurb.com/playground/jquery-joyride-feature-tour-plugin
