### ISSUE TITLE
Automatically updating apps from github on OOD

### ISSUE THREAD

**Issue by adameubanks** [OSC/ondemand#3731]
Hi all,

Currently, it seems the best way to update an app on Open OnDemand is to either change it in the dev environment, or delete it and then recreate it from the github repo with the updated code.

Could there be a way to simply "sync" from github to avoid this constant updating/deleting?

**Comment by johrstrom** [comment]
Automation tools like ansible or puppet I think are your best bet. With Puppet, we creat RPMs that we then update the puppet configuratons to.

Ansible has the ability to sync a github repository, though if it's a Passenger app you'd need another step to build the app.

https://github.com/OSC/ood-ansible?tab=readme-ov-file#ood_install_apps

**Comment by adameubanks** [comment]
Awesome, thank you.
