### ISSUE TITLE
Project Manager - Cannot save some fixed attributes in launcher

### ISSUE THREAD

**Issue by ashton22305** [OSC/ondemand#3743]
In the launchers#edit page, all attributes have an option to be fixed. The script and nodes attributes appear to be fixed, but do not persist when the launcher is saved. The environment variables attribute similarly can't be saved, but also doesn't appear to be in the page.

**Comment by johrstrom** [comment]
I think I'm finding that we add something to the controller like `auto_cores`, but we don't add `auto_cores_fixed`, so it never makes it past the controller.
