### ISSUE TITLE
Reduce size of icons for OSC's interactive apps (and any relevant images in OnDemand)

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#376]
https://www.smashingmagazine.com/2015/06/efficient-image-resizing-with-imagemagick/ has some ideas with ImageMagick which is available on our login nodes

The biggest offenders include:

- https://github.com/OSC/bc_osc_comsol/blob/master/icon.png
- https://github.com/OSC/bc_osc_abaqus/blob/master/icon.png
- https://github.com/OSC/bc_osc_qgis/blob/master/icon.png

But [all of the interactive apps](https://osc.github.io/ood-documentation/master/install-ihpc-apps.html#id2) could stand to have these fixed. In OnDemand, there are only a few places we display these icons:

1. In the dropdown menus: 14x14
2. In the app sharing dashboard and developer interface: 100x100px

So the minimum size required is 100x100 (not 400x400 or larger as some of these icons actually are).

**Comment by matthu017** [comment]
All the interactive app icons were resized to 100x100
I found a newer logo of ansys and replaced the picture.

https://github.com/OSC/bc_osc_abaqus/pull/9
https://github.com/OSC/bc_osc_ansys_workbench/pull/19
https://github.com/OSC/bc_osc_comsol/pull/7
https://github.com/OSC/bc_osc_matlab/pull/10
https://github.com/OSC/bc_osc_jupyter/pull/34
https://github.com/OSC/bc_osc_jupyter_spark/pull/8
https://github.com/OSC/bc_osc_paraview/pull/10
https://github.com/OSC/bc_osc_rstudio_server/pull/31
https://github.com/OSC/bc_osc_vmd/pull/2
https://github.com/OSC/bc_osc_qgis/pull/1
https://github.com/OSC/bc_osc_stata/pull/1

**Comment by ericfranz** [comment]
For reference, what ImageMagick command with what arguments did you use to do the resizing?

**Comment by matthu017** [comment]
ImageMagick was hard to figure out what I was cropping out and I was unable to add dead space to the .png files.
I used an online image editor to form the icon into square and add dead space. Then I used imagemagick's -thumbnail 100x100 to reduce both the pixel and file size.

**Comment by ericfranz** [comment]
Which online image editor?

What was the exact command you used with ImageMagick to generate the thumbnail size?

**Comment by matthu017** [comment]
https://pixlr.com/x/
This was used to convert the images to squares (496x496, 275x275, etc.)

convert -thumbnail 100x100 start.jpg final.jpg
-thumbnail was used instead of -resize to reduce the file size further (in some cases, file size increased using -resize). Alternatively, there are online websites that can do this as well.
