### ISSUE TITLE
Add "About this installation" page

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#379]
Add about page with:

1. table of installed apps and their version strings if available (if git repos, git information) that might be helpful to an admin
1. version of OnDemand and link to documentation
1. possibly cluster config information (including if there appear to be problems with a cluster config) or other helpful information about the configuration
1. basic metrics based on [quick analysis of per user log files](https://github.com/OSC/ood-usage-report/blob/9cd90ec12ba4ec811e2c499da5299ce8fa1090e7/app.rb#L29-L53) (if you have access, of course), and link to setting up more metrics, or directions on making these metrics available

Link to it under help -> about.

Needs design first!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737522084487) by [Unito](https://www.unito.io)

**Comment by msquee** [comment]
@ericfranz This feature was brought up in the survey results from the _SGCI UX analysis survey_. Just bringing this up so it's in our minds, I can come up with a design for this.
