### ISSUE TITLE
average time between release and rpm in the yum.osc.edu repo

### ISSUE THREAD

**Issue by stdweird** [OSC/ondemand#3849]
I am being a bit impatient perhaps, but the 3.1.8 release has not yet made its way to the yum.osc.edu repo? What is the normal delay between a release on github and rpms showing up?

**Comment by johrstrom** [comment]
> I am being a bit impatient perhaps, but the 3.1.8 release has not yet made its way to the yum.osc.edu repo? What is the normal delay between a release on github and rpms showing up?

About a week or so. We like to put it on OSC systems before releasing to the general public. 3.1.8 will not be realesed to the 3.1 repo because it has a pretty fatal bug in it, so that's why you're not seeing it. I'm working on getting that patched and deployed to OSC this week.

**Comment by stdweird** [comment]
@johrstrom i see that the 3.1.9 rpms are already there. thanks for all this work!
