### ISSUE TITLE
bc_clean_old_dirs also cleanup db files

### ISSUE THREAD

**Issue by stdweird** [OSC/ondemand#3860]
bc_clean_old_dirs now cleans up session output dirs that are certain age; but can it be extended to cleanup also files in the db dir, eg `~/ondemand/data/sys/dashboard/batch_connect/db` ? we have some users who have files there that are very very old, and reference clusters that are no longer around. afaik, these files are one per job; so shouldn't be older then max job age (but we are fine if they are cleaned eg together with the bc_clean_old_dirs logic

**Comment by stdweird** [comment]
or simply skip the db files if there is no matching configured cluster when trying to run job status commands for that session

**Comment by johrstrom** [comment]
These files do get cleaned up after so long (7 days after it's completed is the default). 

Maybe it's a case of backward comparability? Like we started to clean these files, but never cleaned the files from previous versions?

**Comment by stdweird** [comment]
@johrstrom that's possible. the old files i found were from our 2.0.X setup (and over 9 months old); but that means they were also not cleaned up by 2.0 (not sure when the cleanup was added). anyway, i will try to cleanup as much as possible; and will reopen this when i see files from 3.1 era not being cleaned up.

**Comment by johrstrom** [comment]
To be clear - here's the logic to delete them if they're old. I feel like it was added in 2.0, but would have to check to be sure.

https://github.com/OSC/ondemand/blob/de41471a188fedc76a5b90d7b8cdcfe8479965f5/apps/dashboard/app/models/batch_connect/session.rb#L157

It would seem that `modified_at` isn't available, so it's thinking that the cards are not in fact old enough to delete.

https://github.com/OSC/ondemand/blob/de41471a188fedc76a5b90d7b8cdcfe8479965f5/apps/dashboard/app/models/batch_connect/session.rb#L200-L206
