### ISSUE TITLE
Test OnDemand with Chromium Microsoft Edge

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#387]
https://support.microsoft.com/en-us/help/4501095/download-the-new-microsoft-edge-based-on-chromium

**Comment by matthu017** [comment]
Test shell access: cannot see emoji in shell by running command  `curl https://emojipedia.org/thumbs-up-sign/ | grep thumbs-up | tail -n 5`

**Comment by matthu017** [comment]
File explorer: Shows /var/log/httpd24

**Comment by ericfranz** [comment]
@matthu017 change that emoji test to just executing this command:

```
printf '\xF0\x9F\x91\x8D\n'
```

**Comment by matthu017** [comment]
![Abaqus_CAE](https://user-images.githubusercontent.com/56143351/78589773-bdf44900-780e-11ea-98fc-d32746eb4a17.PNG)
Although I think this is a licensing problem as it occurred on all different versions of Abaqus/CAE

**Comment by johrstrom** [comment]
I'm satisfied with the Edge support we have. A quick spot check showed it worked OK, plus I'm sure we'd have heard about it (we mostly Safari issues).
