### ISSUE TITLE
BC Desktop support for singularity

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#388]
[This discourse](https://discourse.osc.edu/t/need-some-help-with-custom-submission-and-custom-script-files-together-with-bc-desktop-app/680/4) topic came in where someone wanted to run a singularity image instead of say, xfce, in the bc_desktop application.

This ticket is to support that use case. 

I think the easiest way would be to add a `singularity.sh` to `apps/bc_desktop/template/desktops` and some way to specify the image and the command in the `form.yml` and these variables in turn show up in the shell script.

The topic creator wanted a way to override `script.sh.erb` (and instead use a sh file in `/etc/ood/config`). Of course we can discuss that option here, but I think that's a much larger change for the actual feature requested.

**Comment by novosirj** [comment]
I think my request is ultimately more useful to more people, as it seems to me there might be a lot more possibilities for differences you'd want to have in the desktop launch script, and it makes some of that stuff a little more modular, extensible, but I'm no expert on the existing codebase and I may not understand the ramifications.

That said, if it's a lot more work and this other method can be used to satisfy this request at least in the meantime, I think that's a win all around. My primary motivation was to have something that I don't have to maintain myself when the changes are so minimal/could be handled by overlaying a couple of the files if that were supported.

Is there something I can do to help somehow, including passing on how we do this today?

**Comment by johrstrom** [comment]
Yea my thinking with the first approach was to have environment variables for image and entrypoint like `BC_DESKTOP_SING_IMG` and `BC_DESKTOP_SING_ENTRY` so folks could point to say `/opt/ood/config/bc_desktop/singularity/{cool_img.sif,cool_entry.sh}` but something that could pull initially from `shub://` so it worked out of the box.  

But I agree with your desire for it to be modifiable/extendible and that the first option would have to those properties. 

And yea, I think any input you want to give us is great! Especially in requirements or what your current solution looks like.

**Comment by xhejtman** [comment]
Would not be podman (see https://podman.io) integration more usefull than singularity? We already made some progress here running debian10 + xfce container.

**Comment by novosirj** [comment]
For us, no/maybe, given we already use Singularity, but I could look into it more fully/perhaps it's easy enough to support both? We also already use Singularity in this way/the modifications are somewhat minimal, so by that metric, we have already made some progress as well. The real request in the ticket is to make this doable without having to modify distribution code, which then has to be patched on every release.

**Comment by xhejtman** [comment]
Our only issue is how to forward ports from container to websocket. We know the port only from outside of the container, not from the inside to modify connection.yaml easily. Is this somehow done in singularity? I mean in case you want to run GUI image, perhaps with xfce installed in container, you need turbovnc and websockify stuff inside with proper portforward.

**Comment by novosirj** [comment]
This works fine for us. Websockify runs inside the container, and connection.yml is in the user's home directory, which is bind mounted into the container, so WebSockify has access to it. We don't actually install Websockify or TurboVNC into the container, instead having it on a shared filesystem that is also bind mounted into the container, but I don't think there's any reason it couldn't be in the container instead if preferred.

We've had this in production for some time, so it's not just theoretical in our case.

**Comment by johrstrom** [comment]
I think that'd be amazing to use podman! I'm a big fan of that, I just don't see a lot of folks using it.  But with subuids enabled, do something like [toolbox](https://github.com/containers/toolbox) where folks could become "root" (not really root, just inside the container) and install packages as they please.  I think that'd b boss :boom:.

**Comment by xhejtman** [comment]
@johrstrom that is exactly what we are providing in our computing center. We have subuids enabled and wrapper around standard pbspro scripts to run the script inside podman container. And now we are preparing BC Desktop and other ondemand apps to run through the podman container.

**Comment by sbutcher** [comment]
> 
> We've had this in production for some time, so it's not just theoretical in our case.

@novosirj would you mind sharing a tarball (or link to repo) of your working app please using desktop in a singularity container? I'm looking to do the same and it would be a real help.

**Comment by johrstrom** [comment]
Yea pull requests welcome for both singularity or podman support!

**Comment by johrstrom** [comment]
I got a sort of trivial example of this going today.  I'd need to work out how to pass different mount points into the shell script.

I can set the environment variables like so.  In this example I want to mount just `/home,/usr,/lib` 
```yaml
  job_environment:
    CONTAINER_IMAGE: "/users/PZS0714/johrstrom/src/images/shelf/centos.sif"
    CONTAINER_ARGS: "-B /home,/usr,/lib"
    DESKTOP_CMD: "gnome-session"
```
But PBSPro doesn't deal well with environment variables that have commas in it because the `-v` option separates the the variables with a comma.

So this translates into `-v CONTAINER_ARGS=-B /home,/usr,/lib,DESKTOP_CMD="gnome-session` and it gets all tripped up on what's the variable value and what's the next variable. 

In any case, we'd have to work through an interface that allows users to specify mount points and likely all sorts of other flags to the container runtime in a way that's easy (or at least in the easiest way).

**Comment by novosirj** [comment]
> @novosirj would you mind sharing a tarball (or link to repo) of your working app please using desktop in a singularity container? I'm looking to do the same and it would be a real help.

Sure thing. I personally am dramatically overloaded (I'm president of my labor union, and as you can imagine we're being inundated with employees being asked to do unsafe things), but this should be a small ask. I just have to confirm there's nothing proprietary in the app/that giving you the app gives you what you need/that there aren't vital portions outside of it. I might want to go through and do a diff of the distribution version too, to give a better idea of what's changed (though possibly if I hand that tarball off, you can do that?).

**Comment by johrstrom** [comment]
I have [this pull request](https://github.com/OSC/ondemand/pull/476). The basic idea is admins setting up the desktop would specify things through environment variables like what mounts you want and the containers' entypoint.  

Can someone let me know if that's fits your needs and could replace what you've implemented at your sites?

**Comment by novosirj** [comment]
I've put a note on my to-do list for the next 24 hours to respond to the various outstanding questions about this that involve me. Will get to it ASAP. Great to see some progress here!

**Comment by johrstrom** [comment]
Thanks! I think what I've provided in the PR doesn't quite hit the mark for podman users.   I think singularity doesn't do unprivileged network namespaces, so there's no need to care or worry about port forwarding, but in the case of podman (or docker) we would have to.

**Comment by xhejtman** [comment]
good point! one can actually use podman with --net host and does not need to deal with portforward anyway.. but net isolation would be definitely better.

**Comment by novosirj** [comment]
> I have [this pull request](https://github.com/OSC/ondemand/pull/476). The basic idea is admins setting up the desktop would specify things through environment variables like what mounts you want and the containers' entypoint.
> 
> Can someone let me know if that's fits your needs and could replace what you've implemented at your sites?

I'm not entirely sure how it works, but it looks like it does what I need. The only arguments we use to Singularity are multiple -B to do bind mounts.

The current change we make is to script.sh.erb, basically changing this:

`source "<%= session.staged_root.join("desktops", "#{context.desktop}.sh") %>"`

...to this:

`singularity exec -B ... -B ... etc. $IMAGE /bin/bash "<%= session.staged_root.join("desktops", "#{context.desktop}.sh") %>"`

...where -B ... is something like `-B /etc/slurm` or `-B /cache/sw:/opt/sw`, etc.

The only other changes we make are environmental (eg. start with `module load singularity` so that Singularity is in the PATH, etc.).

**Comment by johrstrom** [comment]
OK, I believe I have good news from [this discourse topic](https://discourse.osc.edu/t/mate-desktop-in-a-singularity-container/696/21) which is: I believe we support this out of the box.

I can show the example in that topic how to do this with singularity, and this should translate fairly easily to podman `--net=host`. 

Port binding may not be all that different.  You find an open port in the `script_wrapper`, set the `min_port` and `max_port` to 2000 and bind the random port generated in the script_wrapper to 2000. We don't have podman or docker installed here, so I can't test that, but I believe it's possible and relatively straight forward approach from the example given in that topic. 

I think now, the work to be done is documenting how to do this.

**Comment by johrstrom** [comment]
I'm closing this as I'm fairly sure there's nothing to do now but document the strategy of how to do this and some example image definitions.
