### ISSUE TITLE
rename 'scripts' directory to 'launchers'

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3901]
While we refactored the `Launcher` models and controllers recently, we left this one piece standing - the `scripts` directory itself. We should change the name of this directory before the 4.0 release.

This directory here:
https://github.com/OSC/ondemand/blob/1b076a88e94a98b03d2d6450ef33b49881798324/apps/dashboard/app/models/launcher.rb#L12-L14

I deferred this because there are likely a lot of tests that need to be updated.

**Comment by euler-room** [comment]
fixed in #3922
