### ISSUE TITLE
Provide an OnDemand "branded" OIDC error template

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#392]
This would be included in /opt/ood/ondemand and referenced using OIDCHTMLErrorTemplate. Ideally would be in default location /opt/ood/ondemand and overridable by adding a file to /etc/ood/config. Unlike the other OIDC variables which may be set in a separate site managed auth_openidc.conf, this would be set in ood-portal.conf so it could be managed by ood-portal-generator. An if else block could be used to check for the existence of an /etc/ood/config/oidc_html_error_template.html (or whatever path is appropriate for that config file).

See https://github.com/zmartzone/mod_auth_openidc/blob/1b38dcc1a6e9f92da8a731b355bba2d608af9fa9/auth_openidc.conf#L624-L635

https://github.com/zmartzone/mod_auth_openidc/wiki#19-how-do-i-customize-the-user-facing-error-pages

Old repo that started this work: https://github.com/OSC/ood_auth_error

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737572193802) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
reviewed,
already possible,
not a huge impact
