### ISSUE TITLE
Session Card Bug - Missing templates?

### ISSUE THREAD

**Issue by abujeda** [OSC/ondemand#3937]
I was looking at the session cards and I notice that there are some missing partials from previous versions

It looks like after the refactoring completed on: https://github.com/OSC/ondemand/commit/50c35143cb8f01186377d2740151f628401cddc7 some partials for the session card didn't get included. I think that the `custom_info_view` and `session_completed_view` are missing in the new version of the session card.

Current version:
https://github.com/OSC/ondemand/blob/master/apps/dashboard/app/views/batch_connect/sessions/card/_card_body.html.erb

Should it be like this?

```ruby
<div class="card-body">
  <div>
    <div class="float-end"><%= cancel_or_delete(session) %></div>
    <%= render_card_partial('host', session) %>
    <%= render_card_partial('created', session) %>
    <%= render_card_partial('session_time', session) %>
    <%= render_card_partial('id', session) %>
    <%= render_card_partial('support_ticket', session) if Configuration.support_ticket_enabled? %>
    <%= render_card_partial('display_choices', session) %>
    <%= render_card_partial('custom_info_view', session) if session.app.session_info_view %>
    <%= render_card_partial('completed_view', session) if session.app.session_completed_view &&  session.completed? %>
    <%= render_connection(session) %>
  </div>
</div>
```

**Comment by moffatsadeghi** [comment]
Thanks for submitting this and catching this, @abujeda!
