### ISSUE TITLE
Enable SGE for extended view in Active jobs

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#399]
Again in [discourse](https://discourse.osc.edu/t/active-jobs-with-ssge-8-1-9-request-for-jobs-failed-due-to-body-parsing-error/704) SGE is not enabled for extended view in Active jobs. For context, extended view gives the drop down table in the image below.  

It tracked it down to this [line](https://github.com/OSC/ondemand/blob/b7a02b0599c7034dbef88619d8a6a5737ef4e3cc/apps/activejobs/app/models/jobs_json_request_handler.rb#L70) that doesn't explicitly enable that adapter.

This ticket is to enable it.  It could be as simple as adding it to the list.  If not, if there's some conversion of the variables (say turning `project_id` into `accounting_id`) any of those should be called out.

accounting_id
![image](https://user-images.githubusercontent.com/4874123/74760639-b7067c80-5248-11ea-9fe3-f757927f3d99.png)

**Comment by johrstrom** [comment]
It should also be noted that `extended view` gives users the ability to delete their jobs, which is functionality that the discourse user also wants (to have parity with Slurm).

**Comment by jms27000** [comment]
Hi @johrstrom 
when do you plan to deliver this facility ?

thanks, jean-marie

**Comment by johrstrom** [comment]
It's unlcear, but I did file #416 which I think would be more feasible to provide sooner.

**Comment by ericfranz** [comment]
I just marked this for 1.8.

**Comment by ericfranz** [comment]
For the adapter, we will want to make sure that the native attribute is being set and also contains a few extra fields if available

**Comment by matthu017** [comment]
Looking at the ood_core gem, it looks like sge needs some work to improve native attribute reporting: https://github.com/OSC/ood_core/blob/63187f8874e62b752a73e39263f539ce0241495a/lib/ood_core/job/adapters/sge/qstat_xml_j_r_listener.rb#L31
However the native attribute is technically "set" which should allow for extended view.
