### ISSUE TITLE
User Form text_area doesn't support the pattern attribute

### ISSUE THREAD

**Issue by hansen-m** [OSC/ondemand#3990]
Based on the documentation and my testing the User Form text_area doesn't support the pattern attribute to check it against a regular expression. Can this be added so that it functions in the same way as text_field does?

https://osc.github.io/ood-documentation/latest/how-tos/app-development/interactive/form.html

**Comment by johrstrom** [comment]
Hi, thanks for the issue, but unfortunately no we can't. The `pattern` HTML attribute only applies to [text](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text), [tel](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel), [email](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email), [url](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url), [password](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password), and [search](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search) input types.

Which is to say, even if we could embed the attribute in the HTML, browsers won't respond to it.

From the MDN documentation for the same:

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern

**Comment by hansen-m** [comment]
@johrstrom Thanks for that info, makes sense now.

Are there any examples of how this or something similar might be done within the form.js instead?

**Comment by johrstrom** [comment]
Well I guess you'd want to attach an event handler to the launch button's `onclick` event. When there is a click event, validate the text area. Browsers do the validation of `pattern`s automatically and update the HTML to show the error. You're not going to be able to do the same exact thing within javascript, but maybe a `window.alert` could work.
