### ISSUE TITLE
data-exclusive-option-for 

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#4013]
I'm finding that we need some compliment to `data-option-for`  that's sort of the opposite. 

`data-option-for` is sort of saying `this is generally available, but not for this specific selection`.

`data-exclusive-option-for` would sort of say `this not generally available, but is exclusively available for this specific selection`.

All options are visible by default. This would change that. Any option that has the `data-exclusive-option-for` attribute then it would be hidden by default (unless those options have been chosen).

**Comment by moffatsadeghi** [comment]
Confirmed via changelog that this actually got into 4.0 so I am removing the 4.1 stuff
