### ISSUE TITLE
user.rb initialize assumes all ArgumentErrors are due to a missing user

### ISSUE THREAD

**Issue by banfelder** [OSC/ondemand#405]
https://github.com/OSC/ondemand/blob/515eb6c4b205e5fb956d71225f89eb7b46314e28/nginx_stage/lib/nginx_stage/user.rb#L40

The rescue clause here assumes all ArgumentErrors are due to a missing user. In one case, we were hitting this exception because the user's LDAP entry specified a gid that didn't exist. I.e., the ArgumentError came from Etc.getgrgid gid, not from Etc.getpwnam as seems to be assumed. The misleading error message led to extra troubleshooting time. Maybe don't squash so much information from the exception, or be more granular about error reporting.

**Comment by johrstrom** [comment]
Hi! Thanks so much for the heads up and looking into it in depth.  I've just submitted a patch.

**Comment by ericfranz** [comment]
@banfelder this will be in the 1.7 release
