### ISSUE TITLE
Support quotas by group rather than just by user

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand#412]
We have this at OSC in the `quotas_other` array:

```json
        {
            "block_limit": 10737418240, 
            "file_limit": 1000000, 
            "group": "PZS0720", 
            "path": "/fs/project", 
            "total_block_usage": 10534483488, 
            "total_file_usage": 566201
        }
```

This could be used to show overall health of a group limit

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737573536771) by [Unito](https://www.unito.io)

**Comment by moffatsadeghi** [comment]
Trey's response: I’m indifferent if it gets fixed.  If the community hasn’t expressed an interest then seems fine to close and can revisit if there is a community need."

**Comment by moffatsadeghi** [comment]
Closing issue based on response and feedback
