### ISSUE TITLE
Load OOD external configuration in all apps

### ISSUE THREAD

**Issue by msquee** [OSC/ondemand#433]
In all apps included with OnDemand we should be loading the OOD external configuration to ensure that we have a consistent UI across OOD.

To do this I would go through all apps and make sure that there is a local env file in the root directory of the application named `.env.local` with the following contents:

```
OOD_LOAD_EXTERNAL_CONFIG=1
```

With that configuration, our apps will inherit the same theme (navigation bar) as the `dashboard` application.

From this:
![image](https://user-images.githubusercontent.com/6081892/77288082-6a7de900-6cad-11ea-838a-56c2414bfd5d.png)

To something like this:
![image](https://user-images.githubusercontent.com/6081892/77288115-7f5a7c80-6cad-11ea-97ad-78c9f7f76f64.png)

_This issue was created based on feedback from the SGCI UX analysis survey_

**Comment by ericfranz** [comment]
This will be addressed by https://github.com/OSC/ondemand/pull/101 in 1.7. Though it doesn't address apps that do not have this navigation bar, such as Files app, File editor and Shell.

As far as the `OOD_LOAD_EXTERNAL_CONFIG` is concerned, all the apps in production mode by default load the external config from /etc/ood/config so ensuring `OOD_LOAD_EXTERNAL_CONFIG` is set is not necessary.
