### ISSUE TITLE
Job Composer help button not working

### ISSUE THREAD

**Issue by msquee** [OSC/ondemand#434]
![image](https://user-images.githubusercontent.com/6081892/77288384-158ea280-6cae-11ea-94da-6720f69d1d1b.png)

There are reports that the Job Composer tutorial modal window does not work when clicking on the Help button in the navigation.

_This issue was created based on feedback from the SGCI UX analysis survey_

**Comment by msquee** [comment]
I will circle back on this after testing again in multiple browsers / devices, unfortunately we don't have any other information other than it doesn't work as expected.

**Comment by ericfranz** [comment]
This may be [fixed in 1.7](https://github.com/OSC/ondemand/issues/368)

**Comment by johrstrom** [comment]
Yea this got fixed with the joyride.  Well, the help button _is_ the joyride so yes it did get fixed.
