### ISSUE TITLE
Improve error messages in Files application

### ISSUE THREAD

**Issue by msquee** [OSC/ondemand#436]
Currently the Files application doesn't have support for editing `image/jpeg` files, when a user tries to do that they are sent to a new tab with this scary looking error message making them think that they broke something.

Let's present this information to the user in a nicer way and without redirecting the user to another tab to see a message like this. The survey results proposed that we should show this message inline and inside of a modal that the user can click out of.

Example error message:
![image](https://user-images.githubusercontent.com/6081892/77289349-30faad00-6cb0-11ea-918b-833ff41d2910.png)

_This issue was created based on feedback from the SGCI UX analysis survey_

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737574657063) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
error message no long occurs
