### ISSUE TITLE
Add ability to double click on files to open / edit in Files application

### ISSUE THREAD

**Issue by msquee** [OSC/ondemand#438]
Add the ability to double click on a file in the Files application and open that file for editing or viewing (not sure on which one should be the default, maybe user configurable?)

The Files application should mimic as closely as possible the experiences that we are used to in Explorer / Finder 

![image](https://user-images.githubusercontent.com/6081892/77290456-9a7bbb00-6cb2-11ea-94b1-d02966a15a11.png)

_This issue was created based on feedback from the SGCI UX analysis survey_

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737630125068) by [Unito](https://www.unito.io)

**Comment by Seegee** [comment]
This is invalid.

**Comment by matt257** [comment]
reviewed,
closing because single clicks open the viewer currently
