### ISSUE TITLE
ondemand copies job files to "default directory"

### ISSUE THREAD

**Issue by puneet336** [OSC/ondemand#445]
I have a job directory where required input for job is present , example - 

```
[puneet@cluster1 2]$ pwd
/home/puneet/MyJobs/2
[puneet@cluster1 2]$ ls
a.out  ff.sh  input.dat
```

I create a new slurm job as - 
JobComposer>NewJob>FromSpecifiedPath, and here is what in fill in "Create a new job from a path" form -

```
Source Path: /home/puneet/MyJobs/2
Name: Myjob2
Script Name: ff.slrm
ClusterName: Cluster1
Account:

```

on clicking save, a new directory is created - 

`/home/puneet/ondemand/data/sys/myjobs/projects/default/1/`
having contents - 
`a.out  ff.slrm  input.dat`

Is it possible to run/submit job from **/home/puneet/MyJobs/2** via openondemand instead of `/home/puneet/ondemand/data/sys/myjobs/projects/default/1/` ? 

* concern is that if /home/puneet/MyJobs/2 is large in size (say - more than 100G) then ood may create copy of same.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737575325134) by [Unito](https://www.unito.io)

**Comment by trecakov** [comment]
@ericfranz  Thanks you

**Comment by johrstrom** [comment]
We're replacing the job composer now with the project manager that will allow for stuff like this. Namely just creating a project on top of an existing directory.
