### ISSUE TITLE
Streamline noVNC copy and pasting into VNC applications (Chrome)

### ISSUE THREAD

**Issue by msquee** [OSC/ondemand#455]
"cut-and-paste from outside the browser to desktop apps inside the browser and with typing control characters in desktop apps."

_This issue was created based on feedback from the SGCI UX analysis survey_

The original copy paste in Chrome was added https://github.com/OSC/ondemand/pull/335

An issue to disable this was added in https://github.com/OSC/ondemand/issues/356 and the changes in the previous PR were reverted for OnDemand 1.7.

Consider re-applying changes, but to new noVNC version. Will need to change source files and then generate new build, which is the new process now.

**Comment by ericfranz** [comment]
Also worth reviewing the noVNC upstream project as there were lots of different PRs in flight related to copy/paste and maybe there is a better approach to apply instead of the one we were going to apply.

**Comment by msquee** [comment]
Instructions for building noVNC are here: https://github.com/OSC/ondemand/tree/master/apps/dashboard#building-novnc-with-ondemand-custom-changes

https://github.com/OSC/ondemand/issues/356#issuecomment-601648765

I would start here: https://github.com/OSC/ondemand/blob/master/apps/dashboard/public/noVNC-1.1.0/app/ui.js#L323
