### ISSUE TITLE
Add VSCode Online as interactive application

### ISSUE THREAD

**Issue by msquee** [OSC/ondemand#457]
"I feel there is ​a need for a generic full suite text editor."

I agree, we should explore these two JavaScript editors.

https://github.com/c9/core/
https://microsoft.github.io/monaco-editor/

_This issue was created based on feedback from the SGCI UX analysis survey_

**Comment by ericfranz** [comment]
Now investigating https://theia-ide.org/

**Comment by Nosferican** [comment]
Related https://github.com/OSC/Open-OnDemand/issues/62
VS Code [beta](https://github.com/OSC/bc_osc_codeserver)

**Comment by Nosferican** [comment]
Is there any rough timeline? For example, fall of this year?

**Comment by ericfranz** [comment]
Theia definitely November. But I'd like to see it by July.

I think sometime in next couple weeks some of the problems with this should be addressed though: https://github.com/OSC/bc_osc_codeserver

**Comment by msquee** [comment]
@Nosferican I have a working branch for code-server here: https://github.com/OSC/bc_osc_codeserver/tree/upgrade/codeserver

**Comment by Nosferican** [comment]
Might be helpful in terms of being able to install extensions. https://medium.com/@isaiah.taylor/use-vs-code-on-a-supercomputer-15e4cbbb1bc2

**Comment by Nosferican** [comment]
This is a cool application of VS Code as an app and connecting it to HPC
https://www.youtube.com/watch?v=JVUJ5Oohuhs&list=PLP8iPy9hna6Tl2UHTrm4jnIYrLkIcAROR

**Comment by Nosferican** [comment]
One alternative would be to integrate with the Code Spaces self-hosted solutions https://docs.microsoft.com/en-us/visualstudio/codespaces/how-to/vscode#self-hosted as an option for an interactive app.

**Comment by msquee** [comment]
@Nosferican https://github.com/OSC/bc_osc_codeserver/pull/2 was merged in about 2 weeks ago, Code Server is available for use now

**Comment by Nosferican** [comment]
Aye. Thanks! I am helping to test it in our cluster and so far it works really well.

**Comment by ericfranz** [comment]
We have a few improvements to help with deployment and cookie management added as issues to https://github.com/OSC/bc_osc_codeserver. We will also update the documentation to mention this app. Since the basic app is working and reported by another site outside of OSC, I'll mark this issue as complete. If you see any problems with the app, please post an issue on https://github.com/OSC/bc_osc_codeserver!
