### ISSUE TITLE
File Browser should have mass download and mass transfer (to another directory) function.

### ISSUE THREAD

**Issue by msquee** [OSC/ondemand#459]
File Browser should have mass download and mass transfer (to another directory)
function.

_This issue was created based on feedback from the SGCI UX analysis survey_

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737631716537) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Not sure what this meant, but I feel like we have it when selecting multiple things. That is we can select multiple items and transfer or download them, so i'm going to close this as nothing to do.
