### ISSUE TITLE
Supply some httpd auth modules

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#46]
It came up in this [PR](https://github.com/OSC/ood-documentation/pull/180) that maybe we aught to be supplying the community with commonly used httpd modules built against the SCL httpd24 version so that users don't have to download the regular rpm, unextract it, and move the .so files around. 

This is a discussion on whether we should do that, what modules we should supply and how that may be implemented.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823917546570) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
There is the possibility we will drop RHEL 6 in OnDemand 2.0 which would mean we could rely on the OS Apache and not have to use SCL Apache. That would solve this problem.

**Comment by johrstrom** [comment]
Yea I think there's kinda nothing to do here.
