### ISSUE TITLE
Add flag to Job Composer to not show tutorial after completed by user one time

### ISSUE THREAD

**Issue by msquee** [OSC/ondemand#470]
The default functionality in the Job Composer is to show the Help modal on every page load. This can get annoying quickly, we should add a flag to the Job Composer UI that only shows the Help modal once.

![image](https://user-images.githubusercontent.com/6081892/78590574-0ceeae00-7810-11ea-902b-912d51182fcd.png)

Proposed implementation:
- When a user clicks the "X" in the right corner of the modal, send `POST` request to Job Composer with a flag to indicate that the user has seen the help modal once.

POST `/myjobs/settings/showHelpModal`
```json
{
    "showHelpModal": false
}
```
- Receive that POST request and write to SQLite database for `jobscomposer` app. Maybe we can have a `settings` table with a similar schema to:
- On subsequent page loads, `GET` the `showHelpModal` value and update the DOM accordingly.

|VARCHAR(255) setting|BOOLEAN enabled|
|---|---|
|showHelpModal|false|

**Comment by ericfranz** [comment]
What did you have in mind here? The tutorial only appears if you do not have any jobs, so I don't think it is too problematic if it appears every time you access the main page with zero jobs.

**Comment by msquee** [comment]
@ericfranz Oh, no need to reinvent the wheel then haha. I'll close this issue. This was just bugging me as I'm testing Job Composer
