### ISSUE TITLE
Add ability to disable file uploads

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#471]
Related to https://github.com/OSC/ondemand/issues/262

Sometimes we have situations where we want to prevent users from easily uploading files, but still have the rest of the file manager experience. See https://discourse.osc.edu/t/antivirus-scan-uploading-files-from-home-to-ood-servers-via-web-interface/823 for an example.

Right now you can set in /etc/ood/config/apps/files/env this:

```
FILE_UPLOAD_MAX=0
```

If you try to upload a file you then will just get an error message:

![screen 2020-04-07 at 8 09 33 AM](https://user-images.githubusercontent.com/512333/78668023-fdbb3f00-78a7-11ea-97aa-84737e59719b.png)
![screen 2020-04-07 at 8 09 42 AM](https://user-images.githubusercontent.com/512333/78668025-fe53d580-78a7-11ea-9ad7-a7f1fa9f050e.png)

We want a separate flag so the upload button is hidden and the user is properly informed.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737576675937) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
feature exists,
completed in a previous release
