### ISSUE TITLE
Add support for intteruption free deployments

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#473]
One common approach to interruption free deployments is blue green deployment: https://martinfowler.com/bliki/BlueGreenDeployment.html

We could do this for all of OnDemand, or only focus on high risk apps like the Files app (for file uploads) and the Shell app (for sessions being terminated).

Right now, if I have shell app open, and a new version of the shell is deployed with the restart file touched, my shell session will remain working unless at the same time I open a new shell session. If I do that, the result is a new request sent to the shell app, and Passenger will then restart the process before returning the response. Since that kills the process my other shell is killed.

Ideally, my old session with the old code works, and when I start a new session along side the new session uses the new code. Or both sessions use the old code until my PUN restarts and then they both use the new code. So in that case it could be that the deployment location for sys apps becomes something like `/var/www/ood/apps/sys_green/` and `/var/www/ood/apps/sys_blue/` and you alternate.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737576838411) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
Another approach that would mitigate the problem would be if part of the installation process ensured that if no files changed in an app between deployments, the tmp/restart.txt was not touched. Then modifications that only affect the dashboard app or active jobs and not apps like Shell and Files could be deployed safely.

**Comment by treydock** [comment]
We have to approach this problem in terms of what RPMs support.  The restart.txt is %posttrans and that has limited information, it doesn't know anything about previous installs or the new install, it's just a series of commands that get executed.  If you wanted to make the process only touch the file if the app was updated then we'd have to provide some way for the RPM processes to know before and after states via files on the filesystem and that is a very ugly solution and bad idea.

As a system administrator I expect some degree of interruption when performing updates. Zero interruption updates are going to introduce lots of complexity and fragility with what I deem little benefit.  With how infrequently we deploy updates I think forcing a restart of sessions is fine.  Also I would be in favor of the opposite which is restarting all PUNs upon every update because we've had situation in the past where PUNs running before an update break after an update and as a system administrator that's unacceptable.  I'd rather everything restart than leave things in a possibly broken state.

I think the friendliest user facing solution is that before an update we post announcement, then do the update that restarts all PUNs. This ensures the most consistent behavior between updates and ensures PUNs are in the healthiest possible state after an update.  It might not be user friendly but it's not like we do updates every few days in most cases.

**Comment by ericfranz** [comment]
As discussed offline this was previously possible when we had separate rpms per app but we switched to one rpm when we switched to the monorepo.

A more flexible approach may be doing this using nginx_stage instead. The nginx_stage script could actually manage the "green blue" deployments of the apps at risk, such as the shell app. One way you could imagine that working is before switching user, nginx_stage copies the shell app to /var/www/ood/apps/shell.green (if the copy hasn't happened yet) and then the PUN launches with that. When the shell app changes (due to a new deployment), nginx_stage switches to /var/www/ood/apps/shell.blue for new PUN starts. Since the old PUN is using the green code, those server processes would never be interrupted till the PUN was restarted and then PUN config regenerated.

It is still quite a bit of complexity for temporary interruption to users.

**Comment by ericfranz** [comment]
Brainstorming an approach:

Core apps are deployed to:
/opt/ood/1.7.12/apps

A symlink is created:
/opt/ood/apps => /opt/ood/1.7.12/apps

A symlink is added to the existing location for the core apps:

/var/www/ood/apps/sys/dashboard => /opt/ood/apps/dashboard
/var/www/ood/apps/sys/myjobs =>  /opt/ood/apps/myjobs
/var/www/ood/apps/sys/shell => /opt/ood/apps/shell

When nginx_stage starts a PUN, before generating an app config for the shell, for example, it gets the actual path to the shell app. So /var/www/ood/apps/sys/shell is resolved to /opt/ood/1.7.12/apps/shell and then then PUN starts.

Now, if you could install OnDemand via rpm in a way that after upgrading from 1.7.12 to 1.7.14 the old /opt/ood/1.7.12 directory is left untouched, but the symlinks are all updated, then you would have a situation where:

1. PUNs currently running will be using 1.7.12 version of the apps
2. PUNs started after install will be using 1.7.14 version of the apps
3. PUNs currently running, after a restart, will use 1.7.14

I think this is not possible unless:

1. the apps themselves have the version in the rpm package, just like the ondemand gems do
2. nginx_stage generates the app configs on the fly every time the PUN is created

**Comment by treydock** [comment]
This is not possible with RPMs. An RPM will remove any files from the previous version upon upgrade, that's not possible to bypass. The only way we got around this with ondemand-gems is two things:

1) The version is in name, so ondemand-gems-1.7.12 is the name (names having to be unique)
2) No files for ondemand-gems-1.7.12 overlap with any other version of ondemand-gems

The only way to keep an RPM from not removing files from a previous version is to not put the files in the RPM, by instead having the RPM be a tarball and extracting the tarball as part of %post. I would strongly discourage such things as it makes the RPMs successful install entirely dependent on successful %post and if %post fails the RPM may still be seen as "installed" despite an unhealthy state for the actual files you intended to deploy. This would also make uninstall not actually remove the files that got installed and would make it really hard for us to ensure the proper state of a given version.  Again, I would not be comfortable making this change, it would be a huge step backwards.

I would also not recommend we do with ondemand RPM what we did with ondemand-gems, that's a very unfriendly admin experience as it requires some amount of admin effort to clean up old installs, which is something we need to address with ondemand-gems at some point.

**Comment by ericfranz** [comment]
Ah yeah the suggestion above would only work if we took the apps directory and did with that what we currently do with ondemand-gems.

Seems like instead, the best approach to support interruption free deployments would be to either:

1. decouple long running processes that may be interrupted from the Passenger apps (i.e. handle those somehow completely in NGINX)
2. isolate long running processes to separate Passenger apps that are very simple - so the entire app is in memory once it is started and impervious to future deployment changes, and then we don't touch the tmp/restart.txt files for those apps - so to pick up a change to those apps would require a PUN restart or a site to manually touch those restart files

Just not touching the restart files of the apps in concern seems to be a saner approach than adding complexity and playing games with rpms.

**Comment by treydock** [comment]
I have concerns about the behavior change of not touching restart files by default. What about logic to not touch if a `.norestart` file exists at the app root? Not touching by default would put a larger burden on admins during upgrades even mimor upgrades.

**Comment by matt257** [comment]
reviewed,
HA proxied and 2 VMs take care of this
