### ISSUE TITLE
Making Shell App code modular and Adding Testing

### ISSUE THREAD

**Issue by samirmansour** [OSC/ondemand#480]
Currently we have been able to get away with having all of the backend code for the shell app in one file, app.js. At the time of writing this app.js stands at around 178 lines of code. Recently, new features are being developed that would add to this code base such as the ability to have terminal sessions and the ability to change terminal color schemes. These two features alone have totaled the app.js file lines of code to about 422. This could lead to confusion and harder bug tracing for the future. The solution I am proposing would be to modularize the code.

Current Structure:
**/bin
/public
/tmp
/views
app.js**

New Structure:
**/bin
/public
/tmp
/views
/routes -- new
/middleware -- new
app.js**

Along with the need for modularization. We also should consider adding testing to the shell app because of the amount of middleware that we now have for it.

**/bin
/public
/tmp
/views
/tests -- new
/routes -- new
/middleware -- new
app.js**

I'm open to suggestions on directory structure and the current testing framework that I am planning on using is mocha. Let me know your thoughts.

**Comment by ericfranz** [comment]
A /lib directory that would contain javascript objects/classes/helper functions. I would start with that, and answer the question, what can we pull out of app.js into separate model or helper objects/functions? What are the definitions of all those functions? If we use those from /lib, what does app.js look like?

**Comment by samirmansour** [comment]
With the added ability for color schemes there are at least nine more functions added to the app.js file. All of these functions are mostly helper/middleware functions. I think it would be beneficial to separate the terminals object into its own file. The separation of various parts of the code will allow us better clarity for the purposes of updating and testing the code. The shell app has gotten, in my opinion, more capabilities. With more capabilities comes more chance for an unaccounted for bug. Seperating to code into modules and implementing unit testing should help us to make sure the app is doing exactly what we want it to do. app.js would reduce significantly to just a few function calls and the websocket object as well.

**Comment by ericfranz** [comment]
Identifying some pure functions and refactoring app.js so those are in a separate section of the file would be a good first step. It is likely that after doing that exercise, the resulting express app, even with all its middleware, will be smaller. Once that is achieved, we could reassess whether it is appropriate to move those functions into a separate lib, add some tests for them, and determine if the remaining code in app.js requires more work or is sufficiently simple.

**Comment by ericfranz** [comment]
Discussed offline. Will close this as the next step is just to refactor app.js so there are more functions defined.
