### ISSUE TITLE
Render view.html.erb for vnc apps

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#488]
The view.html.erb would just be there for extra information, and would not control the button that actually launches NoVNC nor the controls to manipulate quality and compression

**Comment by ericfranz** [comment]
The goal Is that I can do this type of thing but for MATLAB and Paraview:

![image](https://user-images.githubusercontent.com/512333/80980029-21fe3300-8df6-11ea-80db-846a737b4df5.png)

**Comment by ericfranz** [comment]
For example, in Paraview, it would be inserted between Session ID and the connection tab:

![screen 2020-05-04 at 11 00 29 AM](https://user-images.githubusercontent.com/512333/80980380-92a54f80-8df6-11ea-9634-e230faec1cd6.png)

Such as:

![screen 2020-05-04 at 11 00 07 AM](https://user-images.githubusercontent.com/512333/80980393-976a0380-8df6-11ea-826d-fccbf0b417c6.png)

**Comment by msquee** [comment]
Relevant files:
- `app/views/batch_connect/sessions/index.js.erb`
- `app/views/batch_connect/sessions/_panel.html.erb`

**Comment by ericfranz** [comment]
Since we discussed splitting this up into two separate PRs, I'll close this PR for now. If you want to reuse this branch for one of the two, you can reopen this PR.
