### ISSUE TITLE
ood-portal-generator update script tells the user to run EL6 commands

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#49]
These are EL6 commands:

https://github.com/OSC/ondemand/blob/4fc7e0602debfc660b9107250f2a27e51f01dbec/ood-portal-generator/sbin/update_ood_portal#L60-L69

We should provide the EL7 commands as well.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737577796148) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
The first part of condition is EL7 commands: https://github.com/OSC/ondemand/blob/4fc7e0602debfc660b9107250f2a27e51f01dbec/ood-portal-generator/sbin/update_ood_portal#L62

**Comment by johrstrom** [comment]
This was fixed at some point. I could look up the commit, I'm satisfied to say that it's at least fixed in 3.1 and beyond.
