### ISSUE TITLE
Find and document a solution for before PUN start and after PUN stop hook scripts 

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#496]
We have several use cases that need ability to add scripts run as the user before the PUN starts and after the PUN stops:

1. In one sites case, it is to run a setup script to mount a user's home directories using sshfs. 
2. For the K8s adapter at OSC, we want to be able to do a token exchange and setup a config file

In both cases, for the setup script, we will want to have access to a claim header or token that normally is stripped and not passed through to the PUN when a request is proxied.

**Comment by johrstrom** [comment]
I've put some work into this by trial and error and here's what I've got.  The pre hook itself is fairly easy to implement and call but passing oidc tokens securely is proving to be problematic. 

* It's fairly trivial to implement a hook that we can pass the oidc token through the commandline (as say `-o <some oidc token>` ).  But this isn't secure, so it's not really viable.
* LUA standard library doesn't allow us to set environment variables, but I've used [this lua posix library](https://github.com/luaposix/luaposix). This works, but would need us to redistribute it (with different builds even for centos 7 and centos 8).
* I'm now looking into passing the token through standard in.  Looks like [the popen api](https://www.lua.org/manual/5.1/manual.html#pdf-io.popen) returns a file that can be read from (standard out) or written to (standard in), but not both. We currently use read to get the output and show the user.  So maybe there's a file redirection trick to employ? I just need to figure out how to pass the variables correctly to stdin and correctly verify the boot process (reading stdin) doesn't bypass the check process that reads the output file.

**Comment by treydock** [comment]
There is a `lua-posix` RPM in EPEL, so we don't have to redistribute anything.  It's a common package to have to install to use LMOD.

**Comment by johrstrom** [comment]
Thanks! That rpm doesn't seem to have `module 'posix.stdlib'` which is module we need. Even though it is from the same source repository. I guess it's in [version 33, because CentOS 8 has the right files](https://centos.pkgs.org/8/centos-powertools-x86_64/lua-posix-33.3.1-9.el8.x86_64.rpm.html) where [version 32 in CentOS 7 doesn't](https://centos.pkgs.org/7/epel-x86_64/lua-posix-32-2.el7.x86_64.rpm.html).

**Comment by treydock** [comment]
If we ended up shipping it for OnDemand from our repos we'd need to name the RPM `ondemand-lua-posix` and put it in non-standard path and somehow load that nonstandard path inside our code.  We have to avoid conflicting with EPEL.  We could also open bugzilla for EPEL to have maintainer of that package upgrade to newer version if possible.
