### ISSUE TITLE
Desktop app GUI feedback of nr of cores and nodes does not match

### ISSUE THREAD

**Issue by baverhey** [OSC/ondemand#504]
Our custom form:
`---
attributes:
  bc_account: Null
  bc_num_slots:
    label: Number of nodes
  bc_queue: Null
  desktop: xfce
  num_cores:
    id: num_cores
    label: Number of cores
    max: '16'
    min: '0'
    step: '1'
    value: '2'
    widget: number_field
cluster: login
form:
- bc_account
- bc_num_hours
- bc_num_slots
- num_cores
- bc_email_on_started
- bc_vnc_idle
- desktop
- node_type
- bc_queue
- bc_vnc_resolution
title: login  desktop
`
If a request 2 nodes for 4 hours on 6cores it shows 1node 1core in the right corner of acctive interactive apps.

**Comment by ericfranz** [comment]
Remind us the batch scheduler and version you are using, thanks!

**Comment by baverhey** [comment]
The OOD quattor profile

`unique template common/ood/web/packages;

variable ONDEMAND_MAJOR_VERSION ?= "1.7";
variable ONDEMAND_MINOR_VERSION ?= "11-1.el7";

variable OS_REPOSITORY_LIST = {
    append('centos_scl');
    append('centos_scl_rh');
    append('openondemand_web');
    SELF;
};

variable OS_SNAPSHOT_REPOSITORY = npush(
    'openondemand_web', '',
);

"/software/packages" = pkg_repl("ondemand", format("%s.%s", ONDEMAND_MAJOR_VERSION, ONDEMAND_MINOR_VERSION), "x86_64");
"/software/packages" = pkg_repl("ondemand-apache", format("%s-*", ONDEMAND_MAJOR_VERSION), "x86_64");
"/software/packages" = pkg_repl("ondemand-ruby", format("%s-*", ONDEMAND_MAJOR_VERSION), "x86_64");
"/software/packages" = pkg_repl("ondemand-python", format("%s-*", ONDEMAND_MAJOR_VERSION), "x86_64");
"/software/packages" = pkg_repl("ondemand-runtime", format("%s-*", ONDEMAND_MAJOR_VERSION), "x86_64");
"/software/packages" = pkg_repl("ondemand-nodejs", format("%s-*", ONDEMAND_MAJOR_VERSION), "x86_64");

prefix '/software/packages';

"bubblewrap" = dict();
"httpd24-httpd" = dict();
"httpd24-httpd-devel" =  dict();
"mod_auth_openidc" = dict();
"ondemand-passenger-devel" = dict();
"ondemand-apache" = dict();
"ondemand-nodejs" = dict();
"ondemand-ruby" = dict();
"ondemand-runtime" = dict();
"python-cachier" = dict();
"python-pathtools" = dict();
"python-portalocker" = dict();
"python-vsc-ood" = dict();
"python-watchdog" = dict();
"python2-futures" = dict();
"python-websockify" = dict();`

**Comment by baverhey** [comment]
dident use the native optin in submit.erb
