### ISSUE TITLE
Add whitelist of hosts for the shell app, defaulting to the cluster config login hosts and DEFAULT_SSHHOST

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#507]
Colon or comma delimited:

    SSHHOST_WHITELIST=owens.osc.edu:ruby.osc.edu

If not set, default to the cluster config login hosts and DEFAULT_SSHHOST if set.

Allow `SSHHOST_WHITELIST="*"` or `SSHHOST_WHITELIST="*.osc.edu"`.

**Comment by matthu017** [comment]
PR: https://github.com/OSC/ondemand/pull/518
