### ISSUE TITLE
Cluster config to allow specifying login host as the default

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#508]
```yaml
v2:
  login:
    host: "owens.osc.edu"
    default: true
```

We would build an array of all the login hosts from each cluster, then the first cluster in that array with "default" set would be used as the default, unless DEFAULT_SSHHOST was set. If neither found, the first host in the array would be the default.

The cluster config "acls" section would be ignored in this case - that could be added later, though a duplicate implementation would need to be implemented using nodejs until this info could be provided in a shared web service.

But the hidden attribute should be respected i.e. if marked as hidden, we don't use as a default.

**Comment by matthu017** [comment]
PR: https://github.com/OSC/ondemand/pull/511
Is a precursor to whitelist issue.
