### ISSUE TITLE
apache restarts don't use additional ood-portal-generator options (-t/--template)

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#523]
We provide the `-t/--template` in the ood-portal-generator sbin/update_ood_portal, but the apache restart command uses the default. So if a user were to use this flag, the apache restart would just overwrite it with the default.

I was thinking instead maybe we could put this option in the `ood_portal.yml` itself.  That way the restart could pick up the different input ERB template.

This actually applies to the `-c/--config` option as well. If a user decides to use a different --config the restart again would overwrite it.  Maybe this we can get rid of altogether? Using a different template is a feature a lot of users have requested, where using a different config file location may not be as useful.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737529645988) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
We could document updating the systemd config that runs the ood-portal generator on restart to use different arguments right now.

Doing this would mean that ood_portal.yml would be read by the ood-portal-generator as well as nginx_stage, though maybe that is appropriate - fewer places to configure things.

**Comment by johrstrom** [comment]
I'm not sure I follow, `nginx_stage` needs to know the location of the httpd template?

**Comment by treydock** [comment]
nginx_stage does not need to know about the apache template that I'm aware of.  I think it makes sense to remove the config flag. If a site really needs to store configs in a different path then they should use symlinks but it's very standard to have applications search for configs in a predefined set of places and not make it configurable.  I like the idea of putting the template into ood_portal.yml , centralizing behavior is also easier to test.

**Comment by johrstrom** [comment]
I'm going to close this as won't do just because who has the time and what's it really for?  The system works well as is and folks don't really need to know or care about extra flags.
