### ISSUE TITLE
batch_connect to support specifying the cluster in submit.yml.erb

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#529]
It came up in the PR linked below that users would like to change the cluster to submit to in the `submit.yml.erb` and not choose it in the `form.yml`. 

New requirement: https://discourse.osc.edu/t/multiple-clusters-from-a-single-app/959/3

> I would just need to be able to modify the cluster specified in
the form after the form is submitted but before the actual job submission occurs.

_Originally posted by @ericfranz in https://github.com/OSC/ondemand/pull/524#issuecomment-640547749_

This ticket should
* If they set `context.cluster` (a string) in the `submit.yml.erb` _that_ is the cluster that the job is submitted to.
* the batch connect app correctly saves the _new_ cluster so that this new cluster is being queried for information.
* errors need to be caught and messaging around those errors shown (i.e., couldn't create the adapter, you don't have access to that adapter)
* create a documentation ticket when merged

**Comment by ericfranz** [comment]
I changed the title to "specifying the cluster" because I think we want to support the case where cluster is not specified in form.yml but is specified in submit.yml(.erb) only.

**Comment by johrstrom** [comment]
I have code ready for this building off of the other PR mentioned above.

The interface in the `submit.yml.erb` would look like this. Specifically, we'd be looking for the `cluster` attribute of the templated yml.
```erb
<%-
  cluster = 'owens'
-%>
---
cluster: "<%= cluster %>"
batch_connect:
  template: "basic"
```

If you request a cluster that doesn't exist or is somehow problematic, you'd end up hitting this exception.
https://github.com/OSC/ondemand/blob/9142ae1eeccf3eefd38a3798ab50ce571cc250e1/apps/dashboard/app/models/batch_connect/session.rb#L112

If you don't request a cluster at all (either through submit or in the form), you get a brand new translatable error message.

I'll submit the PR when the other is closed so there's less confusion and rebasing issues.
