### ISSUE TITLE
Support ability to specify "all clusters" in a batch connect app

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#531]
https://github.com/OSC/ondemand/pull/524 added the ability to do `cluster: [ owens, pitzer]` instead of just `cluster: owens`. This feature would extend this ability to specify all clusters (and possibly other subsets). Clusters that are hidden or `job_allow?` false would be omitted when building the dropdown.

A simple solution that gives more capability for configuration would be to assume each cluster string is the middle of a regular expression inserted between`/^` and `$/`. Then `cluster: owens` would be processed as `clusters.map(&:id).grep(/^owens$/)` and `cluster: .*` for all clusters would be `clusters.map(&:id).grep(/^.*$/)`. And then cases like all clusters starting with o would be easy: `cluster: o*`.

We could also special case "*" so that if `cluster: *` is used we just use all the clusters.

**Comment by johrstrom** [comment]
Fixed in #536.
