### ISSUE TITLE
GitHub action to add issues to issue repo appears to not work

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#551]
This is supposed to create issues for each PR merged: https://github.com/OSC/ondemand/blob/master/.github/workflows/document-merge.yml

However, https://github.com/OSC/ondemand/pull/544 was merged 11 hours ago and an issue was not created.

**Comment by johrstrom** [comment]
Sigh, we're getting authentication issues. We may have to use the osc-wiag bot to do cross repo stuff. I'm looking into it.

**Comment by johrstrom** [comment]
This works now, it just created https://github.com/OSC/ood-documentation/issues/274.  I guess we'll wait to create follow ups if needed (to carry labels or change the title and body it of the issue it creates).
