### ISSUE TITLE
Merge our batch connect apps into a single repo

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#554]
Each app would be in a subdirectory. The rpm would be responsible for copying the app to the appropriate location.

When doing development, it would be a little annoying because we couldn't easily clone to ~/ondemand/dev and just use it, we might need to play symlink games unless we fixed at least search and loading of these plugin files in dev.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737636517500) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
I'd be concerned about other sites that reference our repos right now, such as in their Ansible scripts, or use our rpms in latest for deploying interactive apps - as if we switched to a single repo we would not be providing that anymore.

**Comment by ericfranz** [comment]
The plan as discussed with @treydock:

1. 1 version and 1 repo: batch_connect_osc
2. 1 directory per app
3. 1 spec file - produces an rpm per app (so a change to one app will result in generation of a bunch of new rpms but that is okay)
4. leave the old rpms but link to the new one (some people might reference the old ones)
5. CHANGELOG will prefix each fix or change with `app_name:` - see https://github.com/grafana/grafana/blob/master/CHANGELOG.md for an example
6. development will be slightly more annoying, but we could configure the paths for searching for dev apps in OnDemand to be configurable (and be multiple paths) so the dashboard would find batch connect apps at a different location

**Comment by johrstrom** [comment]
Would they all share the same version in puppet? It'll sort of trivialize semantic versioning, like Rstudio would jump from 1.x to 7.x if  we've been updating other things in between. That's OK I guess, as long as the changelog is up to date.  

I feel like I can move fast on an individual repo because it doesn't affect anything outside of it.  I guess as long as we have that safety in place it's OK. Which kind of answers my question about puppet, that all the apps should have their own version.

It'll be kind of odd if we're updating and releasing 2 apps at the same time, but I feel like we rarely do that.

**Comment by johrstrom** [comment]
But to the Ansible thing, I think if we just archive the old repo folks will still be able to clone it, which is what Ansible does. But I kind of doubt they pull ours as it'd probably be cleaner to fork and modify rather than clone and modify in place.

**Comment by treydock** [comment]
For Puppet it would look like this:

```
ondemand_batch_connect_apps:
  ensure: <version>
openondemand::install_apps:
  bc_osc_abaqus: "%{alias('ondemand_batch_connect_apps')"
  bc_osc_comsol: "%{alias('ondemand_batch_connect_apps')"
  # Example of what to do on stat host
  bc_desktop:
    mode: '0700'
```

The alias function in Hiera is how you reference non-strings from other places in Hiera.  For every batch connect app defined in Hiera, they would all get updated at same time when the single version is bumped.

**Comment by johrstrom** [comment]
Well I guess we'll have to practice sharing bc apps instead of installing development version. I'm thinking of Rstudio recently where I was tagging and deploying versions to dev for Shameema to test.  Now I knew these RPMs wouldn't go to production, but I installed them so she could see and use them and they were never promoted, so it was fine.

So with this scheme, basically anything in master will be in production, so I guess we'll just have to take more care with that fact and use `usr` apps more if we need to share with other folks.

**Comment by ericfranz** [comment]
>So with this scheme, basically anything in master will be in production

I had assumed that it would work the same way the ondemand repo works. You tag the repo following a specific condition and that tag gets generated as an rpm for production. If you tag the repo using a tag that indicates it is a test version it gets placed in the /ci/ repo and we can install it to webdev02.

**Comment by treydock** [comment]
Right so production non RC type tags to to `ci` repo and everything else goes to `latest` and for `ci` repo and ondemand dev nodes just run Puppet to install `latest` but for test and prod you'd have to bump the version in Hiera to get the version updated from new one in `latest` repo.  You could even tag non-RC and just not update Puppet and those would never get installed on test or dev nodes and could install them only on dev by running Puppet.  For test and prod, presence in the repo does not mean it will get installed.

**Comment by treydock** [comment]
To be extra clear, all packages to go to `ci` repo and RC and such packages are the ones that only go to `ci`.  So any tag will hit `ci` repo but only non-RC tags go to `latest`.

**Comment by johrstrom** [comment]
Let's say I have Rstudio updates in master and we tagged that to be _rc.  Then we need to update Jupyter in production so we give that a real tag. That production tag for Jupyter includes the developmental Rstudio updates.  Unless we're tagging off branches other than master?

**Comment by ericfranz** [comment]
I see what you mean. You can tag rc tags on branches other than master today, and that makes the most sense in this situation. So you are right - assume that master is production. Though we can just communicate, like we do with the ondemand_test branch in puppet. Sometimes we have things that are under test

In a sense, we do that today with OnDemand - assume it is production - in that we typically do not merge a PR that is missing a feature flag or breaks OnDemand in some way that we could not deploy a new version today.

This is the same problem as with when we moved to a mono repo for ondemand. We lost a little bit of flexibility deploying individual components (dashboard, shell) but we gain in other ways.

**Comment by johrstrom** [comment]
I'm going to close this as won't do just because we don't have the time and it seems to add little benefit other than 1 repo. We may revisit but it's unlikely.
