### ISSUE TITLE
run command after interactive job finishes

### ISSUE THREAD

**Issue by SpontaneousDuck** [OSC/ondemand#557]
I am working on making apps for my cluster and am wondering if there is a way to run a script when the user deletes an interactive job. I am hoping to perform some clean up operations when the user quits instead of the job expiring. It appears like deleting cancels `script.sh` so I cannot run something after the line creating the server and `clean.sh` also appears to only run when the job completes, not when it is canceled.

Thanks!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737529923968) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Hey there! No I don't believe this functionality exists yet in batch connect apps, as you indicate, `clean.sh` executes within the job and so if the job is killed or expires it doesn't run.

Though we have some functionality for what schedulers call `epilogues`, I don't think we expose that functionality through interactive apps.

**Comment by SpontaneousDuck** [comment]
Thanks! I have a workflow where an app builds a container to run and it would be wonderful to be able to clean that container up no matter how the job exits.

**Comment by johrstrom** [comment]
Hi sorry for the delay in getting back to you. What we've found is that scheduler's provide mechanisms to do this.  In Slurm they're called task epilog. That's something you could explore to handle this workflow.

https://slurm.schedmd.com/prolog_epilog.html

**Comment by johrstrom** [comment]
I'm going to close this as we don't have a way to do this beyond what the scheduler provides. As I've stated above, Slurm epilogues should do the trick and other schedulers may have similar features.

I also think that Slurm has direct container support - so that may be what you're looking for as well.
