### ISSUE TITLE
Shell crashes trying to figure out the default sshhost

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#569]
While looking at another PR, the shell app crashes with this error if I navigate directly to `/pun/dev/shell`. 

```
App 10393 output: Listening on 3000
App 10393 output: /users/PZS0714/johrstrom/ondemand/misc/ondemand/apps/shell/app.js:173
App 10393 output:   hostname = match[1] === "default" ? default_sshhost : match[1],
App 10393 output:                   ^
App 10393 output: 
App 10393 output: TypeError: Cannot read property '1' of null
App 10393 output:     at host_and_dir_from_url (/users/PZS0714/johrstrom/ondemand/misc/ondemand/apps/shell/app.js:173:19)
App 10393 output:     at Server.upgrade (/users/PZS0714/johrstrom/ondemand/misc/ondemand/apps/shell/app.js:236:17)
App 10393 output:     at Server.emit (events.js:198:13)
App 10393 output:     at onParserExecuteCommon (_http_server.js:553:14)
App 10393 output:     at onParserExecute (_http_server.js:499:3)
```

**Comment by matthu017** [comment]
if you navigate directly to `pun/dev/shell` then there is no value for match[1]. Use cases considered when making the default host and whitelist always considered that the `/ssh/owens.osc.edu/` or `/ssh/default/` would be there.
If this is a functionality you'd like to have, it can ssh to the default host if match[1] is null.
Not exactly sure how the regex will handle pathing w/this use case though

**Comment by johrstrom** [comment]
Yes, we'd want to keep existing behaviour. If I go to `/pun/sys/shell/` it redirects to -> `/pun/sys/shell/ssh` and I login to the `DEFAULT_SSHHOST` (or localhost if it's not set).
