### ISSUE TITLE
user_map_cmd also accepts piped std in 

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#57]
From this [discourse topic](https://discourse.osc.edu/t/forcing-lowercase-username-after-login/491/3).

Most bash programs expect things to be piped through standard in.  In the topic from this, the user simply wanted to force lowercase usernames. 

This simple configuration would have sufficed, but will not currently work because `user_map_cmd` expects  the `user_env` to be given as it's first (and only) argument. 

```bash
# /etc/ood/config/ood_portal.yml
---
# ...
user_map_cmd: "tr '[:upper:]' '[:lower:]'"
user_env: 'REMOTE_USER'
```

A workaround can be supplied to simply `echo $1 |  '[:upper:]' '[:lower:]'` in some shell script and call that, but it would be nice for users if they could just have one liners like this directly into the user_map_cmd without having to maintain other files and file locations.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737582185742) by [Unito](https://www.unito.io)

**Comment by matt257** [comment]
reviewed,
little gain for community if implemented,
would likely take a lot of effort

**Comment by epruesse** [comment]
@matt257 It would be nice if the regex option could do a regex-replace. I think a common scenario is just the lower-case of an AD supplied uppercase name that SSSD then doesn't like.
