### ISSUE TITLE
no need for cluster attribute in form if only one cluster config exists?

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#588]
In versions 1.7 and below it seems that if a site has only 1 configuration file, admins do not need to specify the `cluster` attribute in their `form.yml`.  That's more of a question than a statement as I've gotten this information off hand from our UBCCR partners and through a discourse topic so it's unclear to me whether this is true or not.

All the updates to submitting with multiple clusters, we've definitely broken this behaviour if it is in fact real, which I suspect it is.

**Comment by ericfranz** [comment]
Not a bug.
