### ISSUE TITLE
Choose a more secure default for the client id secret for Dex

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#590]
https://github.com/OSC/ondemand/blob/6a41ab65fca815b04fd2d553db8aa2b5d342cd88/ood-portal-generator/lib/ood_portal_generator/dex.rb#L157 specifies client secret default as `Digest::SHA1.hexdigest(client_id)`. This faciliates zero-config install - so you can do yum install ondemand and then start OnDemand and access it.

We could still support zero-config install but perhaps have a more secure solution by storing a generated secret in a file, perhaps in a 600 file `/etc/ood/dex/#{OodPortalGenerator.fqdn}.secret`.

**Comment by treydock** [comment]
To ease the burden on sites who may wish for multiple clients...if client ID is `ondemand` then search for file `/etc/ood/dex/ondemand.secret` if no path is specified.  This way sites using xdmod could have xdmod client ID and supply `/etc/ood/dex/xdmod.secret` if they wanted and it would "just work".  I also use a pattern in many Python programs at OSC where I do this:

```
if value is file:
  secret = read file
else
 secret = value
```
```

**Comment by ericfranz** [comment]
Related,  since we now encourage optionally specifying a custom secret in ood_portal.yml we should probably make that file by default have restricted permissions.
