### ISSUE TITLE
update_ood_portal does exit 1 on "no changes" 

### ISSUE THREAD

**Issue by wdpypere** [OSC/ondemand#60]
when you run update_ood_portal and the apache configuration does not change is does an ```exit 1```.
This seems wrong as no error has occured.

We have created a systemd unit file that adds the update_ood_portal to the ExecStartPre of httpd24-httpd.service like so:
```
cat /etc/systemd/system/httpd24-httpd.service.d/regen_config.conf 
[Service]
ExecStartPre=/opt/ood/ood-portal-generator/sbin/update_ood_portal
```
However systemd detects the exit 1 and fails the restart.

as a workaround this works:
```
ExecStartPre=/opt/ood/ood-portal-generator/bin/generate -c /etc/ood/config/ood_portal.yml -o /opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf
```

But it seems to me using the update_ood_portal would be better and the exit 1 is wrong.

**Comment by treydock** [comment]
Change `ExecStartPre` to be this:

```
[Service]
ExecStartPre=-/opt/ood/ood-portal-generator/sbin/update_ood_portal
```

Notice the hyphen before the command. That will cause systemd to not consider non-zero exit as a failure.

**Comment by treydock** [comment]
We use non-zero exit code to signal a change was made. It is a bit counter intuitive but if someone is writing scripts that use `update_ood_portal` it's handy to know if the script changed or didn't change the Apache configs.

**Comment by wdpypere** [comment]
@treydock thanks for the reply, I did not know that function of the hyphen. But that does mean if anything else goes wrong with the script systemd will also ignore it, right?

**Comment by treydock** [comment]
That's correct. I think I'll take the approach as Puppet with a flag like `--detailed-exitcodes` that will exit non-zero for changes but make default behavior to exit 0 upon success.

**Comment by treydock** [comment]
Opened #62 which would make default behavior exit 0 unless there's an actual error.
