### ISSUE TITLE
Hide Safari alert by default

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#608]
Now that we are using Dex as the default recommendation for authentication, we should not require sites to configure OnDemand to disable the Safari alert.

<img width="1125" alt="screen 2020-07-24 at 12 01 30 PM" src="https://user-images.githubusercontent.com/512333/88411170-74bc0b00-cda5-11ea-80f0-78bd0a83c591.png">

**Comment by msquee** [comment]
@ericfranz Should this error message be completely removed along with the `DISABLE_SAFARI_BASIC_AUTH_WARNING` environment variable?

Since Dex is enabled by default, I don't think a site would explicitly enable HTTP Basic Authentication over Dex.

**Comment by ericfranz** [comment]
You still have to manually install Dex. But maybe we should remove it completely.

**Comment by ericfranz** [comment]
https://github.com/OSC/ood-documentation/issues/333
