### ISSUE TITLE
Possible XDMoD integration bug with new XDMoD user not being mapped

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#611]
In the hpctoolset if you login with the hpcadmin to XDMoD prior to having submitted any jobs, you will be unmapped. Then after you submit jobs and they are ingested, you will not see job efficiency reports for that user until you fix the mapping.

If we enable XDMoD integration at OSC, the first thing new users might do is log into OnDemand, and that means we will try to sign them into XDMoD. Assuming that succeeds, won't they become "unmapped" since they have not submitted a job that completed and was ingested into XDMoD?

**Comment by treydock** [comment]
Mapping isn't a manual process with XDMOD.  If you sign into XDMOD without jobs there is no mapping performed IIRC but if you sign in with jobs there is a mapping.  If you start out unmapped because you had no jobs, I'm not sure if the XDMOD ingest steps each day will fix the mapping once you have jobs on the system.  I think that's a question for CCR. If there is manual mapping taking place at OSC then it's being done by Client Services who have admin rights inside XDMOD.  I know the manual mapping I've documented for OSC is the process of making someone a PI but that is not something to be worried about for OnDemand.

**Comment by ericfranz** [comment]
>I'm not sure if the XDMOD ingest steps each day will fix the mapping once you have jobs on the system

In the images the mapping was not fixed for the hpcadmin user and I had to manually fix the mapping. The rationale was I logged into XDMoD with hpcadmin when hpcadmin had no jobs. Since we are auto-logging in users to XDMoD when they log into OnDemand, every new user would theoretically have this experience if the first thing they do is access OnDemand - also this experience may be a shared by workshop users as well.

**Comment by treydock** [comment]
I wonder if the best solution to that problem is some new API functionality, if none already exists, in XDMOD that allows external apps to map users.  The mapping is pretty simple, just mapping one username to another if it exists in XDMOD database.

**Comment by plessbd** [comment]
So how Open XDMoD works:

If the user logs in via SSO it will try to link the user to the `systemaccount`.`username`.  That `systemaccount`.`username` is populated by jobs having been run.  If they have not run jobs, it will mapp them to `Unkown`

If you then ingest jobs that the user has run, if they are still logged in to Open XDMoD then they will not get remapped.

They will need to log out of Open XDMoD and out of the IdP and then upon logging in again, it will try to remap the user.

Though we can probably figure out some sort of an administrative API that could be used to update that mapping (technically it exists as part of the web ui, but there should be a more direct way of doing it)

**Comment by ericfranz** [comment]
According to @plessbd description, seems like the problem as stated would only occur in the time period, starting with these conditions

- user has been mapped to Unkown (because they logged in and there were no jobs)
- the user is logged into Open XDMoD
- the user ran some jobs
- those jobs have been ingested

The time period during which jobs would not appear would be the time when the first ingest of jobs runs while the user is logged to the time when the user logs out of Open XDMoD (or their session expires) and they are forced to log back into Open XDMoD, facilitated through the SSO process with OnDemand.

This window is at most 24 hours, and contingent on the user being logged into Open XDMoD at the time of ingest.

I think that this won't be a problem for users.
