### ISSUE TITLE
Sometimes after deleting a session job an error with a stack trace occurs due to incorrect redirect

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#620]
The user appears to be redirected to the uuid of the session as its own page, which is the wrong:

![image](https://user-images.githubusercontent.com/512333/88837727-84bd5b80-d1a6-11ea-9466-0a48f91e2e59.png)

**Comment by msquee** [comment]
To add some context, this happens for me sometimes when I move too fast and try to delete multiple sessions in quick succession.

**Comment by johrstrom** [comment]
duplicate of #659
