### ISSUE TITLE
Enable running Shell app tests in CI

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#623]
The Rakefile in the root of the directory has a task `rake test` that executes a bunch of tests in each app. We should add the Shell app to the mix.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737533004882) by [Unito](https://www.unito.io)

**Comment by lukew3** [comment]
Shell app testing has already been added to the `rake test` task in commit 21e8481bf51ece881a4bc83a6fafbdf2e44f25d9
