### ISSUE TITLE
qsub: illegal -N value

### ISSUE THREAD

**Issue by jxdn** [OSC/ondemand#641]
Hi Team,

I have on-demand portal, with PBS pro 19.1.3.
I can submit the job from the portal, file explorer, and shell working fine.

When i deploy bc_desktop, it have error 
Failed to submit session with the following error:

qsub: illegal -N value
usage: qsub [-a date_time] [-A account_string] [-c interval]
	[-C directive_prefix] [-e path] [-f ] [-h ] [-I [-X]] [-j oe|eo] [-J X-Y[:Z]]
	[-k keep] [-l resource_list] [-m mail_options] [-M user_list]
	[-N jobname] [-o path] [-p priority] [-P project] [-q queue] [-r y|n]
	[-R o|e|oe] [-S path] [-u user_list] [-W otherattributes=value...]
	[-S path] [-u user_list] [-W otherattributes=value...]
	[-v variable_list] [-V ] [-z] [script | -- command [arg1 ...]]
       qsub --version

This is my submit script.
---
script:
  native:
    - "-l"
    - "select=<%= bc_num_slots.blank? ? 1 : bc_num_slots.to_i %>:ncpus=28:mem=40gb"

this is my yml script:
---
title: "Desktop"
cluster: "my_cluster"
submit: "submit/mycluster_desktop.yml.erb"
attributes:
  desktop: "gnome"
  bc_queue: null
  bc_account: null

I think somehow it detects the scheduler is SLURM that's why using -N, even I change the native as -l in the submit script it keep using -N.

any idea how to fix this?

**Comment by ericfranz** [comment]
What does your cluster config file named and look like?

**Comment by jxdn** [comment]
Hi ,
managed to fixed it, 
pun_custom_env:
   OOD_JOB_NAME_ILLEGAL_CHARS: "/"

/etc/ood/config/ngink_stage.yml
