### ISSUE TITLE
Convention for bash conditionals?

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#67]
treydock johrstrom MorganRodgers

The update_ood_portal script (https://github.com/OSC/ondemand/blob/d626961a3183c9f73e15a1633ca11ece765d5087/ood-portal-generator/sbin/update_ood_portal) is inspiration for this question: is there a best practice for conditional expressions in bash?

I’ve seen arguments in the past in favor of always using double brackets.

In the update_ood_portal script we have three different approaches:

1. No brackets: `if ! grep -q "$APACHE" $SUM 1>/dev/null 2>&1; then`
1. Single brackets: `if [ sha256sum --quiet --status --check $SUM 1>/dev/null 2>&1 ] || [ ! -f "$APACHE" ]; then`
1. Double brackets: `if [[ $? -ne 0 ]]; then`
1. Mixed: `if [ $RPM -eq 1 ] || ! $REPLACE; then`

Is there a reason to not to just always use double brackets? How do you determine when?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737640910890) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
You can't put brackets around booleans like `$REPLACE` so in that case it's necessary to mix.

```
$ REPLACE=true
$ if [[ $REPLACE ]] ; then echo "REPLACE" ; else echo "NO REPLACE" ; fi
REPLACE
$ REPLACE=false
$ if [[ $REPLACE ]] ; then echo "REPLACE" ; else echo "NO REPLACE" ; fi
REPLACE
$ REPLACE=true
$ if $REPLACE ; then echo "REPLACE" ; else echo "NO REPLACE" ; fi
REPLACE
$ REPLACE=false
$ if $REPLACE ; then echo "REPLACE" ; else echo "NO REPLACE" ; fi
NO REPLACE

```

**Comment by treydock** [comment]
Also double brackets around some things isn't valid

```
[root@ood ~]# /opt/ood/ood-portal-generator/sbin/update_ood_portal 
Generating Apache config using YAML config: '/etc/ood/config/ood_portal.yml'
/opt/ood/ood-portal-generator/sbin/update_ood_portal: line 59: conditional binary operator expected
```

This is what I did:

```
if [[ sha256sum --quiet --status --check $SUM 1>/dev/null 2>&1 ]] || [[ ! -f "$APACHE" ]]; then
```

It was the double brackets around `sha256sum` that caused problems.

**Comment by johrstrom** [comment]
😆 my guess is @gerald-byrket would like this somewhere, please advise.

**Comment by treydock** [comment]
Per my previous comments, there can't be a standard, it really depends on what you are comparing.  I believe a lot of shell conventions we use come from shellcheck which is tests built into this repo.
