### ISSUE TITLE
(OpenXDMoD integration) recent jobs show "all jobs"

### ISSUE THREAD

**Issue by plessbd** [OSC/ondemand#684]
when an OpenXDMoD user is center staff or center director (probably PI) the job list shows "all jobs"

I am not 100% sure how to fix this (otherwise I would do a full PR), specifically I do not know if/where the response from the login is store (this should contain person_id) but this line needs to be modified

https://github.com/OSC/ondemand/blob/master/apps/dashboard/app/views/dashboard/_xdmod_widget_jobs.html.erb#L73

it should be
`jobsUrl.searchParams.set('params', JSON.stringify({person: openXDMoDUser.person_id}));`
Maybe have a way of switching between having that and not.

Hit me up on slack or in here if you have more questions

**Comment by ericfranz** [comment]
Ok, this works for the jobs widget but not for the aggregate widget. So currently if I am center staff with this change I will see something like:

![screen 2020-10-01 at 9 20 51 AM](https://user-images.githubusercontent.com/512333/94814567-86361a80-03c7-11eb-8a2b-be827566ad74.png)

* the aggregate is for a different user
