### ISSUE TITLE
(Open XDMoD integration) Change `XDMoD to Open XDMoD`

### ISSUE THREAD

**Issue by plessbd** [OSC/ondemand#685]
Would like to switch references of XDMoD to Open XDMoD.  If I find time I will put in a PR for this.

**Comment by msquee** [comment]
@plessbd Sourcegraph can make this easy, here: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/OSC/ondemand%24+XDMoD&patternType=literal&case=yes
