### ISSUE TITLE
ood-portal-generator tests require root escalation

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#699]
ood-portal-generator tests require root escalation and the apache group to exist. I never noticed before because I used to routinely run in a container where I could escalate. 

Here's an example of a test's stack trace.
```text
  10) update_ood_portal dex replaces dex config
      Failure/Error: exit!(false)
      
        OodPortalGenerator::Application received :exit! with unexpected arguments
          expected: (0)
               got: (false)
      # ./lib/ood_portal_generator/application.rb:274:in `rescue in start'
      # ./lib/ood_portal_generator/application.rb:243:in `start'
      # ./spec/update_ood_portal_spec.rb:150:in `block (4 levels) in <top (required)>'
      # ./spec/spec_helper.rb:105:in `with_modified_env'
      # ./spec/update_ood_portal_spec.rb:143:in `block (3 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # Errno::EPERM:
      #   Operation not permitted @ apply2files - /tmp/apache20201016-89023-134pl1b.new
      #   ./lib/ood_portal_generator/application.rb:189:in `update_ood_portal'
```
I believe I tracked it down to 
https://github.com/OSC/ondemand/blob/f99e4477229832f9e188a5227569261204b612ed/ood-portal-generator/lib/ood_portal_generator/application.rb#L178

and 
https://github.com/OSC/ondemand/blob/f99e4477229832f9e188a5227569261204b612ed/ood-portal-generator/lib/ood_portal_generator/application.rb#L189

Anyway, we should probably stub `FileUtils.chown` or force everyone to run unit tests in a container to isolate the environment, but is a much larger lift.

**Comment by ericfranz** [comment]
@treydock do you have any comment on this issue?

**Comment by treydock** [comment]
That's very odd, when I run the unit tests I do so on my Mac not within a container.  The only issue I've had is if I don't connect to VPN my GID doesn't map:

```
uid=623703847(tdockendorf) gid=758353319 groups=758353319,12(everyone),20(staff),62(netaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),702(com.apple.sharepoint.group.2),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae),701(com.apple.sharepoint.group.1)
```

Notice how `gid=` doesn't contain a group, and this causes unit tests to fail because my user account isn't really valid.  This particular issue is specific to OSC laptops where our primary group comes from Active Directory and won't map when not on VPN.

Without VPN where my GID is invalid:

```
  33) update_ood_portal dex replaces dex config
      Failure/Error: group = Etc.getgrgid(gid).name
      
      ArgumentError:
        can't find group for 758353319
      # ./spec/update_ood_portal_spec.rb:30:in `getgrgid'
      # ./spec/update_ood_portal_spec.rb:30:in `block (2 levels) in <top (required)>'
      # ./spec/update_ood_portal_spec.rb:126:in `block (3 levels) in <top (required)>'
```

With VPN:

```
No change in Apache config.
Backing up previous Dex config to: '/var/folders/mm/pgf9yph93zv49lg14gfrpqrrkksxs7/T/dex.yaml20201016-61214-o32jy.20201016T115145'
Generating new Dex config at: /var/folders/mm/pgf9yph93zv49lg14gfrpqrrkksxs7/T/dex.yaml20201016-61214-o32jy
chown tdockendorf:SI\Domain Users /var/folders/mm/pgf9yph93zv49lg14gfrpqrrkksxs7/T/dex.yaml20201016-61214-o32jy
chmod 600 /var/folders/mm/pgf9yph93zv49lg14gfrpqrrkksxs7/T/dex.yaml20201016-61214-o32jy
    replaces dex config

Finished in 0.38417 seconds (files took 0.3664 seconds to load)
51 examples, 0 failures
```

We mock the user and group assigned to the files: https://github.com/OSC/ondemand/blob/master/ood-portal-generator/spec/update_ood_portal_spec.rb#L27-L31

This means the chown operations should be happening as the person running the tests.

**Comment by johrstrom** [comment]
Yea looks like we already stub FileUtils chown and chmod, but not for this test case - `update_ood_portal`. I think what happened was this: I rebased to the current master and picked up these new dex tests. 

These tests pass on Pitzer login. So it could be my updated kernel/OS `5.8.12-200.fc32.x86_64` or that I have a slightly higher version of ruby `ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]` (`ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]` in our env).

In either case, if I add FileUtils chown and chmod stubs for this test case specifically and it works.
https://github.com/OSC/ondemand/blob/f99e4477229832f9e188a5227569261204b612ed/ood-portal-generator/spec/update_ood_portal_spec.rb#L142-L151

**Comment by johrstrom** [comment]
OK, went to make the patch for this, and it doesn't happen for me on master, so clearly it's some issue in rebasing `nginx_stage_prehook` to the current master.
