### ISSUE TITLE
navbar is a mix of lists and buttons

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#701]
The Dashboard navbar is a mix of lists and buttons. It seems that a screen-reader interprets them all as buttons but only `Files` and `Develop/Help` are interpreted as lists.

It seems like they should at least be consistent; that all buttons are also lists, or we remove the list functionality from `Files` and `Develop/Help`.  

Glancing at the resulting html I can't tell why this is the case.  Files button and say Jobs button appear to be the same html structure. 

Tested on Firefox, NVDA & Windows.

**Comment by ericfranz** [comment]
I wonder what the case is with the Bootstrap 4 navbar, and if we will face the same issue or if it will be improved.

**Comment by johrstrom** [comment]
This is a non issue.  I guess I thought the top level list (the NavConfig categories (Files through Interactive Apps) + All apps) shouldn't exist. Instead, if one was doing list navigation, they would hit Files, then Jobs, then Clusters.

But this is not the case.  A quick browse of other poplar websites wrap dropdown menu items in a top level list like we're currently doing. Which is - users list navigate to a list that starts with Files, and then item navigate through that list.
