### ISSUE TITLE
Set more secure default values for whitelist_paths/allowlist_paths

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#703]
* whitelist_paths/allowlist_paths are not set by default
* in 2.0 we should default to the home directory or home directory+favorites (and for job composer, perhaps also include the template directories in /etc/)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737588585612) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
Seems like we need to clarify requirements here. For example, we might want to support a deny_list and not let easy access to hidden directories by default (ssh keys, etc.)?

Also https://github.com/OSC/ondemand/issues/881 might change the story here altogether.

**Comment by matt257** [comment]
reviewed,
difficult and maybe a breaking change
