### ISSUE TITLE
Switch from SCL Apache to system Apache

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#706]
RHEL7 and 8 supports Apache 2.4 without requiring SCL. Switching away from SCL means all of the Apache authentication modules can be installed using rpm, without modifying the install locations.

**Comment by treydock** [comment]
Part of this involves relying on system Ruby for things directly called from Apache like the OOD user mapping scripts unless we hardcode the path to SCL Ruby in those scripts which would cause problems for sites not installing on RPM systems with SCL Ruby.  There could also be a build step to modify the script before install to put appropriate shebang at top of scripts.

**Comment by ericfranz** [comment]
Looks like we cannot do this for 2.0 since we want to support CentOS 7 and the system Apache version for CentOS 7 cannot proxy to unix domain sockets, currently a requirement for OnDemand.

**Comment by johrstrom** [comment]
There's nothing to do for this. Centos 7 won't be supported forever but it will be for at least the next few years.
