### ISSUE TITLE
Use Lua pattern matching as default mapping strategy in mod_ood_proxy  

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#710]
Instead of forking a process to execute Ruby to apply a regex to the Apache REMOTE_USER, the default mapping strategy should be Lua with pattern matching. Will need to identify common uses of the regex on REMOTE_USER and verify that the Lua pattern matching will be sufficient.

**Comment by treydock** [comment]
This would be great for moving to system Apache and not having Apache execute Ruby.

This is a semi complex regex we use for OIDC default Dex install to pull username out of email address: `'^([^@]+)@.*$'`.

**Comment by ericfranz** [comment]
One thing is that Lua doesn't support regex by default. I don't know yet what the Lua pattern matching equivalent of the regex you share there would be, and my guess is we might need to have some backwards support for forking a process to map the user, but then Ruby would just be an option and not a requirement (and definitely not SCL Ruby).

FWIW I do know luaposix supports http://luaposix.github.io/luaposix/modules/posix.fnmatch.html so you can do shell style pattern strings which might also be useful.

**Comment by treydock** [comment]
It does support regex by default, I make heavy use of it in SLURM job submit plugin that is Lua.

Example substring extract:

```lua
local out = string.match(script, "#PBS %-o ([^\n]*)\n")
```

There is regex support in the string library.

**Comment by ericfranz** [comment]
Which version of Lua? I was basing my statement off of what the Lua docs said in https://www.lua.org/pil/20.1.html for example:

>Unlike several other scripting languages, Lua does not use POSIX regular expressions (regexp) for pattern matching.
>
>Of course, the pattern matching in Lua cannot do all that a full POSIX implementation does. Nevertheless, pattern matching in Lua is a powerful tool and includes some features that are difficult to match with standard POSIX implementations.

**Comment by ericfranz** [comment]
I guess that's what I meant to say - if `string.match` lets us do everything we want to do then great!

**Comment by treydock** [comment]
```
[root@pitzer-slurm01 ~]# lua -v
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
```

The string library has many ways to handle regexes.  Also the characters needing to be escaped is much different than with Ruby.

**Comment by ericfranz** [comment]
Duplicate of https://github.com/OSC/ondemand/issues/728
