### ISSUE TITLE
Pinned apps on the dashboard

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#714]
- [x] Admin can configure specific apps (`sys/bc_osc_ansys_workbench`, `sys/bc_desktop/vdi`), 
   - [x] or group of apps by type (`type: usr` apps, all `type: sys` apps, all `type: dev` apps)
   - [ ] or group apps by categories/subcategories
   - [ ] or group apps by metadata keys (`field_of_science: `)
- [x] A new `metadata: yaml` map can be added to manifest files, with arbitrary key/value pairs that will be used in this selection.
- [x] Configured pinned apps can be specified in a config file in `/etc/ood/config/config.yml` (a new config file to start centralizing configuration to)
- [x] Can ERB render `/etc/ood/config/config.yml.erb` to provide per-user pinned app lists (unless we want to provide a simpler approach to providing per user or per group control using just yaml - like a `default:` then `per_user:` then `per_group:` config)
- [x] If pinned apps are specified, a new "Apps", menu is added to top left corner
- [x] If pinned apps are specified, a new Apps widget is added to the top right corner of the dashboard view, above the MOTD, displaying apps as icons similar to the macOS Launcpad or the iOS/Android app launch interface

![screen 2020-10-26 at 2 23 09 PM](https://user-images.githubusercontent.com/512333/97212472-dae66e80-1796-11eb-87c4-93080cd00d32.png)

**Comment by ericfranz** [comment]
So an MVP would just be allowing admin to specify a config.yml with something like

```
pinned_apps:
  - sys/bc_osc_ansys_workbench
  - sys/bc_desktop/vdi
```

And then those appear.

**Comment by johrstrom** [comment]
```yaml
pinned_apps:
  - usr/efranz/*
  - category: Interactive Apps
    subcategory: Servers
    field_of_science: Chemistry
