### ISSUE TITLE
Redesign All Apps page using datatable

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#715]
- [x] Link to All Apps appears at bottom of the Apps menu in https://github.com/OSC/ondemand/issues/714
- [x] Datatable shows list of all apps user has access to
- [ ] Datatable includes custom columns for app manifests that specify the `metadata:` map (with one key per column)
- [x] Consolidate the files and shell apps as single launch icons with dropdown for the launch options

**Comment by johrstrom** [comment]
Need a little clarity on the last item for showing pinned apps at the top of the table. Are you saying Pinned apps should be rows items within the table or should they appear as icons like they do in the dashboard?

If it's the former, I think the only thing we could do is add hidden text to ensure a proper default sorting order?

I don't know if any sorting order is guaranteed without some hidden text. 
![image](https://user-images.githubusercontent.com/4874123/107977616-66c01880-6f89-11eb-99bb-6cc3d4891b1b.png)
