### ISSUE TITLE
Add ability for user to specify "favorite apps"

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#716]
1. A "clickable star" or other mechanism to specify an app favorite appears in the All Apps page: https://github.com/OSC/ondemand/issues/715
1. Apps marked as favorite appear at top of the page
1. Apps marked as favorite appear in the Apps dropdown above pinned apps
1. Apps marked as favorite appear in the apps widget on the dashboard (along above pinned apps https://github.com/OSC/ondemand/issues/714)
1. `$XDG_CONFIG_HOME/ondemand/config.yml` contains the list of app favorites and this acts as the storage convention for user settings

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737589173338) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Yes please! related to https://github.com/OSC/ood_core/issues/182

**Comment by ericfranz** [comment]
MVP here is you manually edit the config.yml and then reload the dashboard.

**Comment by johrstrom** [comment]
This is kinda in progress now. It's not `favorite apps`, but `saved settings`. So it's not like you're saving Jupyter as your favorite application, it's more like you're saving XYZ settings for Jupyter to relaunch it with those settings. So I'm going to close as in progress or superseded by other features.
