### ISSUE TITLE
Recent apps

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#717]
1. Can piggyback off implementation for https://github.com/OSC/ondemand/issues/716 in storing a record of recently accessed apps. An "access" in this case could be something more substantial, such as a job submission (launching RStudio) or creating a new job directory from a template in the Job Composer, instead of just navigating to the app (unless the app is outside of the core apps - such as Weld Predictor). Each "access" can result in updating a list in the config.yml.
1. The list of recent apps should be limited to 5.
1. List of recent apps appears above favorite apps in launch widget and apps dropdown

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737643576134) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
This has been fixed in #2477
