### ISSUE TITLE
Optional chaining (?.) is not supported in all browers

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#737]
The javascript feature [optional chaining (?.)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) is not supported in all browsers (see the linked documentation for a table). 

In particular, this is where we use them.
https://github.com/OSC/ondemand/blob/7ce5276d76d877ecf33985ca1df349a939da0531/apps/dashboard/app/views/dashboard/_xdmod_widget_job_efficiency.html.erb#L52

We can close as 'won't fix' but it should at least be a concious decision to do so.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737644607177) by [Unito](https://www.unito.io)

**Comment by msquee** [comment]
@ericfranz @johrstrom Here's a working replacement that uses a ternary operator:

```js
user.results ? user.results.person_id ? user.results.person_id : undefined : undefined
```

**Comment by ericfranz** [comment]
According to the table on that page, it is not supported in:

1. IE
2. Firefox for Android
3. Opera for Android
4. Samsung Internet

We said we would drop IE. Is the only mobile browser here under consideration supporting "Firefox for Android"?

If we want to consider that, I think we need to know the full scope of JS features that are not supported by this and identify places we use those unsupported features.

Regardless, two tenary operators in a row is difficult to read. This is preferable if we use that approach and also shorter:

```
"filters": { "person": (user && user.results) ? user.results.person_id : undefined }
```

**Comment by lukew3** [comment]
Optional chaining supported by all but IE via [caniuse.com](https://caniuse.com/mdn-javascript_operators_optional_chaining)
