### ISSUE TITLE
General purpose ERB rendering

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#759]
From [this PR](https://github.com/OSC/ondemand/pull/647) we can render ERB templates in the MOTD classes.  Apps can render `form.yml.erb`, `submit.yml.erb` and all files in a `template` directory.

This ticket is to make some common use cases in ERB rendering more easily available to those renders.

The idea being something like this function available because I know I use it all the time to determine of the user is in a group.

```ruby
def groups
  @groups ||= OodSupport::Process.groups.map(&:name)
end
```

Whether this is another class entirely or just module functions that we include in the classes that render is unclear. It's likely the implementer is going to have to experiment a bit and find what's the cleanest both to implement and maintain and then to use by an app developer or admin writing ERB MOTDs.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204178337465483) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
I think the first steps here are to:

1. enumerate all of the places where we do custom ERB rendering (not Rail's views) with links to code or even code examples, explaining what the context is
2. of those places, identify which ones we want to extend to include groups and username (is there anything else?)
3. of those ones we want to extend, determine the steps to extend those
4. given those code changes, identify an abstraction that can be refactored to (if one exists)

**Comment by johrstrom** [comment]
I'm going to close this in favor of #906. With `CurrentUser` this may already be done, but #906 is indeed not complete.
