### ISSUE TITLE
VNC key bindings question

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#781]
Someone in [discourse here](https://discourse.osc.edu/t/how-to-increase-font-size-in-vnc-terminal/944/2) wanted to use ctrl++ to resize windows. It's unclear if that's possible right now or if we need to add a feature to the vncserver to `SendSpecialKeys=FALSE` or how that may be accomplished.

Also this may even just be a documentation ticket so it could move to that repo instead after some investigation.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202827505743809) by [Unito](https://www.unito.io)

**Comment by charmichaeld** [comment]
I requested this earlier but now there is a way with OnDemand version 2.0.28 which has a newer version of noVNC that now has a 'Toggle Ctrl' button.
To increase the font size, click the 'Show Extra Keys' button in the noVNC toolbox menu and click the Ctrl button. Then mouse over the terminal and press and hold the right-click mouse button and a menu will pop up allowing you to change font size. Then you can toggle the Ctrl key back after changing the font size.
![vnc](https://user-images.githubusercontent.com/4388946/201222092-b9263b00-6e66-40e3-b4f2-2fa167ab908b.png)

**Comment by Oglopf** [comment]
Thanks for the update! Closing this since the functionality now exists.
