### ISSUE TITLE
Make path to /var/www/ood/apps apps directory easily configurable 

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#782]
Currently the knowledge of where these apps are located is duplicated between nginx_stage and the dashboard app.

As a result, while we could change the location of these apps in nginx_stage.yml the dashboard has the original paths hardcoded:

* dev: https://github.com/OSC/ondemand/blob/3b10306e4cb94260d40bf642bd28f0e409e67fa6/apps/dashboard/app/apps/dev_router.rb#L28-L30
* sys: https://github.com/OSC/ondemand/blob/3b10306e4cb94260d40bf642bd28f0e409e67fa6/apps/dashboard/app/apps/sys_router.rb#L31-L33
* usr: https://github.com/OSC/ondemand/blob/3b10306e4cb94260d40bf642bd28f0e409e67fa6/apps/dashboard/app/apps/usr_router.rb#L59-L84

Removing this duplication would help.

Another approach would be to shift the scanning of apps users can launch to nginx_stage, generating the app configs dynamically like we generate the nginx_stage config.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737674657261) by [Unito](https://www.unito.io)

**Comment by Oglopf** [comment]
This issue should be labeled bug as we say the `sys` path can be configured in our docs, but it can't. We've also had a user bring this to our attention on the discourse and request that it get fixed.

Adding some tags to prioritize the work.

**Comment by matt257** [comment]
unclear how to implement this given how .rpm and .deb files are built

**Comment by fenz** [comment]
@matt257 The issue was closed but the documentation (linked in the message right before) still says it is possible.
If you decided it can't be done then you may really want to remove it from the documentation.
