### ISSUE TITLE
Merge file editor into the dashboard

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#783]
Breaking up #711 into several tickets, this ticket is for merging the file editor app into the dashboard app.

Open questions are:
* how (if?) to keep the URLs for backward compatibility. 
* How to deal with permissions if sites want to only allow this app for only certain group(s).
    * I'm guesisng we likely _can't_ do this through just file permissions, we'll likely have to add some sort of allowlist or blocklist configuration.

**Comment by ericfranz** [comment]
For URLs for backwards compatibility, we can add to the nginx configs a set of redirects for the preexisting apps. We can also make that nginx block configurable.

For dealing with permissions there are several options.

1. We support optional backwards compatibility with the old directories by adding the routes for the file editor only if the "file-editor" directory is readable/executable by the user.
2. We support access to the new file editor using a controller in a namespace. So, for example, the controller might be under `app/controllers/file-editor/file_editor_controller.rb` but the rest of the code (if any) would be outside of that namespace. Then an admin could control file permissions on ``app/controllers/file-editor` directory but any other model, js, css code could be in places that is reusable by other parts of the app. This could be the same strategy with other apps.
3. We support access to the new file editor using a boolean flag in a config file

**Comment by ericfranz** [comment]
Note: what should change should be the "root URL" of the file-editor, not the URL patterns following that, so we can continue to use https://github.com/osc/ood_appkit#file-editor-app URL helpers that are used throughout the code - we would just be setting a new location by default.

**Comment by johrstrom** [comment]
Thinking about this a second time - why would we want to restrict access to the file editor?  Seems like if you have rx permissions to a file you should be able to edit it.  If you have access to OnDemand you should be able to edit it through a browser. Why should we allow the limitation?

**Comment by ericfranz** [comment]
Because you don't want the user to use the web interface to edit arbitrary files. We do this on apps.totalsim.us:

```
efranz@web03:~$ ls -l /var/www/ood/apps/sys/
total 36
drwxr-xr-x  9 root root 4096 Dec 14 16:47 .
drwxr-xr-x  5 root root 4096 Dec 14 16:47 ..
drwx------ 14 root root 4096 Dec 15 12:37 activejobs
drwx------  3 root root 4096 Dec 15 12:37 bc_desktop
drwxr-xr-x 13 root root 4096 Dec 15 12:37 dashboard
drwx------ 14 root root 4096 Dec 15 12:37 file-editor
drwx------  8 root root 4096 Dec 15 12:37 files
drwx------ 14 root root 4096 Dec 15 12:37 myjobs
drwx------  9 root root 4096 Dec 15 12:37 shell
```
