### ISSUE TITLE
set HOME to be different from what's in LDAP

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#79]
From [discourse](https://discourse.osc.edu/t/missing-home-directory-error/541/2)

```
We connect to Active Directory but we override it with sssd settings since the value in 
Active Directory does not match our system. We do this with "override_homedir = 
/users/%u" option. It is working fine on the command line for users just not 
through ondemand.
```

Essentially they need to override the home directory from the Etc module [here](https://github.com/OSC/ondemand/blob/17e3011b4529470f8d211f996b9750e869c8b605/nginx_stage/lib/nginx_stage/user.rb#L27) because the value in LDAP is incorrect.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737646387302) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
There is also this issue:

https://github.com/OSC/ood_support/blob/a5e42a1b31d90763964f39ebe241e69c15d0f404/lib/ood_support/user.rb#L27

So the problem may be present in other areas beside [checking for the existence of the home directory on startup](https://github.com/OSC/ondemand/blob/357c23d794022fef7813741b8b8f42edde2d4b21/nginx_stage/lib/nginx_stage/views/pun_config_view.rb#L90-L92)

**Comment by ericfranz** [comment]
http://rfranz.com/2018/10/31/ruby_home_and_getpwnam.html
