### ISSUE TITLE
Selinux context in $HOME/ondemand is blocking permissions to the owning user

### ISSUE THREAD

**Issue by sleonard617** [OSC/ondemand#843]
Greetings,

I am seeing some permissions issues in the user home dir based on selinux context.
```
An example from the user perspective:
[shawn.m.leonard@host1 ~]$ ls -lrt ondemand/data/sys/dashboard/batch_connect/sys/rstudio/output/2c6bb63c-25b2-42ca-92d2-d0ee5a55b85d/
ls: cannot access ondemand/data/sys/dashboard/batch_connect/sys/rstudio/output/2c6bb63c-25b2-42ca-92d2-d0ee5a55b85d/job_script_options.json: Permission denied
ls: cannot access ondemand/data/sys/dashboard/batch_connect/sys/rstudio/output/2c6bb63c-25b2-42ca-92d2-d0ee5a55b85d/job_script_content.sh: Permission denied
ls: cannot access ondemand/data/sys/dashboard/batch_connect/sys/rstudio/output/2c6bb63c-25b2-42ca-92d2-d0ee5a55b85d/before.sh: Permission denied
ls: cannot access ondemand/data/sys/dashboard/batch_connect/sys/rstudio/output/2c6bb63c-25b2-42ca-92d2-d0ee5a55b85d/script.sh: Permission denied
ls: cannot access ondemand/data/sys/dashboard/batch_connect/sys/rstudio/output/2c6bb63c-25b2-42ca-92d2-d0ee5a55b85d/user_defined_context.json: Permission denied
total 11
-?????????? ? ?               ?               ?            ? user_defined_context.json
-?????????? ? ?               ?               ?            ? script.sh
-?????????? ? ?               ?               ?            ? job_script_options.json
-?????????? ? ?               ?               ?            ? job_script_content.sh
-?????????? ? ?               ?               ?            ? before.sh
drwxr-xr-x. 2 shawn.m.leonard domain users 4096 Dec 14 14:44 bin
-rw-------. 1 shawn.m.leonard domain users  110 Dec 16 13:07 connection.yml
-rwx------. 1 shawn.m.leonard domain users  364 Dec 16 13:07 rsession.sh
-rw-r--r--. 1 shawn.m.leonard domain users  187 Dec 16 13:07 rsession.log
-rw-r--r--. 1 shawn.m.leonard domain users 4493 Dec 16 14:07 output.log
```
From the root perspective of the same directory:
```
[root@host1]# ls -lrtZ /home/shawn.m.leonard/ondemand/data/sys/dashboard/batch_connect/sys/rstudio/output/466ba98f-358d-47c7-930d-9c2f468798ab/
drwxr-xr-x. shawn.m.leonard domain users system_u:object_r:user_home_dir_t:s0 bin
-rw-r--r--. shawn.m.leonard domain users system_u:object_r:user_home_dir_t:s0 user_defined_context.json
-rwxr-xr-x. shawn.m.leonard domain users system_u:object_r:user_home_dir_t:s0 before.sh
-rwxr-xr-x. shawn.m.leonard domain users system_u:object_r:user_home_dir_t:s0 script.sh
-rw-r--r--. shawn.m.leonard domain users system_u:object_r:user_home_dir_t:s0 job_script_content.sh
-rw-r--r--. shawn.m.leonard domain users system_u:object_r:user_home_dir_t:s0 job_script_options.json
-rw-------. shawn.m.leonard domain users user_u:object_r:user_home_t:s0   connection.yml
-rwx------. shawn.m.leonard domain users user_u:object_r:user_home_t:s0   rsession.sh
-rw-r--r--. shawn.m.leonard domain users user_u:object_r:user_home_t:s0   rsession.log
-rw-r--r--. shawn.m.leonard domain users system_u:object_r:user_home_t:s0 output.log
```
As you can see, the user does not have access to the `system_u:object_r:user_home_dir_t`.

Interestingly, the jobs perform exactly as expected.  However, with this permission issue the user can not remove these files or directories in the ondemand directory in their space.  

Any insight or advice would be greatly appreciated.

Thank you!

**Comment by johrstrom** [comment]
I was chatting with @sleonard617  on slack and he's running 1.7 with `ondemand-selinux` installed.

**Comment by johrstrom** [comment]
I guess maybe we should ask for `uname -a` and the output from `rpm -qa selinux*` for good measure.

**Comment by sleonard617** [comment]
```
[root@host1]# uname -a
Linux host1 3.10.0-957.21.3.el7.x86_64 #1 SMP Fri Jun 14 02:54:29 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@host1]# rpm -qa selinux*
selinux-policy-3.13.1-268.el7_9.2.noarch
selinux-policy-targeted-3.13.1-268.el7_9.2.noarch
```

**Comment by johrstrom** [comment]
My files in a similar directory have this policy `system_u:object_r:nfs_t:s0` is your $HOME directory an NFS mount?

Also, and I don't know if this is necessary to add but the PUN starts under `system_u:system_r:ood_pun_t:s0` context which may be why the files are under `system_u`?

**Comment by sleonard617** [comment]
Our storage cluster and home dirs are GPFS

**Comment by johrstrom** [comment]
Did you mount it with special `-o context=` options?  I can't tell from our autofs config files, but it appears `nfs_t` is the default? @treydock any idea?

**Comment by treydock** [comment]
OnDemand itself has zero control over the context of files created in a user's home directory.  The only SELinux contexts OnDemand manages are on the web server for files used to run the PUN and related things, the files created in home directories are purposely not managed by policies we create because trying to create policies for the many ways home directories can exist is not possible especially when things like NFS set the policies for the entire mount point so what OnDemand could do in case of NFS is nothing.  That means that I believe the context `user_home_dir_t` is correct context and that's likely based on the path starting with `/home`.

The only policy we have that has anything to do with home directories is the boolean `ondemand_manage_user_home_dir` which allows the OnDemand PUN to access files with context `user_home_dir_t`.  So if the issue you are facing is that OnDemand cannot access those files then you will need to do `setsebool -P ondemand_manage_user_home_dir=on`: https://osc.github.io/ood-documentation/latest/installation/modify-system-security.html#ood-selinux

**Comment by treydock** [comment]
One clarification, majority of times the context for a file is based on the path. So base OS policies treat anything stored under `/home` to have a specific context.  The only contexts we set based on paths are paths managed by the OnDemand RPM and by OnDemand processes directly. Because home directory paths can be so varied from center to center, we cannot manage the context of things stored in home directories because we have no way to know what the path of home directories might be.

Why some files are `user_home_t` and some are `user_home_dir_t` I am not sure unless the host those files were created from had different underlying methods of access for that shared filesystem or the systems creating those files had different SELinux policies set for what context to assign files stored under `/home`.

**Comment by johrstrom** [comment]
I can clear up the files - `job_script_options.json` is created by OOD on the OOD webserver and `connection.yml` was created during the job's execution (Slurm?) on the compute node.

```
-rw-r--r--. shawn.m.leonard domain users system_u:object_r:user_home_dir_t:s0 job_script_options.json
-rw-------. shawn.m.leonard domain users user_u:object_r:user_home_t:s0   connection.yml
```

**Comment by sleonard617** [comment]
ondemand_manage_user_home_dir bool is "on" and has been since install.

And as Jeff points out, its the files created by OOD that get context owner "system_u".  Files made by the submitted job get context owner "user_u".  So I don't think its "user_home_dir_t" vs "user_home_t" (both can be found in the applied .te files) but in the context owner.

**Comment by sleonard617** [comment]
a little more information:

looking only at the user_defined_context.json file
```
[root@compute-sleonard-client-1 ~]# restorecon -nv -RF /home/shawn.m.leonard/ondemand/data/sys/dashboard/batch_connect | grep user_defined_context
restorecon reset /storage1/fs1/home1/Active/home/shawn.m.leonard/ondemand/data/sys/dashboard/batch_connect/sys/rstudio/output/a74686dc-2d64-40ff-a53d-77bd0957e29e/user_defined_context.json context system_u:object_r:user_home_dir_t:s0->user_u:object_r:user_home_t:s0
restorecon reset /storage1/fs1/home1/Active/home/shawn.m.leonard/ondemand/data/sys/dashboard/batch_connect/sys/jupyter/output/43d5f137-9d5f-4e4f-8ca2-c9db936860c5/user_defined_context.json context system_u:object_r:user_home_dir_t:s0->user_u:object_r:user_home_t:s0
```

and looking at the nginx process that wrote it:
```
[root@compute-sleonard-client-1 ~]# ps -efZ|grep nginx
system_u:system_r:ood_pun_t:s0  root     23348     1  0 14:00 ?        00:00:00 nginx: master process (shawn.m.leonard) -c /var/lib/ondemand-nginx/config/puns/shawn.m.leonard.conf
system_u:system_r:ood_pun_t:s0  shawn.m+ 23351 23348  0 14:00 ?        00:00:00 nginx: worker process
```

**Comment by treydock** [comment]
The context role is set by the role of the pun:

```
role system_r types ood_pun_t;
```

But if the issue is the user in the context, that's not something we've explicitly set by policies to `system_u` that is either getting inherited by the `system_r` role of the PUN or some other mechanism is setting that on files created by the PUN.  I'm not 100% sure how to go about making `system_u` become `user_u` from the context of files created by OnDemand.  I can experiment a little and see if it's as simple as changing the role.

**Comment by treydock** [comment]
I think the `system_u` looking at the process output looks like it's getting inherited because it's originally root that launches the processes, so that's an architectural aspect to OnDemand that might not be something we can change.  Because processes inherit the context of their parent process, I cannot think of a way to transition a root owned process from `system_u` to `user_u`.

**Comment by treydock** [comment]
I compiled the SELinux policy in Vagrant with SELinux enabled and set the role to `user_r` for `ood_pun_t` but that does nothing to change the behavior.  I also tried forcing nginx to use `user_u` user context via modified policy but that is not working.  Changes I attempted are below. I'm far from an SELinux expert so not really sure yet why this did not work to at least modify the context forced for the nginx binary.

```diff
diff --git a/packaging/ondemand-selinux.fc b/packaging/ondemand-selinux.fc
index 3d392185..0ea69132 100644
--- a/packaging/ondemand-selinux.fc
+++ b/packaging/ondemand-selinux.fc
@@ -1,7 +1,7 @@
 /opt/ood/nginx_stage/bin/(.*)? gen_context(system_u:object_r:ood_pun_exec_t,s0)
 /opt/ood/nginx_stage/sbin/(.*)? gen_context(system_u:object_r:ood_pun_exec_t,s0)
-/opt/ood/ondemand/root/usr/sbin/nginx gen_context(system_u:object_r:ood_pun_exec_t,s0)
-/opt/ood/ondemand/root/usr/lib64/passenger/support-binaries/PassengerAgent gen_context(system_u:object_r:ood_pun_exec_t,s0)
+/opt/ood/ondemand/root/usr/sbin/nginx gen_context(user_u:object_r:ood_pun_exec_t,s0)
+/opt/ood/ondemand/root/usr/lib64/passenger/support-binaries/PassengerAgent gen_context(user_u:object_r:ood_pun_exec_t,s0)
 /var/run/ondemand-nginx(/.*)?     gen_context(system_u:object_r:ood_pun_var_run_t,s0)
 /run/ondemand-nginx(/.*)?     gen_context(system_u:object_r:ood_pun_var_run_t,s0)
 /var/lib/ondemand-nginx(/.*)?     gen_context(system_u:object_r:ood_pun_var_lib_t,s0)
diff --git a/packaging/ondemand-selinux.te b/packaging/ondemand-selinux.te
index 7fe39b79..888107b1 100644
--- a/packaging/ondemand-selinux.te
+++ b/packaging/ondemand-selinux.te
@@ -1,4 +1,4 @@
-policy_module(ondemand-selinux, @VERSION@)
+policy_module(ondemand-selinux, 2.0.1)
 
 require {
   type bin_t;
@@ -15,6 +15,7 @@ require {
   type krb5_conf_t;
   type sssd_var_run_t;
   class dbus send_msg;
+  role user_r;
 }
 
 # Define custom types
@@ -25,7 +26,7 @@ type ood_pun_exec_t;
 domain_type(ood_pun_t);
 domain_entry_file(ood_pun_t, ood_pun_exec_t);
 init_daemon_domain(ood_pun_t, ood_pun_exec_t);
-role system_r types ood_pun_t;
+role user_r types ood_pun_t;
 
 # executable support
 can_exec(ood_pun_t, ood_pun_exec_t)
```

**Comment by treydock** [comment]
Changing the context of binaries does not change the context of process:

```
[root@ood vagrant]# ls -laZ /opt/ood/ondemand/root/usr/sbin/nginx 
-rwxr-xr-x. root root user_u:object_r:ood_pun_exec_t:s0 /opt/ood/ondemand/root/usr/sbin/nginx

[root@ood vagrant]# ps -efZ|grep nginx
system_u:system_r:ood_pun_t:s0  root      5532     1  0 22:44 ?        00:00:00 nginx: master process (ood) -c /var/lib/ondemand-nginx/config/puns/ood.conf
system_u:system_r:ood_pun_t:s0  ood       5533  5532  0 22:44 ?        00:00:00 nginx: worker process
```

I think the issue might stem from the fact the initial process is launched as root and changes to the user running OnDemand.

**Comment by sleonard617** [comment]
Thanks!  I looking at some context updates too to see if I can come up with something.  I'll let you know if I find anything useful.

**Comment by sleonard617** [comment]
I am able to allow the user to delete directories (but not files) by adding the following update to the rules to my .te and deploying:

-allow user_t user_home_dir_t:file { append ioctl open read write };
+allow user_t user_home_dir_t:file { append ioctl open read write unlink };

While solves a symptom but not the cause.  User still can't read the files or remove an individual file but can `rm -rf` the directory.  This confuses me, but audit2allow displayed it and it worked.

That the restorecon displays updates but with this update rule nothing gets logged when interacting as the user with the denied permissions is very confusing.

**Comment by treydock** [comment]
If there are denials but nothing logged you could be facing "do not audit" denials: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security-enhanced_linux/sect-security-enhanced_linux-fixing_problems-possible_causes_of_silent_denials.  Those are silent denials that you can get logged but it will cause a huge flood of logs to the audit logs as there are usually a lot of silent denials.

**Comment by sleonard617** [comment]
ooooh, TIL!

Thank you for that!  With dontaudit disabled I can now see the denial (getattr) and applied the patch.  For future reference to anyone that needs it:

+ class file { append create execute execute_no_trans ioctl lock open read rename getattr setattr unlink write };
+ allow user_t user_home_dir_t:file { append ioctl open read write unlink getattr };

With this, the symptom is controlled.  The context is still owned by system_u as indicated by restorecon  -nv -RF, and that doesn't sound like its fixable.
