### ISSUE TITLE
Address change in build from source directions

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#85]
See discussion ending with https://github.com/OSC/ondemand/pull/82#discussion_r335245018.

Summary is https://github.com/OSC/ondemand/pull/82 stopped "building" the infrastructure components, which were just a recursive copy to a build directory and rake install was a recursive copy from build to other locations.

So build directions changed like this:

```diff
 rake build
 rake install
+cp -r mod_ood_proxy /opt/ood/
+cp -r nginx_stage /opt/ood/
+cp -r ood-portal-generator /opt/ood/
+cp -r ood_auth_map /opt/ood/
```

We could update the `rake install` to "do a long rsync command with 5 sources all going to single destination" and then install from source would be `rake build && rake install`.

Instead I'd prefer:

1. change the code so the directory structure stay basically the same when deployed to /opt/ood (i.e /opt/ood/apps for core apps instead of /var/www/ood/apps/sys) 
1. remove the need for a rake install all together (if you want to move the directory to /opt/ood when installing from source, that could be your choice)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737593480298) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
https://github.com/OSC/ood-ansible/pull/3 created. Fairly simple change.
