### ISSUE TITLE
Interactive App question

### ISSUE THREAD

**Issue by btsherid** [OSC/ondemand#850]
Hi,

Is it possible to have a different max value for memory for certain queues for an interactive app?

This is what I currently have in form.yml.erb:
  custom_queue:
    label: Partition
    help: Please select a partition from the drop-down
    widget: select
    options:
      - [ "allnodes", "allnodes" ]
      - [ "crunchnodes", "crunchnodes" ]
      - [ "bioinformatics", "bioinformatics" ]
      - [ "gpu", "gpu" ]
      - [ "abacus", "abacus" ]
  bc_mem:
    label: "Memory"
    widget: "number_field"
    required: true
    help: "Please input a value between 1 and 8 (GB)"
    min: 1
    max: 8
    step: 1

I'd like to do something like if custom_queue = abacus, bc_mem.max=16 else bc_mem.max=8.

I tried to do something like the if statement from this page, but couldn't get it working. https://osc.github.io/ood-documentation/master/app-development/interactive/submit.html

Thank You,
Brendan Sheridan

**Comment by johrstrom** [comment]
Hey, thanks for the ticket, it reminded me to open #851.

Right now you have to add your own javascript do do this. You can checkout our jupyter app at https://github.com/OSC/bc_osc_jupyter to see how we add `data-min-ppn-owens` attributes to our options in our `form.yml`. Then in our `form.js` we can add an event handler when cluster changes and search for this attribute and set the mins an maxes for that cluster accordingly.  This would be super similar to your use case, just change cluster to queues and instead of fixing cores (searching for `batch_connect_session_context_num_cores`) you're fixing the memory form item.

**Comment by johrstrom** [comment]
Bummer.  Yea it may be a while before we add this sort of dynamic capabilities to the form.

For what it's worth (which may not be much!): start small and build on it. Copy just the event handler and the setup_even handler and iterate on it.
* Create an event handler, console log 'hello' when that event happens
* see if you can get the min/max value (console log  to debug)
* see if you can set the min/max value
* see if you can set the min/max value based on the event

**Comment by btsherid** [comment]
OK that is helpful. I accomplished the first one (console log queue name when that event happens). 

I see that custom_queue_input.val() holds the name of the selected queue. Any idea how I access the options from form.yml for that value?

Thanks,
Brendan

**Comment by johrstrom** [comment]
OK so you have this javascript (I changed the names of the variables to be `queue`). 

```javascript
// get the queue form element
const queue = $('#batch_connect_session_context_custom_queue');

// get the 'data' related to that element (html attributes with 'data-' prepended to them)
const data = queue.find(':selected').data();

// 'data-max-memory' in the form yml below turns into camel case 'maxMemory'
const max = data["maxMemory"];
```

And so in the `form.yml` you have all these `data-` attributes tied to each option. Here I've given min and max for the allnodes queue.
```yaml
custom_queue:
  label: Partition
  help: Please select a partition from the drop-down
  widget: select
  options:
    - [ 
        "allnodes", "allnodes"
        data-min-memory: 1,
        data-max-memory: 8,
      ]
```

The developer tools, and specifically the console, in your browser is going to be a good friend. You can interactively run jquery against it (jquery library that does all the the `$('#find_this_stuff)` stuff)
![image](https://user-images.githubusercontent.com/4874123/105099928-7a578c80-5a7a-11eb-9d13-a94b5106ed0c.png)

**Comment by btsherid** [comment]
Perfect, thanks. That's much better than the way I had it working.

I'll work on the rest tomorrow.

**Comment by btsherid** [comment]
I got it working. You can close this. Thanks for the help.

Here's my final form.js:
function clamp(min, max, val) {
  return Math.min(max, Math.max(min, val));
}

function set_custom_queue_change_handler() {
  let custom_queue_input = $('#batch_connect_session_context_custom_queue');
  custom_queue_input.change((event) => custom_queue_change_handler(event));
}

function custom_queue_change_handler(event) {
        const custom_queue_input = $('#batch_connect_session_context_custom_queue');
        const data = custom_queue_input.find(':selected').data();
        const max = data["maxMemory"];
        const min = data["minMemory"];
        console.log(min + " " + max);

        const bc_mem_input = $('#batch_connect_session_context_bc_mem');
        bc_mem_input.attr('max', max);
        bc_mem_input.attr('min', min);

//      bc_mem_input.val(
//          clamp(min, max, bc_mem_input.val())
//      );
}

set_custom_queue_change_handler();


-Brendan

**Comment by johrstrom** [comment]
Glad to hear it!
