### ISSUE TITLE
Passenger Apps background color and favicon

### ISSUE THREAD

**Issue by btsherid** [OSC/ondemand#857]
Hi,

I followed the directions here https://osc.github.io/ood-documentation/latest/app-development/tutorials-passenger-apps/ps-to-quota.html to make a custom app. It works great, but I don't see any instructions on how to change the title bar background color (default grey) and the favicon (a default, not the same as the one I have configured for the rest of OnDemand).

Thank You,
Brendan Sheridan

**Comment by johrstrom** [comment]
There's no out of the box way to yet (though maybe this should move to [ood_appkit](https://github.com/OSC/ood_appkit)?).

So it looks like you'll have to recreate the functionality.

We do this in the dashboard by adding a `<style>` element from [this erb file](https://github.com/OSC/ondemand/blob/master/apps/dashboard/app/views/layouts/nav/_styles.html.erb). We call it by doing this [render partial here](https://github.com/OSC/ondemand/blob/af45b6960e47a8abba34976eb2bc7471cb57ac35/apps/dashboard/app/views/layouts/application.html.erb#L17).  Looks like Sinatra has a similar functionality (OOD is mostly Rails and that app is from the Sinatra framework).

Configuration.bg_background_color is defined here. This app _may_ be able to use the same Boostrap defaults, but II wouldn't count on it. So you may have to do something to ensure there's a valid default.
https://github.com/OSC/ondemand/blob/af45b6960e47a8abba34976eb2bc7471cb57ac35/apps/dashboard/config/configuration_singleton.rb#L200-L202

**Comment by btsherid** [comment]
Thanks. Nothing I've tried has made any difference. I can't figure out what file/files need to be edited to make this happen. I can probably live with it being a different color and having a different favicon.

**Comment by btsherid** [comment]
I was able to set the favicon by adding this to views/layout.erb in the <head> element:
<link rel="icon" href="https://<OnDemand URL>/public/favicon.ico">

-Brendan
