### ISSUE TITLE
Passenger apps user that runs command

### ISSUE THREAD

**Issue by btsherid** [OSC/ondemand#860]
Hi,

I set up a passenger app using the instructions here: https://osc.github.io/ood-documentation/latest/app-development/tutorials-passenger-apps/ps-to-quota.html. It works good but the command is run as the logged in OnDemand user. Is there a way to get this command to run as root?

Thanks,
Brendan Sheridan

**Comment by btsherid** [comment]
I was able to get the output I want by adding a flag to the command but I will leave this open in case this might be a useful feature.

-Brendan

**Comment by treydock** [comment]
OnDemand apps are by design going to run as the user who is logged in, that's how OnDemand is designed.  If you want something to run as root then you have to use something like sudo from within the app.  Launching apps as root is not a feature OnDemand can support.
