### ISSUE TITLE
info.{html,md}.erb should have different context?

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#878]
Right now, `info.{html,md}.erb` is rendered with the `BatchConnect::Session`'s context. But it may be more appropriate to use `BatchConnect::SessionContext` and/or both?

[From a discourse topic](https://discourse.osc.edu/t/how-to-customize-interactive-app-card/1306), the requester seems to want to show the thing the user chose in the form (which would be held in `BatchConnect::SessionContext`).

Seems like you'd want both what the user has requested (SessionContext) and what actually happened (Session, specifically Session.info).

**Comment by ericfranz** [comment]
The session context is serialized to the file `user_defined_context.json` with the method user_defined_context_file to get the Pathname to it.

**Comment by ericfranz** [comment]
For now lets just better document what can be done with the existing solution https://github.com/OSC/ood-documentation/issues/477
