### ISSUE TITLE
New Google Streams is causing problems with analytics collection

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#886]
Reported by https://discourse.osc.edu/t/new-google-analytics-connection/1295 Google has a new way of collecting analytics and there may be a bug with the way we are set to interact with it. We should switch to this to verify the issue.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737595182644) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
We fixed this in 3.1.
