### ISSUE TITLE
Job Composer results in exception after job submission

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#887]
Reported from https://discourse.osc.edu/t/ondemand-1-7-7-job-composer-bug/1152

    App 115138 output: [2020-10-05 11:16:12 -0600 ] INFO "execve = [{\"PBS_DEFAULT\"=>\"[hostname_2]\", \"PBS_EXEC\"=>\"/opt/pbs\"}, \"/opt/pbs/bin/qstat\", \"-f\", \"-t\", \"2859773.sawtoothpbs\"]" 
    App 115138 output: [2020-10-05 11:16:12 -0600 ] INFO "method=GET path=/pun/sys/myjobs/ format=html controller=WorkflowsController action=index status=500 error='ArgumentError: wrong number of arguments (given 1, expected 0)' duration=198.89 view=0.00 db=25.27" 
    App 115138 output: [2020-10-05 11:16:12 -0600 ] FATAL "" 
    App 115138 output: [2020-10-05 11:16:12 -0600 ] FATAL "ArgumentError (wrong number of arguments (given 1, expected 0)):" 
    App 115138 output: [2020-10-05 11:16:12 -0600 ] FATAL "" 
    App 115138 output: [2020-10-05 11:16:12 -0600 ] FATAL "app/models/workflow.rb:19:in `each'\napp/models/workflow.rb:19:in `update_status!'\napp/controllers/workflows_controller.rb:224:in `each'\napp/controllers/workflows_controller.rb:224:in `update_jobs'"Two problems here. First, logging output should include a request ID. This is good practice considering that logs from multiple services (Apache, NGINX, the apps themselves) handle requests and also because looking at these logs it is not clear which requests the ArgumentError is a part of - is it the request that submits the job or the follow on request that results in update_jobs getting invoked - or is it a single request for both?Also it appears to be clear that the exception occurs in update_jobs being called.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737595260444) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I'm going to close this as won't fix as we're redoing the job composer and putting all our effort into that.
