### ISSUE TITLE
xdmod-slurm-helper broken due to sacct command failure with SLURM 20.11.4

### ISSUE THREAD

**Issue by lpouillo** [OSC/ondemand#938]
Hello,

Due to the deprecation of the ReqGRES output format in SLURM 20.11.4, the xdmod-slurm-helper failes to gather SLURM data with the following error :
```
2021-03-10 18:59:18 [notice] xdmod-slurm-helper start (process_start_time: 2021-03-10 18:59:18)
2021-03-10 18:59:19 [critical] Error while executing sacct: sacct: error: Start time (2021-03-09T23:50:27) requested is after end time (2021-03-09T22:59:59).
```

This is related to the deprecation of the ReqGRES element.

$TZ=UTC /usr/bin/sacct --clusters $SLURM_CLUSTER_NAME --allusers --parsable2 --noheader --allocations --format jobid,jobidraw,cluster,partition,account,group,gid,user,uid,submit,eligible,start,end,elapsed,exitcode,state,nnodes,ncpus,reqcpus,reqmem,reqgres,reqtres,reqtres,timelimit,nodelist,jobname --state CANCELLED,COMPLETED,FAILED,NODE_FAIL,PREEMPTED,TIMEOUT --starttime 2016-01-01T00:00:00 --endtime=now
sacct: fatal: ReqGRES is deprecated, please use ReqTRES

A quick patch has been proposed on the mailing list by Goëtz Waschk that provide a workaround, but that may break some other features.

```
--- /usr/share/xdmod/classes/OpenXdmod/Shredder/Slurm.php.orig	2021-03-01 13:25:39.473815456 +0100
+++ /usr/share/xdmod/classes/OpenXdmod/Shredder/Slurm.php	2021-03-01 13:35:06.023204035 +0100
@@ -53,7 +53,6 @@
         'ncpus',
         'reqcpus',
         'reqmem',
-        'reqgres',
         'reqtres',
         'alloctres',
         'timelimit',
@@ -87,7 +86,6 @@
         'ncpus',
         'req_cpus',
         'req_mem',
-        'req_gres',
         'req_tres',
         'alloc_tres',
         'timelimit',
```
Thanks in advance if you have time to address this issue.

Best regards,

Laurent

**Comment by lpouillo** [comment]
wrong repository sorry :)

**Comment by treydock** [comment]
@lpouillo This has been patched upstream: https://github.com/ubccr/xdmod/pull/1479
