### ISSUE TITLE
Fix logo height

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#962]

**Comment by msquee** [comment]
Closed in https://github.com/OSC/ondemand/pull/952

**Comment by ericfranz** [comment]
#952 is the wrong answer for controlling the height

.navbar-brand needs a height fixed to the desired height of the navbar, and the images (png or svg) need to have their height set to 100%

**Comment by johrstrom** [comment]
We just pulled in #984 but it's unclear to me if that's satisfactory for you. Let me know!

**Comment by ericfranz** [comment]
It is not ideal as it makes the logos small. For example in OOD1.8 we had:

![screen 2021-03-16 at 10 18 36 PM](https://user-images.githubusercontent.com/512333/111404726-aae82b00-86a5-11eb-853e-5b9675c737f6.png)

Now we have:

![screen 2021-03-16 at 10 18 41 PM](https://user-images.githubusercontent.com/512333/111404738-b3d8fc80-86a5-11eb-8fab-14d22cb3fa26.png)

So sites using the logo header might be unhappy with the change. The original fix to get this to work in Bootstrap 3 took some clever changes as I recall several custom CSS rules. It could take the same work for this, and there are bigger problems to solve. So maybe worth an issue for an intern to work on later, or we could wait for a complaint. (for example, you could imagine hugging the logo to the left/top of the screen (removing it from the flow) and then inserting extra padding to push the rest of the nav items over - there might be other ideas).

**Comment by ericfranz** [comment]
I opened https://github.com/OSC/ondemand/issues/988
