### ISSUE TITLE
Dev list and view details buttons need fixed

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#964]
- List view buttons Shell and Files don't look like a button
- Detail view buttons

![screen 2021-03-15 at 4 56 05 PM](https://user-images.githubusercontent.com/512333/111220276-5d899200-85af-11eb-860d-024239d9653f.png)

**Comment by msquee** [comment]
Fixed in #973 (https://github.com/OSC/ondemand/pull/973/commits/3c4fab1053c5a784d64de7896077ab043a568306)

![image](https://user-images.githubusercontent.com/6081892/111290318-695f6d80-861c-11eb-83f0-10c69d217401.png)
