### ISSUE TITLE
Dev view breadcrumb missing class

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#965]
![screen 2021-03-15 at 4 57 18 PM](https://user-images.githubusercontent.com/512333/111220412-8578f580-85af-11eb-9cde-53b6c45012df.png)

**Comment by msquee** [comment]
Fixed in #973 https://github.com/OSC/ondemand/commit/4cf4cb7e8897241bbdcb5784f0d385ef2ebf0cd1
