### ISSUE TITLE
Adjust colors to match oh-tech/ood1.x branding

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#967]
- [ ] update default navbar colors and font colors to match that of OnDemand 1.8 (in particular white font color for the dark navbar)
- [ ] verify or adjust use of non-semantic tags in session panels
- [ ] Add SASS overrides for `bg-color`

**Comment by ericfranz** [comment]
Along with adjusting the colors, consider adjusting the bg-color to be the [lighter background's from bootstrap 3](https://getbootstrap.com/docs/3.3/css/#helper-classes-backgrounds) instead of the [bold defaults in bootstrap 4](https://getbootstrap.com/docs/4.0/utilities/colors/#background-color) which encourage us to use non-semantic tags to use lighter colors https://github.com/OSC/ondemand/pull/968

**Comment by msquee** [comment]
Fixed in #972
