### ISSUE TITLE
Fix height and accessibility of quota limit alert

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#969]
Adjustments post https://github.com/OSC/ondemand/pull/959:

- h4 should probably not be used here - so bold like other alerts and if we want to increase the font size slightly we can
- increase the progress bar to at least 20px height https://getbootstrap.com/docs/4.0/components/progress/#height

**Comment by msquee** [comment]
Fixed in https://github.com/OSC/ondemand/pull/927/commits/d7178f5dd9d380573e38e43c259783922eb891e5
