### ISSUE TITLE
batch connect sessions helper needs updated for bootstrap 4

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#977]
The `app/helpers/batch_connect/sessions_helper.rb` file uses some old bootstrap 3 classes and may have not been properly updated for bootstrap 4 (in particular, pull-right):

```
app/helpers/batch_connect/sessions_helper.rb
173:      class: "btn btn-danger pull-right btn-delete",
```

**Comment by johrstrom** [comment]
Fixed in #980.
