### ISSUE TITLE
Optimize nav logo sizing

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#988]
This "defect" was introduced in OOD2.0

In OOD1.8 we had:

![screen 2021-03-16 at 10 18 36 PM](https://user-images.githubusercontent.com/512333/111404726-aae82b00-86a5-11eb-853e-5b9675c737f6.png)

Now we have:

![screen 2021-03-16 at 10 18 41 PM](https://user-images.githubusercontent.com/512333/111404738-b3d8fc80-86a5-11eb-8fab-14d22cb3fa26.png)

So sites using the logo header might be unhappy with the change. The original fix to get this to work in Bootstrap 3 took some clever changes as I recall several custom CSS rules. It could take the same work for this, and there are bigger problems to solve. So maybe worth an issue for an intern to work on later, or we could wait for a complaint. (for example, you could imagine hugging the logo to the left/top of the screen (removing it from the flow) and then inserting extra padding to push the rest of the nav items over - there might be other ideas).

This is affected by env var OOD_DASHBOARD_HEADER_IMG_LOGO. See https://osc.github.io/ood-documentation/latest/customization.html#branding

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737651326006) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Closing this as it doesn't seem all that important anymore. Plus nobody complained.
