### ISSUE TITLE
desktop portal start error

### ISSUE THREAD

**Issue by flybirdkh** [OSC/ondemand#997]
Hi Team,

I have on-demand portal, with slurm19.05
When i deploy bc_desktop, it have error
Failed to submit session with the following error:
![image](https://user-images.githubusercontent.com/53069666/112007756-dfedf500-8b5f-11eb-9681-5aac86bad928.png)

How to fix it

**Comment by flybirdkh** [comment]
what configuration I show can be good for solving this problem?

**Comment by johrstrom** [comment]
What does this return when you run in a shell?  Is it your correct HOME? `sbatch --export=NONE --wrap 'echo $HOME'`.  

You can set environment variables in the `batch_connect.before_script` as we do here:
https://github.com/OSC/osc-ood-config/blob/4ad4ade5a2a65c5c66f43a3806afb1ea057f8e77/ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb#L61-L70

I guess I'd be curious to see if you added an `echo "home is: $HOME"` statement there what it would print. All these are `bash` scripts. Do you have something odd in your `~/.bashrc`?  Or is there anything else in the `output.log` that would indicate that your shell environment is being setup incorrectly?

**Comment by flybirdkh** [comment]
nothing in the file of outlog when i do "sbatch --export=NONE --wrap 'echo $HOME"
there was nothing else in  the output.log 
my .bashrc is keeping default

**Comment by flybirdkh** [comment]
how to debug it ?
the output.log cannot show me what i was defined in before.sh.erb and script.sh.erb,also in the xfce.sh

**Comment by flybirdkh** [comment]
how to debug it ?
the output.log cannot show me what i was defined in before.sh.erb and script.sh.erb,also in the xfce.sh

**Comment by flybirdkh** [comment]
sbatch --wrap 'echo $HOME'   can correctly show my home path

**Comment by johrstrom** [comment]
You can change the environment we submit with like so:

Add this to you're `submit.yml.erb` or cluster wide then OOD will submit the job with `--export=ALL` (the default, same as not specifying anything).
```yaml
script:
  copy_environment: true
```

**Comment by flybirdkh** [comment]
it works with adding this in submut.yml.erb
https://github.com/OSC/ondemand/issues/997#issuecomment-804264420

thanks
