### ISSUE TITLE
Add to XDMoD Jobs Widget walltime and memory efficiency

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#998]
Currently this information not available in the single request we do for the jobs widget. However, we only display 10 jobs at a time in that widget, so in the short term we could do 10 requests to XDMoD, one per job, to get this information.

https://www.osc.edu/resources/getting_started/howto/how_to_look_at_requested_time_accuracy_using_xdmod

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737681590447) by [Unito](https://www.unito.io)

**Comment by abujeda** [comment]
At Harvard IQSS we are looking into XDMoD and possible improvements to the data displayed in the OnDemand dashboard.

We created a prototype to add extra job metrics into the XDMoD Jobs widget.
The prototype uses the` /rest/v1.0/warehouse/search/jobs/analytics` API call.

This a demo of the initial look and feel:
![xdmod_jobs](https://github.com/user-attachments/assets/e181e74c-b6b4-41f4-aef3-ef53c88a219d)

**Comment by abujeda** [comment]
This is a comparison of the before and after for the widget:
Before:
<img width="650" alt="Screenshot 2024-09-02 at 16 42 05" src="https://github.com/user-attachments/assets/323224c9-e100-4ea2-be20-f110fd771b10">

After:
<img width="650" alt="Screenshot 2024-09-02 at 16 41 55" src="https://github.com/user-attachments/assets/1f744a59-9935-489b-bc83-c86854f72b7d">

**Comment by abujeda** [comment]
FYI @johrstrom: Possible improvements to the XDMoD jobs widget

**Comment by abujeda** [comment]
Great!! 🚀 
Will continue working on the implementation and present a PR in the next couple of days!
